[3기-이동준] 1~2주차 과제 : 계산기 구현 미션 제출합니다
prgrms-be-devcourse/java-calculator pull request #102
Opened 2022-10-26 15:27 UTC by Albatross3

# 📌 과제 분석 

## 요구사항 분석 (동작환경, 데이터 범위)
**객체지향적인 코드로 계산기 구현**

**콘솔로 구현**

**입력 데이터 범위**
- [x] 정수 범위라고 가정 -> long 으로 입력받았습니다
- [ ] 실수 범위라고 가정  

**사칙연산 구현**
- [x] 사칙연산(+, -, *, /) 에 대해서만 고려하였습니다
- [ ]  ( ) 괄호에 대한 고려
- [ ]   log, 1/x, root 에 대한 고려

# 👩‍💻 객체지향적인 설계
### 자바 계산기 1차 설계도
![자바 계산기 1차 설계도](https://user-images.githubusercontent.com/43260658/198066034-32555e09-0e88-47cf-a76a-64663f9ab0f1.png)

# ✅ 구현 내용
- [x] 정규식을 사용하여 입력 검증
- [x]  더하기
- [x]  빼기
- [x]  곱하기
- [x]  나누기
- [x]  우선순위(사칙연산)
- [x]  계산 이력을 맵으로 데이터 저장기능 만들기
- [ ]  테스트 코드 작성
# ❓  PR 포인트 & 궁금한 점 

- 설계단계에서 객체 지향적으로 설계가 잘 되었는지 궁금합니다. 부족하다면 어떤 부분에 고쳐야 하는지 궁금합니다!
- 현재 inteface에 필요한 메서드를 모두 정의하고 class에서 구현하여서 Calculator에서 사용하고 있는데 이렇게 하는 것이 객체 지향적인 코드인지 궁금합니다!
- Compute 인터페이스에서 입력을 토큰화 시키는 부분이 확장을 고려했을 때 공통적이라 판단하여 default 메서드로 작성했는데 default 메서드를 이런식으로 활용하는게 맞는 것인지 궁금합니다!
- Enum을 Menu 와 Operator 에 적용시켰습니다. Enum을 적절히 활용하였는지 궁금합니다!

# ✅ 피드백 반영사항

2022-10-27 03:47 UTC, hongbin-dev commented
동준님! 현재 폴더가 Calculator 폴더 내에 src가 존재하는데요.
Calculator를 제거하시고, src를 루트로 옮겨주시면 좋을 것 같아요.

2022-10-27 03:48 UTC, hongbin-dev commented
@Albatross3

2022-10-27 04:24 UTC, hongbin-dev requested changes
안녕하세요 동준님. 앨런입니다
코멘트 남겼으니 확인부탁드려요~

2022-10-27 04:24 UTC, hongbin-dev commented on Calculator/src/main/java/org/example/compute/Operator.java
> +        return Arrays.stream(Operator.values()).filter(o -> o.operator.equals(newOperator)).findFirst().get();
객체지향생활체조 `한 줄에 점을 하나만 찍는다.`를 참고해보면 좋을 것 같아요~

2022-10-27 04:24 UTC, hongbin-dev commented on Calculator/src/main/java/org/example/repository/HashMapRepository.java
> +    private final HashMap<Long, String> results = new LinkedHashMap<>();
Map으로 선택하신 이유가 있나요~?

2022-10-27 04:24 UTC, hongbin-dev commented on Calculator/src/test/java/org/example/compute/ComputeArithmeticOperationTest.java
> +        String input = "132 + 2 + 31";
테스트를 잘 모르는데 시도해보신거 👍
우선순위가 잘 동작하거나, 어떨 때 실패하는지 테스트해보는것도 좋아보이네요 ㅎ

2022-10-27 04:31 UTC, hongbin-dev commented
## 설계단계에서 객체 지향적으로 설계가 잘 되었는지 궁금합니다. 부족하다면 어떤 부분에 고쳐야 하는지 궁금합니다!
전반적으로 입출력과 로직을 잘 나눠주신 것 같습니다.
다만 Compute의 로직이 흩어져있는 것 같습니다. 입력을 검증하고(Validator), 수식을 만들고 계산하는데요. 이 부분을 Compute객체가 책임을 갖으면 안될까요?

1. Compute 생성 (입력 검증 및 토큰화)
2. Compute 연산 (토큰된 값들을 계산)

이런식으로요.


## 현재 inteface에 필요한 메서드를 모두 정의하고 class에서 구현하여서 Calculator에서 사용하고 있는데 이렇게 하는 것이 객체 지향적인 코드인지 궁금합니다!

제가 인터페이스로 분리한 이유를 잘 모르겠는데요. 어떤곳에서 공통적으로 쓰일 인터페이스라고 생각할 수 있을까요?


## Enum을 Menu 와 Operator 에 적용시켰습니다. Enum을 적절히 활용하였는지 궁금합니다!
Enum과 람다를 이용해서 잘 활용해주신 것 같습니다👍

2022-10-27 06:39 UTC, Albatross3 commented on Calculator/src/main/java/org/example/Calculator.java
> +            // 유효한 메뉴인지 확인
주석 제거하였습니다!

2022-10-27 13:54 UTC, seung-hun-h reviewed
안녕하세요 동준님 함승훈입니다.
Enum을 활용해서 분기문을 최대한 줄이려고 노력하신 것 좋네요!
리뷰 남겼으니 확인해주세요.

### 설계단계에서 객체 지향적으로 설계가 잘 되었는지 궁금합니다. 부족하다면 어떤 부분에 고쳐야 하는지 궁금합니다
- 최대한 객체지향적으로 설계하려 하신 것 같습니다
- 아쉬운점은 Calculator 객체에 너무 많은 역할이 부여된 것 같습니다. 아마 Console 앱이 아니라면 Calculator는 사용할 수 없을 것 같네요
- 사용자에게 보여주는  View 객체, View 객체에서 사용자의 어떤 명령을 받고 그 명령을 전달하는 Router 객체, 계산을 수행하는 객체 등등으로 세분화해서 나눈다면 더 좋았을 것 같네요
- 외부와 상호작용하는 객체들은 최대한 바깥으로 뺴주는 것이 좋습니다. 중요한 기능을 하는 객체들은 순수하게 남겨주세요

### 현재 inteface에 필요한 메서드를 모두 정의하고 class에서 구현하여서 Calculator에서 사용하고 있는데 이렇게 하는 것이 객체 지향적인 코드인지 궁금합니다!
- 사실 인터페이스를 사용하신 이유를 잘 모르겠습니다. 인터페이스를 사용하는 대표적인 이유는 다형성 때문인데, 다형성을 고려하여 설계된 것이라고는 생각되지 않네요

### Compute 인터페이스에서 입력을 토큰화 시키는 부분이 확장을 고려했을 때 공통적이라 판단하여 default 메서드로 작성했는데 default 메서드를 이런식으로 활용하는게 맞는 것인지 궁금합니다!
- 공통적이라고 생각되는 부분을 추상화한 점은 좋습니다
- 다만 인터페이스의 디폴트 메서드는 구현체에서 재정의 가능합니다. 그렇다면 기존에 설계한 의도대로 동작하지 않을 가능성이 있겠죠?
- 이러한 경우 추상 골격 구현 클래스와 인터페이스를 같이 사용하곤 합니다. 고정적인 부분은 추상 골격 구현 클래스에 작성하고, 타입은 인터페이스로 정의하는 방법이에요. 
https://dzone.com/articles/favour-skeletal-interface-in-java

Enum을 Menu 와 Operator 에 적용시켰습니다. Enum을 적절히 활용하였는지 궁금합니다!
- Enum을 잘 활용하신 것 같아요!

2022-10-27 13:54 UTC, seung-hun-h commented on Calculator/src/main/java/org/example/Menu.java
> +    }
접근 제어자를 사용하지 않은 이유가 있나요?

2022-10-27 13:54 UTC, seung-hun-h commented on Calculator/src/main/java/org/example/io/ConsoleOutput.java
> +        System.out.println();
`ConsoleInput`에는 `InputStreamReader`를 사용하고 `ConsoleOutput`에는 `System.out.println`을 사용하신 이유가 있을 까요?

2022-10-27 13:54 UTC, seung-hun-h commented on Calculator/src/main/java/org/example/io/ConsoleInput.java
> +    private final BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
지금도 좋지만 `BufferedReader`를 외부에서 주입받을 수 있도록 생성자를 만들어주면 좋겠네요. 생성자를 만들어 외부에서 의존성을 주입 받을 수 있게하면 어떤점이 좋을까요?

2022-10-27 13:54 UTC, seung-hun-h commented on Calculator/src/main/java/org/example/io/ConsoleInput.java
> +    public String selectMenu(String s) throws IOException {
`IOException`를 `Main` 까지 던져주고 있는데요, 예외가 발생했을 때 예외 내용을 사용자에게 그대로 보여준다면 좋은 방법일까요?

2022-10-27 13:54 UTC, seung-hun-h commented on Calculator/src/main/java/org/example/io/Input.java
> +public interface Input {
`Input`과 `Output`을 인터페이스로 정의하신 이유가 있을까요?

2022-10-27 13:54 UTC, seung-hun-h commented on Calculator/src/main/java/org/example/repository/HashMapRepository.java
> +        results.values().forEach(System.out::println);
`HashMapRepository`가 출력까지 담당하고 있네요. 적절한 값을 반환하고 `Ouput`이 출력해주는 것이 좋을 것 같아요

2022-10-27 13:54 UTC, seung-hun-h commented on Calculator/src/main/java/org/example/validate/ValidateExpression.java
> +        return expression.matches(expressionPattern);
`String`의 `matches` 메서드 내부 구현을 본 적 있을까요?
항상 동일한 동작을 하는 객체가 한 번쓰고 버려지고 있을 수 있겠네요

2022-10-27 13:54 UTC, seung-hun-h commented on Calculator/src/test/java/org/example/compute/ComputeArithmeticOperationTest.java
> +        String input = "132 + 2 + 31";
테스트 메서드 이름을 어떻게하면 잘 지을 수 있을 지도 생각해보는게 좋겠네요.

2022-10-27 13:54 UTC, seung-hun-h commented on Calculator/src/main/java/org/example/compute/Operator.java
> +    DIVIDE("/", 3, (num1, num2) -> num1 / num2);
Enum을 잘 활용하셨네요!
다만 코드 포매팅을 맞추면 더 좋을 것 같아요. 어떤 코드는 쉼표가 붙어있고 다른 코드는 쉼표가 띄어져있네요

2022-10-27 13:54 UTC, seung-hun-h commented on Calculator/src/main/java/org/example/compute/ComputeArithmeticOperation.java
> +                while (!stack.isEmpty() && isLowerThanStack(token, stack.peek())) {
`isLowerThanStack`이라는 메서드명은 모호한 것 같네요.
우선순위가 더 낮다는 의미를 가진 이름을 지어주면 더 좋을 것 같아요

2022-10-27 13:54 UTC, seung-hun-h commented on Calculator/src/main/java/org/example/compute/ComputeArithmeticOperation.java
> +    private final String patternNumber = "\\d+";
상수로 선언해주면 더 좋겠네요

2022-10-28 16:45 UTC, Albatross3 commented on Calculator/src/main/java/org/example/Calculator.java
> +            }
switch 문을 활용해서 열거 타입으로 구분하였습니다.

2022-10-28 16:47 UTC, Albatross3 commented on Calculator/src/main/java/org/example/Calculator.java
> +        while (true) {
while문에 true를 없애기 위해서 상태를 책임지는 ComputeManger .class를 생성했습니다. 
EXIT 를 만나는 경우에 setter를 통해 상태를 변경시켰는데 setter를 쓰는 것이 객체 지향 체조 원칙에 부합하지 않아서
어떤 다른 방법이 있는지 궁금합니다!

2022-10-28 16:49 UTC, Albatross3 commented on Calculator/src/main/java/org/example/Calculator.java
> +            } else if (Menu.CALCULATE.getNumber() == menuNumber) {
menuNumber를 입력받으면 Menu 타입이 나오는 메서드를 정의해서 switch 문에서 열거 타입 이름만으로 비교할 수 있도록 하였습니다

2022-10-28 16:51 UTC, Albatross3 commented on Calculator/src/main/java/org/example/compute/Operator.java
> +        return Arrays.stream(Operator.values()).filter(o -> o.operator.equals(newOperator)).findFirst().get();
한 줄에 점 하나로 바꾸었습니다!

2022-10-28 16:55 UTC, Albatross3 commented on Calculator/src/main/java/org/example/compute/Compute.java
> +public interface Compute {
현재 계산기는 사칙연산만 담당하고 있지만 좀 더 다양한 연산기능이 추가되었을 때 공통적인 부분을 추상화시켜서 사용할 수 있다고 판단했습니다. 또한 다른 기능들과 마찬가지로 의존 역전 원칙을 유지하기 위해서입니다

2022-10-28 17:09 UTC, Albatross3 commented on Calculator/src/main/java/org/example/repository/HashMapRepository.java
> +    private final HashMap<Long, String> results = new LinkedHashMap<>();
없는 것 같습니다.. 생각해보니 현재 order라는 필드를 사용하는 것도 아니고(일급 컬렉션 사용에 위배) ArrayList<String> 으로도 충분히 저장이 가능할 것 같아서 변경하였습니다!

2022-10-28 17:43 UTC, Albatross3 commented on Calculator/src/main/java/org/example/compute/Operator.java
> +    DIVIDE("/", 3, (num1, num2) -> num1 / num2);
코드 formatting 하였습니다!

2022-10-28 17:48 UTC, Albatross3 commented on Calculator/src/main/java/org/example/Menu.java
> +    }
Enum 에서 생성자는 private으로 고정되는 것으로 알고 있는데 혹시 아닌가요??

2022-10-28 17:51 UTC, Albatross3 commented on Calculator/src/main/java/org/example/compute/ComputeArithmeticOperation.java
> +    private final String patternNumber = "\\d+";
final을 통해 상수로 선언하였습니다!

2022-10-29 13:11 UTC, hongbin-dev commented on Calculator/src/main/java/org/example/Calculator.java
> +        while (true) {
상태 변경은 항상 일어날 수 있다고 생각해요. 비즈니스적으로 상태를 변경하는것과 setter는 약간 다르다고 생각해요.

2022-10-29 13:14 UTC, hongbin-dev commented on Calculator/src/main/java/org/example/compute/Compute.java
> +public interface Compute {
더 다양한 연산기능이 추가되면, 어차피 인터페이스는 변경되는거 아닌가요?
불필요한 추상화라고 생각되네요

2022-10-29 13:20 UTC, hongbin-dev approved these changes
동준님! 고생많으셨습니다.
코멘트 몇가지 남겼고, 리뷰는 여기서 마칠게요~

2022-10-29 13:20 UTC, hongbin-dev commented on Calculator/src/main/java/org/example/Calculator.java
> +    }
`{}`는 생략하지말아주세요!

 또 적절한 개행은 가독성을 향상시킵니다~

2022-10-29 13:20 UTC, hongbin-dev commented on Calculator/src/main/java/org/example/Calculator.java
> +                break;
Menu enum에 필드가 추가되면 요기는 어떻게 동작할까요?

2022-10-29 13:20 UTC, hongbin-dev commented on Calculator/src/main/java/org/example/repository/ArrayListRepository.java
> +}
요기는 단순 저장하고, 저장된걸 반환하는 역할만하면 좋겠네요

출력은 담당 객체가 해주면 좋겠습니다~ (`=` 를 더하는 계산 포맷을 맞추는것도요)

2022-11-01 04:59 UTC, seung-hun-h commented on Calculator/src/main/java/org/example/Menu.java
> +    }
그렇군요! 제가 몰랐던 부분이네요. 배워갑니다
https://www.geeksforgeeks.org/why-enum-class-can-have-a-private-constructor-only-in-java/

2022-11-06 00:17 UTC, merged