[3기-고승원] 1~2주차 과제 : 계산기 구현 미션 제출합니다
prgrms-be-devcourse/java-calculator pull request #104
Opened 2022-10-27 11:51 UTC by goseungwon

# java_calculator
자바 계산기 구현 미션 Repository입니다.

### 과제를 통해 기대하는 역량

- 깃허브를 통한 코드리뷰를 경험해보자
- 기본적인 테스트 코드 작성 및 활용하는 능력해보자
- 스스로 OOP를 생각하고 코드로 옮길 수 있는 능력해보자

### 요구사항
- 콘솔로 구현입니다.(스윙으로 구현하시는 분들 계실까봐) 
- 객체지향적인 코드로 계산기 구현하기
    - [x]  더하기
    - [x]  빼기
    - [x]  곱하기
    - [x]  나누기
    - [x]  우선순위(사칙연산)
- [x]  테스트 코드 구현하기 ? 세모입니다.
- [x]  계산 이력을 맵으로 데이터 저장기능 만들기
    - 애플리케이션이 동작하는 동안 데이터베이스 외에 데이터를 저장할 수 있는 방법을 고안해보세요.
- [ ] 정규식 사용(선택)

### 코드리뷰(PR) 요청사항!
 - 코드 포맷을 맞춰주세요!
     - https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html
 - 객체지향 생활체조를 실천해봐요. 
   - https://jamie95.tistory.com/99
 - 한 메서드에 오직 한 단계의 들여쓰기만 한다. 
   - 이 부분은 처음 적용하긴 어려우니 2번의 들여쓰기로 노력해봐요.
 - 리뷰받고싶은부분, 자신없는부분을 남겨주세요.
   - ex) ~~.class에서 stream api를 처음사용해봤는데, 이 부분이 잘 적용됐는지 궁금합니다~
 - 커밋은 기능단위로 커밋 + 커밋컨벤션을 설정해볼까요?
   - https://www.slipp.net/questions/525
 - 배열을 지양하고 컬렉션을 사용해주세요!
 - 롬복 사용을 하지말아주세요!

### 클래스 다이어그램
![image](https://user-images.githubusercontent.com/85796588/198272917-dac2068f-c988-4875-a611-c531c7875bb4.png)

---
# 자신 없는점, 궁금한 점

### 설계
 - 객체간 올바르게 역할을 부여한 것인지 궁금합니다.
   - 더 쪼갰어야 하는지 
   - 덜 쪼갰어야 하는지
   - 비효율적인 구조인지
 - 인터페이스를 올바르게 사용하고 있는지 궁금합니다.

### 예외처리

 - 예외를 만들어서 Enum단계에서 던져줬는데 올바른 선택인지 궁금합니다.
 - 계산식 입력 과정에서 식이 올바르게 입력되었는지 검증하는 과정을 잘 모르겠습니다. (1 + + 2)
   - 동준이형에게 정규식으로 하는 방법을 들었는데 좋은 방법인지 궁금합니다.
 - Calculate와 Storage관련 테스트 코드를 만들지 못했습니다.
   - 제 눈에는 방법이 생각나지 않는데, 애초에 코드를 잘못 만든 것인지 견해가 좁은 것인지 궁금합니다.
 
### enum의 활용
 - Symbol에서는 직접 사칙연산 식까지 구현을 했습니다. 반면에 Menu에서는 Enum을 활용하고 있다는 생각이 들지 않습니다.
 - Calculator에서 if-else를 사용하지 않고 바로 처리하는 방법이 있는지 궁금합니다.

### depth
 - depth를 2로 제한하셨는데, 못지킨 부분이 있습니다.
   - 이에 관련하여 CalculatePostfix에서 나누어 봤는데 좋은 방법인지 궁금합니다.

2022-10-27 16:20 UTC, hongbin-dev requested changes
안녕하세요 승원님! 
시간이 없어서 답변보다 리뷰 먼저 남겼어요. 리뷰 먼저 확인해주세요 😅

2022-10-27 16:20 UTC, hongbin-dev commented on src/main/java/com/programmers/calculator/Calculator.java
> +                //if else 없이 Symbol 에서 잘 처리해주면 된다고 생각하는데 잘 모르겠습니다.
궁금하신점 남겨주신 것 좋네요ㅎㅎ 다음에는 주석보다는 github에 코멘트 남겨주시면 더 좋을 것 같아요.
이 부분은 오늘 이야기나눠봤었는데, 궁금하신점 있으면 채널에서 이야기나눠봐용~

2022-10-27 16:20 UTC, hongbin-dev commented on src/main/java/com/programmers/calculator/engine/calculation/CalculatePostfix.java
> +        number1 = stack.pop();
```suggestion
        double number2 = stack.pop();
        double number1 = stack.pop();
```
선언해놓고 쓰지마세요! 항상 null이 발생하지않도록 코드를 작성해주세요.

2022-10-27 16:20 UTC, hongbin-dev commented on src/main/java/com/programmers/calculator/engine/conversion/ConversionFormula.java
> +    }
https://stackoverflow.com/questions/3874350/naming-conventions-for-java-methods-that-return-boolean

boolean 메서드 네이밍을 참고해보면 좋을 것 같아요

2022-10-27 16:20 UTC, hongbin-dev commented on src/main/java/com/programmers/calculator/engine/conversion/ConversionFormula.java
> +        Stack<String> symbolStack = new Stack<>();
이쪽 메서드가 길어서 이해하기가 어렵네요. 조금 더 분리해볼 수 있을까요?

2022-10-28 01:55 UTC, seung-hun-h reviewed
안녕하세요 승원님 함승훈입니다.
이번 PR 요구사항을 최대한 지키려 하신거 같네요.
리뷰 남겼으니 확인 부탁드릴게요!

### 객체간 올바르게 역할을 부여한 것인지 궁금합니다.
- 일단 다른분들과 마찬가지고 `Calculator`가 너무 많은 일을 하고 있어요. 우리가 생각하는 계산기에서 조금 벗어나서 객체를 더 나누어보면 좋을 것 같아요

### 인터페이스를 올바르게 사용하고 있는지 궁금합니다.
- 인터페이스를 사용하는 가장 큰 목적은 다형성입니다.
- 예를 들면 `Storage`를 다양하게 구현할 수 있겠죠. HashMap을 사용해서 메모리에 저장할 수 있고, File을 사용할 수도 있고, Database를 사용할 수도 있겠죠
- 하지만 구현이 달라진다고 하더라도 구현체들이 하는 일들은 근본적으로 동일합니다
- 객체를 저장하거나, 키를 받아서 객체를 찾거나, 저장되어 있는 모든 객체를 반환할 수도 있을거에요
- 이러한 행동들을 인터페이스에 정의하면, 클라이언트 코드에서는 `Storage`가 어떤 구현체인지 관련 없이  인터페이스에 정의된 메서드를 호출해서 원하는 결과를 얻을 수 있을 거에요


### 예외를 만들어서 Enum단계에서 던져줬는데 올바른 선택인지 궁금합니다.
- 넵 Enum에서 예외 던지는 것은 아무런 문제가 되지 않습니다

### 계산식 입력 과정에서 식이 올바르게 입력되었는지 검증하는 과정을 잘 모르겠습니다. (1 + + 2) 동준이형에게 정규식으로 하는 방법을 들었는데 좋은 방법인지 궁금합니다.
- 넵 정규식을 잘 사용할 수 있다면 쓰는 것도 좋을 것 같아요
- 정규식을 사용하면 성능이 조금 떨어질 수도 있지만, 성능에 민감한 애플리케이션이 아니라면 간편하고 알아보기 쉬운쪽이 좋은 선택인 것 같아요

### Calculate와 Storage관련 테스트 코드를 만들지 못했습니다. 제 눈에는 방법이 생각나지 않는데, 애초에 코드를 잘못 만든 것인지 견해가 좁은 것인지 궁금합니다.
- 테스트를 작성하지 못한 이유에 대해서 생각해보면 좋겠네요. 왜 테스트가 힘들었나요?

### Symbol에서는 직접 사칙연산 식까지 구현을 했습니다. 반면에 Menu에서는 Enum을 활용하고 있다는 생각이 들지 않습니다.
- Menu에 사용자에게 노출할 Description 필드를 사용하는 것은 어떤가요?

2022-10-28 01:55 UTC, seung-hun-h commented on src/main/java/com/programmers/calculator/Calculator.java
> +    }
다른 분들과 마찬가지로 `Calculator`가 너무 많은 책임을 가지고 있는 것 같아요. 어떻게 하면 잘 분리할 수 있을 지 생각해 보는 것이 좋겠네요.

2022-10-28 01:55 UTC, seung-hun-h commented on src/main/java/com/programmers/calculator/engine/calculation/CalculatePostfix.java
> +    void isNumber(String token) {
`private` 접근 제어자를 사용하지 않으신 이유가 있나요?

2022-10-28 01:55 UTC, seung-hun-h commented on src/main/java/com/programmers/calculator/engine/calculation/CalculatePostfix.java
> +        stack.push(Symbol.calculate(token, number1, number2));
`token`으로 `Symbol` 인스턴스를 생성하고 메시지를 전달하는 것이 조금 더 좋을 것 같아요
```suggestion
	Symbol symbol = Symbol.of(token);
	symbol.calculate(number1, number2);
```

2022-10-28 01:55 UTC, seung-hun-h commented on src/main/java/com/programmers/calculator/engine/conversion/ConversionFormula.java
> +            }
`else`를 사용하지 않는 것 좋습니다!

2022-10-28 01:55 UTC, seung-hun-h commented on src/main/java/com/programmers/calculator/engine/conversion/ConversionFormula.java
> +        }
`symbol`의 우선순위는 변하지 않는 값으로 보이네요. switch문을 잘 사용하는 것도 좋은 방법이지만, `Map`을 사용해서 미리 우선순위를 초기화 해주는 것도 좋을 것 같네요

2022-10-28 01:55 UTC, seung-hun-h commented on src/main/java/com/programmers/calculator/engine/io/Console.java
> +    }
메서드를 구현하지 않은 이유가 있을까요?

2022-10-28 01:55 UTC, seung-hun-h commented on src/main/java/com/programmers/calculator/engine/menu/Menu.java
> +//    LOOKUP("1", (formula, result) -> new 조회로직),
해당 코드를 사용하지 않는다면 제거하는 것이 좋을 것 같아요

2022-10-28 01:55 UTC, seung-hun-h commented on src/main/java/com/programmers/calculator/engine/storage/HashMapStorage.java
> +public class HashMapStorage implements Storage {
`HashMapStroage` 처럼 구체적인 자료구조를 클래스 이름에 사용하는 것은 좋은 방법은 아니라고 생각해요.
클래스에서 사용하는 자료구조는 구체적인 구현에 해당하고, 타입은 외부에 노출하게 되니까요.
만약 `HashMap`이 아니라 `HashTable`을 사용하게되면 `HashTableStorage`라고 이름을 변경해야 할 수도 있을 것 같네요.

2022-10-28 01:55 UTC, seung-hun-h commented on src/main/java/com/programmers/calculator/engine/storage/HashMapStorage.java
> +    }
`Storage`에서는 전달받은 객체를 저장하고, 저장된 객체를 반환하는 책임만 가지고 있는 것이 더 좋은 것 같아요.
출력은 `Colsole`에서 해주면 좋겠네요

2022-10-28 01:55 UTC, seung-hun-h commented on src/test/java/com/programmers/calculator/engine/conversion/ConversionFormulaTest.java
> +    Conversion conversion = new ConversionFormula();
`private` 접근 제어자를 사용하는 것이 좋겠네요

2022-10-28 12:23 UTC, goseungwon commented on src/main/java/com/programmers/calculator/Calculator.java
> +            }
이 부분에 대해서는 35라인에서 값을 받을 때 Menu.java 파일에서 이넘을 통해 입력값을 검증하려 코드를 작성했습니다.

다만 Menu enum에서 바로 메서드를 반환해서  Calculator에서 if문을 쓸 필요 없이 인풋값에 알아서 메서드를 호출하게 할 수 있는지 궁금합니다.

2022-10-28 12:29 UTC, goseungwon commented on src/main/java/com/programmers/calculator/engine/calculation/Calculate.java
> +public interface Calculate {
이 인터페이스를 만들 때 전위, 중위, 후위 표기법이 있기 때문에 인터페이스를 만들었습니다.
지금 생각해보면 모두 후위표기법으로만 계산하지 않을까 생각이 드네요.

2022-10-28 13:48 UTC, goseungwon commented on src/main/java/com/programmers/calculator/engine/calculation/Symbol.java
> +    }
바로 symbol을 사용하지 않고 String.format() 메서드를 사용한 이유가 있나요??

2022-10-29 13:24 UTC, hongbin-dev approved these changes
승원님 리뷰는 여기서 마치겠습니다~
궁금하신건 채널에 남겨주세용~

2022-10-29 13:24 UTC, hongbin-dev commented on src/main/java/com/programmers/calculator/Calculator.java
> +            }
enum 필드 내에 함수형인터페이스를 넣어보는건 어떨까요? 

https://jojoldu.tistory.com/137

2022-10-30 13:30 UTC, goseungwon commented on src/main/java/com/programmers/calculator/engine/calculation/CalculatePostfix.java
> +    void isNumber(String token) {
isNumber 메소드는 재사용할 일이 생길거라 생각해서 열여뒀습니다.
이외 메서드 부분은 제가 깜빡하고 적지 않았습니다.

2022-10-30 13:37 UTC, goseungwon commented on src/main/java/com/programmers/calculator/engine/io/Console.java
> +    }
처음과 설계가 달라졌는데 깜빡하고 지우지 못한 부분입니다.
찾아주셔서 감사합니다.

2022-10-30 13:45 UTC, goseungwon commented on src/main/java/com/programmers/calculator/engine/storage/HashMapStorage.java
> +public class HashMapStorage implements Storage {
저는 오히려 `Storage` 는 변경 가능성이 많기 때문에 매번 구현체마다 다른 이름을 사용해야 된다고 생각했는데, 만약 해시맵이 아닌 해시테이블 또는 db를 사용하게 되어도 구현 클래스 명은 일관적이어야 된다는 말씀인가요??

2022-10-30 16:06 UTC, goseungwon commented on src/main/java/com/programmers/calculator/engine/calculation/CalculatePostfix.java
> +        stack.push(Symbol.calculate(token, number1, number2));
이 방법에 관하여 인스턴스를 통한 메시지 전달의 장점을 찾아봤는데 잘 이해가 안되서 질문 남깁니다
`Symbol symbol = Symbol.of(token);` 이 방법은 Symbol에 대한 값에 대한 검증을 위한건가요??

2022-11-01 04:47 UTC, seung-hun-h commented on src/main/java/com/programmers/calculator/engine/calculation/CalculatePostfix.java
> +        stack.push(Symbol.calculate(token, number1, number2));
`of`는 `Symbol`의 인스턴스를 만들기위한 정적 팩터리 메서드입니다.
https://hudi.blog/effective-java-static-factory-method/

객체를 생성하고 그 객체에게 메시지를 전달해주면 좀 더 객체지향적이라고 볼 수 있다고 생각해서 말씀드렸어요. 제가 좀 더 자세히 답변드렸어야 했네요

2022-11-01 04:53 UTC, seung-hun-h commented on src/main/java/com/programmers/calculator/engine/storage/HashMapStorage.java
> +public class HashMapStorage implements Storage {
`Storage`의 구현 상태를 이름으로 노출하게 되면, 나중에 내부 구현의 문제점을 찾아냈을 때 그 문제점이 선택한 자료구조에 있다면 구현 클래스의 이름을 바꿔야 할 것 같아요. 그렇게되면 `HashMapStorage`를 사용하는 모든 코드에서 클래스 이름을 변경해야 할 것 같다는 생각이 들어 말씀드렸어요!

예를 들어 `InMemoryStorage`라는 이름을 부여하면 해당 스토리지가 메모리에 데이터를 저장하기 때문에 데이터가 프로그램이 동작하는 동안에만 영속된다는 것을 개발자가 알겠지만 구현이 `HashMap`인지 `ConcurrentHashMap`인지는 몰라도 되는 거죠. `HashMap`을 사용하다가 동시성 문제가 발생한다는 것을 알게된 후 `ConcurrentHashMap`을 사용해도 클라이언트에서는 코드를 변경할 필요가 없을 것 같다는 생각에 말씀드렸습니다.

승원님 말씀도 틀린게 아니라고 생각해요. 단순히 저의 생각이었습니다 :)

2022-11-01 04:55 UTC, seung-hun-h commented on src/main/java/com/programmers/calculator/engine/calculation/Symbol.java
> +    }
개인적인 선호도 차이일 수도 있을 것 같아요. `+`를 사용할 수도 있겠지만 저는 `String.format`을 사용하는 것을 좋아합니다

2022-11-04 17:03 UTC, goseungwon commented on src/main/java/com/programmers/calculator/engine/calculation/Symbol.java
> +    }
취향차이였군요!

2022-11-04 17:09 UTC, goseungwon commented on src/main/java/com/programmers/calculator/engine/storage/HashMapStorage.java
> +public class HashMapStorage implements Storage {
그렇네요 수정될 가능성이 다분하기에 인터페이스를 사용했지만, 구현 클래스의 이름까지는 미처 생각하지 못했습니다.

큰 애플리케이션에서는 리팩토링 기능을 사용해서 변경하면 위험하다 들어서 이런일이 없게 하려면 이름을 지을때 신중해야하군요!

2022-11-06 00:18 UTC, merged