[3기-이택승] 1~2주차 과제 : 계산기 구현 미션 제출합니다
prgrms-be-devcourse/java-calculator pull request #107
Opened 2022-10-28 02:57 UTC by dlxortmd987

## 📌 과제 설명 
- 후위연산을 통해 계산기를 구현했습니다.
- 어떤 연산을 했는지 조회하는 기능도 구현했습니다.

## 👩‍💻 요구 사항과 구현 내용 
- [feat : gradle 프로젝트 생성](https://github.com/dlxortmd987/java-calculator/commit/c8272cf99d2a9e8052057fb897f2eae9d48b4887) -> gradle 프로젝트 생성
- [feat: 엔진 레이어 구현을 위한 클래스 추가](https://github.com/dlxortmd987/java-calculator/commit/94adf77907e3601f6ce1b372eae9b4c57d720012) -> 엔진 레이어에 구현 코드를 제외한 사용할 클래스 추가
- [feat: 메인 루프 구현](https://github.com/dlxortmd987/java-calculator/commit/00236ac0979c2759409ab2b80d6197e947ad0f61) -> Calculator의 run() 메인 루프 구현 (거기서 사용하는 메소드 구현은 제외됨)
- [feat: 변환 메소드 개발](https://github.com/dlxortmd987/java-calculator/commit/8c4176305593ebc0be4bdfc894a043d71819eacd) ->parseExpression(), 식 변환 메소드 구현
- [feat: 연산 메소드 계발](https://github.com/dlxortmd987/java-calculator/commit/4d3bf4891e9ac0716dfb6fda5746277b176da49e) -> 후위연산으로 연산하는 메소드 구현
- ~~[feat: Operator implements 구현](https://github.com/dlxortmd987/java-calculator/commit/679a17a227a365e0f819e68a6f3b284928c01349) -> Operator 구현~~ (현재 코드에선 변경됨)
- [feat: Console 계산기 쪽 implements 구현](https://github.com/dlxortmd987/java-calculator/commit/10e1f9e69877f0336bdd1cef199c2cafe0acb4bc) -> Console 구현
- [feat: 저장 기능 구현](https://github.com/dlxortmd987/java-calculator/commit/0cda505419f2ac564c5150831b1a33bb6dfd68cb) -> 식 저장 기능 구현
- ~~[refactor: Plus, Minus, Multiply, Divide 인터페이스 메소드 default로 변경](https://github.com/dlxortmd987/java-calculator/commit/d0efebe4a8c7ddc0e9af5d4298b6611cb7567e47) -> Plus, Minus, Multiply, Divide 인터페이스 메소드 default로 변경~~ (현재 코드에선 완전 바뀜)
- [refactor: Calculator interface 분리](https://github.com/dlxortmd987/java-calculator/commit/0d10151728e17d14d6f487d17479fc98d3a21ed8) -> Calculator를 인터페이스로 사용, CalculatorIml에 구현
- [fix: Calculator와 History 분리, run() 메소드에서 History 객체 생성 부분 삭제](https://github.com/dlxortmd987/java-calculator/commit/c06470c52dd6e2d84dc9a6791b1cadf234d6d699) -> 계산 기능하고 저장 기능 분리 (Menu 클래스에서)
- [fix: 답 Answer 객체로 wrapping](https://github.com/dlxortmd987/java-calculator/commit/dd99e7af7e61628b092e39d03a27d4968a5cb95b) -> 답 부분 Answer 클래스로 wrapping
- [fix: Menu Option enum 클래스 추가](https://github.com/dlxortmd987/java-calculator/commit/220a6f9dd50a0c6642807962a84a441efb9250f4) -> enum으로 옵션 선택하도록 변경(MenuType)
- [fix: Console 클래스의 checkInt, Answer 클래스로 리팩토링](https://github.com/dlxortmd987/java-calculator/commit/ea392963095fbb534e19288bf61bf8f9444aa608) -> Console 클래스의 checkInt Answer 클래스 내부로 이동
- [fix: History 필드 타입 변경 및 출력 로직 변경](https://github.com/dlxortmd987/java-calculator/commit/ca6c58c4fa6109feb2a6caa2bdb95158764f75d3) -> 순서 보장되도록 History 필드 구현체 변경
- [fix: Menu에 따른 if-else 문 제거 후 OCP 위반하지 않도록 수정](https://github.com/dlxortmd987/java-calculator/commit/b9987b0a22e09ffe096eb68bbdbf8caa90205ffc) -> 계산 기능과 저장 기능의 분기를 전략 패턴으로 변경
- [fix: Operator enum 클래스로 변경 후, 계산 부분에서 if-else 삭제](https://github.com/dlxortmd987/java-calculator/commit/ce7c19c665aaf74fec392a886d46676f7a9ebbd9) -> 연산자 분기를 enum 클래스로 변경
- [fix: 사용자가 선택한 옵션 exception 처리:](https://github.com/dlxortmd987/java-calculator/commit/4b2a3bcba2c92ee05d5a6b4905e16aeeee0f8bac) -> 계산 기능과 저장 기능 이외 선택시 validation 처리
- [fix: 사용자 입력 validation 처리 및 음수 입력 지원](https://github.com/dlxortmd987/java-calculator/commit/7b696840d0d4d47ed8471ad1cfe67f66b9d206e4) -> 사용자가 입력한 식 validation 처리 및 음수 입력 지원
- [fix: 히스토리 저장 시 출력 띄어쓰기해서 저장](https://github.com/dlxortmd987/java-calculator/commit/5f966a84eb49d86daf05ed49b14190b0afdb2fdb) -> 계산 이력 저장시 띄어쓰기 해서 저장
- [fix: 0으로 나눈 경우 validation 수정](https://github.com/dlxortmd987/java-calculator/commit/dc66c8c933137ea10f3cd99119e8f61cac45f3a7) -> Zero Division Exception 부분 수정
- [fix: validation 코드 분리](https://github.com/dlxortmd987/java-calculator/commit/d15b5ae901e00639714d53e587e47067f47c6b0e) -> Validation 처리 코드 따로 클래스 생성
- [fix: 계산기 기능 테스트 코드 수정](https://github.com/dlxortmd987/java-calculator/commit/7acca10a176606c3e2af3398d86548460f3634b5) -> 테스트 코드 새로 작성

## ✅ 피드백 반영사항  
[x] 1 / 0
[x] - 1 * - 1
[x] 210000000000 * 2
[x] 1 + + 1
[x] 종료 버튼
[x] 테스트 실패 케이스 작성
[x] if-else 문 깊이 줄이기
[x] 답, 식, 등식 wrapping 클래스 추가
[x] Optional 부분 삭제 (사용하기 애매한 부분)
[x] 저장 부분과 계산 부분 분리

## ✅ PR 포인트 & 궁금한 점 
- 저장 기능을 테스트 하려면 save와 findAll을 한 테스트에서 불러야 하는데 따로 테스트하도록 바꾸는 방법이 궁금합니다.

2022-10-28 04:03 UTC, WooSungHwan requested changes
수고하셨습니다! 코멘트 확인해주세요! ㅎㅎ

2022-10-28 12:48 UTC, dlxortmd987 commented on calculator/src/main/java/com/programmers/java/engine/model/MenuType.java
> +    }
사실 Unknown 으로 처리할까 Exception 처리를 할까 고민했는데 모르고 두 개 다 적은 것 같아요. Exception 처리만 하는 걸로 바꿀 예정입니다!

2022-10-29 04:48 UTC, WooSungHwan commented
저장 기능을 테스트 하려면 save와 findAll을 한 테스트에서 불러야 하는데 따로 테스트하도록 바꾸는 방법이 궁금합니다.

-> save하고 단건을 호출할 수 있도록 수정하세용. save한 놈이랑 데이터가 같으면 되겠네요.

2022-10-29 10:55 UTC, dlxortmd987 commented on calculator/src/main/java/com/programmers/java/App.java
> +            }
이 부분 수정 완료했습니다!

2022-10-29 10:58 UTC, dlxortmd987 commented on calculator/src/main/java/com/programmers/java/engine/history/HistoryInMemoryInterface.java
> +    }
일단 Expression과 EquationRecord를 일급 컬렉션으로 생각해서 로직을 구현해봤습니다. 
Expression에서 생성할 경우 validation 처리를 위해 Validation의 구현체를 builder를 통해 주입받고 있는데 이렇게 하는 것보다 더 좋은 방법이 있을지 궁금합니다. 
고민해본 내용으로는 TokenValidator의 메소드를 static으로 만드는 것인데 혹시 이 방법이 맞을까요?

2022-10-29 11:00 UTC, dlxortmd987 commented on calculator/src/main/java/com/programmers/java/engine/calculator/CalculatorImpl.java
> +    }
일단은 Calculator 에는 계산 기능만 넣었고 후위 연산은 PostfixUtils 로 넣어봤습니다!

2022-10-29 11:01 UTC, dlxortmd987 commented
> 저장 기능을 테스트 하려면 save와 findAll을 한 테스트에서 불러야 하는데 따로 테스트하도록 바꾸는 방법이 궁금합니다.
> 
> -> save하고 단건을 호출할 수 있도록 수정하세용. save한 놈이랑 데이터가 같으면 되겠네요.
> -> 감사합니다! 이렇게 수정해보겠습니다.

2022-10-30 05:45 UTC, choi1204 reviewed
고생하셨습니다. 택승님
코멘트 확인하시고 학습에 도움되시면 좋겠습니다

2022-10-30 05:45 UTC, choi1204 commented on calculator/src/main/java/com/programmers/java/App.java
> +            return null;
이 부분 65번째 line에 menuType = null 로 해서 간략화 하면 어떨까요?

2022-10-30 05:45 UTC, choi1204 commented on calculator/src/main/java/com/programmers/java/application/config/Validator.java
> +public interface Validator {
Exception을 주로 CustomException을 사용하시네요.
CustomExcpetiopn을 왜 사용하고 왜 사용하면 안되는지 정리를 하시고 사용하시면 좋을 것 같아요
이 주제에는 정답이 없고 주로 개발자들끼리 얘기를 하는 주제이기에 말씀드려요

2022-10-30 05:45 UTC, choi1204 commented on calculator/src/main/java/com/programmers/java/engine/model/History.java
> +        if (equations.containsKey(equation)) {
return !equations.containsKey(equation);
로 축약가능할 것 같네요

2022-10-30 05:45 UTC, choi1204 commented on calculator/src/main/java/com/programmers/java/application/Operator.java
> +    private static Map<String, Operator> operatorMap = Collections.unmodifiableMap(
Enum을 검색할때 주로 사용되는 방법이 주로
1.택승님이 사용하신 static Map을 활용하여서 미리 초기화 시켜두는 방법
2.검색시 Enum.values을 활용해서 검색하는 방법 
이렇게 나누어지는데 각각의 방법의 장단점을 파악하면 좋을 것 같아요

2022-10-30 06:04 UTC, dlxortmd987 commented
> 고생하셨습니다. 택승님
> 코멘트 확인하시고 학습에 도움되시면 좋겠습니다

> 피드백 감사함니다! 확인하고 공부해볼게요!

2022-10-31 09:28 UTC, WooSungHwan approved these changes
과제하시느라 고생하셨습니다. 조그맣게 노친 부분들 짚어드렸어요! ㅎㅎ

2022-10-31 09:28 UTC, WooSungHwan commented on calculator/src/main/java/com/programmers/java/App.java
> +                    option = new HistoryOption(console, historyRepository);
이거는 사실 선택할때마다 힙에 인스턴스를 생성해서 좋은 구조는 아닌것같아요. 아무리 싱글스레드라고 해도 gc에 대한 부담을 주게 됩니다. gc의 stop the world 라는 내용을 참조해보세요.

2022-10-31 09:28 UTC, WooSungHwan commented on calculator/src/main/java/com/programmers/java/engine/option/CalculatorOption.java
> +                    .build();
노파심에 말씀드립니다만. 나중에 try - catch는 이렇게 데이터 처리로 쓰일 수 있지만 되도록이면 exception을 한곳에서 처리하게 될거에요.
Spring 배울때 RestControllerAdvice 라는 어노테이션 꼭 돌아보시고 원하는 OnlyNumberException이 아닌 Exception이 터졌을 경우에도 고민을 해주세요 ㅎㅎ

2022-10-31 09:28 UTC, WooSungHwan commented on calculator/src/main/java/com/programmers/java/engine/model/Equation.java
> +    }
오.. 좋은 시도네요 ㅎㅎ 근데 equals와 hashCode의 기준이 다른데 달라도 괜찮을까요?ㅎㅎ

2022-10-31 09:43 UTC, dlxortmd987 commented
> 과제하시느라 고생하셨습니다. 조그맣게 노친 부분들 짚어드렸어요! ㅎㅎ
> 말씀하신거 조사해보고 고쳐볼게요! 감사합니다.

2022-11-04 18:19 UTC, merged