parksejun/java-caculator
prgrms-be-devcourse/java-calculator pull request #111
Opened 2022-10-28 14:36 UTC by park-se-jun

## 📌 과제 설명 

## 👩‍💻 요구 사항과 구현 내용 

-  [x]  더하기
-  [x]  빼기
-  [x]  곱하기
-  [x]  나누기
-  [x]  우선순위(사칙연산)
-  [x]  계산 이력을 맵으로 데이터 저장기능 만들기
-  [ ]  테스트 코드 구현하기 <- 추후 추가

## ✅ 피드백 반영사항  
Page 구조를 다 드러내 주었으면 좋겠다.
-  Page 구조를 다 드러내고 controller와 Service 구조로 변경하였습니다.
- 처음에 switch case 문을 타고 controller의 로직을 실행합니다.
- Page에 개별로 붙어있던 input, output을 Console로 만들어 에러처리, 입력 출력을 한번에 관리합니다.

레이어간 전달되는 객체를 Wrapping 했으면 좋겠다
- DTO로 Data들을 Wrapping 하였습니다.

그때 일단 피드백을 하기엔 너무 코드가 달라서 page를 전부 드러내 달라는 큰 피드백 하나를 위주로 진행했습니다!
또한 page 제거 작업을 진행하면서 계층간 전달되는 데이터의 wrapping까지 해봤습니다.

제가 미쳐 적용시키지 못한 세부적인 피드백들 해주시면 감사하겠습니다..!
## ✅ PR 포인트 & 궁금한 점 

service와 controller의 경우 해당 객체가 service이다, controller이다 라는것을 알려줘야 할것 같아 일단 Service와 Controller라는 interface를 만들고 implement를 하는데 코드를 강제하거나 그러지는 않습니다.
만약 어떤 코드를 강제한다고 해도 Service와 Controller는 각각마다 Return도 다르고, 파라미터도 달라서 어떤 코드를 강제해야할지 잘 모르겠습니다. 어떻게 해야 할까요?

Exception들을 따로 만들지 않고 new Exception에 메시지를 그때그때 넘겨주는 방식으로 구현이 되어 있는데 전부 만드는 편이 나을까요?

여러 Spring 예제 코드들을 보고 Controller, Service, Dto를 흉내내 봤는데 객체지향관점으로 봤을때 어떤가요?

CaculationController에서 뭔가 기차놀이 하는듯한 코드 작성이 이루어 졌는데 괜찮은 건가요?

지금은 response를 바로 다음 Service의 매개변수로 넣어주고 있는데, requestDto를 따로 만드는게 맞을까요?

저는 현재 Dto를 만들때 public static final from 메소드를 구현해 만들고 있는데 Dto는 일반적으로 어떤 방식으로 만들어 지나요? 

추가적인 피드백 부탁드립니다....!
p.s 일단 풀리퀘를 하나 만들어야할것 같아서 테스트 코드는 한개도 없습니다...  계속 추가하겠습니다...

2022-10-30 00:14 UTC, WooSungHwan requested changes
세준님 코드가 정말 좋아졌네요 ㅎㅎ 코멘트확인 부탁드려요!

2022-10-30 00:14 UTC, WooSungHwan commented on src/main/java/com/programmers/ConsoleCaculator.java
> +            .tokenizeService(new TokenizeService()).build();
이 부분은 너무 클래스들이 강하게 ConsoleCalculator와 엮여있기 때문에 주입을 받는게 좋습니다.

2022-10-30 00:14 UTC, WooSungHwan commented on src/main/java/com/programmers/ConsoleCaculator.java
> +            }
딱 좋습니다. 이런 Private 메소드로부터  추상화가 들어가야합니다 ㅎㅎ

2022-10-30 00:14 UTC, WooSungHwan commented on src/main/java/com/programmers/ConsoleCaculator.java
> +            }
다만 1 2 3 에 대한 변수화가 진행되면 좋겠네요. enum으로 관리되면 좋을 것 같습니다.

2022-10-30 00:14 UTC, WooSungHwan commented on src/main/java/com/programmers/ConsoleCaculator.java
> +    }
system.exit 호출은 하지마세요.

2022-10-30 00:14 UTC, WooSungHwan commented on src/main/java/com/programmers/ConsoleCaculator.java
> +    }
적절하게 로직을 끝낼 고민을 해주세요.

2022-10-30 00:14 UTC, WooSungHwan commented on src/main/java/com/programmers/caculation/ParseService.java
> +    public ParseResponseDto parseRequest(Collection<NumberAndOperator> numOrOp){
Collection 보다는 List, Map, Set 같은 인터페이스 사용을 권장합니다. Object 를 파라미터로 선언하는 느낌이라서 컬렉션은 저 세가지 타입으로 구분해주세요.

2022-10-30 00:14 UTC, WooSungHwan commented on src/main/java/com/programmers/caculation/TokenizeService.java
> +public class TokenizeService implements Service {
이 클래스는 tokenize 메소드의 로직이 너무 크네요. 다른 클래스들처럼 적절히 private 메소드로 분리해보세용.

2022-10-30 00:14 UTC, WooSungHwan commented on src/main/java/com/programmers/caculation/parser/PostfixParser.java
> +    public ParseResponseDto parse(Collection<NumberAndOperator> numOrOp) {
depth 가 너무 깊습니다. 적절히 메소드 extract 진행해주세요.

2022-10-30 00:14 UTC, WooSungHwan commented on src/main/java/com/programmers/io/Console.java
> +public class Console implements Input, Output {
깔끔하네요

2022-10-30 00:14 UTC, WooSungHwan commented on src/main/java/com/programmers/util/Operator.java
> +public class Operator {
이 클래스는 new 로 인스턴스 생성할 수 없는 구조로 변경해주세요 ㅎㅎ

2022-10-30 00:22 UTC, WooSungHwan commented
service와 controller의 경우 해당 객체가 service이다, controller이다 라는것을 알려줘야 할것 같아 일단 Service와 Controller라는 interface를 만들고 implement를 하는데 코드를 강제하거나 그러지는 않습니다.
만약 어떤 코드를 강제한다고 해도 Service와 Controller는 각각마다 Return도 다르고, 파라미터도 달라서 어떤 코드를 강제해야할지 잘 모르겠습니다. 어떻게 해야 할까요?
-> 코드를 강제한다는건 어떤의미인가요? 인터페이스를 구현하는 것 자체가 코드의 구현을 강제하는 행위입니다.

Exception들을 따로 만들지 않고 new Exception에 메시지를 그때그때 넘겨주는 방식으로 구현이 되어 있는데 전부 만드는 편이 나을까요?
-> 미래의 세준님도 팀으로 생각한다면 팀의 비즈니스로직 이해를 위해서 만들어주는게 백배 좋습니다.ㅎㅎ

여러 Spring 예제 코드들을 보고 Controller, Service, Dto를 흉내내 봤는데 객체지향관점으로 봤을때 어떤가요?
-> 차라리 지금 시점에서는 그렇게 흉내내보시는게 더 좋을 것 같습니다. 객체지향 관점에서는 스스로 계속 이렇게 질문 던져가면서 고민해보시고 정교하게 바로잡아나가 보셔요. 클래스네이밍 자체로도 효과가 좋습니다.

CaculationController에서 뭔가 기차놀이 하는듯한 코드 작성이 이루어 졌는데 괜찮은 건가요?
-> 기차놀이가 뭔지 모르지만.. 좀더 엔터로 구분을 줘도 되고 private 메소드로 구분을 단순화해줘도 될것 같습니다!

지금은 response를 바로 다음 Service의 매개변수로 넣어주고 있는데, requestDto를 따로 만드는게 맞을까요?
-> 네 목적이 다른다면 따로 만들어주세요.ㅎㅎ

저는 현재 Dto를 만들때 public static final from 메소드를 구현해 만들고 있는데 Dto는 일반적으로 어떤 방식으로 만들어 지나요?
-> 어떤 방식이 있는건 아닙니다. 비슷하게 만듭니다. ㅎㅎ

2022-10-30 07:45 UTC, choi1204 reviewed
세준님 코드가 진짜 몰라보게 바뀌었군요! 
고생 많으셨습니다!!
전반적으로 interface로 추상화를 할려는 노력이 보였습니다.
왜 자바에서는 interface를 사용하는지, interface를 효율적으로 사용할려면 어떻게 할지 서칭해보면 좋을 것 같아요!

2022-10-30 07:45 UTC, choi1204 commented on src/main/java/com/programmers/ConsoleCaculator.java
> +    Console console = new Console();
콘솔을 그대로 사용하게 되는데 이렇게 되면 input과 output을 인터페이스로 추상화한 이유가 없는 것같아요.
인터페이스인 Input과 Output을 받고 그걸 인터페이스로 사용하는 것을 추천합니다.
그렇게 해야 나중에 콘솔이 아닌 파일 입출력으로 바뀌어도 FileInput, FileOutput을 바꿀때 의존성만 바꿀 수 있는 코드가 될 것같아요!

2022-10-30 07:45 UTC, choi1204 commented on src/main/java/com/programmers/caculation/model/Expression.java
> +    final String originExpression;
아래 두 변수 result와 allExpression의 경우에는 바뀔 수 있기에 final을 안하신것인가요?

2022-10-30 07:45 UTC, choi1204 commented on src/main/java/com/programmers/caculation/model/NumberAndOperator.java
> +        if (number != null) {
위 식은 
number != null 로 간략히 표현이 가능할 것 같네요.
하지만 number가 null일 수도 있기에 Objects클래스를 활용해서 null 체크를 해주시면 좋을 것 같아요

2022-10-30 08:22 UTC, park-se-jun commented on src/main/java/com/programmers/util/Operator.java
> +public class Operator {
private constructor를 추가하였습니다

2022-10-30 08:22 UTC, park-se-jun commented on src/main/java/com/programmers/io/Console.java
> +public class Console implements Input, Output {
감사합니다.

2022-10-30 08:22 UTC, park-se-jun commented on src/main/java/com/programmers/caculation/parser/PostfixParser.java
> +    public ParseResponseDto parse(Collection<NumberAndOperator> numOrOp) {
depth를 줄였습니다.

2022-10-30 08:22 UTC, park-se-jun commented on src/main/java/com/programmers/caculation/TokenizeService.java
> +public class TokenizeService implements Service {
tokenize를 token으로 빼고, 로직을 나눠봤습니다.근데  tokenize랑 validation이랑 역할이 강하게 결합되 있는 문제를 발견했습니다....그러다보니 함수명이괴랄해지네요....

2022-10-30 08:22 UTC, park-se-jun commented on src/main/java/com/programmers/caculation/ParseService.java
> +    public ParseResponseDto parseRequest(Collection<NumberAndOperator> numOrOp){
List로 전부 변경했습니다.

2022-10-30 08:22 UTC, park-se-jun commented on src/main/java/com/programmers/ConsoleCaculator.java
> +    }
exitSign이라는 필드를 두어 while문 진입시 exitSign을 확인하도록 변경하였습니다.

2022-10-30 08:22 UTC, park-se-jun commented on src/main/java/com/programmers/ConsoleCaculator.java
> +            }
default의 경우도 추상화하였습니다.
1,2,3dmf Menu enum으로 변경 하였습니다.
근데 로직이 조금 한바퀴 돌아가는 느낌이라서 흑구님이라면 어떻게 했을지가궁금합니다..!

2022-10-30 08:22 UTC, park-se-jun commented on src/main/java/com/programmers/ConsoleCaculator.java
> +            .tokenizeService(new TokenizeService()).build();
AppConfig를 생성해 그곳에서 static final로 클래스들을 만들고 넣어주게 바꿨습니다.

2022-11-01 10:35 UTC, park-se-jun commented on src/main/java/com/programmers/ConsoleCaculator.java
> +            }
1,2,3을 이넘으로 변경하는 과정에서 사용자의 입력을 제대로 받지 못하는 문제를 발견했습니다.
이를 수정했습니다.

2022-11-01 10:35 UTC, park-se-jun commented on src/main/java/com/programmers/caculation/model/NumberAndOperator.java
> +        if (number != null) {
Objects.isNull()이라는게 있었군요! 수정했습니다!

2022-11-01 10:35 UTC, park-se-jun commented on src/main/java/com/programmers/caculation/model/Expression.java
> +    final String originExpression;
alllExpression의 경우  getAllExpression을 할때 생성되기 때문에 final을 안했고, result의 경우 처음에는 Expression에서 만들었었기 때문에 final이 안붙어 있었습니다! result에 final 키워드 추가 하였습니다.

2022-11-01 10:35 UTC, park-se-jun commented on src/main/java/com/programmers/ConsoleCaculator.java
> +    Console console = new Console();
input과 output의 확장성에 대해 고려하지 못했네요! 변경했습니다!

2022-11-04 03:23 UTC, WooSungHwan approved these changes
코드가 많이 발전하셨네요. ㅎㅎ 좀더 OOP를 추구해보고자 한다면 제가 코멘트한 부분 떠올려보시고 적용해보시면 좋을 것 같습니다.
main 메소드에서 뭘 바로 시작한다고 생각하지는 마시고 프레임워크에서 필요한 Bean들을 먼저 생성해내는 부분을 떠올려보시고 수정해보시면 좋을 것같습니다. 
그래야 클래스들이 서로 분리가되어 테스트에도 많은 모킹을 하지 않고 특정 로직만 테스트하기에도 용이해질 것 같아요 ㅎㅎ

2022-11-04 03:23 UTC, WooSungHwan commented on src/main/java/com/programmers/ConsoleCaculator.java
> +            excuteByUserInput(userInput);
이런애들이 이제 클래스로 따로 빠져서 역할을 하게 됩니다. 그럼 내부적으로 주입이 한번 더 필요하겠죠? 그때 인터페이스를 도입해서 구현체마다 다른 일을 하도록 다형성을 구성할 수 있습니다.

private 메소드로 분리하고나서 class로 빠지고 추상화가 가능한 객체가 될지. 인터페이스로 분리할 수 있을지. 분리해서 내가 취할 수 있는 이득은 뭐가 있을지?

인터페이스로 분리할 수 있다면 다형성을 활용하여 구현체만 갈아 끼움으로써 해당 인터페이스를 직접 호출하는 부분에 대한 수정을 배재할 수 있습니다.

이 부분 한번 리마인딩 해보세요 ㅎㅎ

2022-11-04 03:23 UTC, WooSungHwan commented on src/main/java/com/programmers/Main.java
> +        new ConsoleCaculator().start();
ConsoleCalculator 클래스가 아닌 다른 클래스를 정의해서 구현해야한다면 여기있는 Main 클래스의 main 메소드를 수정해야될 일이 있겠군요? 
근데 Main 메소드를 프레임워크라고 생각한다면 그 부분은 당연한 것 같습니다. 그렇다면 다른 부분에서는 특정 클래스를 수정할때 다른 부분이 변경되어야 하는 분이 없을지를 봐야합니다.

그렇다면 변경이필요한 부분은 한군데일 필요가 있을 것 같습니다.

따라서 Calcuatror를 추상화를 하여 갈아끼우는 방법을 고려하면 좋을 것 같고 Main 클래스가 프레임워크라고 생각하고 코드를 변경해보면 좋을 법합니다.

이 main 메소드에서 리소스를 만들고(new 생성자) 주입해서 넣는 방식으로 변경해보세요!

2022-11-04 03:23 UTC, WooSungHwan commented on src/main/java/com/programmers/caculation/CaculationController.java
> +    private HistoryRepository  historyRepository;
얘는 왜 final이 아닌가요?

2023-06-05 18:38 UTC, closed without merging