[4기-구범모] 1~2주차 과제 : 계산기 구현 미션 제출합니다.
prgrms-be-devcourse/java-calculator pull request #114
Opened 2023-06-05 02:53 UTC by BeommoKoo-dev

- 객체지향적인 코드로 계산기 구현하기
    - [x]  더하기
    - [x]  빼기
    - [x]  곱하기
    - [x]  나누기
    - [x]  우선순위(사칙연산)
- [x]  테스트 코드 구현하기
- [x]  계산 이력을 맵으로 데이터 저장기능 만들기
    - 애플리케이션이 동작하는 동안 데이터베이스 외에 데이터를 저장할 수 있는 방법을 고안해보세요.
- (선택) 정규식 사용 (아직 구현하지 않았습니다.)

# 계산기 과제

## 구현 내용

### Commander

기본적인 입력을 받는 클래스입니다. `Memorizer`, `Calculator` 클래스와 연관 관계에 있습니다.

입력을 받고, 입력 중에서 input 형식에 맞지 않는 입력을 예외처리 해주고, input 형식이 맞으면 해당 command에 맞게 명령을 수행합니다.

마지막으로 맞는 input이라면, calculator에서 연산을 수행한 이후, input으로 받은 수식과 결과값을 합쳐 memorizer에 저장까지 해줍니다.

### Memorizer

객체가 하나만 있으면 된다고 보아, 싱글톤으로 구현해 보았습니다.

`1.조회` 에 해당하는 기능을 수행하는 클래스입니다. 계산의 결과를 `Queue<> history` 에 저장하여, FIFO형식으로 먼저 계산됐던 수식들과 결과를 출력합니다.

### Calculator

역시 객체가 하나만 있으면 된다고 보아, 싱글톤으로 구현해 보았습니다.

`2.계산`에 해당하는 기능을 수행하는 클래스이며, 주어진 연산의 핵심이 되는 클래스입니다.

### calculate() 메소드

연산자의 모음이 되는 `Ops enum` 을 inner enum으로 선언해 주고, 해야 할 연산의 형태가 덧셈 / 뺄셈 인 경우에는 `PM` Ops, 해야 할 연산의 형태가 곱셈 / 나눗셈인 경우에는 `MD` Ops에 해당 연산의 형태를 memoizing합니다.

command에는 정수, 연산자가 담겨 있습니다.

들어가기에 앞서, flush란, 스택에 들어있는 정수를 단순히 결과값을 저장하는 result변수에 덧셈 / 뺄셈해주는 것을 뜻합니다.

연산의 로직은 이렇습니다.

1. 해당 command가 정수인 경우.
- 스택이 비어있는 경우 : 이전의 덧셈 / 뺄셈연산에 의해 스택이 flush된 상태이므로, 단순히 스택에 해당 정수를 push합니다.
- 스택이 비어있지 않은 경우 : 이전의 곱셈 / 나눗셈 연산에 의해 스택에 이전 정수값이 flush되지 않고, 곱셈 / 나눗셈 연산을 기다리는 상태입니다. 이전 값(stack top)과 이전의 곱셉 / 나눗셈 연산이 저장된 MD Ops에 맞게 `이전 값과 현재 값의 연산`을 수행하고, 다시 스택에 push합니다.
2. 해당 command가 연산자인 경우.
- +, - 연산자인 경우 : 이전까지 연산이 진행되었던 값을 flush해 줍니다. 이 때, flush를 덧셈으로 해 줄지, 뺄셈으로 해 줄지는 해당 시점의 연산자에 결정되지 않고, 제일 최근의 +, - 연산자에 의해 진행됩니다. (`PM` Ops에 해야할 연산의 유형이 저장되어 있습니다. )
    
    마지막으로 `PM` 값을 해당 시점의 +, - 연산형태로 갱신합니다.(이후의 flush의 부호에 영향을 주기 위함.)
    
- *, / 연산자인 경우 : flush해주지 않습니다. 단순히 `MD` 값에 해당 곱셈 / 나눗셈 연산형태를 저장해 둡니다.

## PR 포인트

저는 객체지향 프로그래밍을 잘 하지 않는 편입니다. 

따라서 필요한 클래스와 각 의존관계를 설정해 보고 코드 작성에 들어갔으나, 

1. 클래스마다 정말 필요한 기능만 추가한 것인지, 클래스를 더 세분화 시킬 수 있는지
2. 프로젝트 명세상 싱글톤 구현을 하는 것이 맞는지, 맞다면 싱글톤스럽게(?) 구현을 잘 한것인지
3. 각 함수 혹은 멤버변수가 static / non-static으로 잘 선언되어 있는건지. 언제 static을 선언해야 하고 언제 non-static으로 선언해야 하는지
4. 객체지향에 맞는 코드인지
5. 요구사항 중 `계산 이력을 맵으로 데이터 저장기능 만들기` 가 있었는데, 큐가 아닌 맵을 이용할 필요성이 있는지

감이 잘 오지 않아서, 위를 중점으로 코드리뷰해 주시면 감사드립니다.

긴 글 읽어주셔서 감사드립니다.

2023-06-05 05:12 UTC, BeommoKoo-dev commented
![java-calculator (1)](https://github.com/prgrms-be-devcourse/java-calculator/assets/95630007/28c4afab-1e5b-4f8c-ae9c-728492a6e2a6)
추가적으로 클래스 다이어그램 첨부드립니다

2023-06-05 05:16 UTC, dojinyou commented on src/src/Commander.java
> +public class Commander {
명령(요청)을 하는 객체인 것 같은 데, 꽤 많은 일을 하고 있어요!
입력을 받기 위한 준비, 출력, 출력해야할 것들에 대한 정보를 가지고 있는 등! 역할을 나눠보시면 좋을 것 같아요!

2023-06-05 05:16 UTC, dojinyou commented on src/src/Commander.java
> +                if(menu == 3) {
`3`이라는 단순한 숫자가 어떤 의미를 가지는 지가 드러나지 않아서 다른 사람이 보았을 때는 이 의미를 알기가 어려운 것 같아요!
이런 걸 보통 [매직넘버](https://drehzr.tistory.com/1136)라고 하는 데 이런 부분을 전체적으로 개선해보시면 좋을 것 같아요.

2023-06-05 05:16 UTC, dojinyou commented on src/src/Commander.java
> +        Scanner scanner = new Scanner(System.in);
만약, 입출력 방식이 변경된다면(예를 들어 파일로 읽고 json으로 출력을 해준다던지?) 코드 수정이 굉장히 많을 것 같아요!
이런 부분도 역할로 보고 분리하시면 좋을 것 같아요!

2023-06-05 05:16 UTC, dojinyou commented on src/src/Commander.java
> +        String s;
변수 네이밍도 직관적으로 이해할 수 있으면 좋을 것 같아요. 
`s`라는 네이밍은 짐작은 가지만 직관적이진 않은 것 같아서 더 좋은 이름을 부여하면 좋을 것 같아요

2023-06-05 05:16 UTC, dojinyou commented on src/src/Commander.java
> +    public static boolean isDigit(String s) {
`char`의 Wrapper Class `Charater.isDigit`이라는 [메서드](https://docs.oracle.com/javase/8/docs/api/java/lang/Character.html#isDigit-char-)도 한번 보시면 좋을 거 같아요!

2023-06-05 05:16 UTC, dojinyou commented on src/test/CalculatorTest.java
> +    void calculateTest() {
밑에 여러 테스트의 형태가 유사한 건 `동일한 테스트의 파라미터`만 다르기 때문인 거 같아요.
[@ParameterizedTest](https://www.baeldung.com/parameterized-tests-junit-5) 관련해서 한번 찾아보시면 좋을 것 같아요!

2023-06-05 05:36 UTC, BeommoKoo-dev commented on src/src/Calculator.java
감사합니다 ! 구현 이후에도 객체지향성이 많이 떨어진다고 스스로 느껴졌는데, 링크 참고하고 코드 수정을 좀 더 해보겠습니다!
피드백 감사드립니다.

2023-06-05 06:30 UTC, dojinyou commented on .idea/.gitignore
https://gitignore.io/ 라는 곳을 이용하면 간단한 태그들로 만들 수 있어요!

2023-06-05 14:21 UTC, seung-hun-h requested changes
1. 클래스마다 정말 필요한 기능만 추가한 것인지, 클래스를 더 세분화 시킬 수 있는지
- 한 클래스가 많은 기능을 하고 있는 것 같아요
- 연산자, 숫자도 클래스로 만들어 볼 수 있겠네요

2. 프로젝트 명세상 싱글톤 구현을 하는 것이 맞는지, 맞다면 싱글톤스럽게(?) 구현을 잘 한것인지
- 리뷰 남겼습니다
- 싱글톤을 왜 써야하는 지 고민해보세요. 여러 사용자가 있을 때 각각 서로 다른 상태를 가져야 한다면 싱글톤은 적절하지 않을 것 같네요

3. 각 함수 혹은 멤버변수가 static / non-static으로 잘 선언되어 있는건지. 언제 static을 선언해야 하고 언제 non-static으로 선언해야 하는지
- static을 사용하면 한 클래스의 모든 인스턴스가 해당 데이터를 공유하게 됩니다.
- 예를 들어 자바에서는 상수를 `static final` 키워드를 사용하여 선언합니다. 상수는 변하지 않는 값이므로 모든 인스턴스가 공유할 수 있습니다.
- 메소드를 static으로 선언하면, 그 메소드는 클래스 메소드가 되어 객체 생성 없이 클래스 이름으로 직접 호출이 가능합니다. 보통 유틸 메서드에서 많이 사용합니다

5. 요구사항 중 계산 이력을 맵으로 데이터 저장기능 만들기 가 있었는데, 큐가 아닌 맵을 이용할 필요성이 있는지
- 일단 구현하신 코드를 보면 큐를 사용하셨어요. poll하고 add 하는 과정이 조회때 마다 반복되고 있는데 조금 비효율적일 수 있겠죠
- 맵을 사용하는 이유는 키를 알고있을 때 상수시간(O(1))에 원하는 값을 찾기 위함입니다. 만약에 각 연산에 키를 부여한다면 나중에 연산 결과를 찾기 쉬울 것 같네요
- 키를 부여하지 않고 순서대로 모든 값을 보여준다면 오히려 ArrayList 같은 자료구조를 사용하는 것이 더 좋아보이네요

2023-06-06 00:04 UTC, BeommoKoo-dev commented on src/src/Commander.java
> +                if( (s.equals("+") || s.equals("-") || s.equals("*") || s.equals("/") ) == false )
아! 다른분들께서 구현한 코드를 조금씩 봤는데, Enum에서 사칙연산을 정의하신 코드를 자주 봤습니다!
잘 모르는 부분이라 이게 뭔지 싶었는데 이런 부분이였군요! 첨부하신 링크가 도움이 많이 되었습니다. 토대로 코드 수정해보겠습니다!
감사합니다.

2023-06-06 00:05 UTC, BeommoKoo-dev commented on src/src/Calculator.java
> +    private static Ops MD;
감사합니다. 싱글쓰레드 환경에서만 프로그램을 생각하고 오류를 범했던 것 같습니다!

2023-06-06 06:25 UTC, BeommoKoo-dev commented
@seung-hun-h 안녕하세요 승훈멘토님, 먼저 리뷰에 감사드립니다!!
다름이 아니라 남겨주신 리뷰 토대로 코드를 수정하고 있는데, 연산자 같은 경우에는 Enum으로 관리하여 얻을 수 있는 이점이 많을거라고 생각됩니다.
다만 숫자(이하 Number)도 클래스로 만들면 좋겠다고 하셨는데, 제 생각에는 받은 입력(String)을 int로 치환하고, 그 안에서 valid한 input인지를 검증하는 기능 빼고는 Number 클래스가 갖는 이점이 없을 것 같다고 생각이 듭니다.
하지만 Number클래스를 만든다는 것 자체가 단일책임과 연관이 있어, 이 클래스가 담당하는 일을 하나로 만듦과 동시에 다른 클래스에서의 책임을 덜어주는 것으로 받아들이고 Number클래스를 작성하는게 좋을까요?? 미리 답변에 감사드립니다.

2023-06-06 06:29 UTC, seung-hun-h commented
> @seung-hun-h 안녕하세요 승훈멘토님, 먼저 리뷰에 감사드립니다!! 다름이 아니라 남겨주신 리뷰 토대로 코드를 수정하고 있는데, 연산자 같은 경우에는 Enum으로 관리하여 얻을 수 있는 이점이 많을거라고 생각됩니다. 다만 숫자(이하 Number)도 클래스로 만들면 좋겠다고 하셨는데, 제 생각에는 받은 입력(String)을 int로 치환하고, 그 안에서 valid한 input인지를 검증하는 기능 빼고는 Number 클래스가 갖는 이점이 없을 것 같다고 생각이 듭니다. 하지만 Number클래스를 만든다는 것 자체가 단일책임과 연관이 있어, 이 클래스가 담당하는 일을 하나로 만듦과 동시에 다른 클래스에서의 책임을 덜어주는 것으로 받아들이고 Number클래스를 작성하는게 좋을까요?? 아니면 이 부분은 구현에 따라 만들지 않아도 되는 클래스일까요?? 미리 답변에 감사드립니다.

네 구현에 따라 Number 클래스를 만들 수도 있고 그렇지 않을 수도 있습니다. 범모님이 말씀하신 정도면 굳이 만들 필요가 없을 수 있어요.
Number 클래스를 만드는 것이 정답이라는 것이 아니라 만들어 볼 수도 있겠다는 의미로 드린 말이었어요.

2023-06-06 06:38 UTC, BeommoKoo-dev commented
@seung-hun-h 넵 알겠습니다. 혹시 다음 커밋부터 gitignore해도 될까요??

2023-06-06 06:39 UTC, merged