Handmade cloud
prgrms-be-devcourse/java-calculator pull request #115
Opened 2023-06-05 05:43 UTC by HandmadeCloud

## 📌 과제 설명

자바 계산기를 객체지향적으로 생각해보면서 한 미션입니다.

## 👩‍💻 요구 사항과 구현 내용
후위표기식 연산 완료_1

우선 연산자와 피연산자의 관계로 나누어 생각했습니다.

1. 
연산자의 경우 enum 클래스의 특성을 활용해서 연산을 수행할 수 있는 메소드와 함께 넣었습니다.
데이터간의 연관관계를 표현하고 상태와 행위를 한곳에서 처리하도록 했습니다.
사칙연산의 우선순위를 생각해 그 속성을 추가한 것이 포인트!

2.
피연산자의 경우 계산기 클래스에서 진행했습니다. 연산의 우선순위를 위해 후위표기법으로 변경하는 로직을 구현했습니다.

3. 
메인에서는 지금까지 구현한 내용을 확인하게 부득이하게 후위표기법 내용이 있습니다만, 계산 과정에서는 수정할 예정!

## ✅ PR 포인트 & 궁금한 점
1. 이렇게 설계하는게 맞나요? ㅋㅋㅋㅋ
2. 객체지향적으로 누가 책임을 가지고 어떻게 메세지를 보내는 지에 대해서 생각하면서 구현했습니다.
    수정할 포인트가 있다면 말씀해주세요!

2023-06-06 04:03 UTC, Jo-GyuHyeon requested changes
안녕하세요 재현님 반갑습니다. 🙇 
첫 PR 축하드려요. 🥳 

리뷰 코멘트에 앞어서 git 에 대한 리뷰도 드리면 어떨까 해요.
프로젝트에서 형상관리에 불필요한 파일들은 .gitignore 로 등록하시면 좋을것 같아요.

참고 링크에요.
https://git-scm.com/docs/gitignore
https://www.toptal.com/developers/gitignore

해당 프로젝트 구조에 대해 말씀드리고 싶은 부분이 있어요.
java 공식 문서로 존재 하진 않지만, 표준 처럼 사용 되는 구조는 src/main 이라는 폴더 구조를 가지고 있어요.
maven, gradle 에서는 해당 구조는 규칙으로 가이드 되어 있기도 해요.

intellij, eclipse 등 java 프로젝트를 생성 하면 src/main 으로 구성 되어 있을거에요.
해당 repository 를 clone 받은 후 많은 사용자들이 사용하는 IDE 에서 실행 가능 한 것을 선호하고 제안 드리고 싶어서 말씀드려 보았어요. 🙇 

후위식으로 변경 하신 이유는 우선순위를 고려 했기 때문이라고 PR 설명을 보았습니다.
해당 메서드가 고민할 포인트가 많을것 같은데요. 현재 리뷰 내용이 많으니 우선순위는 다음 PR 에서 진행 해보는것은 어떨까요?

2023-06-06 08:43 UTC, HandmadeCloud commented on CalculateType.java
> +    });
나눗셈에만 예외처리가 생각나서 여기에 했었는데, 다른 예외사항도 고려하면 책임을 따로 분리하는게 좋을 것 같네요 👍

2023-06-06 08:45 UTC, HandmadeCloud commented on CalculateType.java
> +                .orElse(null);
Optional 을 잠시 고민했었는데 더 나은 방법이었군요!!
null 을 처리하는 두가지 방법 모두 연습해봐야겠습니다 😄

2023-06-06 08:47 UTC, HandmadeCloud commented on CalculateType.java
> +    }
크게 생각하지 않고 무심코 써버렸네요 ㅠㅠ 바로 수정해야겠습니다!

2023-06-06 08:48 UTC, HandmadeCloud commented on CalculateType.java
> +        //apply : 제네릭 타입인 한 개의 매개변수를 전달받아 특정 작업을 수행 후 값을 반환합
아하 몇몇 주석들은 처음 사용해본 경우 다시 잊어버릴까봐 메모 형식으로 적어둔 부분이 있습니다
pr 보낼때는 정리를 해서 날려야겠네요!

2023-06-06 08:51 UTC, HandmadeCloud commented on View/OutputView.java
> +    public static void printRecords(ArrayList<String> arithmeticRecords) {
조금 더 상위 타입으로 하면 유연한 설계가 되었을텐데 크게 생각하지 않았던 것 같아요!
이런 것들도 조금씩 신경쓰는 습관을 길러야겠습니다 😆

2023-06-06 08:56 UTC, HandmadeCloud commented on Main.java
> +            else if (select == 2) {
바~로 수정하겠습니다ㅋㅋㅋㅋㅋ 확실히 너무 대충해버린 티가 나네요

2023-06-06 08:59 UTC, HandmadeCloud commented on View/InputView.java
> +        Scanner sc = new Scanner(System.in);
이부분에 대해서 범준님한테도 피드백을 받아보았습니다 😃 
재사용할 수 있도록 필드로 뺴는 것이 적절할 것 같습니다
생성한뒤에 close처리하는 부분은 처음 들어봐서 그부분도 같이 공부해보겠습니다~

2023-06-06 09:00 UTC, HandmadeCloud commented on Calculator.java
> +        }
else를 지양하는 방식으로 개선해볼 수 있을 것 같아요 (if문에는 continue 추가)
객체지향생활체조에 대해서 들었는데, 그부분을 생각하면서 들여쓰기를 개선해나갈 수 있을 것 같습니다!

2023-06-06 09:04 UTC, HandmadeCloud commented on Calculator.java
> +        if (value.matches("[0-9]+")) {
그런 방법이 있었군요 😮 
프로젝트를 할 때는 휴대폰번호 정규식은 그렇게 해봤는데...
세심하게 생각해봐야겠다는 생각을 많이 하게 되네요 ㅎㅎ

2023-06-11 07:30 UTC, Jo-GyuHyeon commented on Calculator.java
> +                        calculateType.getPriority() < CalculateType.findBySymbol(operatorStack.peek()).getPriority()) {
반복문에 있는 조건들을 의미 있는 변수로 할당 해보면 어떨까요? 그렇게 된다면 가독성이 증가 될거라 기대해요.

2023-06-12 07:05 UTC, HandmadeCloud commented
첫번째 pr 종료

2023-06-12 07:05 UTC, closed without merging