[4기 - 주홍석] 자바 계산기 구현 미션 중간 pr입니다.
prgrms-be-devcourse/java-calculator pull request #116
Opened 2023-06-05 07:22 UTC by Juhongseok

## 📌 과제 설명 
OOP를 활용하여 계산기를 만드는 과제
- [x] 메뉴 선택 기능
- [ ] 계산 기능

## 👩‍💻 요구 사항과 구현 내용
크게 두개의 기능으로 나누었고 그 중 메뉴 선택 기능 구현입니다

1. Enum을 활용해서 각 메뉴가 할 역할을 지정해 뒀습니다.
2. Input 과 Output 클래스를 통해 역할을 분리했습니다

## ✅ PR 포인트 & 궁금한 점
1. Menu와 Calculator간의 관계에 대해서 아직 의문입니다
    calculator가 menu를 가지고 있어야 할 것 같은데 menu에 calculator를 넘겨주는 것이 되어 버린 것 같습니다
    Main에서 calculator를 생성 할 때 menu를 선택해서(지금은 1, 2번만 있지만 나중에 늘어난다고 하면 원하는 것만 선택?) 주입을 해주는 방법은 어떤지 여쭤봅니다

2023-06-06 05:39 UTC, Jo-GyuHyeon requested changes
안녕하세요. 홍석님 반가워요. 🙇 
첫 PR 축하드려요. 🥳 

### 🦅 Git
커밋 메시지를 하나한 보았습니다. 커밋 단위를 잘게 나눈것 같았지만, 메시지 내용과 단위가 조금 아쉬움이 남았던것 같아요. 
하지만 커밋 메시지를 자세히 작성 하시려고 description 을 이용하셨던 부분은 좋게 생각해요.  👍 
커밋 메시지만을 보고 해당 작업이 얼마나 어떻게 이루어 졌나가 파악이 되면, 좋은 단위라고 생각이 들어서 말씀드리고 싶었어요. 🛩️ 

### 🧑‍⚕️ PR Comment
코멘트가 다소 많을 수 있다고 생각합니다. (모든 코드 라인을 리뷰드리진 못했어요. 😢)
괄호에 대한 우선순위, 과제에서 선택 할 수 있는 기능들은 다음 PR 에서 진행 하는 것을 권유 드리고 싶어요.

그림도 좋고, 글자도 좋아요. 이번 과제는 OOP 에 집중하는 것인것 만큼 계산기에 필요한 도메인, 클래스 들과 해당 역할과 책임을 정리 해보면 더 좋은 코드가 될것이라 생각이 들어 제안 드려 보아요. 👍

2023-06-06 05:39 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/calc/Calculator.java
> +    }
view 에 대한 내용은 뒤에도 나올 예정이에요. 😄 
해당 메서드를 보았을때 계산기의 실행은 메뉴를 선택 하고, 실행 행동을 라고 해석이 되는 것 같아요.
다른 클래스들간의 관계를 따지기 이전에 Calculator 내에 해당 행위들이 필요할까? 라는 의문을 갖게 되는 것 같아요. 🤔 
뒷 부분에도 리뷰들이 이어질 테니 리뷰 내용들을 보시고 다시 고민 해보시면 어떨까요?

2023-06-06 05:39 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/calc/model/Menu.java
> +    public static String doAction(int selectedNumber, Calculator calculator) {
해당 메서드는 2가지 행위를 하나로 합친것 같아요. 
doAction 이라는 메서드 명을 보았을땐 static 할 필요는 없다고 생각이 들어요. 
다만 메뉴를 찾기 위한 정적 메서드 패턴을 사용 하였다면 static 이 적절한것 같아요.
2가지 행위를 적절히 나눠 보는 것은 어떨까요?? 😄

2023-06-06 05:39 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/calc/model/Operator.java
> +    CLOSE(")", 1, null),
해당 과제의 요구사항은 아래와 같은 것으로 알고 있어요. 
괄호에 대한 우선순위라면 다음 PR 에 진행 하는 방향은 어떨까요? 😄 

---
- 객체지향적인 코드로 계산기 구현하기
    - [ ]  더하기
    - [ ]  빼기
    - [ ]  곱하기
    - [ ]  나누기
    - [ ]  우선순위(사칙연산)
- [ ]  테스트 코드 구현하기
- [ ]  계산 이력을 맵으로 데이터 저장기능 만들기

2023-06-06 05:39 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/calc/model/Token.java
> +}
비워져 있는 해당 인터페이스는 어떠한 용도로 사용 될까요?

2023-06-06 05:39 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/calc/model/Operator.java
> +        }
sign 목록들을 미리 정의 한 후 동일 비교를 하게 된다면 들여쓰기(인덴트) 를 줄이는 효과를 가질수 있을 것 같아요 😄

2023-06-06 05:39 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/calc/repo/CalcHistoryRepository.java
> +    public String getAllHistories() {
메서드 명을 보았을때 리턴 타입은 복수형이라고 생각을 하였어요.
toString 의 역할을 해당 메서드가 하고 있지 않을지? 의심이 되었어요. 😢

2023-06-06 05:39 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/view/Output.java
> +        }
반복문을 처리 하는 다른 방법을 소개 해볼까 해요. 🤙
향상된 for 문, stream 의 foreach 가 있어요. 해당 방법을 추천하는 이유는 array 의 인덱스에 직접 접근 하지 않는 방법이기 때문이에요.

인덱스를 직접 접근 해야 하는 케이스도 존재 하지만, 그렇지 않다면 순차적으로 접근 하는 방향을 문법에 맡기는 것을 제안드리고 싶어요. 🎲
인덱스 접근으로 실수가 발생 하게 될 수도 있고, 가독성 면에서도 떨어질수 있다고 생각해요. 🤔

2023-06-06 05:39 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/view/Input.java
> +        }
parse 에서 발생 할 수 있는 예외들을 잡아서 RuntimeException 로 다시 변경하신 이유가 궁금한데 알려 주실수 있으실까요? 🙇

2023-06-06 05:39 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/valid/FormulaValidator.java
> +        return Pattern.matches("\\(?\\d+(\\s[+\\-*/]\\s\\(?\\d+\\)?)+", formula);
정규식 변수로 정의하면, 의미를 부여 할 수 있기에 가독성이 증가되고, 재사용성을 높일수 있을것 같아요. 😄

2023-06-06 05:39 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/util/Converter.java
> +        Stack<Operator> stack = new Stack<>();
개인적으로 자료형의 네이밍 피하려고 노력하는 편이에요. 
단순히 stack 기능을 표현 하는 것 보다 조금더 의미를 부여하면 좋을것 같아요. 👍

2023-06-06 05:39 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/util/Converter.java
> +        stack.pop();
해당 코드는 이전 호출부의 이해가 있어야 될것 같다는 생각이 들어요.
만약 어쩔수 없다면 해당 부분은 주석을 남기는 것이 다른 동료들에게 이해도를 높여 줄 수 있을 것이라 생각이 들어요. 😄

2023-06-06 05:39 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/util/Converter.java
> +    private static void processOperator(List<Token> result, Stack<Operator> stack, char currentChar) {
해당 메서드가 static 인 이유가 궁금해요. 어떤 이유인지 알려주실 수 있으실까요? 🙇

2023-06-06 05:39 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/util/Converter.java
> +        Operator newOperator = Operator.find(currentChar);
newOperator 네이밍을 보니 비교, 대비 할 대상인 이전에 사용 되는 operator 라는 변수명을 기대 했는데 못찾은것 같아요.
네이밍의 prefix로 new 를 붙인 이유는 어떤 점이 있을까요?

2023-06-06 06:18 UTC, HyoungUkJJang reviewed
안녕하세요 홍석님. 첫 과제 진행하시느라 고생하셨습니다 ! ☺️

여기저기 고민을 하신 흔적이 보여 좋았습니다 ㅎㅎ 규현 멘토님께서 리뷰를 잘 작성해 주셨네요 👍🏻
저도 멘토님과 중복되는 의견들이 있어서 그 부분은 제외하고 추가적으로 조금 의견을 남겨 봤습니다 
한번 참고해주시면 좋을 것 같아요 !

무엇보다 홍석님의 의견이 가장 중요하니 편하게 남겨주시면 좋을 것 같습니다 🥳

2023-06-06 06:35 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/Calculator.java
> +    public String calc() {
초반에 작성을 할 때 calc라는 단어를 이전부터 많이 써와서 괜찮겠지라고 생각했는데 전체를 작성하도록 변경을 해야겠어요!!😊

2023-06-06 06:40 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/Calculator.java
> +        List<Token> tokens = converter.infixToPostfixFormula(formula);
기존에는 사용자로부터 입력을 받고 결과값을 보내주는 것까지를 계산기에서의 계산하다라는 것이라고 생각을 했어요
그래서 `calc()` 메소드에서 하나로 묶어뒀고 직접적인 계산을 진행하는 것을 `calculate()`로 따루 분리를 해뒀어요

위와 같은 생각을 가지고 구현을 하고 테스트 코드를 작성을 하는 도중에 계산하는 것만 테스트를 원하는데 다른 추가적인 것들이 있어서 테스트 코드도 복잡하다고 생각을 해서 입력받는 부분을 분리를 할 지 고민하고 있었는데 분리하는 것도 좋은거 같아요

2023-06-06 06:42 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/Calculator.java
> +        return result;
`Output,viewResult()`라는 메소드에서 계산 결과 값이랑 계산 이력의 값을 받아서 출력을 하고있어요
두개의 값 모두 메뉴를 선택하고 나온 최종 결과 값이라고 생각을 해서 하나의 메소드에서 출력을 하기로 하고 공통되게 String 값으로 넘겨주도록 했어요

2023-06-06 06:44 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/Calculator.java
> +    }
1. 메뉴의 값을 받는다
2. 메뉴에 맞게 행동을 한다
이렇게가 Calculator의 역할인 것 같아요

view의 기능들은 상위 부분으로 뽑는 것이 좋아보이네요╰(*°▽°*)╯

2023-06-06 06:45 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/model/Number.java
> +public class Number implements Token{
아.. 그러네요ㅎㅎ 잘 사용하지 않다보니까 잊어버리고 있었어요 네이밍을 변경하는 것이 좋아보이네요👌

2023-06-06 06:49 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/Calculator.java
> +            stack.push(((Operator) token).doAction(secondNumber, firstNumber));
형식을 변환하는 것만 있어서 하나의 라인으로 입력을 해뒀는데 좋지않은 습관인거군요
하나 더 코딩 규칙을 정하고 갑니다!!!!

doAction보다는 계산하다의 calculate or 실행하다의 execute로 변경하는 것이 괜찮은 것 같아요

2023-06-06 06:52 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/model/Menu.java
> +    NONE(0, "default do not use zero number", calculator -> {throw new RuntimeException("없는 메뉴");}),
주로 사용자들 기준에서 번호를 입력을 하라고 하면 1번부터 사용을 하고 추가적으로 생성을 한다고 해도 그 이후 번호를 사용한다고 생각을 했어요

그래서 예외 발생을  사용하지 않을 것 같다고 생각한 0번에 할당을 해뒀어요
음.. 혹시 다른 더 좋은 값이 있을까요???🤔

2023-06-06 06:56 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/model/Menu.java
> +    CALC(2, "계산", Calculator::calc),
네!!! 알겠습니다👍

2023-06-06 06:57 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/Calculator.java
> +    }
메뉴의 값을 입력받는 것은 외부로 빼내고 해당 값을 전달해 주는 방식으로 결정했답니다😊

2023-06-06 06:59 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/model/Menu.java
> +    public static String doAction(int selectedNumber, Calculator calculator) {
아!! 메뉴를 찾는 것과 실행을 하는 것 두가지의 행위를 나누는 것을 말씀하신거죠?

정적 메서드 패턴에 대해서도 한번 다시 공부를 해봐야겠어요

2023-06-06 07:01 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/model/Token.java
> +}
단순히 Number, Operator를 하나의 공통된 타입으로 묶어서 계산기에 넘겨주기 위해 사용되고 있어요

2023-06-06 07:02 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/model/Operator.java
> +        }
Operator 내부에 상수 Map?객체를 만들어서 미리 목록을 정의해 두면 되겠네요👍

2023-06-06 07:11 UTC, Juhongseok commented on src/main/java/com/devcourse/view/Output.java
> +        }
menu에서 0번은 출력을 하면 안되기 때문에 인덱스를 사용을 했는데 위 Operator의 리뷰와 같이 Menu도 목록을 미리 정의해두면 다른 방식으로 변경할 수 있겠네요😁

2023-06-06 07:12 UTC, Juhongseok commented on src/main/java/com/devcourse/view/Input.java
> +        }
가장 큰 이유는 메소드마다 `thorws Exception`을 작성하기 싫은 것이 가장 큰 이유였어요

예외 처리에 대한 부분은 가장 상위 메소드에서 작업을 진행해볼 예정이에요

2023-06-06 07:14 UTC, Juhongseok commented on src/main/java/com/devcourse/util/Converter.java
> +        Stack<Operator> stack = new Stack<>();
확실히 변수명에 대해서는 좀더 고민을 해봐야겠어요 앞선 token도..

어디 변수명 잘 지어주는게 있으면...🤣

2023-06-06 07:15 UTC, Juhongseok commented on src/main/java/com/devcourse/util/Converter.java
> +        stack.pop();
주석이라.. 완전 생각도 안하고 있던 것인데 확실히 다른 친구한테 보여주니까 이해를 쉽게 못하기는 하네요
좀더 좋은 코드 구성을 생각해보고 안되면 설명을 달아놔야겠어요😊

2023-06-06 07:17 UTC, Juhongseok commented on src/main/java/com/devcourse/util/Converter.java
> +    private static void processOperator(List<Token> result, Stack<Operator> stack, char currentChar) {
기존에는 converter클래스를 유틸 클래스로 사용을 하기로 설계를 해뒀지만 calculator 내부에서 직접 가지고 있는 것이 맞다고 생각을 해서(지금은 중위표현식에서 후위표현식으로 변경하지만 다른 방식으로도 변경을 할 수 있어서) 
유틸클래스에서 일반 클래스로 변경을 하게 되었는데 그부분에서 미처 확인을 못하고 넘어간것 같아요

빨리 수정을 해둬야겠어요👍

2023-06-06 07:22 UTC, Juhongseok commented on src/main/java/com/devcourse/util/Converter.java
> +        Operator newOperator = Operator.find(currentChar);
stack.peek()에 있는 값이 이전 operator이기 때문에 새로 들어온 값이라 해서 new를 prefix를 붙이게 되었어요

stack.peek() inline으로 설정하면서 이름의 의미가 퇴색된 느낌이네요ㅜ..

2023-06-06 07:27 UTC, Juhongseok commented on src/main/java/com/devcourse/Main.java
> +        while (true) {
처음에 생각한 거는 계산기를 켜서 구동을 시키면 외부에서 끄지 않으면 계속 작동을 시킨다였어요
계산기 전원 버튼을 눌러서 끈다?라는 식으로요

한번 그 방식으로도 생각을 해봐야겠어요

2023-06-06 07:29 UTC, Juhongseok commented on src/main/java/com/devcourse/view/Input.java
> +            throw new RuntimeException(e);
예외 관련된 것은 이번 pr리뷰 작업 후 진행할 예정이에요

pr메세지에 작성을 할 때 이런 부분도 작성을 해둬야하는데 못적어 뒀네요..ㅜ

2023-06-06 07:30 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/model/Menu.java
> +    CALC(2, "계산", Calculator::calc),
통일을 해주는 것이 좋아보이네요 :)
처음에 짤 때 너무 생각없이 타이핑 하는 것 같네요.. 반성합니다

2023-06-06 07:35 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/Calculator.java
> +    }
`showHistory`와 `calc()`두개의 메소드가 Menu안에 람다를 통해서 호출이 되어 Calculator.run()에서 값을 받아 출력을 하도록 해뒀어요

메뉴에서는 조회와 계산의 action을 관리해요
그리고 Output은 출력만을 담당하기 때문에 이력을 조회는 계산기 내부에서 해야한다고 생각해요

2023-06-06 07:36 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/Calculator.java
> +    }
계산기내부에 이력을 저장을 해야하고 변환하는 것도 현재는 중위 표현식에서 후위 표현식으로의 변환이지만 나중에는 계산기마다 다른 방식으로도 바꿀수 있다고 생각을 해서 생성자를 통해 주입을 하도록 했어요😊

2023-06-06 07:37 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/repo/CalcHistoryRepository.java
> +    private int index = 0;
Map을 사용한 의도는 요구사항에 `계산 이력을 맵으로 데이터 저장기능 만들기`라고 되어있어서 사용을 했고 index는 단순히 auto increment와 같은 구분을 위해서 사용했어요😊

2023-06-06 07:38 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/repo/CalcHistoryRepository.java
> +        histories.put(index++, history);
이 부분도 고민을 안한것은 아닌데 단순히 index를 증가만 시켜주는 것을 메소드로 분리를 하는것도 괜찮은가요???🤔

아래와 같이 한줄만 작성을 해서 우선은 한줄로 작성을 했어요
```java
public void increaseIndex() {
    this.index++:
}
```

2023-06-08 07:07 UTC, Juhongseok commented
답글이 많아 혼잡할 것 같아 닫고 리뷰 반영한 PR 보내겠습니다

2023-06-10 16:02 UTC, Jo-GyuHyeon commented
해당 PR 에서 리뷰 내용이 존재하기도 하며, 반영 여부를 확인하기가 좋을것 같아서 Re Open 결정하게 되었어요.

2023-06-10 17:51 UTC, Jo-GyuHyeon requested changes
안녕하세요. 홍석님 추가적으로 리뷰를 남겨두었어요.
아직 이전 리뷰에 대해 반영이 다 되진 않은것 같아요. 
차근히 리뷰 반영 해주시면 좋을것 같아요!! 화이팅!!!!!!

2023-06-10 17:51 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/calc/model/Menu.java
> +    }),
https://github.com/prgrms-be-devcourse/java-calculator/pull/116#discussion_r1219020864

해당 코멘트에 대한 답변을 여기서 남길게요.
메뉴 출력 할때도 마찬가지이지만 0번에 대한 메뉴를 사용자에게 설명할 필요가 있을까요??

예외 메시지로써 사용하게 된다면 enum 객체로 정의할 필요가 있을지 의문이 들어요.

2023-06-10 17:51 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/calc/converter/ConverterWithBracket.java
> +    }
https://github.com/prgrms-be-devcourse/java-calculator/pull/116#discussion_r1218932869 코멘트와 관련 있는데요.
이런 경우는 메서드 분리를 안하는게 좋을 수도 있다고 생각해요. 
해당 메서드의 로직을 보았을때 순수하게 bracket을 제거 한다고 이해하기가 힘들어요.

2023-06-10 17:51 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/calc/Calculator.java
> +        if (result instanceof History history) {
instanceof 를 지양하는 편이에요. 같은 리뷰 내용이 있어서 구체적인 내용은 생략 할게요.

2023-06-12 08:27 UTC, Juhongseok commented on src/main/java/com/devcourse/view/Input.java
> +            String formula = reader.readLine();
별도 메소드로 분리하는 것이 좋아보이네요👌

2023-06-12 08:36 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/model/Operator.java
> +    }
`private final Map<String, Operator> operators = Arrays.stream(values())....`
위 처럼 한번에 초기화를 하는 것을 말씀하시는 것일까요?🤔

2023-06-12 11:31 UTC, Juhongseok commented on src/main/java/com/devcourse/Main.java
> +                Output.viewResult(calculator.run(menu));
정확히 어떤 뜻인지 이해를 못했어요
예외 메시지 출력을 위해 감싼건데 해당 부분을 제거하라는 말씀이신가요??🤔🤔

2023-06-12 11:31 UTC, Juhongseok commented on src/main/java/com/devcourse/view/Input.java
> +            String formula = reader.readLine();
메소드 분리가 가능해 보이네요 분리를 해봐야겠어요!!

2023-06-12 11:53 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/Calculator.java
> +    public String showHistory() {
`showHistory()`랑 `calculate()`의 결과 값을 `Output.viewResult()` 하나의 메소드를 통해 출력을 하게 해뒀고 repository.toString()을 만들어서 그냥 repository를 반환을 해주고 출력시에 `toString()`이 호출 되게 끔 만들까 고민을 하다가 

repository자체를 반환하는 것이 이상하다고 생각을 해서 모든 목록을 받아온 후 String 값으로 후처리해서 반환하게 해뒀어요

2023-06-12 11:55 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/Calculator.java
> +        List<Token> tokens = converter.convertFormula(formula);
계산 이력을 저장하는 것과 동시에 입력받은 수식을 원하는 데로 변경을 하는 것도 계산기의 역할이라고 생각하기 때문에 입력을 받은 후에 계산기에서 변환을 해야 한다고 생각해요😊

2023-06-12 11:57 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/Calculator.java
> +        Operand result = calculate(tokens);
계산 결과 값도 피연산자라고 생각을 잘못 했던 거 같아요..

2023-06-12 11:59 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/model/Menu.java
> +    }),
입력을 받을 때 검증을 따로 하면 되겠네요
너무 한 곳에서 모든 것을 처리해서 생긴 문제인 것 같아요

2023-06-13 06:28 UTC, Juhongseok commented on src/main/java/com/devcourse/view/Input.java
> +            String formula = reader.readLine();
[012216C](https://github.com/prgrms-be-devcourse/java-calculator/pull/116/commits/012216c0a1596c70e9e42fcfdf8d287c0e4c7cdf) 반영

- reader.readLine() 부분 메소드 분리

2023-06-13 06:32 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/model/Menu.java
> +    public static final Map<Integer, Menu> menus = new HashMap<>();
아래와 동일 커밋입니다
---

1a2e366 반영

- static 스코프 제거
- stream 통한 목록 초기화

2023-06-13 06:33 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/model/Operator.java
> +    private static void checkDivideZero(Integer number2) {
[f247c83](https://github.com/prgrms-be-devcourse/java-calculator/pull/116/commits/f247c83b2740cf5b8c293baa19b2b235d30b75a1) 반영

2023-06-13 06:33 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/Calculator.java
> +    private String processResult(Object result) {
[f247c83](https://github.com/prgrms-be-devcourse/java-calculator/pull/116/commits/f247c83b2740cf5b8c293baa19b2b235d30b75a1) 반영

2023-06-13 06:34 UTC, Juhongseok commented on src/main/java/com/devcourse/valid/FormulaValidator.java
> +        String expressionValidationNoBracket = "\\d+(\\s[+\\-*/]\\s\\d+)+";
[f247c83](https://github.com/prgrms-be-devcourse/java-calculator/pull/116/commits/f247c83b2740cf5b8c293baa19b2b235d30b75a1) 반영

2023-06-13 06:36 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/model/Menu.java
> +    }),
[b43d1f0](https://github.com/prgrms-be-devcourse/java-calculator/pull/116/commits/b43d1f0561e488a85ce6ac956b5ed12432a907ea) 반영

- 0번 값 제거
- 사용자 메뉴 입력 값 검증 로직 추가

2023-06-13 06:37 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/Calculator.java
> +    public String showHistory() {
[40834a4](https://github.com/prgrms-be-devcourse/java-calculator/pull/116/commits/40834a431f900f2760da92c4cca22eb473c3fd92) 반영

- 추가적으로 CalculateRecord 모델 정의
- 메소드 반환 값 변환

2023-06-13 06:38 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/Calculator.java
> +            if (symbol instanceof Operand number) {
[fa6cd88](https://github.com/prgrms-be-devcourse/java-calculator/pull/116/commits/fa6cd8867615f0bd79cf1edd6e5c1b25a0c7ad79) 반영

- instance of 제거
- Token interface에 공통 로직 처리 메소드 추가

2023-06-13 06:39 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/converter/ConverterWithBracket.java
> +    }
[0784917](https://github.com/prgrms-be-devcourse/java-calculator/pull/116/commits/07849173236eea6c711c77261192137b8e924f8f) 반영

2023-06-13 06:40 UTC, Juhongseok commented
## 23.06.13
리뷰 반영 완료했습니다

2023-06-13 19:53 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/calc/model/Operator.java
> +    private static final Map<String, Operator> operators = Arrays.stream(values()).collect(toMap(operator -> operator.sign, operator -> operator));
Value 로 Function.identity() 를 사용해봐도 좋을것 같아요.
https://javabydeveloper.com/java-8-identity-function-examples/

2023-06-13 20:12 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/Main.java
> +                Output.viewResult(calculator.run(menu));
단순히 의견이 궁금했어요. 

전역적으로 try catch 구문을 사용하면 어디에서 예외가 발생한지 찾기 어려울수 있다고 생각해요.
하지만, 전역적으로 예외 메시지를 출력 한다면 의미가 있을수 있다고 생각해요. 
한편으로 꼭 전역적으로 예외메시지가 필요한가? 도 고민해보면 좋을것 같아요.

2023-06-13 20:12 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/calc/converter/Converter.java
> +            result.add(new Operand(Integer.parseInt(operandNumber.toString())));
괄호 안에 인자들을 많이 중첩되는 구조가 되는 것 같아요. 가독성을 위해 변수로 빼는 것도 좋은것 같아요.

2023-06-13 20:12 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/calc/model/Operator.java
> +    }
레퍼런스 (혹은 사이드 이펙트)를 이용하면 데이터 변경의 추적이 어려워요.
== 동작 방식을 추측 하기 어려움이 있어요.
다란 방법은 없을까요??

deal 이라는 네이밍이 다소 어색함이 있어요. 네이밍에서 어떤 의도였는지 말씀해주실수 있을까요?

2023-06-14 08:04 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/model/Menu.java
> +    private final Function<Calculator, Object> action;
Object 관련해서 다 수정했다 생각했는데 너무 여러군데에서 사용중이었네요..

2023-06-14 23:43 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/converter/Converter.java
> +            result.add(new Operand(Integer.parseInt(operandNumber.toString())));
[b6251a6](https://github.com/prgrms-be-devcourse/java-calculator/pull/116/commits/b6251a6d129cfc7dca1dc6b01c2f1c392fb9537a) 반영

- 공통 로직 메소드 분리 추가

2023-06-14 23:43 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/model/Menu.java
> +    private final Function<Calculator, Object> action;
[9f9f82b](https://github.com/prgrms-be-devcourse/java-calculator/pull/116/commits/9f9f82b58dc4bf593f91082315ab486accb3540f) 반영

- Result 상위 객체 생성 후 공통 타입 반환 처리
- Object 제거

2023-06-14 23:43 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/model/Operator.java
> +    }
[5a36e8c](https://github.com/prgrms-be-devcourse/java-calculator/pull/116/commits/5a36e8cd55d0e2b3f00ee88037dcad7d92ebf80a) 반영

- deal -> getProcessedNumber
- 레퍼런스를 넘기는 방식에서 필요한 값만 추출 후 처리 된 결과 값을 받아오도록 변경

- 이전에 instance of 를 사용했던 코드와 거의 비슷한 구조를 가지지만 다른 점은 isDigit 메소드를 통해 직접 동작을 정의했다는 것과 하위 클래스의 정보를 직접적으로 알아야 하지 않아도 됨

2023-06-14 23:56 UTC, Juhongseok commented
## 23.06.15 
말씀해주신 피드백들을 최대한 반영해서 커밋하고 누락된 요구사항과 구현 내용, 피드백 반영 사항을 PR 내용에 수정 했습니다!!

항상 생각 하지 못했던 부분에서와 세세한 피드백 감사합니다😊😊

2023-06-15 09:48 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/calc/Calculator.java
> +    }
Menu 와 Calculator 연관 관계에 대해 고민이 되는것 같아요. 🤔 
electedMenu.execute() 에 this 를 넘겨주면서 어떠한 장점과 단점이 있을까요?

2023-06-15 09:48 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/calc/Calculator.java
> +        List<Token> tokens = converter.convertFormula(formula);
계산`기`에 대한 역할을 여쭙기 보다 계산하다 라는 행위(메서드) 에 대해 말씀드리고 싶었어요.
홍석님이 생각하시는 계산기의 역할에서 입력 수식을 변경하는 것을 할 수 있다는 점에 대해 공감 하기도 해요.
하지만, 계산기가 아닌 계산하다에서 이뤄져야 할까? 라는 의문이 남기도 해요.

2023-06-15 10:10 UTC, Jo-GyuHyeon reviewed
간단히 리뷰 남겼어요.
고생하셨어요. 🙇

2023-06-15 10:10 UTC, Jo-GyuHyeon commented on src/main/java/com/devcourse/calc/model/Operator.java
> +        return operators.get(Character.toString(sign));
Character.toString() 를 사용하시는것 보아 sign 은 String 이 아닌 char 타입은 어떠할까요?

2023-06-15 10:10 UTC, Jo-GyuHyeon reviewed
간단히 리뷰 남겼어요.
고생하셨어요. 🙇

2023-06-16 03:59 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/model/Operator.java
> +        return operators.get(Character.toString(sign));
음 그게 더 좋아보이네요 처음에 String으로 해둔게 계속 그대로 사용된거 같아요

2023-06-16 04:00 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/model/Operand.java
> +    }
제일 어려운... 더 고민해볼게요

2023-06-16 04:03 UTC, Juhongseok commented on src/main/java/com/devcourse/view/Input.java
> +    }
Input에서는 selectMenuNumber로 변경하고 이를 사용하는 Main 에서 Menu 타입을 반환하도록 해야겠어요

2023-06-16 04:38 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/Calculator.java
> +    }
장점으로는 Menu안에 동작을 미리 정의할 수 있다?
단점으로는 연관관계가 역으로 사용되는 것 같아요 Calculator에서 Menu를 써야하는데 오히려 반대로 되서 주체가 바뀐느낌이에요 굳이 몰라도 되는 정보를 알고 있는 것 같아요

2023-06-17 01:29 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/Calculator.java
> +    }
[51d71bb](https://github.com/prgrms-be-devcourse/java-calculator/pull/116/commits/51d71bb10218a9a8302510cf40a67e30475ecaf9) 반영

- Calculator내부 repository, converter 분리
- Console 객체를 통한 위 3개 객체 관리
- Menu와 Calculator 결합도 분리

2023-06-17 01:30 UTC, Juhongseok commented on src/main/java/com/devcourse/view/Output.java
> +                .forEach(System.out::println);
[8d68641](https://github.com/prgrms-be-devcourse/java-calculator/pull/116/commits/8d68641d775d10efefa3c24fc607f46306459a69) 반영

- stream foreach -> 향상된 for문 변경
- Menu 목록 접근 메소드 추가

2023-06-17 01:32 UTC, Juhongseok commented on src/main/java/com/devcourse/view/Input.java
> +    }
[8296080](https://github.com/prgrms-be-devcourse/java-calculator/pull/116/commits/8296080d580f608b99591476e577b24a36c14e2c), [51d71bb](https://github.com/prgrms-be-devcourse/java-calculator/pull/116/commits/51d71bb10218a9a8302510cf40a67e30475ecaf9) 반영

- Input.selectMenu -> Input.selectMenuNumber (int 반환)
- Main.selectMenu -> Console.selectMenu (Menu 반환)

2023-06-17 01:32 UTC, Juhongseok commented on src/main/java/com/devcourse/calc/model/Operator.java
> +        return operators.get(Character.toString(sign));
[e200640](https://github.com/prgrms-be-devcourse/java-calculator/pull/116/commits/e20064085295b0d2a0afeedfa82d1899e4027387) 반영

2023-06-17 01:57 UTC, Juhongseok commented
## 23.06.17
메소드 네이밍 제외 리뷰 반영 완료했습니다
네이밍은 적절한게 떠오르지않아 계속 고민 중이에요

마지막까지 리뷰와 설명 감사드려요!! 😊😊

2023-06-20 01:53 UTC, merged