[4기-김도연] 1~2주차 과제 : 계산기 구현 미션 제출합니다.
prgrms-be-devcourse/java-calculator pull request #118
Opened 2023-06-05 13:14 UTC by joyfulviper

## 📌 과제 설명 
요구사항과 동일한 계산기를 만들었습니다. 특히 SRP, OCP, 캡슐화를 잘지키기 위해 노력했습니다.

## 👩‍💻 요구 사항과 구현 내용 
[chore: 초기 설정](https://github.com/prgrms-be-devcourse/java-calculator/commit/fcce32c663497b4810a5c9873219a8613bd90f83) -> gardle init으로 초기화 한 사항에 대한 내용입니다.

[chore: Junit5 테스트 의존성 추가](https://github.com/prgrms-be-devcourse/java-calculator/commit/530050deaa66615ef4b76a48b93a34ce008bf792) -> gradle init 시 JUnit4로 선택이 돼서 JUnit 5로 변경했습니다.(최신 버전에 익숙해지고 싶어서)

기본적으로 TDD 방법론을 이용했기 때문에 테스트 코드와 기능 개발을 함께 했습니다.
[feat: 출력 모듈, 테스트 추가](https://github.com/prgrms-be-devcourse/java-calculator/commit/b106090427c086aa706cd42bdf97ff0b4426f36b) -> 커밋 메시지와 동일

[feat: 연산 기록 모듈, 테스트 추가](https://github.com/prgrms-be-devcourse/java-calculator/commit/76f603cfea9bdc28ffec83ed93b56725fee9b29c) -> 커밋 메시지와 동일

[feat: util 모듈(문자열 분리, 숫자변환, 검증), 테스트 추가](https://github.com/prgrms-be-devcourse/java-calculator/commit/ed10cab086619dd3a41ff0323e8405bd9f10e603) -> 계산기 클래스에 이러한 역할을 갖게 하기에는 너무 많은 책임을 부여하는거 같아서 유틸 클래스를 만들었으며, 재사용 가능하게 했습니다.

[feat: 연산 모듈, 테스트 추가](https://github.com/prgrms-be-devcourse/java-calculator/commit/ef0c2411945611998465181234418c80b5d17f85) -> 연산 역할을 하는 구현체 클래스 입니다.

[feat: 계산기 엔진(계산 로직이 담겨있는 캡슐화된 클래스) 모듈, 테스트 추가](https://github.com/prgrms-be-devcourse/java-calculator/commit/ca19f4051229a048ddc38793b852c00ec3922a7b) -> 계산기가 계산하는 과정의 로직이 복잡해 engine 클래스를 만들어 캡슐화 했습니다.

[feat: 계산기 모듈, 테스트 추가](https://github.com/prgrms-be-devcourse/java-calculator/commit/2dc5dcdb685d20f52fdba698131076bacc146217) -> 저장 객체를 싱글톤으로 구현했습니다.

[feat: 사용자 명령 구현체 모듈(조회, 계산), 테스트(mockito) 추가](https://github.com/prgrms-be-devcourse/java-calculator/commit/bb3f39b37bcbd3baa4306bd71ffa6fe723e47d55) -> 사용자의 명령 1 조회, 2 계산을 명령 패턴으로 구현했습니다. 출력과 입력의 불편함으로 이미 테스트 검증이 끝난 객체에 대해 mocking하여 테스트 했습니다.

[feat: 실행 모듈, 테스트 추가](https://github.com/prgrms-be-devcourse/java-calculator/commit/871168a53cdc614787de5833c297bab4e4414dd3) -> 계산기 시스템을 실행하는 모듈입니다.

[test: 통합 테스트 작성](https://github.com/prgrms-be-devcourse/java-calculator/commit/3f12b325f9b44b842196a00edcabbd1b06361ae1) -> 계산기 시스템의 통합 테스트입니다.

[refactor: 테스트 메소드 명 한글로 변경](https://github.com/prgrms-be-devcourse/java-calculator/commit/13b78edb4c207007c77e464071f7f50ffcec5d47)
[refactor: Repository명 변경](https://github.com/prgrms-be-devcourse/java-calculator/commit/95e92c48cd39a1d963f3292e4cc7827d25b67253)
-> pr올리기 전 검토한 사항입니다.

## ✅ 피드백 반영사항  

## ✅ PR 포인트 & 궁금한 점

2023-06-05 14:14 UTC, dojinyou reviewed
전체적으로 너무 잘 하신 것 같아요~ 
테스트 코드도 꼼꼼히 짜셔서 따로 코멘트할 부분이 많지 않았습니다! 👍

2023-06-05 14:14 UTC, dojinyou commented on app/src/main/java/programmers/java/calulator/common/operator/Operator.java
> +public enum Operator {
너무 좋네요! 👍

2023-06-05 14:14 UTC, dojinyou reviewed
전체적으로 너무 잘 하신 것 같아요~ 
테스트 코드도 꼼꼼히 짜셔서 따로 코멘트할 부분이 많지 않았습니다! 👍

2023-06-05 14:36 UTC, joyfulviper commented on app/src/test/java/programmers/java/calulator/OOPCalculatorIntegrationTest.java
> +import java.io.*;
오 이런 기능이 있군요 습관적으로 import 할 때 alt + enter 키를 눌러서 했는데 와일드 카드로 import 된 줄 몰랐네요 ㅠㅠ  

+ IDE 관련해서는 정말 모르는게 많았는데 알려주셔서 감사합니다!

2023-06-05 14:38 UTC, joyfulviper commented on app/src/test/java/programmers/java/calulator/common/CalculatorTest.java
> +        String expression = "2 + 3 * 4";
아하 ParmeterizedTest에 대해 완전 까먹고 있었네요. 상기시켜주셔서 감사합니다.

아무래도 @BeforeEach를 쓰는게 맞다고 생각합니다. 확장에 신경쓴다고 신경 썼는데 이 부분을 놓쳤네요 감사합니다!

2023-06-05 14:41 UTC, joyfulviper commented on app/src/test/java/programmers/java/calulator/console/runner/ConsoleRunnerTest.java
> +}
오 몰랐는데 바로 적용했습니다 ㅋㅋㅋ 감사합니다!!

2023-06-05 14:43 UTC, joyfulviper commented on app/src/main/java/programmers/java/calulator/console/runner/ConsoleRunner.java
> +        commands.put("2", new ExecuteCalculationCommand(calculator, reader, writer));
아 생각해보니 맞는 말씀이시네요 이거 작성하면서 이상하다 싶었는데 스스로 합리화 하면서 편한 길을 선택한 것 같습니다. 멘토님 커멘트 바탕으로 다시 작성해볼게요!

2023-06-05 14:45 UTC, joyfulviper commented on app/src/main/java/programmers/java/calulator/console/repository/MapRepository.java
> +}
헉... 실수 입니다. 왜 저장소의 확장을 생각하지 못했는지 ㅠ 싱글톤에 꽂히다 보니 다른 생각을 못하게 됐습니다. 이것도 인터페이스로 구현하고 다른 저장소가 추가 될 가능성을 염두하고 작성하겠습니다!

2023-06-05 15:33 UTC, seung-hun-h requested changes
도연님 과제 수행하느라 수고하셨습니다.
객체지향적으로 설계 하시려 노력하신점 좋았습니다.
다만 조금 과하게 클래스를 나누었다는 생각이 드는데요 리뷰 보고 반영해주세요

2023-06-05 15:33 UTC, seung-hun-h commented on app/src/main/java/programmers/java/calulator/console/repository/MapRepository.java
> +    }
이 코드는 내부 구현을 노출하는 것 같아요.
외부에서 `repository.clear()`를 호출하면 저장된 데이터가 전부 삭제될 수 있겠네요.

1. 전체 데이터를 조회하는 기능을 제공하거나
2. 내부 인스턴스가 아니라 뷰 객체를 만들어 반환해보는 것이 좋겠네요

2023-06-06 00:18 UTC, BeommoKoo-dev commented on app/src/test/java/programmers/java/calulator/console/runner/ConsoleRunnerTest.java
> +}
@dojinyou 좋은 설정 알고 갑니다!! 감사합니다 ㅎㅎ

2023-06-06 09:55 UTC, joyfulviper commented on app/src/main/java/programmers/java/calulator/common/Calculator.java
> +}
계산을 하는 역할로 생각했습니다. 사실 여기에 계산과 관련된 코드를 작성했는데 로직이 복잡해졌습니다. 계산기 객체는 다른 객체들과 상호작용하는 객체인데 이러한 로직을 갖고 있다는 자체만으로도  캡슐화가 깨지는 느낌이 들어서요.. 그래서 주요 로직을 캡슐화 하기 위해서 engine 객체에 역할을 위임했습니다.

2023-06-07 09:48 UTC, joyfulviper commented on app/src/main/java/programmers/java/calulator/console/repository/MapRepository.java
> +    }
그런 위험도는 생각하지 못했는데, 저장소가 직접 노출되는 상황을 고려해서 다시 작성해보겠습니다!

2023-06-07 09:51 UTC, joyfulviper commented on app/src/main/java/programmers/java/calulator/common/Calculator.java
> +}
맞는 말씀이시네요 사실은 캡슐화가 깨지지는 않는 것 같은데 Calculator 클래스 안에 로직이 복잡해지다 보니 캡슐화가 깨진다는 착각을 한 것 같습니다. 또한, 이렇게 작성하다 보니 calculator 클래스의 역할이 모호해지는 것 같네요. 계산기 객체의 역할과 책임을 다시 정의하고 작성해보겠습니다!

2023-06-08 04:43 UTC, joyfulviper commented on app/src/main/java/programmers/java/calulator/common/engine/CalculatorEngine.java
> +        parse(tokenizer.getTokens());
넵 동의합니다. 생성자에 많은 책임이 있다고 생각하고 Tokenizer 객체는 사실 String 클래스의 split 함수를 호출하는 역할만 하는데 굳이 이걸 클래스로 만들 필요도 없는 것 같아요. 생성자의 역할에 맞는 행동만 할 수 있게 하고, 유의미한 역할을 하는 객체로 다시 작성해보겠습니다!

2023-06-08 16:59 UTC, seung-hun-h requested changes
도연님 피드백 빠르게 반영해주셨네요.
리뷰 남겼으니 확인해주세요

2023-06-08 16:59 UTC, seung-hun-h commented on app/src/main/java/programmers/java/calulator/common/calculator/StackCalculator.java
> +    private String[] tokens;
인스턴스 변수로 선언할 필요가 있을까요?

2023-06-08 16:59 UTC, seung-hun-h commented on app/src/main/java/programmers/java/calulator/console/repository/MapRepository.java
> +    private Long idCounter;
`MapRepository`는 싱글톤이군요. 그럼 멀티스레드 환경에서 idCount는 문제가 발생할 수 있지 않을까요?

2023-06-08 16:59 UTC, seung-hun-h commented on app/src/main/java/programmers/java/calulator/common/calculator/StackCalculator.java
> +    }
```suggestion
    @Override
    public int calculate(String expression) {
        return calculate(expression.split(" "));
    }

    private int calculate(String[] tokens) {
        for (String token : tokens) {
            Number.of(token).ifPresentOrElse(
                    number -> numberStack.push(number.toInt()),
                    () -> handleOperator(Operator.of(token))
            );
        }
 
        while (!operatorStack.isEmpty()) {
            numStack.push(calculateTop());
        }
        return numStack.pop();
    }

    private void handleOperator(Operator operator) {
        while (!operatorStack.isEmpty() && !operator.isHighPriority(operatorStack.peek())) {
            numStack.push(calculateTop());
        }

        operatorStack.push(operator);
    }
   
   private int calculateTop() {
        int number2 = numberStack.pop();
        int number1 = numberStack.pop();
        Operator operator = operatorStack.pop();

        return operator.calculate(number1, number2);
    }
```
- 메서드가 잘 분리되어 있었는데요 이렇게도 작성해볼 수 있을 것 같아요
- 메서드가 분리 되어 있는 것은 좋지만 맥락을 파악할 수 있어야 한다고 생각합니다
- `finalizeCalculation` 이후에 `numStack.pop()`을 호출하는게 아래 코드를 보기전에는 맥락 파악이 쉽지 않다고 느껴졌어요
- 절대 도연님 코드가 틀렸다는 말이 아니라 메서드 분리를 조금 덜 하는 이러한 방법도 있다는 것으로 이해해주세요

2023-06-08 16:59 UTC, seung-hun-h commented on app/src/main/java/programmers/java/calulator/common/repository/FormatConstants.java
> +}
상수 전용 클래스를 만드는 것 보다는, History 클래스에 위치해야 할 것 같아요. 같은 도메인의 정보인데 클래스만 분리되어 있는 것 같아요.

2023-06-08 16:59 UTC, seung-hun-h commented on app/src/main/java/programmers/java/calulator/console/menu/MenuHandler.java
> +    }
```suggestion
    public MenuHandler(Writer writer, Calculator calculator, Reader reader, Repository repository) {
        this.writer = writer;
        this.commands = initializeCommands();
        this.reader = reader;
        this.calculator = calculator;
        this.repository = repository;
        
    }

    private Map<String, Command> initializeCommands() {
	...
    }
```

생성과 초기화가 분리되어 있는 것 보다는 생성과 함께 초기화 되는 것이 좋아보이네요

2023-06-09 02:01 UTC, evan-vcnc commented on app/src/test/java/programmers/java/calulator/common/calculator/StackCalculatorTest.java
> +    })
👍

2023-06-09 02:01 UTC, evan-vcnc commented on app/src/main/java/programmers/java/calulator/common/operator/Operator.java
> +        }
[nit]
던지는 예외들도 처리하면서 프로그램이 종료되지 않도록 하면 좋을 것 같아요!

2023-06-09 02:04 UTC, dojinyou commented on app/src/main/java/programmers/java/calulator/common/calculator/StackCalculator.java
> +    }
제 생각에는 이 함수의 이름이 parse인데 파싱 과정 중에 계산 과정이 포함되어 있는 것 같아요!
저는 파싱을일반적인 형태(타입)의 입력을 우리가 원하는 특정 형태(타입)로 변환하는 과정 이라고 생각했어요.
계산은 파싱된 데이터를 통한 결과를 추출하는 과정 이라고 생각 했어요.
그래서 이 둘을 분리하면 좋을 것 같다고 생각했어요~

계산은 별도의 함수로 분리할 수도 있을 것 같아요.
또는 파싱을 원하는 특정 형태인 타입을 클래스로 선언하고 해당 클래스에게 역할을 위임할 수도 있을 것 같아요.
그렇게 한다면 Calculator가 계산 가능한 형태만 입력을 받을 수도 있을 것 같아요.

하지만 요건 조금 선택의 영역인 거 같아서 고민해보시면 좋을 것 같아요

2023-06-09 02:04 UTC, dojinyou commented on app/src/main/java/programmers/java/calulator/common/calculator/StackCalculator.java
> +        return numberStack.pop();
이 두 가지 행위의 추상화 레벨이 다르다고 느껴졌어요. 그래서 조금은 가독성이 떨어지는 느낌이에요!
해당 코드를 보았을 때 finalizeCalculation은 특정 로직을 처리하는 추상화된 함수의 호출인데 stack.pop() 스택의 가장 위에 값을 가져오는 행위라 추상화가 되지 않은 것 같아요!

2023-06-09 02:04 UTC, dojinyou commented on app/src/main/java/programmers/java/calulator/console/menu/MenuHandler.java
> +        writer.write("2. 계산");
write 되는 문자열들이 command와 관련 있어보이는 데 command가 알고 있고 그 정보를 활용하는 건 어떨까요?

2023-06-09 02:04 UTC, dojinyou commented on app/src/main/java/programmers/java/calulator/common/operator/Operator.java
> +        }
[nit]
던지는 예외들도 처리하면서 프로그램이 종료되지 않도록 하면 좋을 것 같아요!

2023-06-09 02:04 UTC, dojinyou commented on app/src/test/java/programmers/java/calulator/common/calculator/StackCalculatorTest.java
> +    })
👍

2023-06-10 07:34 UTC, joyfulviper commented on app/src/main/java/programmers/java/calulator/common/calculator/StackCalculator.java
> +    }
넵넵 앞으로는 좀 더 누군가 제 코드를 본다는 생각을 계속 갖고 이해하기 쉬운 코드로 작성해보겠습니다. 객체지향에 초점을 너무 맞추다 보니 메소드가 하나의 행동만 하도록 작성하려고 했던 것 같아요 ㅋㅋㅋ..
확실히 아래의 코드가 제 3자가 봤을 때 이해하기 쉬울 것 같다고 느껴지네요 감사합니다~

2023-06-10 07:36 UTC, joyfulviper commented on app/src/main/java/programmers/java/calulator/common/repository/FormatConstants.java
> +}
넵넵 다른 클래스에서 이 상수를 재사용할 가능성이 없어보이긴 하네요 반영하겠습니다!

2023-06-10 11:45 UTC, joyfulviper commented on app/src/main/java/programmers/java/calulator/common/repository/History.java
> +}
데이터베이스의 확장을 생각해서 추상 클래스로 작성했습니다. 목적 자체를 확장을 생각하고 만든 클래스기 때문에 일반 클래스로 작성하기 보다는 추상클래스로 작성하는게 제 의도를 드러내기 좋다고 생각했습니다.

 제일 필수적인 정보인 expression, result를 필드로 갖는 클래스를 작성했고, id와 같은 값은 어떠한 저장소를 사용하냐에 따라 전략이 달라질 것 같아 넣어 놓지는 않았습니다.

2023-06-10 11:46 UTC, joyfulviper commented on app/src/main/java/programmers/java/calulator/common/calculator/StackCalculator.java
> +    }
아하 넵넵 분리하다 보니 메소드 명을 간과했네요 피드백 참고해서 다시 작성해보겠습니다!

2023-06-10 11:49 UTC, joyfulviper commented on app/src/main/java/programmers/java/calulator/common/operator/Operator.java
> +        }
넵 최상위 클래스(Runner 클래스) 에서 예외를 잡아보겠습니다!

2023-06-10 11:57 UTC, joyfulviper commented on app/src/main/java/programmers/java/calulator/common/calculator/StackCalculator.java
> +    private String[] tokens;
계산기 클래스가 필드를 갖고 있지 않아도 될 것 같습니다. 파라미터로 받아서 결과를 출력하도록 하는게 더 좋은 방법 같네요 감사합니다!

2023-06-10 11:59 UTC, joyfulviper commented on app/src/main/java/programmers/java/calulator/console/repository/MapRepository.java
> +    private Long idCounter;
그렇네요 동시성 문제가 발생할 수 있을 것 같습니다. 멀티 스레드에 안전하게 저장하는 방법을 생각해보겠습니다!

2023-06-10 12:03 UTC, joyfulviper commented on app/src/main/java/programmers/java/calulator/common/calculator/StackCalculator.java
> +        return numberStack.pop();
아하 그렇게 느껴질수도 있을 것 같아요 차라리 `finalizeCalculation`에서 `stack.pop` 메소드를 호출하는게 더 나을 것 같습니다. 감사합니다

2023-06-10 12:06 UTC, joyfulviper commented on app/src/main/java/programmers/java/calulator/console/menu/MenuHandler.java
> +        writer.write("2. 계산");
사실 이 부분은 메뉴가 추가될 때 마다 이 코드를 수정해야하기 때문에 고민을 많이 했는데 적절한 방법이 떠오르지 않아서 이렇게 작성했습니다. 멘토님 말씀대로 command의 정보를 가져와서 하는 방법이 있었네요. 적용해보겠습니다!

2023-06-10 12:08 UTC, joyfulviper commented on app/src/main/java/programmers/java/calulator/console/menu/MenuHandler.java
> +    }
넵 확실히 아래의 방법이 좋다고 생각합니다. 감사합니다!

2023-06-11 12:19 UTC, seung-hun-h commented on app/src/main/java/programmers/java/calulator/common/calculator/StackCalculator.java
> +    private String[] tokens;
이건 제가 드래그를 잘못했네요;;
token에 대한 리뷰였습니다!

2023-06-13 14:30 UTC, seung-hun-h requested changes

2023-06-13 14:30 UTC, seung-hun-h commented on app/src/main/java/programmers/java/calulator/common/command/impl/ExecuteCalculationCommand.java
> +        writer.write(result.toString());
`write(result.toString())` 처럼 toString을 호출하는 것 보다는 해당 타입을 출력할 수 있는 메시지를 정의하는 것이 좋아 보여요

2023-06-13 14:30 UTC, seung-hun-h commented on app/src/main/java/programmers/java/calulator/common/utils/Number.java
> +        return token.matches(NUMBER_REGEX);
Pattern 객체를 상수로 만들면 더 좋겠네요

2023-06-13 14:30 UTC, seung-hun-h commented on app/src/main/java/programmers/java/calulator/common/repository/History.java
> +    private Integer result;
변경될 가능성이 없다면 final을 추가해주는 것이 좋겠네요

2023-06-13 14:30 UTC, seung-hun-h commented on app/src/main/java/programmers/java/calulator/console/repository/MapRepository.java
> +    }
inner class를 활용해서 싱글턴을 잘 구현 하셨네요!
혹시 inner class 를 사용하신 이유가 있을까요?

2023-06-13 14:30 UTC, seung-hun-h commented on app/src/main/java/programmers/java/calulator/console/runner/ConsoleRunner.java
> +    }
예외가 발생해도 애플리케이션이 종료되면 안될 것 같아요

2023-06-14 09:52 UTC, joyfulviper commented on app/src/main/java/programmers/java/calulator/console/repository/MapRepository.java
> +    }
Initialization-on-demand holder 라는 싱글톤을 구현할 때 가장 널리 사용되는 디자인 패턴을 이용했습니다.

이 패턴은 JVM의 클래스 로딩 메커니즘이 클래스가 처음 참조되는 시점에 로드되고 초기화된다는 점을 이용한 것입니다. 이 패턴은 멀티스레드 환경에서도 싱글톤이 한 개만 생성되는 것을 보장하며, 동시에 Lazy initialization(처음 사용될 때 초기화)을 가능하게 합니다.
또한 비용이 비싼 synchronize 키워드 없이 스레드에 안전한 싱글톤을 구현할 수 있기 때문에 inner class를 이용해 싱글톤을 구현했습니다.

2023-06-14 09:52 UTC, joyfulviper commented on app/src/main/java/programmers/java/calulator/common/repository/History.java
> +    private Integer result;
넵 그렇게 하겠습니다!

2023-06-14 09:53 UTC, joyfulviper commented on app/src/main/java/programmers/java/calulator/common/command/impl/ExecuteCalculationCommand.java
> +        writer.write(result.toString());
그게 더 유연할 것 같네요 적용하겠습니다!

2026-01-31 19:00 UTC, closed without merging