[4기 - 고예성] 자바 계산기 구현 미션 중간 PR입니다.
prgrms-be-devcourse/java-calculator pull request #121
Opened 2023-06-06 09:11 UTC by Dev-Yesung

안녕하세요. 첫 PR이라 조금 떨리네요. 어제 과제 관련 조언해주셔서 너무 감사합니다.
아무래도 제가 방향성을 잘못 잡고 과제를 하고 있는 것 같아서 
일단 구현한 부분만 PR하고 피드백을 받고 더 진행하려 합니다.
가감없이 혼내주세요...!

## 📌 과제 설명

- [X]  더하기
- [X]  테스트 코드 구현하기(덧셈만 구현)

## 👩‍💻 요구 사항과 구현 내용

중위표기식을 후위표기식으로 바꾸기 위해 자료구조로 스택을 사용했습니다.

커밋 메시지에 표현을 못했는데, 입력 관련 예외처리를 수행했습니다.
잘못된 문자열이 들어올 경우 예외를 발생시켰습니다.

계산은 단순 덧셈에 관한 기능만 구현했습니다.

## ✅ PR 포인트 & 궁금한 점

제가 너무 여러 부분을 과하게 신경 쓰고 있는 것 같습니다.
집중해야할 부분과 집중하지 않아도 되는 부분에 관한 피드백 부탁드립니다..!
그리고 현재 구현한 코드에 아쉬운 부분에 관해서도 코멘트 부탁드립니다.

2023-06-06 15:54 UTC, Jo-GyuHyeon requested changes
안녕하세요 예성님 반가워요. 🙇
첫 PR 축하드려요. 🥳

### 👾 Git commit
PR 을 잘게 가져가시려고 하신 모습이 좋아요. 👍 
다만 우려 했던 부분이 커밋단위가 PR 단위로 일치 하지 않을까 우려 했던 상황인데요.
현재는 PR 단위는 적적하다고 생각하나, 커밋단위는 조금더 분리 할 수 있을것이라 생각이 드는것 같아요. 🖐️ 

### 🤖 OOP
첫 리뷰인 만큼 간단히 드려 보았어요. 😄 
전반적으로 객체 이해, 책임과 협력에 대해 고민 해보시면 좋을것 같아요. 
또한 코드의 가독성을 위해 불필요한 메서드들로 나뉘지 않았는지 고민 해보시면 더 좋은 어플리케이션이 될것이라 생각이 들어요. 👍 
고생하셨서요. 🙇

2023-06-06 15:54 UTC, Jo-GyuHyeon commented on src/main/java/Operator.java
> +    }
유효성 검사가 꼭 필요한지가 고민이 되는 것 같아요. 🤔

2023-06-06 15:54 UTC, Jo-GyuHyeon commented on src/main/java/Calculator.java
> +    private final Deque<Operator> operators;
Deque 자료 구조를 사용하신 이유가 궁금해요. 혹시 알려주실 수 있으실까요? 😄

2023-06-06 15:54 UTC, Jo-GyuHyeon commented on src/main/java/Calculator.java
> +        return getResult();
코드를 깔끔히 짜신듯 한것 같아요. 👍  
하지만 자세히 보면 side effect 를 이용하여 로직을 수행 한다고 생각이 드는것 같아요. 
절차지향을 단순히 메서드로만 분리 하지 않았나 라고 생각이 들어요.
협력, 메시지 방식에 대해 고민해보시면 좋을것 같아요. 😄

2023-06-06 15:54 UTC, Jo-GyuHyeon commented on src/main/java/Calculator.java
> +        }
isNoExpression() 을 별도의 메서드로 뺄 필요가 있을까요? 🤔 
재사용성을 고려 할 수도 있고, 혹은 해당 객체가 제공하는 기능이라고 생각했을때 불필요하게 나뉜건 아닌지 고민해보면 좋을것 같아요. 😄

2023-06-06 15:54 UTC, Jo-GyuHyeon commented on src/main/java/Calculator.java
> +        }
isValidArgument() 도 위의 리뷰와 유사 합니다. 😄

2023-06-06 15:54 UTC, Jo-GyuHyeon commented on src/main/java/Calculator.java
> +    }
입력, 출력에 대한 책임을 나눠 보시는건 어떨까요?
Calculator 가 가질수 있는 최소한의 책임을 가진 상태로 다른 책임들은 분산 해보시면 좋을것 같아요. 👍

2023-06-06 15:54 UTC, Jo-GyuHyeon commented on src/main/java/Calculator.java
> +    private void checkEmptyArguments(String[] arguments) {
파라미터에 대해 의미있는 네이밍을 정해주면 어떨까요? 🐋

2023-06-06 15:54 UTC, Jo-GyuHyeon commented on src/main/java/Calculator.java
> +            checkPlusAndAdd(operator);
현재 리뷰 기준으로 덧셈 기능을 구현 하신것으로 알고 있어요.
메서드 네이밍은 사람이 보았을때 직관적일 수도 있겠지만 어색한 느낌도 들어요. 🐤 

뎃셈 연산자를 보고 분기처리를 할 수 있지만 check 라는 네이밍을 보았을땐 유효성 검사의 의미를 더 띄게 되는 것 같아요. 😢

2023-06-06 15:54 UTC, Jo-GyuHyeon commented on src/main/java/Calculator.java
> +        return getResult();
계산을 처리 한 후 결과값을 제공하는 행위와, 결과값을 제공하는 행위는 엄밀히 따지면 다른 행위인것 같아요.
getResult()를 보았을때 계산과 무관하게 저장된 결과값을 제공하는 의미로 해석이 되기도 해요. 😢

2023-06-06 15:54 UTC, Jo-GyuHyeon commented on src/main/java/Calculator.java
> +        checkValidCalculation();
결과를 제공할때 유효성 검사가 필요할까요?
예성님은 유효성 검사는 어떨때 주로 하게 되시나요??

2023-06-06 15:54 UTC, Jo-GyuHyeon commented on src/main/java/Calculator.java
> +    }
위의 리뷰에서 언급되었기에 해당 코멘트를 확인해주세요 ✅

2023-06-07 15:19 UTC, Dev-Yesung commented on src/main/java/Operator.java
> +    }
굳이 유효성 검사를 하는 메서드가 없더라도 유효성 체크가 되기 때문에 검사가 필요 없어도 된다고 이해했습니다...! 더 자연스러운 방법을 찾아보겠습니다~

2023-06-07 15:35 UTC, Dev-Yesung commented on src/main/java/Calculator.java
> +    private final Deque<Operator> operators;
어떤 의미로 질문하신 건지 헷갈리지만 두 가지 이유로 나눠서 대답해보겠습니다.

덱을 스택의 용도로 사용하여 후위연산자를 만들기 위해서 사용했습니다.
(근데 제가 알고리즘 구현을 제대로 안해놨습니다...ㅎㅎ)
operands는 연산자인 숫자를 넣는 스택으로 사용합니다.
operators는 Operator, 연산자 상수를 집어넣는 스택으로 사용합니다.
이후 구현에서 연산자에 우선순위를 부여해서 연산에 우선순위를 부여할 것입니다.

아니면 Stack을 안사용하고 굳이 Deque를 사용한 이유를 여쭤보신거라면...!
예전에 Stack이 Vector를 가지고 구현한 
잘못된 구현체라는 글을 읽어서 찝찝해서 덱을 사용했습니다. 아래의 글을 참고했습니다.
https://devlog-wjdrbs96.tistory.com/244

2023-06-07 15:45 UTC, Dev-Yesung commented on src/main/java/Calculator.java
> +        }
뭔가 이해가 될 듯 말 듯하네요...!
멘토님께서 말씀하신 의미는
재사용성과 객체의 책임을 생각해봤을 때,
메소드를 과하게 나눌 필요 없다는 것을 의미하는 것 같은데
뭔가 정확하게는 이해가 안가네요.
만일 스스로 고민해 본 후 이해가 안되면 멘토님께 찾아가겠습니다~

2023-06-07 15:50 UTC, Dev-Yesung commented on src/main/java/Calculator.java
> +    }
아아 이해됐습니다! 입출력에 관한 예외이기 때문에
입력과 출력에 관해 책임을 가진 객체에게 예외처리에 대한
책임을 부여하라는 말씀이시군요...! 감사합니다👍

2023-06-07 15:52 UTC, Dev-Yesung commented on src/main/java/Calculator.java
> +    private void checkEmptyArguments(String[] arguments) {
잘 어울리는 이름을 생각해보겠습니다 ㅎㅎ😁

2023-06-07 15:57 UTC, Dev-Yesung commented on src/main/java/Calculator.java
> +        checkValidCalculation();
생각해보니 유효성 검사는 보통 입력이 올바르게 들어왔는지 체크할 때 사용합니다.
만일 입력된 식이 제대로된 식이란 것이 이미 검증된 상태라면 굳이 결과제공에서 유효성 검사가 필요없을 것 같네요~

2023-06-07 15:58 UTC, Dev-Yesung commented on src/main/java/Calculator.java
> +        return getResult();
이해가 한 50%는 된거 같습니다..! 생각해보니 맥락을 이상하네요.
다르게 바꿔보도록 하겠습니다!

2023-06-07 16:03 UTC, Dev-Yesung commented on src/main/java/Calculator.java
> +            checkPlusAndAdd(operator);
말씀을 듣고 다시 보니 유효성검사의 의미가 더 강조되네요!
메서드에 하나의 역할만 부여하는 더 괜찮은 방법을 생각해보겠습니다~

2023-06-11 17:02 UTC, Jo-GyuHyeon requested changes
안녕하세요 예성님 😄
추가적으로 리뷰 드렸어요.
리뷰내용이 많아서 반영하기 쉽지 않을수 있다고 생각해요.

https://github.com/prgrms-be-devcourse/java-calculator/pull/121#pullrequestreview-1465457163 첫번째 리뷰 이후 피드백 적용을 한 후에 다음 기능을 적용하기를 바랬는데 안내가 부족 했던것 같아요.

피드백 반영을 진행하고 다음 기능을 진행하면 좋을것 같아요.
한번에 반영하게 되면 리뷰 했던 내용을 기억하지 못하고 놓치는 부분이 생길것 같아서 걱정 되는 마음이 있어요.

2023-06-12 04:14 UTC, Dev-Yesung commented on src/main/java/Processor.java
> +        while (true) {
상위라는 의미를 Processor 클래스를 호출한 Application 클래스를 말씀하시는 건가요?
한 번 개선해보도록 하겠습니다!😄

2023-06-12 04:18 UTC, Dev-Yesung commented on src/main/java/Processor.java
> +                }
피드백 감사합니다! 사실 궁금했던 점이기도 했습니다.
예전에 클린코드 책을 읽었을 때, 
switch 문을 사용하는 것을 피하라는 원칙을 읽었던 기억이 있습니다...!
하지만 저도 구현하면서 
'이거 switch로 구현하면 더 깔끔하지 않나?'란 의문이
계속 머릿속에 있었는데 피드백 덕분에 오히려 switch 써야하는
당위성을 찾을 수 있었습니다! 감사합니다🥹

2023-06-12 04:27 UTC, Dev-Yesung commented on src/main/java/Processor.java
> +                view.printNewLine();
맞습니다! 다른 객체에서 던지는 예외메시지를 출력하기 위해 
위와 같은 구조를 택했습니다!
그런데..! 제가 위에 코멘트에서 이해한 상위가 Processor를 호출한
상위클래스로 이해한 것이 맞는지 의문이 듭니다.

제가 설계한 Processor 객체의 책임은
다른 객체들로부터 발생한 예외를 잡아주는 역할을 하는 것인데,
만일 제가 이해한 상위의 개념이 호출한 객체라고 생각한다면
책임이 변경되는 것으로 해석이되네요...!

혹시 멘토님께서 말씀하신 상위라는 것이
Processor 객체에 새로운 메소드를 만들고
start 메소드를 호출하도록 만들라는 의도일까요?
한 번 스스로 고민해보겠습니다~! 감사합니다🙇‍♂️

2023-06-12 04:27 UTC, Dev-Yesung commented on src/main/java/Processor.java
> +                    view.printNewLine();
맞습니다! switch문과 함께 개선하겠습니다👍

2023-06-12 04:29 UTC, Dev-Yesung commented on src/main/java/exception/IllegalExpressionException.java
> +}
이것도 궁금했습니다! 
혹시 나중에 필요할 때를 고려해 기본생성자를 미리 만들어 놓는게 어떨까?라고
생각했는데,  미리 추가해놓으면 오히려 읽는 분들이 헷갈리거 같네요~
감사합니다!😆

2023-06-12 04:43 UTC, Dev-Yesung commented on src/main/java/view/ViewMessage.java
> +    private final String message;
제가 상수를 ViewMessage와 Command 클래스로 따로 분리한 이유는

1. 매직넘버에 의미있는 이름을 지어주기
2. 원시 타입이 아닌 Command 타입으로 관리해서 버그와 혼동 피하기
3. 명령과 메시지를 확장성을 고려해 코드 변경을 최소화하기 위해서
입니다.

enum클래스가 아닌 상수로 관리했을 때와 비교해서 생각해봤습을 때
추가적인 이점이 있어서 이렇게 관리했습니다😊

2023-06-12 04:45 UTC, Dev-Yesung commented on src/main/java/model/Operator.java
> +    }
Operand 코멘트와 같은 이유로 했습니다!

2023-06-12 04:53 UTC, Jo-GyuHyeon commented on src/main/java/Processor.java
> +                view.printNewLine();
넵 말씀 하신것 처럼, 상위가 Processor를 호출한상위클래스를 의미 하고 있습니다.
전체를 감싸고 있는것은 어플리케이션 전체 (글로벌) 에 해당 하기에 더 상위로 빼도 될것 같다고 생각하였습니다.

2023-06-12 04:54 UTC, Dev-Yesung commented on src/main/java/model/Operand.java
> +    }
헉 맞습니다...!
일급컬렉션을 의도하여 사용했습니다.

예전에 일급 컬렉션에 관한 글을 읽은 적이 있었는데,
컬렉션을 단순히 자료구조로 사용하는 것이 아니라
유의미한 객체로 정의할 수 있고
상태와 행동을 하나의 클래스에서 의미있고 명확하게 관리할 수 있다는 것이
장점인 것으로 알고 있습니다!

제가 Operator와 Operand 모두 일급컬렉션을 의도하여 사용한 이유는

1. 비즈니스 영역에서 발생할 수 있는 예외를 객체의 책임에 따라
명확하게 관리할 수 있다는 것
2. Calculator에 코드를 줄여 가독성을 줄 수 있다는 점에서 사용했습니다.

하지만 멘토님께서 이해하지 못하셨다는 말씀을 하신 것 보니
제가 잘못된 방법으로 사용한 것 같습니다.
아무래도 제가 일급 컬렉션에 관한 이해도가 떨어져서 그런것 같습니다.
(Operator의 경우에는 일급 컬렉션의 정의에서 벗어나네요🥲)

혹시 어떤 이유에서 이해하지 못하셨나요?
스스로 생각해보긴 하겠지만 그래도 멘토님의 의견을 명확하게 반영해서
코드를 수정하고 싶습니다~!

2023-06-12 04:54 UTC, Jo-GyuHyeon commented on src/main/java/view/ViewMessage.java
> +    private final String message;
중복과 책임이 분산 되지 않을지 고민 해보시면 어떨까요? 🤔

2023-06-12 04:55 UTC, Dev-Yesung commented on src/main/java/model/Calculator.java
> +            }
네~ 좀더 명확한 코드로 바꿔서 돌아오겠습니다😆

2023-06-12 04:55 UTC, Jo-GyuHyeon commented on src/main/java/model/Operator.java
> +    }
Operator, Operand 는 객체로써 복수형의 의미가 있을까요?? 🤔 
1급 컬렉션을 사용하였지만, 적절하지 않은것 같아요.
또한 올바른 행위인가에 대해 의문이 들어요.

2023-06-12 04:56 UTC, Dev-Yesung commented on src/main/java/model/Calculator.java
> +        for (String expComponent : expression.split("")) {
변수명은 항상 어렵네요! 
축약안하면 너무 길거 같아서 소심하게 줄여봤는데,
그냥 풀어쓰도록 하겠습니다~ 감사합니다!🙇‍♂️

2023-06-12 11:06 UTC, Dev-Yesung commented on src/main/java/Processor.java
> +                view.printNewLine();
넵 이해했습니다! 감사합니다~

2023-06-12 11:08 UTC, Dev-Yesung commented on src/main/java/view/ViewMessage.java
> +    private final String message;
오... 생각지 못했던 방향이네요 고민해보고 적용해보도록 하겠습니다!

2023-06-12 11:12 UTC, Dev-Yesung commented on src/main/java/model/Operator.java
> +    }
객체로써 복수형의 의미가 있다는 말씀을 해주셨는데,
지금 사용하고 있는 Operator, Operand 객체가 여러 개 생성될 수 있다는 말씀이신가요?
정확히 이해는 안가지만 저는 복수형을 의도한 것은 아닙니다..!
복수형이 된다면 제가 의도한 것과는 다른 것이 되네요. 생각해보지 못했습니다.
어떤 의미인지 더 고민해보고 잘 모르겠으면 질문하도록 하겠습니다~
바쁘신데 너무 감사합니다!🥹

2023-06-12 15:43 UTC, Dev-Yesung commented on src/main/java/model/Operator.java
> +    }
> Operator, Operand 는 객체로써 복수형의 의미가 있을까요?? 🤔 1급 컬렉션을 사용하였지만, 적절하지 않은것 같아요. 또한 올바른 행위인가에 대해 의문이 들어요.

1급 컬렉션이 부적절하다는 의미는 이해했습니다! Operand클래스를 예로 들어 생각했을 때,
컬렉션과 관련된 처리로직이 필요한데, 저의 경우 단순히 push, pop과 같은 컬렉션의 메서드만 래핑해서 사용하기 때문에
결과적으로 1급컬렉션이 부적절하다는 것을 알았습니다~ 코드를 수정해보겠습니다. 감사합니다!

2023-06-13 04:21 UTC, Dev-Yesung commented on src/main/java/view/ViewMessage.java
> +    private final String message;
> 중복과 책임이 분산 되지 않을지 고민 해보시면 어떨까요? 🤔

멘토님께서 말씀하신 것 이제 이해했습니다!
굳이 Command와 ViewMessage를 나눌 필요가 없네요
결국 COMMAND_ONE이나 HISTORY_COMMAND나 같은 것이고
명령이면 명령에 관한 상태를, 메시지이면 메시지에 관한 상태를 사용하면 된다는 생각이 들었습니다.
개선해보도록 하겠습니다~🙇‍♂️

2023-06-13 05:13 UTC, Dev-Yesung commented on src/main/java/Processor.java
> +        while (true) {
[73bb883](https://github.com/prgrms-be-devcourse/java-calculator/pull/121/commits/73bb883bca635e3a39c67f77907ae5b9ba54045a)에 반영했습니다~

2023-06-13 05:13 UTC, Dev-Yesung commented on src/main/java/Processor.java
> +                }
[73bb883](https://github.com/prgrms-be-devcourse/java-calculator/pull/121/commits/73bb883bca635e3a39c67f77907ae5b9ba54045a)에 반영했습니다

2023-06-13 05:13 UTC, Dev-Yesung commented on src/main/java/Processor.java
> +                view.printNewLine();
[73bb883](https://github.com/prgrms-be-devcourse/java-calculator/pull/121/commits/73bb883bca635e3a39c67f77907ae5b9ba54045a)에 반영했습니다.

2023-06-13 05:14 UTC, Dev-Yesung commented on src/main/java/exception/IllegalExpressionException.java
> +}
[45323f6](https://github.com/prgrms-be-devcourse/java-calculator/pull/121/commits/45323f679b86ce28357363bc2ef5ccc3cd436edb)에 반영했습니다.

2023-06-13 05:15 UTC, Dev-Yesung commented on src/main/java/view/ViewMessage.java
> +    private final String message;
[f9ea1c8](https://github.com/prgrms-be-devcourse/java-calculator/pull/121/commits/f9ea1c8173fc813a3263db46f085b94880a7b617)에 반영했습니다!

2023-06-13 05:15 UTC, Dev-Yesung commented on src/main/java/model/Operator.java
> +    }
[7bb0979](https://github.com/prgrms-be-devcourse/java-calculator/pull/121/commits/7bb097995feacf62d02700e445e2854828556774)에 반영했습니다~

2023-06-13 05:15 UTC, Dev-Yesung commented on src/main/java/model/Calculator.java
> +            }
[3ae0742](https://github.com/prgrms-be-devcourse/java-calculator/pull/121/commits/3ae07427e654833acb2e8861bef3904bcc67950a)에 반영했습니다

2023-06-13 05:32 UTC, Dev-Yesung commented
안녕하세요! 리뷰해주셨던 내용들 PR에 반영했습니다.
리뷰해주신 덕분에 객체의 책임 중복에 관해서도 생각해보고 
일급콜렉션에 관한 올바른 이해를 할 수 있었습니다~
리뷰 잘 부탁드립니다!😄

2023-06-13 15:37 UTC, HyoungUkJJang reviewed
고생하셨습니다 예성님 :) 👍🏻

규현 멘토님께서 리뷰를 잘 남겨주셔서 제가 남길 부분은 많이 없는 것 같네요 
그래도 작은 의견을 몇개 달아보았는데 예성님도 자유롭게 의견을 말씀해주시면 좋을 것 같습니다 ~ ☺️

2023-06-13 15:37 UTC, HyoungUkJJang commented on src/main/java/view/ViewMessage.java
> +                .orElseThrow();
return 전에는 개행처리 한번 해주는 것은 어떻게 생각하시나요? (가독성 측면)

orElseThrow()에 조금 더 상세한 예외를 명시하는것은 어떻게 생각하시나요?

2023-06-13 15:37 UTC, HyoungUkJJang commented on src/main/java/model/Operator.java
> +import java.util.*;
쓰지 않는것 까지 import 하는 것은 권장하지 않습니다 🧐

임포트를 하다보면 특정 개수가 넘어 갈 경우 와일드카드로 변경되는 설정이 있는데 해당 설정을 인텔리제이에서 수정하시면 방지할 수 있습니다 ~ 아래 링크를 한번 참조해보세요 !

[와일드카드 임포트 인텔리제이 수정하기](https://velog.io/@eora21/Intellij%EC%97%90%EC%84%9C-%EC%99%80%EC%9D%BC%EB%93%9C%EC%B9%B4%EB%93%9C-%EC%9E%84%ED%8F%AC%ED%8A%B8-%EC%84%A4%EC%A0%95-%EB%B3%80%EA%B2%BD%ED%95%98%EA%B8%B0)

2023-06-13 15:37 UTC, HyoungUkJJang commented on src/main/java/model/Calculator.java
> +        }
옵셔널을 사용해서 코드를 수정해보면 어떨까요?

2023-06-13 15:37 UTC, HyoungUkJJang commented on src/main/java/model/Calculator.java
> +        for (String expressionComponent : expression.split("")) {
공백 없이 문자열 모두 배열로 변환하는게 목적이라면 `toCharArray()` 도 있는데 어떻게 생각하시나요?

2023-06-14 16:31 UTC, Dev-Yesung commented on src/main/java/Processor.java
> +    private ViewMessage getCommand() throws RuntimeException {
멘토님 의견주셔서 감사합니다~ 사실 이전에 Command와 클래스를 통합하면서 적절한 이름을 어떻게 줄지 고민하다 안떠올라서 일단 뒀습니다! 다음 PR에 적절한 이름으로 돌아오도록 하겠습니다😊

2023-06-14 16:35 UTC, Dev-Yesung commented on src/main/java/view/View.java
> +        if (expression.length() == 1 || !Pattern.matches("^\\d+([+\\-*/]\\d+)*$", expression)) {
앗 맞습니다...! 이 부분은 수정한다고 해놓고 잊어버렸네요! 감사합니다~
+ 궁금한 점이 있는데 그 옆에 있는 정규표현식도 의미있는 상수변수 이름으로 만들어주는게 더 괜찮을까요?
아니면 바꾸는 것이 더 나을까요?🤔

2023-06-14 16:51 UTC, Dev-Yesung commented on src/main/java/view/ViewMessage.java
> +                .orElseThrow();
확인했습니다! 감사합니다~

2023-06-14 16:52 UTC, Dev-Yesung commented on src/main/java/model/Operator.java
> +import java.util.*;
오... 사실 커밋전에 자꾸 인텔리제이가 와일드카드로 바꾸길래 원래 이런가 싶어서 그냥 커밋했던건데 꿀팁 감사합니다~~

2023-06-14 16:56 UTC, Dev-Yesung commented on src/main/java/Processor.java
> +            case HISTORY_COMMAND -> viewLogs();
오... 맞습니다. 바로 반영하겠습니다~ 감사합니다!😊

2023-06-16 07:51 UTC, Dev-Yesung commented on src/main/java/model/HistoryStorage.java
> +        storage.put(id++, expression + " = " + result);
[4155fba](https://github.com/prgrms-be-devcourse/java-calculator/pull/121/commits/4155fba8ce76fd02c83953f47a8b9ef26400ea41)에 반영했습니다!

2023-06-16 07:53 UTC, Dev-Yesung commented on src/main/java/view/ViewMessage.java
> +                .orElseThrow();
[58d64ab](https://github.com/prgrms-be-devcourse/java-calculator/pull/121/commits/58d64ab9378e6290e13a0d3276b7b9ac8c1ff9e5)에 반영했습니다~

2023-06-16 07:54 UTC, Dev-Yesung commented on src/main/java/model/Operator.java
> +import java.util.*;
변경했는데 구체적인 커밋을 안넣었네요 ㅠ 죄송합니다...!

2023-06-16 07:54 UTC, Dev-Yesung commented on src/main/java/view/ViewMessage.java
> +    HISTORY_COMMAND("1. 조회", 1), CALCULATE_COMMAND("2. 계산", 2), SELECT_COMMAND("선택 : ", -1);
[f36b8bc](https://github.com/prgrms-be-devcourse/java-calculator/pull/121/commits/f36b8bcf260a16abd88d7acf9cdc45656684aa7d)에 반영했습니다!

2023-06-16 07:56 UTC, Dev-Yesung commented on src/main/java/model/Calculator.java
> +        }
[9f67c44](https://github.com/prgrms-be-devcourse/java-calculator/pull/121/commits/9f67c441115add0422e008cffb7d24bf57dfd00f)에 반영했습니다!

2023-06-16 07:58 UTC, Dev-Yesung commented on src/main/java/model/Calculator.java
> +        for (String expressionComponent : expression.split("")) {
[5b8246f](https://github.com/prgrms-be-devcourse/java-calculator/pull/121/commits/5b8246fbc149fd22dc4d1a842c6cb326c6a8e9b1)에 반영했었으나
테스트코드 작성 중에 두자리 수 이상의 사칙연산이 불가능한 것을 발견했습니다.
그래서 아래의 커밋에서 String으로 다시 변경했습니다...!

[034d684](https://github.com/prgrms-be-devcourse/java-calculator/pull/121/commits/034d684f1a34fdefdfc61aa94833b3f522a69337)

2023-06-16 07:58 UTC, Dev-Yesung commented on src/main/java/Processor.java
> +            case HISTORY_COMMAND -> viewLogs();
[abeb4ac](https://github.com/prgrms-be-devcourse/java-calculator/pull/121/commits/abeb4ac6efb36d0494adf5b3299ae2cf4f074daa)에 반영했습니다~

2023-06-16 07:59 UTC, Dev-Yesung commented on src/main/java/Processor.java
> +    private ViewMessage getCommand() throws RuntimeException {
[79a509b](https://github.com/prgrms-be-devcourse/java-calculator/pull/121/commits/79a509b7c8159e95c70223afc45369454001521f)에 반영했습니다!
ViewMessage 자체를 변경해서 기존과 코드가 달라졌습니다.

2023-06-16 08:01 UTC, Dev-Yesung commented on src/main/java/view/View.java
> +        if (expression.length() == 1 || !Pattern.matches("^\\d+([+\\-*/]\\d+)*$", expression)) {
[f36b8bc](https://github.com/prgrms-be-devcourse/java-calculator/pull/121/commits/f36b8bcf260a16abd88d7acf9cdc45656684aa7d)에 반영했습니다

2023-06-16 08:13 UTC, Dev-Yesung commented
리뷰해주셨던 부분을 최대한 반영해서 올렸습니다...! 
하지만 시간이 촉박하다보니 테스트 같은 것들을 구현하다보니
기존 PR을 반영하면서 객체의 역할이 약간씩 변경되었습니다.

여러번 PR을 올리는 방식으로 멘토님들과 소통하는 방식으로 진행했어야 했는데,
이러한 중요성을 늦게 깨닫고 진행하게 되어 제 선택에 아쉽습니다.

그래도 마지막 PR까지 잘 부탁드립니다..!
그동안 프리팀에서 바쁘신 와중에도 코드 리뷰 해주셔서 감사합니다.🙇‍♂️
더 성장하도록 노력하겠습니다!🥹

2023-06-16 13:49 UTC, HyoungUkJJang reviewed
예성님 고생하셨습니다 :) 멘토님이 이전에 리뷰를 잘 남겨주셨네요 👍🏻

간단하게 코멘트 몇개 남겼으니 참고해주세요 !!

2023-06-16 13:49 UTC, HyoungUkJJang commented on src/main/java/exception/NoSuchCommandException.java
> +    }
여기에만 기본생성자가 있는 이유는 무엇인가요?

2023-06-16 13:49 UTC, HyoungUkJJang commented on src/main/java/model/Calculator.java
> +        }
`"".equals(expression)`으로 사용한다면 어떤 차이점이 있을까요?

2023-06-16 13:49 UTC, HyoungUkJJang commented on src/main/java/model/Calculator.java
> +            if (operandStack.size() < 2) {
매직넘버 ㅠ

2023-06-16 13:49 UTC, HyoungUkJJang commented on src/main/java/util/CalculatorUtils.java
> +public class CalculatorUtils {
유틸리티 클래스는 외부에서 생성해서 사용하지 못하도록 private 생성자를 추가하는 것을 권장드립니다.

2023-06-17 11:06 UTC, Dev-Yesung commented on src/main/java/exception/NoSuchCommandException.java
> +    }
resolveCommand에서 상수를 찾지 못할 경우 NoSuchCommandException을 던지고 있습니다! 이 메소드를 호출한  commandReader가 예외를 잡아서 메시지를 싣고 다시 던집니다. 그래서 기본생성자를 사용했습니다..!

2023-06-17 11:30 UTC, Dev-Yesung commented on src/main/java/model/Calculator.java
> +        }
만약에 expression == null이 없을 경우에 equals에 의해 에러가 발생할지 발생하지 않을지에 대해 차이가 있다고 생각합니다..! 만일 expression에 null이 들어왔을 때, expression.equals를 호출한다면 NullPointerException이 발생하게 됩니다. 하지만 "".equals(expression)이라면 ""가 빈 String 클래스이기 때문에 NPE로부터 안전한 코드가 됩니다. 

이러한 점으로 생각해봤을 때, "".equals로 작성하게 되면 null과 빈 문자열을 동시에 검사할 수 있기 때문에 앞에 expression == null을 작성 안해도 된다는 생각이 들었습니다!
피드백 감사합니다~😆

2023-06-17 11:33 UTC, Dev-Yesung commented on src/main/java/util/CalculatorUtils.java
> +public class CalculatorUtils {
앗 이 점은 생각을 못하고 있었네요. 피드백 감사합니다!

2023-06-17 11:49 UTC, Dev-Yesung commented on src/main/java/model/Calculator.java
> +        }
둘의 차이에 관해 생각해봤을 때, expression.equals("")를 사용할 경우 expression에 null이 올 경우 equals메소드를 사용할 수 없어서 NPE가 발생합니다. "".equals(expression)을 사용할 경우 문제가 생겼을 때, ""에 문제가 없다는 것은 보장되고 expression에 문제가 있다는 것을 확신할 수 있어 디버깅(?)에 좋을거 같습니다. 지금은 String객체라 티가 안나지만 다른 객체라면 두 방법 사이의 차이가 날거라 생각합니다..!(맞나요...ㅎㅎ;)🫠

2023-06-17 12:09 UTC, HyoungUkJJang commented on src/main/java/model/Calculator.java
> +        }
@Dev-Yesung 

넵 예성님 🙂
저희가 평소 equals를 다룰 때 크게 생각하지 않고 작성하는 경우가 많은데 혹시 반대로 했을 때 어떤 차이점이 존재하는지도 한번 생각해보시면 좋을 것 같아서 여쭤봤어요 ㅎㅎ 예성님이 차이점을 잘 생각해서 답변해주신 것 같습니다 ! 👍🏻 저도 NPE방지를 막기위해서 개발공부를 했을때는 위의 방식대로 사용했던 적도 많았어요 !

2023-06-22 16:24 UTC, merged