Byeolhaha
prgrms-be-devcourse/java-calculator pull request #123
Opened 2023-06-06 13:21 UTC by byeolhaha

## 📌 과제 설명 
- 사용자가 "1"을 선택한 경우 
 조회 기능으로 Map에 저장된 모든 계산 이력을 출력합니다.
- 사용자가 "2"를 선택한 경우
  계산 기능으로 사칙연산의 결과를 출력합니다.
## 👩‍💻 요구 사항과 구현 내용 
- Map에 연산 저장 및 조회 기능 구현 완료 
  - repository를 따로 만들어 구현하였습니다.
  - Map은 저장된 계산 이력에 순서(오래된~최신)가 존재하기 때문에 TreeMap을 이용하였습니다.
  - 저장하는 메서드 save의 경우 
    - key는 항상 map.size()+1이 되어 뒤에부터 저장됩니다.
  - 조회하는 메서드 findAll의 경우
     - Map에 아무것도 들어있지 않으면 return;
- 연산을 숫자와 연산자로 구별하는 기능 구현 완료
  - 정규식을 이용하여 숫자와 연산자를 분리하는 class를 별도로 분리했습니다. 
- "2"번 계산을 선택한 경우 계산 서비스 구현 완료
   - 후위표기식을 이용하였습니다.
- "1"번 조회 선택시 repository에 있는 목록 조회 기능 완료
   - MapRepository에 구현된 findAll()메서드를 호출하여 모든 계산 이력을 가져옵니다.
-  main()메서드 구현 완료
## ✅ PR 포인트 & 궁금한 점 
- 기능들을 어느정도까지 쪼개야하는지 잘 모르겠습니다.
  - SearchServie.class는 MapRepository의 findAll()메서드를 호출하는데 main()에서 바로 findAll() 호출하는게 맞는지 모르겠습니다. 

## 구현하지 못한 기능
-  eof로 구현
-  0으로 나눌 때의 예외처리
-  테스트 코드

2023-06-06 17:35 UTC, Jo-GyuHyeon requested changes
안녕하세요 별 🌟  님 반가워요. 🙇
첫 PR 축하드려요. 🥳

커밋 단위를 최대한 잘게 나뉘려고 노력하신 부분이 느껴져서 좋았습니다. 👍 


### 👽 코드 정렬 
이번 리뷰 코멘트가 많은것은 코드 정렬 때문이에요. 코드 정렬은 가독성과 연결이 될 수도 있는데요.
흔히 아버지가 방에 들어 가신다. -> 아버지 가방에 들어 가신다.  라는 것을 들어 보셨을까요? 
![image](https://github.com/prgrms-be-devcourse/java-calculator/assets/20269425/e718e1c8-d932-4a07-9125-efd8714419c1)

그만큼 별개 아닐수 있지만 실은 중요한 포인트로 생각을 하고 있어요.

만약 정렬에 대한 도움을 받고 싶으시다면 해당 IDE 에서 자동정렬 기능을 이용하는 것도 좋아요.
(Intellij 기준  MacOS ->  Cmd + option + L , Windows -> ctr + alt + L)
https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html

### 👐 
첫 PR 에 코멘트가 많아 어려움이 있을것이라 생각도 들어요. 🔆 
다음을 진행 하기 보다 리뷰 내용을 바탕으로 개선한 뒤에 다음 PR 에서 추가 기능, 구현 하지 못한 기능을 이어나가면 어떨까 싶어요. 🙇 
OOP 과제인 만큼 최대한 OOP 에 스타일에 집중 해볼까요? 👍

2023-06-06 17:35 UTC, Jo-GyuHyeon commented on src/main/java/com/programmers/java/service/CalculateService.java
> +            }
해당 범위의 코드를 보았을때는 어떠한 조건이 맞지 않았는지 눈에 쉽게 보이지 않는것 같아요. (가독성이 낮아요) 👀 
어떤 조건인지 한눈에 띄면 더욱 가독성도 좋아 질 뿐더라 들여쓰기(인덴트) 를 줄일수 있는 효과도 같이 따라 올것이라 기대 해요. 👯

2023-06-06 17:35 UTC, Jo-GyuHyeon commented on src/main/java/com/programmers/java/service/CalculateService.java
> +                    int secondP = prior.indexOf(output);
여러 포인트에서 인덱스를 직접 활용하여 문자열에 접근하는 코드들이 보이는 것 같아요. 🙄 
이번 과제는 OOP 을 특징을 살리는 것 만큰 객체의 관점과 협력 할 수 있는 방향에 고민을 하여 문자열을 다루는 로직을 최소한으로 가져 가는 방향에 대해 고민을 해보시면 좋을것 같아요.
한번에 생각하기 어렵다면 큰 문제들을 최대한 작은 단위로 쪼개어서 고민 해보시면 도움이 될것 같아요. 🎇

2023-06-06 17:35 UTC, Jo-GyuHyeon commented on src/main/java/com/programmers/java/repository/MapRepository.java
> +
키 값을 순차적인 숫자로 사용하시게 된다면, Key 의 의미는 어떤 것이 있을까요?
활용도는 Array 와 유사할것 같아 질문을 드려보았어요. 😄

2023-06-06 17:35 UTC, Jo-GyuHyeon commented on src/main/java/com/programmers/java/service/CalculateService.java
> +                break;
위의 리뷰 내용과 동일하여 간단히 제안만 드려볼게요. 🌤️
```suggestion
            case "+":
                digitResult = Integer.toString(first + second);
                break;
```

2023-06-07 13:20 UTC, byeolhaha commented on src/main/java/com/programmers/java/Main.java
> +            SearchService searchService = new SearchService();
재사용을 고려하지 못했는데 고려하도록 노력하겠습니다!

2023-06-07 13:21 UTC, byeolhaha commented on src/main/java/com/programmers/java/Main.java
> +
띄어쓰기와 코드 정렬 고치도록 하겠습니다!

2023-06-07 13:22 UTC, byeolhaha commented on src/main/java/com/programmers/java/Main.java
> +        }else{
그 생각을 하지 못했습니다. swtich default문을 사용해서 그 외 처리를 하도록 고치겠습니다!

2023-06-08 14:41 UTC, byeolhaha commented on src/main/java/com/programmers/java/Main.java
> +        }else{
넵 고치겠습니다!

2023-06-08 14:41 UTC, byeolhaha commented on src/main/java/com/programmers/java/repository/MapRepository.java
> +
넵 고치겠습니다!

2023-06-08 14:42 UTC, byeolhaha commented on src/main/java/com/programmers/java/repository/MapRepository.java
> +    public static void findAll() throws IOException {
SearchService에서 사용해서 static으로 해놓았습니다.

2023-06-08 14:43 UTC, byeolhaha commented on src/main/java/com/programmers/java/repository/MapRepository.java
> +        if(map.size()==0) return;
넵 고치겠습니다!

2023-06-08 14:45 UTC, byeolhaha commented on src/main/java/com/programmers/java/service/SearchService.java
> +        MapRepository.findAll();
아 이 부분은 제가 생각해도 이상해서 고치도록 하겠습니다!

2023-06-08 14:45 UTC, byeolhaha commented on src/main/java/com/programmers/java/service/SearchService.java
> +    public void searchResult() throws IOException{
네 고치도록 하겠습니다!

2023-06-08 14:45 UTC, byeolhaha commented on src/main/java/com/programmers/java/util/OptSplit.java
> +        while(matcher.find()){
네 고치도록 하겠습니다!

2023-06-09 17:09 UTC, byeolhaha commented on src/main/java/com/programmers/java/service/CalculateService.java
> +                        digit.add(makeResult(digit.pop(),inputResult.get(i),output));
제가 전반적으로 다른 사람이 이해하기 어려운 코드를 구현하는 습관을 가지고 있어 다음 pr에서는 개선된 모습으로 등장하겠습니다. 😂

2023-06-09 17:14 UTC, byeolhaha commented on src/main/java/com/programmers/java/service/CalculateService.java
> +            }
생각하지 않고 단순히 구현에만 치우친 부분들이 많아 개선하도록 노력하겠습니다. 또한 else 구문에 대해서 고민하여 사용하도록 하겠습니다 🧾

2023-06-09 17:19 UTC, byeolhaha commented on src/main/java/com/programmers/java/service/CalculateService.java
> +                    int secondP = prior.indexOf(output);
미리 종이에 적으며 작은 단위로 쪼개고 생각한 다음에 구현하도록 노력하겠습니다.  📖 제가 팀장의 역할을 맡았다고 생각하고 각각의 역할과 책임의 구분을 짓도록  생각하고 구현하겠습니다. 💡

2023-06-09 17:21 UTC, byeolhaha commented on src/main/java/com/programmers/java/repository/MapRepository.java
> +
생각해보니 Array에 저장하면 앞에서부터 순서대로 저장되는데 그 생각을 하지 못했습니다 다음에 pr에서는 Array를 사용하도록 하겠습니다

2023-06-09 17:25 UTC, byeolhaha commented
코드 리뷰해주셔서 정말 감사합니다.
전체적으로 가독성이 떨어지고 
저 혼자만 읽을 수 있는 코드를 구현한 것 같습니다.
또한 OOP의 특징을 찾아볼 수 없어 다음 PR에서는 더 개선된 모습으로 등장하겠습니다.🐣
같은 부분을 계속 틀렸는데 그 부분에 대해서 매번 고쳐주셔서 정말 감사드립니다.

2023-06-09 17:46 UTC, byeolhaha commented on src/main/java/com/programmers/java/util/OptSplit.java
> +public class OptSplit {
저는 혼자만 알아볼 수 있는 코드를 전체적으로 구현한 것 같아 이 부분에 대해서 계속 생각하며 구현하겠습니다.

2023-06-09 17:53 UTC, byeolhaha commented on src/main/java/com/programmers/java/util/OptSplit.java
> +        Pattern pattern = Pattern.compile("\\d+|[-+*/]");
변수로 선언하는 이유조차 잊어버리고 코드를 너무 생각 없이 만들었습니다. 
생각하며 구현하도록 노력하겠습니다.

2023-06-09 17:53 UTC, byeolhaha commented on src/main/java/com/programmers/java/service/CalculateService.java
> +    private static String prior= "-+*/";
네 단축키를 외워서 이제는 절대 위와 같이 구현하지 않도록 노력하겠습니다.

2023-06-09 17:54 UTC, byeolhaha commented on src/main/java/com/programmers/java/service/CalculateService.java
> +        String answer="";
네 고치겠습니다 !

2023-06-09 17:57 UTC, byeolhaha commented on src/main/java/com/programmers/java/util/OptSplit.java
> +    public ArrayList<String> getSplit(String optString){
메서드의 이름으로 역할이 더 명확하게 보여지도록 생각하며 구현하겠습니다

2023-06-09 17:58 UTC, byeolhaha commented on src/main/java/com/programmers/java/service/CalculateService.java
> +
불필요한 부분을 제거하겠습니다 !

2023-06-09 18:01 UTC, byeolhaha commented on src/main/java/com/programmers/java/service/CalculateService.java
> +
네 고치겠습니다 !

2023-06-09 18:03 UTC, byeolhaha commented on src/main/java/com/programmers/java/service/CalculateService.java
> +        switch (secondP){
같은 부분인데 매번 지적해주셔서 감사합니다.  다음번에는 더 성장해서 등장하겠습니다.

2023-06-09 18:04 UTC, byeolhaha commented on src/main/java/com/programmers/java/repository/MapRepository.java
> +public class MapRepository {
해당 객체의 명확한 역할이 나타나도록 네이밍 하도록 하겠습니다. 😭

2023-06-09 18:06 UTC, byeolhaha commented on src/main/java/com/programmers/java/service/CalculateService.java
> +        mapRepository.save(sb.toString());
제가 책임과 역할에 대해서 고려하지 않고 구현한 것 같습니다. 해당 객체는 계산의 역할만 담당했어야 했는데 제가 저장하는 객체에서 해야 할 일까지 주었습니다.

2023-06-09 18:06 UTC, byeolhaha commented on src/main/java/com/programmers/java/service/CalculateService.java
> +        String digitResult ="";
네 제가 이 부분은 꼭 고치겠습니다. (정말 매번 고쳐주셔서 정말 감사합니다)

2023-06-09 18:47 UTC, byeolhaha commented on src/main/java/com/programmers/java/service/CalculateService.java
> +                break;
가독성 있는 코드를 구현하도록 노력하겠습니다

2023-06-10 16:01 UTC, Jo-GyuHyeon commented
- https://github.com/prgrms-be-devcourse/java-calculator/pull/116 해당 PR 은 Re Open 처리 하도록 할게요.
이전 PR 에서 리뷰 내용이 존재하기도 하며, 반영 여부를 확인하기가 좋을것 같아서 결정하게 되었어요.

해당 PR 은 CLOSE 처리 도와 드릴게요.

2023-06-10 16:03 UTC, Jo-GyuHyeon commented
해당 PR 에서 리뷰 내용이 존재하기도 하며, 반영 여부를 확인하기가 좋을것 같아서 Re Open 결정하게 되었어요.

2023-06-10 17:32 UTC, byeolhaha commented
개선할 점들을 반영하여 다시 PR 제출하겠습니다.

2023-06-12 00:59 UTC, byeolhaha commented on src/main/java/com/programmers/java/Main.java
> +        }else{
2b3859a에 반영
- switch문을 활용하여 1과 2가 아닌 경우 예외 처리를 반영하였습니다.
- 예외 처리의 경우 "계산기를 종료합니다." 라는 안내와 함께 시스템이 종료되도록 설계하였습니다.
-----------------------------
2a99e24에 반영
- 계산된 결과를 조회할 수 있도록 콘솔창을 다시 불러오는 재귀함수를 사용하여 반영하였습니다.

2023-06-12 01:06 UTC, byeolhaha commented on src/main/java/com/programmers/java/service/CalculateService.java
> +                        digit.add(makeResult(digit.pop(),inputResult.get(i),output));
[c95dd3f](https://github.com/prgrms-be-devcourse/java-calculator/pull/123/commits/c95dd3fcce72e7eabacca8f327808c76b80068e2)
- for문의 경우 증감식을 사용하지 않기 때문에 while문을 사용하는 방법을 적용하였습니다.
- index라는 변수가 인덱스 접근 범위에 벗어나지 않도록 while문 조건식에 추가하였습니다.

2023-06-12 01:08 UTC, byeolhaha commented on src/main/java/com/programmers/java/repository/MapRepository.java
> +
[426465f](https://github.com/prgrms-be-devcourse/java-calculator/pull/123/commits/426465f89059abe58c4d548cb7de57f4497a2fbc)에 반영
- Map에 키 값이 굳이 필요하지 않다고 느껴 ArrayList를 이용하여 뒤에 계속 저장하는 방식으로 구현하였습니다.

2023-06-12 01:12 UTC, byeolhaha commented on src/main/java/com/programmers/java/Main.java
> +            SearchService searchService = new SearchService();
[029fd54](https://github.com/prgrms-be-devcourse/java-calculator/pull/123/commits/029fd5461bd7129c15835f11aae8824358022d87)에 반영
- 재사용성을 고려하여 main 메서드에 생성해서 계속 재사용하는 방법으로 구현하였습니다.

2023-06-12 01:15 UTC, byeolhaha commented on src/main/java/com/programmers/java/service/CalculateService.java
> +                    int secondP = prior.indexOf(output);
[d651305](https://github.com/prgrms-be-devcourse/java-calculator/pull/123/commits/d651305f2aaacd3a2d4d29a33b09e6347c9153b0)에 반영
- 미리 종이에 어떻게 나눌 수 있는지 고민하고 구조를 설계해 보았습니다
- 이전에 말씀해주셨던 조회 기능(Seacher)과 조회 결과(Output)를 보여주는 기능을 나누었습니다.

2023-06-12 01:51 UTC, byeolhaha commented
## 💡 이전 코드리뷰 피드백은 반영하여 계산기 구현 미션 다시 제출합니다.

### 📌 과제 설명
- 코드리뷰 피드백만을 개선하였고
-  `우선순위`를 고려하지 않고 설계하였습니다.

### 👩‍💻 요구 사항과 구현 내용
이전에 주셨던 코드 리뷰 피드백을 반영하여 
- 가독성 부족한 부분에 대하여 코드 정렬과 자연스러운 메서드명을 사용하려고 노력하였습니다.
- OOP 설계를 고려하여 미리 종이에 설계하여 팀장의 역할을 맡았다 생각하고 역할과 책임을 쪼개 보았습니다.
- static 메서드의 특징을 고려하여 설계하였습니다.

### 🧨구현하지 못한 기능
- 우선순위
- 테스트 코드

2023-06-12 02:52 UTC, Jo-GyuHyeon requested changes
별님 고생하셨어요. 🙇 
간단하게 리뷰를 남겨 보았는데요. 
다음 리뷰는 이번 코드 리뷰 내용을 반영해주신 것 까지만 진행 하여 짧게 끊어 가면 어떨까 싶어요.

2023-06-12 02:52 UTC, Jo-GyuHyeon commented on src/main/java/com/programmers/java/calculator/Controller.java
> +        Output output = new Output();
console 메서드 실행 시킬때 마다 객체 생성이 이루어 질 것 같아요.
Controller 의 필드로 둬도 될것 같아요.

2023-06-12 02:52 UTC, Jo-GyuHyeon commented on src/main/java/com/programmers/java/Main.java
> +        controller.console(new Calculator(), new Searcher());
메인에서 보았을때 어떤 객체의 어떤 메서드 (행위) 일까? 라고 생각이 드는 것 같아요.
꼭 Controller 가 필요 할지? 고민 해보시는 것도 좋을것 같아요.

정답은 없어요.
main 에 있어도 괜찮지 않겠어? 라는 생각도 해보셔도 좋을것 같은데 별님의 의견이 중요해요.

2023-06-12 02:52 UTC, Jo-GyuHyeon commented on src/main/java/com/programmers/java/calculator/Controller.java
> +                output.viewCalculateResult(calculator.getResult(expression));
calculator의 getResult() 메서드 보다 계산하다 라는 네이밍이 어떨까요? calculate()
메서드는 리턴 타입으로 리턴 값을 가질수 있어요. 계산 하였으니 리턴된 값은 자연스럽게 계산의 결과 일 것 같아요.

2023-06-12 02:52 UTC, Jo-GyuHyeon commented on src/main/java/com/programmers/java/calculator/calculate/Calculator.java
> +
불필요한 개행은 줄여주세요. 😄

2023-06-12 02:52 UTC, Jo-GyuHyeon commented on src/main/java/com/programmers/java/calculator/calculate/Calculator.java
> +            String token = tokenList.get(index++);
Stack<Double> tempStack 꼭 활용 할까? 라는 생각이 들었어요.
계산 결과와 while 문을 위해서 사용하는것 같아요.

List<String> tokenList 를 (향상된 for 문 == for each loop 으로) 순회 하는 것은 어떨까요?
https://www.w3schools.com/java/java_foreach_loop.asp

2023-06-12 02:52 UTC, Jo-GyuHyeon commented on src/main/java/com/programmers/java/calculator/calculate/Calculator.java
> +        List<String> tokenList = expressionTokenizer.expressionSplit(expression);
String expression 를 파라미터로 받는것도 좋지만, List<String> tokenList 를 파라미터로 받으면 어떨까요? 
별님의 의견이 궁금해요.

2023-06-12 02:52 UTC, Jo-GyuHyeon commented on src/main/java/com/programmers/java/calculator/search/Searcher.java
> +public class Searcher {
Searcher 를 꼭 필요할까요? ResultRepository 를 감싸는 것 이외에 어떠한 장점이 있을지 잘 모르겠어요.

2023-06-12 02:52 UTC, Jo-GyuHyeon commented on src/main/java/com/programmers/java/util/ExpressionTokenizer.java
> +    private static final String REGEXP = "\\d+|[-+*/]";
REGEXP 보다는 어떤 정규식인지 네이밍을 구체화 해주면 더 좋을것 같아요.

2023-06-12 02:52 UTC, Jo-GyuHyeon commented on src/main/java/com/programmers/java/view/Input.java
> +                    break;
Button 의 value 를 활용하여 Button enum 객체를 찾을수 있도록 Button 에게 책임을 몰아주면 좋을것 같아요.

2023-06-12 03:07 UTC, byeolhaha commented on src/main/java/com/programmers/java/calculator/Controller.java
> +        Output output = new Output();
그 부분을 미처 생각하지 못했어요💡  
필드로 둬서 재사용 하도록 하겠습니다 ✏️

2023-06-12 03:41 UTC, byeolhaha commented on src/main/java/com/programmers/java/calculator/Controller.java
> +                output.viewCalculateResult(calculator.getResult(expression));
생각해보니 void가 아닌 모든 메서드는 getResult인데 어떤 역할을 하는지 구체적으로 드러나는 이름을 짓도록 노력할게요.

2023-06-12 03:43 UTC, byeolhaha commented on src/main/java/com/programmers/java/calculator/calculate/Calculator.java
> +
다음엔 불필요한 개행 모두 줄일게요 😵

2023-06-12 04:01 UTC, byeolhaha commented on src/main/java/com/programmers/java/calculator/calculate/Calculator.java
> +            String token = tokenList.get(index++);
Stack으로 하지 않고 그냥 double 변수에 저장해도 되는 일이었는데 불필요하게 Stack을 사용한 것 같아요.
향상된 for문을 적용하여 더 깔끔한 코드로 구현할게요

2023-06-12 04:03 UTC, byeolhaha commented on src/main/java/com/programmers/java/calculator/calculate/Calculator.java
> +        List<String> tokenList = expressionTokenizer.expressionSplit(expression);
계산만 하도록 하는 것이 역할이 더 분명해 보여 파라미터로 tokenList를 받도록 수정할게요✏️

2023-06-12 04:06 UTC, byeolhaha commented on src/main/java/com/programmers/java/util/ExpressionTokenizer.java
> +    private static final String REGEXP = "\\d+|[-+*/]";
변수명에 어떤 정규식인지 알 수 있도록 표현하도록 할게요.

2023-06-12 04:12 UTC, byeolhaha commented on src/main/java/com/programmers/java/view/Input.java
> +                    break;
Enum을 활용하는 방법에 대해서 공부하고 적용해볼게요🐣

2023-06-12 04:14 UTC, Jo-GyuHyeon commented on src/main/java/com/programmers/java/view/Input.java
> +                    break;
@byeolhaha 정척 팩토리 메서드 를 고려해보면 좋을것 같아요!

2023-06-12 04:16 UTC, byeolhaha commented on src/main/java/com/programmers/java/Main.java
> +        controller.console(new Calculator(), new Searcher());
저만 알 수 있는 있도록 네이밍을 한 점과
굳이 불필요하게 나눠서 진행한 점을 고려하여 수정하도록 할게요

2023-06-12 04:25 UTC, byeolhaha commented on src/main/java/com/programmers/java/calculator/search/Searcher.java
> +public class Searcher {
저번에도 같은 피드백을 주셨는데 고려하지 못하고 구현했어요
불필요하게 한번 더 거치도록 만들어서 수정하도록 할게요 ✏️

2023-06-12 04:28 UTC, HyoungUkJJang reviewed
별님 리뷰 반영하느라 고생하셨습니다. 

규현 멘토님께서 리뷰를 잘 작성해주셔서 제가 남길 부분이 크게 많이 없는 것 같네요 :) 
아주 사소한 부분만 남겼으니 한번 참고해 주세요 ~

2023-06-12 04:28 UTC, HyoungUkJJang commented on src/main/java/com/programmers/java/calculator/Controller.java
> +        System.out.println("2.계산");
Output의 책임으로 넘길 수 있을 것 같습니다.

2023-06-12 04:28 UTC, HyoungUkJJang commented on src/main/java/com/programmers/java/view/Output.java
> +    public void viewSearchResult(ArrayList<String> calcList) {
ArrayList에 의존하는 이유는 무엇일까요?

2023-06-12 04:28 UTC, HyoungUkJJang commented on src/main/java/com/programmers/java/view/Input.java
> +            System.out.println("계산기를 종료합니다.");
이것 또한 Output의 책임으로 넘길 수 있을 것 같습니다.

2023-06-12 04:28 UTC, HyoungUkJJang commented on src/main/java/com/programmers/java/repository/ResultRepository.java
> +@Getter
롬복을 사용하신 명확한 이유가 있으실까요?

2023-06-12 04:28 UTC, HyoungUkJJang commented on src/main/java/com/programmers/java/repository/ResultRepository.java
> +    public ArrayList<String> getCalculationResults() {
구현체를 반환하는 이유는 무엇일까요?

2023-06-12 04:37 UTC, byeolhaha commented on src/main/java/com/programmers/java/calculator/Controller.java
> +        System.out.println("2.계산");
Output과 Controller의 책임이 명확하게 구분되어 있지 않네요 
수정하도록 할게요 ✏️

2023-06-12 04:38 UTC, byeolhaha commented on src/main/java/com/programmers/java/view/Input.java
> +            System.out.println("계산기를 종료합니다.");
보이는 책임과 입력의 책임을 명확하게 구분하지 못했어요 
더 깊이 생각하고 구현하도록 할게요 💡

2023-06-12 04:44 UTC, byeolhaha commented on src/main/java/com/programmers/java/view/Output.java
> +    public void viewSearchResult(ArrayList<String> calcList) {
구현체에 의존하기 때문에 List로 수정할게요 ✏️

2023-06-12 04:48 UTC, byeolhaha commented on src/main/java/com/programmers/java/repository/ResultRepository.java
> +    public ArrayList<String> getCalculationResults() {
List로 수정할게요.
확장성을 고려하지 않고 코드를 작성했어요.

2023-06-12 16:14 UTC, byeolhaha commented on src/main/java/com/programmers/java/calculator/Controller.java
> +        Output output = new Output();
[7cf7a62](https://github.com/prgrms-be-devcourse/java-calculator/pull/123/commits/7cf7a62eeec19f2ed0bbeeb69657e12ef5349f99)에 반영
- Controller의 기능을 main으로 옮기며 필드로 수정하였습니다.

2023-06-12 16:16 UTC, byeolhaha commented on src/main/java/com/programmers/java/Main.java
> +        controller.console(new Calculator(), new Searcher());
[c38e9bb](https://github.com/prgrms-be-devcourse/java-calculator/pull/123/commits/c38e9bbe011823c8e7c5c4363b412cdaece8e685)
- 불필요한 Controller 삭제

[7cf7a62](https://github.com/prgrms-be-devcourse/java-calculator/pull/123/commits/7cf7a62eeec19f2ed0bbeeb69657e12ef5349f99)에 반영
- Contorller의 기능을 main으로 옮겨 불필요하게 나눠서 진행한 부분을 수정하였습니다.

2023-06-12 16:17 UTC, byeolhaha commented on src/main/java/com/programmers/java/calculator/Controller.java
> +                output.viewCalculateResult(calculator.getResult(expression));
[a07ecd8](https://github.com/prgrms-be-devcourse/java-calculator/pull/123/commits/a07ecd8c414fabadb0b452969c97c9153e49af0c)에 반영
- 메서드의 기능이 더 잘 나타나도록 getResult에서 calculate로 수정하였습니다.

2023-06-12 16:18 UTC, byeolhaha commented on src/main/java/com/programmers/java/calculator/calculate/Calculator.java
> +
[581cb6d](https://github.com/prgrms-be-devcourse/java-calculator/pull/123/commits/581cb6dd44d59f826b9c27d5c52c7cafff340a7f)에 반영
- 불필요한 개행을 삭제했습니다.

2023-06-12 16:21 UTC, byeolhaha commented on src/main/java/com/programmers/java/calculator/calculate/Calculator.java
> +        List<String> tokenList = expressionTokenizer.expressionSplit(expression);
[04e114b](https://github.com/prgrms-be-devcourse/java-calculator/pull/123/commits/04e114b5a5b0c7c7d6dc769ac63c40b34071d49c)에 반영
- 파라미터를 수정하여 계산의 역할만 하도록 하였습니다.

2023-06-12 16:22 UTC, byeolhaha commented on src/main/java/com/programmers/java/calculator/search/Searcher.java
> +public class Searcher {
[c38e9bb](https://github.com/prgrms-be-devcourse/java-calculator/pull/123/commits/c38e9bbe011823c8e7c5c4363b412cdaece8e685)에 반영

2023-06-12 16:23 UTC, byeolhaha commented on src/main/java/com/programmers/java/util/ExpressionTokenizer.java
> +    private static final String REGEXP = "\\d+|[-+*/]";
[c38e9bb](https://github.com/prgrms-be-devcourse/java-calculator/pull/123/commits/c38e9bbe011823c8e7c5c4363b412cdaece8e685)에 반영
- REGEXP에서 OPERATOR_REGEXP로 수정하였습니다.

2023-06-12 16:24 UTC, byeolhaha commented on src/main/java/com/programmers/java/view/Input.java
> +                    break;
[34ce324](https://github.com/prgrms-be-devcourse/java-calculator/pull/123/commits/34ce3245d38469ce3adc972e726e899a36ce1d05)과 [0af079f](https://github.com/prgrms-be-devcourse/java-calculator/pull/123/commits/0af079fe195ad566d0e1bc085d33f5c874407b28)에 반영
- Button에 value를 활용한 책임을 주었습니다.

2023-06-12 16:25 UTC, byeolhaha commented on src/main/java/com/programmers/java/calculator/Controller.java
> +        System.out.println("2.계산");
[e55608f](https://github.com/prgrms-be-devcourse/java-calculator/pull/123/commits/e55608fc539c8ca34fbd612667838fbf4731f5ac)에 반영
- Output과 Input의 책임을 구분하여 Output으로 책임을 넘겼습니다.

2023-06-12 16:26 UTC, byeolhaha commented on src/main/java/com/programmers/java/view/Output.java
> +    public void viewSearchResult(ArrayList<String> calcList) {
[e55608f](https://github.com/prgrms-be-devcourse/java-calculator/pull/123/commits/e55608fc539c8ca34fbd612667838fbf4731f5ac)에 반영

2023-06-12 16:26 UTC, byeolhaha commented on src/main/java/com/programmers/java/view/Input.java
> +            System.out.println("계산기를 종료합니다.");
[e55608f](https://github.com/prgrms-be-devcourse/java-calculator/pull/123/commits/e55608fc539c8ca34fbd612667838fbf4731f5ac)에 반영
- Input에 있었던 Output의 책임을 Output에게 넘겼습니다.

2023-06-13 11:36 UTC, byeolhaha commented on src/main/java/com/programmers/java/repository/ResultRepository.java
> +@Getter
처음에 실수로 넣었는데 삭제하지 못했어요 😵 [6071833](https://github.com/prgrms-be-devcourse/java-calculator/pull/123/commits/60718330b804323e1f924cc7f90932725f1e4a6b) 에 반영하여 삭제했어요.

2023-06-13 11:37 UTC, byeolhaha commented on src/main/java/com/programmers/java/repository/ResultRepository.java
> +    public ArrayList<String> getCalculationResults() {
[6071833](https://github.com/prgrms-be-devcourse/java-calculator/pull/123/commits/60718330b804323e1f924cc7f90932725f1e4a6b)에 반영

2023-06-14 05:38 UTC, byeolhaha commented
## 💡 이전 코드 리뷰를 반영하여 계산기 구현 미션 다시 제출합니다.

### 👩‍💻 요구 사항과 구현 내용
이전에 주셨던 코드 리뷰 피드백을 반영하여 
-  Java 코딩 켄벤션 지키기 
-  Enum Menu에게 Menu를 찾는 책임을 부여하기 위해 정적 팩토리 메서드로 사용
-  불필요한 클래스 삭제
-  기능과 역할이 잘 나타나도록 메서드명, 변수명, 클래스명 변경
-  불명확했던 Output과 Input 책임 분리
-  자료형에 대한 확장성 부여
-  연산자를 Enum으로 분리
수정하였습니다.
###  📝 UML
![image](https://github.com/prgrms-be-devcourse/java-calculator/assets/108210958/6d791407-9326-41cc-84a0-34447e060739)

### 🧨구현하지 못한 기능
- 우선순위
- 테스트 코드

2023-06-15 04:24 UTC, Jo-GyuHyeon reviewed
간단하게 리뷰 드렸어요.
UML 잘 그리셨군요 👍.
간단한 리뷰라 바로 다음으로 진행 해도 좋을것 같아요.

2023-06-15 04:24 UTC, Jo-GyuHyeon commented on src/test/java/com/programmers/java/view/InputTest.java
> +
불필요한 개행은 줄여 주세요.

2023-06-15 04:24 UTC, Jo-GyuHyeon commented on src/test/java/com/programmers/java/view/InputTest.java
> +    @Test
어노테이션 위에 개행 하나 추가 해주세요. 😄

2023-06-15 04:24 UTC, Jo-GyuHyeon commented on src/main/java/com/programmers/java/Main.java
> +        Double result = calculator.calculate(expressionTokenizer.expressionSplit(expression));
try catch 구문 전후로 개행 추가 하시면 좋을것 같아요.

2023-06-15 04:24 UTC, Jo-GyuHyeon commented on src/main/java/com/programmers/java/view/Menu.java
> +    private final String value;
열거 타입 선언과 value 변수 사이의 개행을 추가 하면 좋을것 같아요.

2023-06-15 11:07 UTC, byeolhaha commented on src/test/java/com/programmers/java/view/InputTest.java
> +
[42dada5](https://github.com/prgrms-be-devcourse/java-calculator/pull/123/commits/42dada5f5fdb03e288fc72ee648b4603ba8abbac)에 반영했어요. 꼼꼼하게 확인해볼게요🕵️‍♀️

2023-06-15 11:07 UTC, byeolhaha commented on src/test/java/com/programmers/java/view/InputTest.java
> +    @Test
[42dada5](https://github.com/prgrms-be-devcourse/java-calculator/pull/123/commits/42dada5f5fdb03e288fc72ee648b4603ba8abbac)에 반영했어요.

2023-06-15 11:08 UTC, byeolhaha commented on src/main/java/com/programmers/java/Main.java
> +        Double result = calculator.calculate(expressionTokenizer.expressionSplit(expression));
[42dada5](https://github.com/prgrms-be-devcourse/java-calculator/pull/123/commits/42dada5f5fdb03e288fc72ee648b4603ba8abbac)에 반영했어요✏️

2023-06-15 11:08 UTC, byeolhaha commented on src/main/java/com/programmers/java/view/Menu.java
> +    private final String value;
[42dada5](https://github.com/prgrms-be-devcourse/java-calculator/pull/123/commits/42dada5f5fdb03e288fc72ee648b4603ba8abbac)에 반영했어요✏️

2023-06-16 01:20 UTC, Jo-GyuHyeon reviewed
간단하게 리뷰 드렸어요.
거의 막바지내요 고생 많으셨어요. 🙇

2023-06-16 01:20 UTC, Jo-GyuHyeon commented on src/main/java/com/programmers/java/Main.java
> +                        (expressionTokenizer.expressionSplit(expression)));
calculate() 는 한줄로 표기하는것이 좋을것 같아요.
인자가 중첩이 많거나 길면 변수로 빼는 것이 좋을것 같아요.

2023-06-16 01:20 UTC, Jo-GyuHyeon commented on src/main/java/com/programmers/java/calculator/calculate/PostfixConverter.java
> +                .forEach(v -> postfixExpression.append(v).append(" "));
단순히 반복만 하는 경우라면 향상된 for 문 (for-each-loop) 를 사용하는 것이 좋을것 같아요.

2023-06-16 01:20 UTC, Jo-GyuHyeon commented on src/main/java/com/programmers/java/calculator/calculate/PostfixConverter.java
> +                    && Operator.evaluatePriority(prevOperator, nextOperator) > 0) {
evaluatePriority() 를 이용해서 0 보다 크나 작다는 가독성이 떨어 지는 것 같아요. (0에 대한 의미 파악이 어려워요)
또한 어떤 Operator 가 우선 순위가 높은지 파악하기 어려 운것 같아요.
prevOperator.isPriority(nextOperator) 와 처럼 객체를 이용해서 비교 하는 것은 어떨까요?

2023-06-16 03:44 UTC, Jo-GyuHyeon commented on src/main/java/com/programmers/java/Main.java
> +    }
System 사용 제한과, while 의 무한 루프 대신 이런식으로 변경 해보면 어떨까 싶어서 코드 제안 드려보았어요.

```suggestion
    public static void main(String[] args) throws IOException {
    	boolean isRunning = true
    	
        while (isRunning) {
            output.viewMenu();

            input.enterMenu().ifPresentOrElse(
                    Main::runCalculator,
                    () -> {
                        isRunning = false;
                        output.viewEndMessage();
                    }
            );
        }
    }
```

2023-06-16 05:24 UTC, byeolhaha commented on src/main/java/com/programmers/java/Main.java
> +                        (expressionTokenizer.expressionSplit(expression)));
너무 길다는 생각이 들었는데 변수로 빼는 방법을 적용할게요 💡

2023-06-16 05:27 UTC, byeolhaha commented on src/main/java/com/programmers/java/calculator/calculate/PostfixConverter.java
> +                .forEach(v -> postfixExpression.append(v).append(" "));
stream()을 이용해서 단순 반복의 forEach만을 사용하는 방법은 추천되지 않는 방법이군요💡 향상된 for문을 사용하도록 할게요📝

2023-06-16 05:32 UTC, byeolhaha commented on src/main/java/com/programmers/java/calculator/calculate/PostfixConverter.java
> +                    && Operator.evaluatePriority(prevOperator, nextOperator) > 0) {
이 메서드에  대해서 저만 알아볼 수 있는 것 같아서 계속 고민했는데 방법을 제안해주셔서 감사해요 🙇‍♀️

2023-06-16 09:43 UTC, byeolhaha commented on src/main/java/com/programmers/java/Main.java
> +    }
더 알기 쉬운 코드를 작성하도록 노력할게요 ✏️

2023-06-16 14:20 UTC, HyoungUkJJang reviewed
별님 고생 많으셨습니다 :) 코드가 정말 많이 좋아진 것 같아요 ~

간단하게 코멘트 몇개 남겼습니다 ! 조금만 더 화이팅이에요 ~ 👍🏻

2023-06-16 14:20 UTC, HyoungUkJJang commented on src/main/java/com/programmers/java/Main.java
> +    static PostfixConverter postfixConverter = new PostfixConverter();
접근제어자를 명시하지 않은 이유가 따로 있으실까요~?

2023-06-16 14:20 UTC, HyoungUkJJang commented on src/main/java/com/programmers/java/view/Output.java
> +        }
Stream으로 한번 변경해볼까요?

2023-06-16 14:20 UTC, HyoungUkJJang commented on src/main/java/com/programmers/java/view/Output.java
> +        }
Stream으로 한번 변경해볼까요?

2023-06-16 14:20 UTC, HyoungUkJJang commented on src/main/java/com/programmers/java/util/OperandChecker.java
> +public class OperandChecker {
유틸리티 클래스는 전역적으로 공유해서 사용하는 클래스이기 때문에 외부에서 생성해서 사용하는 것을 방지하는게 좋을 것 같아요 :) 

private 생성자를 통해 외부 생성을 막는 것은 어떨까요?

2023-06-16 14:20 UTC, HyoungUkJJang commented on src/main/java/com/programmers/java/util/ExpressionTokenizer.java
> +public class ExpressionTokenizer {
util 패키지에 있지만 메서드는 정적 메서드가 아닌 것 같습니다 :) 

util 패키지외에 다른 패키지를 고려해보시는건 어떠신가요?

2023-06-16 15:25 UTC, byeolhaha commented on src/main/java/com/programmers/java/Main.java
> +    }
[65e504c](https://github.com/prgrms-be-devcourse/java-calculator/pull/123/commits/65e504c612e5f6b5a0ce21c9bdf3171032fc5a3d)에 반영
- 람다 바디에 지역변수를 참조하게 되면 final이거나 final처럼 작동해야 하는데 while문 안에서 값을 바꿔주기 때문에 final로 설정할 수 없었어요
- 또 이를 인스턴스 변수로 선언하려고 했는데 메인메서드가 static이기 때문에 사용할 수 없었어요
- 그래서 static으로 바꿨는데 static으로 선언한 경우 멀티 스레드 환경에서 동시 접근 등의 문제가 발생한다고 하여 AtomicBoolean을 사용하였어요

[89ebac2](https://github.com/prgrms-be-devcourse/java-calculator/pull/123/commits/89ebac2360136507c264994300289f6a5d01e234)에 반영
- 계산기는 멀티 스레드 환경이 아니기 때문에 다시 static으로 바꾸게 되었어요 
- 혹시 이 생각의 흐름이 맞을까요?

2023-06-16 23:01 UTC, Jo-GyuHyeon approved these changes

2023-06-17 06:43 UTC, byeolhaha commented on src/main/java/com/programmers/java/Main.java
> +    static PostfixConverter postfixConverter = new PostfixConverter();
Main 클래스가 최상위 패키지에 있고 접근제어자를 생략한 경우 default로 명시되어 있어서 다른 하위 클래스에 접근할 수 없다고 생각해서 생략했어요

2023-06-17 06:45 UTC, byeolhaha commented on src/main/java/com/programmers/java/view/Output.java
> +        }
Stream을 이용해서 단순히 for문만을 사용하는 경우는 권장되지 않는 방법이라서 사용하지 않았어요

2023-06-17 06:45 UTC, byeolhaha commented on src/main/java/com/programmers/java/view/Output.java
> +        }
Stream을 이용해서 단순히 for문만을 사용하는 경우는 권장되지 않는 방법이라서 사용하지 않았어요

2023-06-17 08:26 UTC, byeolhaha commented on src/main/java/com/programmers/java/util/ExpressionTokenizer.java
> +public class ExpressionTokenizer {
생각해보니 하나의 클래스에서만 사용하는 기능이여서 클래스의 위치를 바꾸도록 할게요

2023-06-17 08:26 UTC, byeolhaha commented on src/main/java/com/programmers/java/util/OperandChecker.java
> +public class OperandChecker {
그 부분을 생각하지 못했어요 적용하도록 할게요✏️

2023-06-17 09:53 UTC, byeolhaha commented on src/main/java/com/programmers/java/util/OperandChecker.java
> +public class OperandChecker {
[68431ad](https://github.com/prgrms-be-devcourse/java-calculator/pull/123/commits/68431ad6ba54f9f66909c4c34799a7856093e5ae) 에 반영

2023-06-17 09:53 UTC, byeolhaha commented on src/main/java/com/programmers/java/util/ExpressionTokenizer.java
> +public class ExpressionTokenizer {
[7748e81](https://github.com/prgrms-be-devcourse/java-calculator/pull/123/commits/7748e8118ac58b99c270d0dbe56d9bc6496950aa) 에 반영

2023-06-17 09:58 UTC, byeolhaha commented
## 💡 이전 코드 리뷰를 반영하여 마지막 pr 제출합니다.

### 👩‍💻 요구 사항과 구현 내용
이전에 주셨던 코드 리뷰 피드백을 반영하여 수정하였습니다.
- 개행 추가 및 삭제
- while문 조건식에 대해서 로직의 의미가 잘 드러나도록 변수명 바꾸기
- util 클래스의 private 생성자 선언하기

성장할 수 있도록 도와주시고 바쁘신데 코드 리뷰 많이 해주셔서 감사합니다. 🙇‍♀️

2023-06-17 13:58 UTC, merged