[4기 - 황창현] 1~2주차 과제 : 계산기 구현 미션 제출합니다.
prgrms-be-devcourse/java-calculator pull request #124
Opened 2023-06-06 15:17 UTC by Hchanghyeon

## 📌 과제 설명

TDD와 OOP를 활용하여 계산기 만들기.

- [x]  콘솔 기능
- [x]  계산 기능
    - [x]  더하기
    - [x]  빼기
    - [x]  곱하기
    - [x]  나누기
    - [x]  우선순위(사칙연산)
- [x]  테스트 코드 구현
- [x]  데이터 저장 기능(Map 사용)
- [x]  정규식 사용

## 👩‍💻 요구 사항과 구현 내용

**커밋 별 구현 내용**

- **feat: 콘솔 Input, Output 기능 추가**
    - Input과 Output 인터페이스를 Console 클래스로 구현
    - Input은 **기능 선택 입력과 연산식 입력**의 용도로 사용
    - Output은 여러가지 **메세지를 출력**하기 위한 용도로 사용
    - 메시지는 에러메시지와 안내메시지로 구분하여 **enum으로 관리**

- **feat: 연산식 입력 값 검증 기능, 테스트 구현**
    - 연산 전 입력받은 **연산식에 대한 검증**이 필요하다고 생각해서 구현
    - 입력받은 연산식을 분해 후 **연산 가능한 피연산자와 연산자인지 구분하는 검증** 로직 구현
    - **연산자와 피연산자의 전체 개수 검증 및 위치 검증** 구현
    
- **feat: 연산 로직 구현 및 테스트 코드 작성**
    - **중위 표기법 → 후위 표기법**으로 변경하는 기능 구현
    - **후위표기법으로 계산**하는 기능 구현

- **feat: 연산식 및 연산결과 저장소에 저장 기능 구현 및 테스트 코드 작성**
    - 다른 데이터베이스에도 저장될 수 있어 **Interface로 Repository 구현**
    - **저장 기능과 모든 연산식 출력 기능** 구현

**실행결과**

![스크린샷 2023-06-07 오전 12.05.08.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/e79f1369-334f-4100-82ed-ec7b67248d61/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA_2023-06-07_%E1%84%8B%E1%85%A9%E1%84%8C%E1%85%A5%E1%86%AB_12.05.08.png)

## ✅ 피드백 반영사항

## ✅ PR 포인트 & 궁금한 점

자바와 객체지향에 대해서 공부한지 오래되지 않아 많이 부족하지만 최대한 각 객체의 책임을 구분하려 했습니다! 그리고 아직 객체지향에 대한 개념이 부족하여 구현에 초점을 맞춰서 작성했습니다! 감안해서 봐주시면 감사하겠습니다!! 😊

1. 각 **객체에 대한 책임**이 적절하게 이루어진 것 인지, 객체의 책임을 더 **세분화시켜서 나눠야하는지** 궁금합니다.
2. 입력 값을 받을 때 **원하는 값이 아닌 경우 에러를 throw**를 하여 **프로그램을 멈추게** 하는 것이 맞는지 궁금합니다.
→ 저의 경우 원하는 값이 아닐 경우 따로 에러를 throw하지 않고 잘못 입력되었다고 안내해주고 다시 입력 값을 받을 수 있도록 구현했습니다. 이것은 본인이 생각한 로직에 맞게끔 작성하면 되는걸까요?
3. 강의에서 나오는 테스트 코드만 작성해보고, 스스로 작성한 테스트 코드가 처음입니다. 테스트 코드 작성하는 것이 굉장히 어렵다고 느껴지는데 이렇게 작성하는 것이 맞을까요?
4. 제가 작성한 코드에서 조금 더 객체지향적으로 리팩토링하기 위해 참고하면 좋을 무언가가 있을까요?

2023-06-07 21:07 UTC, JoosungKwon reviewed
안녕하세요 창현님! 걱정하셨던 것보다 잘하고 계신것 같습니다! 👍 

전반적으로 일반적인 [자바 컨벤션](https://shongnote.tistory.com/8)을 적용하실 필요가 있어보입니다! [인텔리제이를 활용](https://fubabaz.tistory.com/42)하시면 편리하게 적용하실 수 있습니다!! 

그리고 질문에 대한 답변을 드리면

> 각 객체에 대한 책임이 적절하게 이루어진 것 인지, 객체의 책임을 더 세분화시켜서 나눠야하는지 궁금합니다.
- 코드가 길어지고 복잡해진다면 객체가 너무 많은 책임을 가지고 있는지 생각해보고 좀 더 세분화하는 것을 고려할 것 같습니다!

> 입력 값을 받을 때 원하는 값이 아닌 경우 에러를 throw를 하여 프로그램을 멈추게 하는 것이 맞는지 궁금합니다.
→ 저의 경우 원하는 값이 아닐 경우 따로 에러를 throw하지 않고 잘못 입력되었다고 안내해주고 다시 입력 값을 받을 수 있도록 구현했습니다. 이것은 본인이 생각한 로직에 맞게끔 작성하면 되는걸까요?

- 사용자 입장에서 생각해시면 좋을 것 같습니다! 잘못 입력했다고 프로그램이 종료가 된다면 안정적인 프로그램이라고 할 수 있을까요?

> 강의에서 나오는 테스트 코드만 작성해보고, 스스로 작성한 테스트 코드가 처음입니다. 테스트 코드 작성하는 것이 굉장히 어렵다고 느껴지는데 이렇게 작성하는 것이 맞을까요?

- 성공 테스트뿐만 아니라 실패 테스트까지 작성해보시는 게 좋습니다. [해당 영상](https://youtu.be/YdtknE_yPk4) 보시길 권장해드립니다~

>제가 작성한 코드에서 조금 더 객체지향적으로 리팩토링하기 위해 참고하면 좋을 무언가가 있을까요?
- [객체지향 체조 원칙](https://jamie95.tistory.com/99)를 적용해시는 건 어떨까요?

2023-06-07 21:07 UTC, JoosungKwon reviewed
안녕하세요 창현님! 걱정하셨던 것보다 잘하고 계신것 같습니다! 👍 

전반적으로 일반적인 [자바 컨벤션](https://shongnote.tistory.com/8)을 적용하실 필요가 있어보입니다! [인텔리제이를 활용](https://fubabaz.tistory.com/42)하시면 편리하게 적용하실 수 있습니다!! 

그리고 질문에 대한 답변을 드리면

> 각 객체에 대한 책임이 적절하게 이루어진 것 인지, 객체의 책임을 더 세분화시켜서 나눠야하는지 궁금합니다.
- 코드가 길어지고 복잡해진다면 객체가 너무 많은 책임을 가지고 있는지 생각해보고 좀 더 세분화하는 것을 고려할 것 같습니다!

> 입력 값을 받을 때 원하는 값이 아닌 경우 에러를 throw를 하여 프로그램을 멈추게 하는 것이 맞는지 궁금합니다.
→ 저의 경우 원하는 값이 아닐 경우 따로 에러를 throw하지 않고 잘못 입력되었다고 안내해주고 다시 입력 값을 받을 수 있도록 구현했습니다. 이것은 본인이 생각한 로직에 맞게끔 작성하면 되는걸까요?

- 사용자 입장에서 생각해시면 좋을 것 같습니다! 잘못 입력했다고 프로그램이 종료가 된다면 안정적인 프로그램이라고 할 수 있을까요?

> 강의에서 나오는 테스트 코드만 작성해보고, 스스로 작성한 테스트 코드가 처음입니다. 테스트 코드 작성하는 것이 굉장히 어렵다고 느껴지는데 이렇게 작성하는 것이 맞을까요?

- 성공 테스트뿐만 아니라 실패 테스트까지 작성해보시는 게 좋습니다. [해당 영상](https://youtu.be/YdtknE_yPk4) 보시길 권장해드립니다~

>제가 작성한 코드에서 조금 더 객체지향적으로 리팩토링하기 위해 참고하면 좋을 무언가가 있을까요?
- [객체지향 체조 원칙](https://jamie95.tistory.com/99)를 적용해시는 건 어떨까요?

2023-06-08 06:01 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/calculate/Operator.java
> +    static public int plus(int a, int b){
앗,, 기본적인 실수를 했네요! 확인해서 모두 수정해보겠습니다!! :)

2023-06-08 06:03 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/Calculator.java
> +    private boolean exitStatus = true;
말씀해주신거 보고 프로젝트를 보니 아직 네이밍을 하는 능력이 많이 부족한 것 같아요! 한 번 다시 고민해보면서 변경할 수 있는 부분은 수정해보도록 하겠습니다!

2023-06-08 06:07 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/Calculator.java
> +                case "1":
확실히 치환하게되면 의미부여가 되어 눈에 더 잘 읽히는 코드가 될 것 같아요! 매직넘버에 대해서 공부해보고 변경해보도록 하겠습니다!!!

2023-06-08 06:12 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/Calculator.java
> +                    formulaRepository.save(formula, result);
저도 여기서 고민을 되게 많이 했었던 것 같아요. swtich문 안에서의 로직이 너무 방대한 느낌이 들어 줄여야겠다고는 생각했는데 case2안의 의존성이 모두 다른 인스턴스를 가르키고 있어서 어떤식으로 줄여야할지 감이 안잡혔던 것 같아요! Calculator안에 따로 메소드를 만들어서 호출하는 방식으로 하는 것이 좋을까요?

2023-06-08 06:15 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/calculate/Calculate.java
> +public class Calculate {
확실히 자바 컨벤션에 대한 부분이 부족한 것 같아요!  기초적인 부분 더 학습해서 모두 수정하도록 하겠습니다!! 👍

2023-06-08 06:18 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/calculate/Calculate.java
> +            "*", 2,
저도 이것에 대해서 고민을 많이했었는데 확실히 주성 서브멘토님께서 말씀하신 것 처럼 반대로 표현하는 것이 더 올바른 표현 법 같네요! 이것도 수정해보도록 하겠습니다!!

2023-06-08 06:21 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/console/Output.java
> +    void menuMsg();
Input, Output은 현재 CONSOLE 형식으로 작성되지만 추후에 GUI로 변경될 수 있지 않을까라는 생각에서 추상화 시켜두었습니다! 계산기 프로그램을 만들면서 어디 부분에서 추상화를 시켜야할지 명확히 나오지 않아서 최대한 찾으려고 하다보니 위와 같은 생각이 나왔던 것 같습니다!

2023-06-08 06:23 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/calculate/Calculate.java
> +                            operatorDeque.add(item);
코드가 좀 길고 반복문과 if문이 많다고 느껴졌었는데 확실히 지금 다시보니 depth가 많이 깊네요. 최대한 메서드랑 객체로 분리해보도록 하겠습니다!

2023-06-08 06:26 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/calculate/Calculate.java
> +                        numberDeque.add(String.valueOf(Operator.plus(num1, num2)));
다른 PR에서 Enum을 통해 Operator 기능 구현을 하는 것을 보고 제 스스로 한 번 만들어볼 수 있는 방법이 어떤 것인지 생각해보다가 이런식으로 작성하게되었습니다! 확실히 링크 걸어주신 글을 보면 더 깔끔하게 리팩토링 할 수 있을 것 같아요! 참고해서 수정해보겠습니다!

2023-06-08 06:27 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/message/ErrorMsg.java
> +    SELECT_VALIDATION_ERROR_MSG("잘못된 입력 값 입니다. 1-3 사이의 숫자를 선택해주세요");
지금 보니 확실히 어떠한 상황에 대한 에러 메시지인지 한 눈에 보기 어려운 것 같습니다! 명확하게 나타내고 중복된 표현은 제거 해보겠습니다!!

2023-06-08 06:37 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/validation/Validation.java
> +public class Validation {
단순히 검증이라고 생각했었는데 소프트웨어적으로 보면 Validator 검증 도구가 더 맞는 표현 같습니다! 네이밍에 대해서는 다시 한 번 생각해보고 작성할 수 있도록 해보겠습니다!

2023-06-08 06:39 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/message/ErrorMsg.java
> +    private final String errorMsg;
제 생각으로는 오히려 같은 클래스내에 동일한 이름을 사용하게되면 통일성이 있다고 생각했는데 너무 개인적인 생각으로 작성했었던 것 같습니다. 헷갈리는 부분도 있고 오히려 통일성보다는 중복되는 느낌이 강하다고 느껴지네요. 필드명은 수정하도록 하겠습니다!

2023-06-08 06:44 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/repository/FormulaRepository.java
> +    void save(String formula, String caculateValue);
특정 Repository를 사용하겠다라고 생각한건 아니지만 다양한 종류의 Repository를 사용할 수 있다고 생각이 들어 추상화했던 것은 맞습니다! 지금 생각해보니 JPA를 사용한다고 하면 DTO를 작성해서 넘겨주는 방법으로 해야 다양한 종류의 Repository에서 사용할 수 있을 것 같네요. 반영해서 수정해보겠습니다! 

void는 save(저장) 후 해당 데이터를 다시 받아서 사용할 일이 없다고 생각되어 void라고 작성해두었습니다! 저장 기능의 경우 저장 후 리턴 값으로 어떤 것을 받는 것이,, 좋은 로직일까요?

2023-06-08 06:47 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/validation/Validation.java
> +        Boolean afterCheck = false;
앗,, 처음 코드 작성할 때 실수로 기본타입으로 작성한다는 것을 Boolean으로 작성해서 checkFormulaValidation의 반환 값은 boolean으로 변경했는데 afterCheck의 타입을 깜빡했었던 것 같습니다! 이것도 기본 타입으로 변경하겠습니다!

2023-06-08 06:50 UTC, Hchanghyeon commented on src/test/java/org/programmers/java/RepositoryTest.java
> +        Assertions.assertEquals(formula + " = " + result, formulaRepository.getFormulaList().get(0L));
확실히 길어지니 import 하는 경우 조금 더 짧게 보기 좋게 변경할 수 있을 것 같습니다! 좋은 팁 감사드립니다!!

2023-06-08 15:58 UTC, JoosungKwon commented on src/main/java/org/programmers/java/repository/FormulaRepository.java
> +    void save(String formula, String caculateValue);
void 타입으로 리턴하는 것이 틀렸다는 이야기가 아닙니다~ 정답은 없습니다! 다만, void 타입을 리턴하면 저장에 성공했는지 알 수 없을 수도 있지 않을까요? 이러한 부분도 고민해보시면 좋을 것 같아서 이야기 드렸습니다.

2023-06-08 16:05 UTC, JoosungKwon commented on src/main/java/org/programmers/java/Calculator.java
> +                    formulaRepository.save(formula, result);
저는 메서드로 분리하는게 더 가독성이 있다고 생각이 드네요~ 다만, 그냥 분리하시기 보다도 어떻게 나누는 것이 좋을까 고민도 해보시고 분리된 메서드의 위치가 이곳이 적절한지도 고민해보시면 조금 더 객체지향적으로 만들 수 있을 것 같습니다!

2023-06-09 05:07 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/Calculator.java
> +                    formulaRepository.save(formula, result);
감사합니다! 어떻게 나눌지도 한 번 고민해보도록 하겠습니다!! :)

2023-06-09 05:08 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/repository/FormulaRepository.java
> +    void save(String formula, String caculateValue);
말씀하신 내용을 다시 생각해보니 저장한 값이 제대로 저장되었는지 반환 값을 비교해보는 것도 정말 좋은 로직일 것 같습니다! 감사합니다! 한 번 고민해보고 적용해보겠습니다!!

2023-06-09 05:24 UTC, graygreat requested changes
안녕하세요 창현님:)
많이 고민한 흔적이 보이네요! 💯 
전체적으로 잘 짜주셨으나 몇가지 피드백 드릴 것들이 있어서 남겨놨습니다.
확인 부탁드려요~

코드 리뷰 외에 궁금한 것이 있는데, Readme를 보게 되면 요구사항과 구현 내용에 요구사항에 대한 내용이 없는 것 같아요. 그리고 commit에 대한 설명을 적어주셨는데, 커밋이 100개가 된다면 그 설명을 다 적는게 가능할까요?
README에 어떠한 내용들을 담아야하는지에 대한 고민을 해보셨으면 좋겠습니다 :)

창현님이 주신 질문에 대한 답변을 해보자면,

> 1. 각 객체에 대한 책임이 적절하게 이루어진 것 인지, 객체의 책임을 더 세분화시켜서 나눠야하는지 궁금합니다.

객체지향을 생각할 때, 객체를 먼저 나누기 보다는 이 프로젝트에서 어떠한 행위(메시지)들이 필요할지 먼저 고민해보고 객체를 나눠보면 더 좋은 객체지향이 될 수 있을 것 같아요.

> 2. 입력 값을 받을 때 원하는 값이 아닌 경우 에러를 throw를 하여 프로그램을 멈추게 하는 것이 맞는지 궁금합니다.
→ 저의 경우 원하는 값이 아닐 경우 따로 에러를 throw하지 않고 잘못 입력되었다고 안내해주고 다시 입력 값을 받을 수 있도록 구현했습니다. 이것은 본인이 생각한 로직에 맞게끔 작성하면 되는걸까요?

이건 요구사항마다 다를 것 같아요.
throw를 통해 프로그램을 종료 시키는 요구사항이 있을 수 있고, 예외가 발생하면 예외 메시지를 보여준 후에 다시 입력을 받을 수 있는 요구사항이 있을 수 있겠네요.
과제에서 주어진 요구사항이 없다면, 본인이 이유를 가지고 개발하시면 될 것 같습니다 :)

> 3. 강의에서 나오는 테스트 코드만 작성해보고, 스스로 작성한 테스트 코드가 처음입니다. 테스트 코드 작성하는 것이 굉장히 어렵다고 느껴지는데 이렇게 작성하는 것이 맞을까요?

부족한 부분이 있어서 테스트 코드 부분에 코멘트 남겨드렸습니다.

> 4. 제가 작성한 코드에서 조금 더 객체지향적으로 리팩토링하기 위해 참고하면 좋을 무언가가 있을까요?

우선 아무래도 객체지향 관련 책을 읽어보시는게 좋겠죠?
[객체지향의 사실과 오해](https://www.yes24.com/Product/Goods/18249021), [오브젝트](https://www.yes24.com/Product/Goods/74219491) 이 두 책 추천드립니다!

그리고 [객체지향 생활체조원칙](https://catsbi.oopy.io/bf003ff6-2912-4714-8ac2-44eeb7becc93) 이라는 것이 있습니다. 
아래 내용을 지키면서 개발하도록 노력해보세요.

2023-06-09 05:24 UTC, graygreat commented on src/main/java/org/programmers/java/Calculator.java
> +    Calculator(Input input, Output output, Calculate calculate, FormulaRepository formulaRepository){
Calculator에 너무 많은 파라미터를 가지고 있는 것 같아요.
파라미터는 1, 2개 이내로 가질 수 있도록 해보시면 좋을 것 같아요.

2023-06-09 05:24 UTC, graygreat commented on src/main/java/org/programmers/java/console/Console.java
> +public class Console implements Input, Output {
아래의 내용들은 전부 싱글톤으로 사용되어도 괜찮지 않을까요?

2023-06-09 05:24 UTC, graygreat commented on src/main/java/org/programmers/java/console/Console.java
> +    public Console(Validation validation) {
Console이 Validation을 의존하는 구조가 좋지 않아보입니다.
화면을 보여주는 역할을 하는 Console에 유효성 검사를 하는 Validation이 필요할까요?

2023-06-09 05:24 UTC, graygreat commented on src/main/java/org/programmers/java/message/InfoMsg.java
> +
불필요한 개행

2023-06-09 05:24 UTC, graygreat commented on src/main/java/org/programmers/java/repository/FormulaMemoryRepository.java
> +    Map<Long, String> formulaMap = new HashMap<>();
hashMap을 사용하게 되면 장, 단점이 어떤게 있을까요?

2023-06-09 05:24 UTC, graygreat commented on src/main/java/org/programmers/java/validation/Validation.java
> +        if(formulaList.size() != 0) afterCheck = checkFormulaValidation(formulaList);
가독성을 위해서 한줄이라도 중괄호를 사용하는게 좋습니다.

2023-06-09 05:24 UTC, graygreat commented on src/main/java/org/programmers/java/validation/Validation.java
> +        if(!afterCheck) System.out.println(ErrorMsg.CALCULATE_VALIDATION_ERROR_MSG.getErrorMsg());
println을 Validator에서 사용하고 계신데, 화면에 노출시켜주는 책임을 Output에 위임하신거 아닌가요?
현재 구조처럼 Output을 사용하지 않고 print를 찍어준다면 사실상 Output을 만든 이유가 없을 것 같다는 생각이 드네요.

2023-06-09 05:24 UTC, graygreat commented on src/main/java/org/programmers/java/validation/Validation.java
> +            else if(str.matches(operatorMatch)) formulaBeforeValidation.add(str);
else문, switch문을 사용하지 않고 구현하도록 연습해보세요!

2023-06-09 05:24 UTC, graygreat commented on src/main/java/org/programmers/java/validation/Validation.java
> +        if(formulaList.size() != 0) afterCheck = checkFormulaValidation(formulaList);
formulaList.size() != 0

이런 조건들도 메소드로 따로 빼볼 수 있을 것 같아요.

2023-06-09 05:24 UTC, graygreat commented on src/test/java/org/programmers/java/CalculateTest.java
> +public class CalculateTest {
현재 예외에 대한 테스트가 없는데, 예외 테스트를 짜보는 것을 추천드립니다.
그렇다면 왜 예외에 대한 테스트를 해야할까요?

2023-06-09 05:24 UTC, graygreat commented on src/test/java/org/programmers/java/CalculateTest.java
> +          String[] formulaList = {"3", "+", "5", "*", "10"};
[Guide to JUnit 5 Parameterized Tests](https://www.baeldung.com/parameterized-tests-junit-5)

해당 글 보시고 한번 공부해보시죠 ㅎ

2023-06-11 07:57 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/Calculator.java
> +    Calculator(Input input, Output output, Calculate calculate, FormulaRepository formulaRepository){
말씀해주신 객체지향 생활체조원칙 중 하나에 포함되는 것을 확인했습니다! 어떤식으로 줄여야할지 한 번 고민해보고 적용 해보도록 하겠습니다!!

2023-06-11 08:04 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/console/Console.java
> +    public Console(Validation validation) {
처음에는 Console에서 입력받은 후 바로 입력값에 대한 검증이 필요하다고 단순하게 생각해서 의존하는 구조로 만들었던 것 같습니다. 하지만 리팩토링하려고보니 Console에서 Validation을 의존하고 있어 Validation에서 콘솔을 사용하기 어려웠고 View단에 검증 기능이 있는 것이 역할과 책임 분리가 제대로 되지 않은 구조라는 것을 느꼈습니다! 말씀해주신 것 처럼 Console을 싱글톤으로 변경해서 주입하는 방식으로 변경하고 의존 관계를 없애보도록 하겠습니다!!

2023-06-11 08:04 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/message/InfoMsg.java
> +
리팩토링 하면서 불필요한 개행들도 한 번 씩 다시 체크해보겠습니다! 감사합니다!

2023-06-11 08:13 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/validation/Validation.java
> +        if(formulaList.size() != 0) afterCheck = checkFormulaValidation(formulaList);
혼자 개발했던 습관이 있어서 컨벤션과 가독성에 대한 부분을 너무 신경쓰지 않았었던 것 같습니다! 더 신경써서 작성해보겠습니다!!

2023-06-11 08:16 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/validation/Validation.java
> +        if(!afterCheck) System.out.println(ErrorMsg.CALCULATE_VALIDATION_ERROR_MSG.getErrorMsg());
Output에서 모든 것을 처리할 수 있게끔 책임을 위임했었는데 구조를 잘못가져가서 print문으로 대체해서 작성했었습니다! 그때는 어떻게 할지 잘 모르겠었으나 말씀해주신 콘솔을 싱글톤 객체로 변경하고 의존관계를 다르게해서 구조를 다시 잡으면 원래의 취지에 맞게 작성할 수 있을 것 같습니다! 다음번 PR때 반영하겠습니다!

2023-06-11 08:17 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/validation/Validation.java
> +            else if(str.matches(operatorMatch)) formulaBeforeValidation.add(str);
최대한 else if, else, switch문을 사용하지 않고 구현해보도록 하겠습니다!!

2023-06-11 08:18 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/validation/Validation.java
> +        if(formulaList.size() != 0) afterCheck = checkFormulaValidation(formulaList);
가독성이 떨어지는 코드들은 모두 메소드로 빼볼 수 있도록 하겠습니다!

2023-06-11 08:18 UTC, Hchanghyeon commented on src/test/java/org/programmers/java/CalculateTest.java
> +          String[] formulaList = {"3", "+", "5", "*", "10"};
감사합니다!! 보고 테스트 코드 다시 한 번 작성해보도록 하겠습니다!!

2023-06-11 08:40 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/repository/FormulaMemoryRepository.java
> +    Map<Long, String> formulaMap = new HashMap<>();
hashMap은 데이터 저장시 해시함수를 통해 해시코드를 얻어 버킷에 저장하는 방식으로 알고 있습니다! 그래서 리스트 보다 데이터 검색에 빠르다는 장점과 key값이 중복되지 않는 점 등이 있습니다. 단점으로는 순서가 보장되지 않는다는점인데 과제에서 계산된 이력에 대한 것은 순서가 보장되는게 맞다고 생각이 들었고 팀원분들이 LinkedHashMap이 순서보장이 된다고 알려주셨습니다!! LinkedHashMap을 통해 순서를 보장시키는 쪽으로 코드를 리팩토링하려고 합니다. 

Map을 사용할 때 **key를 index**로하고 **value를 연산식 + 결과값**으로 저장하게되면 출력시 어차피 순차적으로 출력할 것인데 Map을 사용하면 Iterator를 사용해야되는 비용이 들어서 오히려 Map을 사용하는 것이 맞나? 그냥 리스트를 사용하면 되지 않나? 라는 생각도 들었습니다. 그렇다고 key를 연산식, value를 결과값으로 하는 경우 Key인 연산식이 중복되는 경우 계산된 이력에서 중복 문제로 저장되지 않기 때문에 해당 이력은 2개가 아닌 1개로 남는 것도 문제가 될 것 이라고 생각하는데,, 이 부분이 잘 이해되지 않는 것 같습니다.

2023-06-11 08:42 UTC, Hchanghyeon commented on src/test/java/org/programmers/java/CalculateTest.java
> +public class CalculateTest {
예외에 대한 예측을 제대로 해야 프로그램이 잘못 돌아가거나 멈추는일을 방지할 수 있기 때문이라고 생각합니다! 예외에 대해서도 한 번 더 공부해보고 반영해볼 수 있도록 하겠습니다!!

2023-06-14 05:12 UTC, Hchanghyeon commented
안녕하세요 네이비 멘토님, 주성 서브멘토님 우선 바쁘심에도 불구하고 하나하나 **꼼꼼하게 리뷰해주셔서 감사드립니다** 👍 👍 

말씀해주신 피드백들을 최대한 반영해서 커밋하고 누락된 요구사항과 구현 내용, 피드백 반영 사항을 PR 내용에 수정해놓았습니다!

아무래도 자바 컨벤션에 대한 이해, 객체지향 체조 원칙에 대한 개념이 없어서 그런지 고칠게 많아서 피드백을 반영하는데 시간이 오래걸렸던 것 같습니다! **자바 컨벤션과 객체지향 체조 원칙에 초점을 맞춰서 리팩토링** 하려고 했고, 한 객체에 책임이 많은 것 같아서 여러 객체로 분리하여 책임을 나누고 depth를 최대한 2이하로 줄이려고 노력했습니다!

그리고 피드백을 반영하면서 **가장 힘들었던 점은 하나를 고쳤는데 연쇄적으로 고쳐야하는 상황**이 여러번 발생했던 점인 것 같아요. 리팩토링하면서 객체지향적으로 설계하지 못했다고 많이 느껴서 그런지 아래와 같이 질문드리고 싶습니다!

> 처음 코드를 작성할 때 나중에 리팩토링 하더라도 많은 로직을 바꾸지 않고 작성할 수 있는 Tip 같은게 있을까요?
>

우선 제가 이러한 문제가 발생된 이유는 요구사항에 대해 명확하게 정의 내리지 않고 코드로 미리 작성하려고 했던 점이 가장 잘못되었던 것 같습니다. 😢😢 

리팩토링 한 코드들도 다시 한 번 잘 부탁드리며 부족한 부분을 많이 솔직하게 얘기해주셔도되니 가감없이 피드백 부탁드립니다 🙏🙏

항상 감사드립니다 👍 👍 😄 😄

2023-06-14 11:34 UTC, JoosungKwon reviewed
@Hchanghyeon
안녕하세요. 창현님 리팩터링하시느라 정말 고생많으셨습니다~ 👍 

피드백을 잘 반영하신 것 같아요~! 안정적인 프로그램을 만들기 위해서 `예외처리` , `실패 테스트` 를 추가하시면 더 좋을 것 같습니다 😄

질문 주신 내용에 답변하자면 

> 처음 코드를 작성할 때 나중에 리팩토링 하더라도 많은 로직을 바꾸지 않고 작성할 수 있는 Tip 같은게 있을까요?

- 바꿔서 말하면 객체지향적으로 설계하는 법을 물어보신 것 같아요! 말씀하신 것 처럼 코드 작성 이전에 요구사항을 바탕으로 설계를 해보시면 도움이 될 것 같습니다! 그림 혹은 UML을 그려보시는 건 어떨까요?

- 그리고 아직 경험이 많지 않기 때문에 처음부터 완벽하게 설계하는 것은 매우 어려운 일입니다. 피드백을 통해 지속적으로 개선하는 방향으로 가면 좋을 것 같아요!! ☺️

2023-06-14 11:44 UTC, JoosungKwon commented on src/main/java/org/programmers/java/calculation/Operator.java
> +    public static Optional<Operator> isSymbol(String inputSymbol){
메서드 명에 반드시 지켜야 하는 규칙은 없습니다만, 일반적으로 자주 사용되는 [관용적인 표현](https://tecoble.techcourse.co.kr/post/2020-04-26-Method-Naming/)이 있습니다! 

`'is'`의 경우, 맞는지 틀린지 판단하는 메서드 명에 자주 사용됩니다.

그렇다면 일반적으로 `isSymbol`를 보고 어떤 메서드일 것이라고 생각할 수 있을까요?

2023-06-14 11:44 UTC, JoosungKwon commented on src/main/java/org/programmers/java/calculation/Operator.java
> +        return Arrays.stream(values())
[최적화](https://pjh3749.tistory.com/279)를 고려해봐도 좋을 것 같아요~~

2023-06-14 18:04 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/App.java
> +        Calculation calculation = new Calculation();
계산하는 부분에 대한 로직을 담는다고 생각하여 계산이라고 지은 것 같습니다! 다시 보니 너무 포괄적인 의미를 담고 있어서 변경하는게 좋을 것 같습니다! DTO가 아닌 객체들은 메소드처럼 동사로 표현하는 것이 좋을까요?! 객체는 뭔가 명사로 지어야된다는 말을 많이 들었어서요!

2023-06-14 18:07 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/Calculator.java
> +        this.validator = new Validator();
우선 네이비 멘토님께서 객체를 생성할 때 매개변수로 들어가는 인스턴스 수를 줄여달라고 말씀하셔서 생성자 객체에서 일부는 new로 전환해야겠다는 생각이 들었습니다! 그 중 메인 로직인 계산과 저장소의 기능보다는 검증을 new로 생성하는 것이 좋을 것 같아서 Validator만 new로 생성했습니다!!.. 근데 매개변수로 들어가는 인스턴스의 수를 줄여야할 때 어떤 방식으로 줄여야할지 감을 못잡겠습니다. 지금처럼 Calculator가 컨트롤러의 역할을 하고 있어서 모든 인스턴스들을 주입받는 형식으로 있다보니,, 어떤식으로 줄여야할지 잘 모르겠습니다!!

2023-06-14 18:11 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/Calculator.java
> +    }
저도 굉장히 고민 많이 했던 것 같습니다. 저번에 save의 void에 대한 말씀을 해주셔서 해당하는 값을 return을 다른걸 주고 무엇을 할 수 있을까 생각하다가 넣은 값이랑 받은 값이 동일한지에 대한 체크를 해보았는데,, 지금 보니 당연히 동일한 것이 나올 수 밖에 없는거라고 생각이 드네요!! 오히려 코드만 길어지고 이것은 다시 고민해보고 다시 void로 바꾸거나 다른 방향으로 생각해보겠습니다!

2023-06-14 18:15 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/validator/FormulaCountValidator.java
> +public class FormulaCountValidator {
Validator에 FormulaCountValidator와 FormulaSplitValidator가 코드가 너무 길어서 객체로 나누었습니다! 아래 남겨주신 코드 한 번 보고 코드를 줄 일 수 있으면 줄여서 다시 합쳐보는 방식으로도 고려해보겠습니다! 감사합니다!

2023-06-14 18:31 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/repository/FormulaMemoryRepository.java
> +        stringBuilder.append(caculateValue);
출력 포맷을 정하는게 되게 단순한일이라고 생각이들어서 그냥 Repository의 책임이어도 될 것 같다고 생각하고 막 작성했던 것 같습니다! 사소한거라도 다시 한 번 책임에 대해서 고민하고 사용해보겠습니다!! :)

2023-06-15 07:34 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/validator/Validator.java
> +        this.output = Console.getInstance();
말씀하신대로 boolean으로 검증의 결과를 Controller측에서 받을 수 있기 굳이 Validator에서 처리하지 않아도 될 것 같습니다! 예외 처리에 대한 부분들도 많이 안되어있어서 한 번 예외처리쪽으로 생각해보겠습니다! 감사합니다!

2023-06-15 07:36 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/validator/Validator.java
> +        if(formularAfterSplitValidate.size() != 0) {
헉! isEmpty메소드 있는것은 알았는데 전혀 쓸 생각을 못했던 것 같습니다! 각 객체에 대한 메소드도 한 번씩 다시 들여다보면서 활용할 수 있는 것들을 최대한 활용해보겠습니다!

2023-06-15 07:37 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/validator/Validator.java
> +public class Validator {
맞습니다! 입력값에 대한 기능만 제공하는 클래스여서 말씀하신대로 유틸성 클래스에 대해서도 한 번 찾아보고 수정해보겠습니다! 감사합니다! :)

2023-06-15 07:39 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/repository/FormulaMemoryRepository.java
> +    }
언급주신 방어적 복사에 대해 찾아보았습니다! 외부에서의 변경을 없애기 위해 방어적 복사를 통해 반환해보도록 하겠습니다!

2023-06-15 08:09 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/calculation/Operator.java
> +        return Arrays.stream(values())
네! 한 번 최적화에 대해서도 고려해보고 반영해보겠습니다! :)

2023-06-15 08:45 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/validator/FormulaSplitValidator.java
> +            return false;
수정해주신 코드 참고해보고 다른 코드들도 바꿀 수 있는것이 있는지 확인해보겠습니다!!

2023-06-15 09:21 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/Calculator.java
> +        this.validator = new Validator();
우선 Validator가 말씀해주신대로 유틸클래스로 사용하면 될 것 같아서 static으로 변경처리하여 삭제처리했습니다!

2023-06-15 11:29 UTC, JoosungKwon commented on src/main/java/org/programmers/java/App.java
> +        Calculation calculation = new Calculation();
@Hchanghyeon 아! 제가 잘못 전달했네요! 동사가 아니고 명사가 맞습니다..😅 다만 객체인 만큼 어떤 동작을 하는 주체로 표현하면 좋을 것 같아요!

2023-06-15 11:35 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/Calculator.java
> +    }
아 그렇네요! 인터페이스를 사용하면 리턴 값에 대해서 신중해야될 것 같습니다! 감사합니다!!! :)

2023-06-15 11:39 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/validator/Validator.java
> +        if(formularAfterSplitValidate.size() != 0) {
Deque, Queue, Stack과 같은 자료구조들은 is를 사용한 메서드가 익숙했는데 List여서 그런지 is메서드가 낯설게 느껴지네요ㅎㅎ 감사합니다!!

2023-06-15 11:42 UTC, JoosungKwon commented on src/main/java/org/programmers/java/repository/FormulaMemoryRepository.java
> +    Map<Long, String> formulaMap = new HashMap<>();
저도 리스트로 해도 충분하다고 생각합니다. 다만, 요구사항이 Map을 활용하라고 되어 있으니 key를 index로하고 value를 연산식 + 결과값으로 저장하는 방식으로 구현해도 될 것 같아요!

2023-06-15 13:56 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/repository/FormulaMemoryRepository.java
> +    Map<Long, String> formulaMap = new HashMap<>();
의견 감사드립니다!!! :)

2023-06-21 09:28 UTC, JoosungKwon approved these changes
@Hchanghyeon 
안녕하세요. 창현님 리팩터링이 끝난 것 같아서 마지막 리뷰만 남기고 해당 PR은 머지하도록 하겠습니다!
리뷰 내용은 반영하시지 않아도 됩니다. 한번 확인 해보시고 다음 과제에서 생각해보시면 좋을 것 같습니다!! 😄
과제하시느라 정말 고생많으셨습니다! 실력이 정말 빠르게 늘어가는 것 같습니다~~ 👍👍 화이팅! 💪

2023-06-21 09:28 UTC, JoosungKwon commented on src/main/java/org/programmers/java/Calculator.java
> +    private String formattingFormula(String inputFormula, String result){
만약 저였다면 inputFormula와 result를 묶는 데이터 객체(DTO)를 만들고 toString 메서드를 포맷에 맞게 재정의해서 사용했을 것 같아요!

2023-06-21 09:28 UTC, JoosungKwon commented on src/main/java/org/programmers/java/repository/FormulaRepository.java
> +    Map<Long, String> getFormulaList();
`getFormulaList` 메서드 명과 달리 반환타입은 `Map` 이네요!

2023-06-21 09:28 UTC, JoosungKwon commented on src/main/java/org/programmers/java/calculation/Operator.java
> +    private int getPriority() {
IntelliJ 자동 정렬 기능을 이용하시면 좋을 것 같아요!

2023-06-21 09:28 UTC, JoosungKwon commented on src/main/java/org/programmers/java/calculation/Operator.java
> +    private String getSymbol() {
접근제어자를 `private`으로 두신 이유가 궁금합니다!

2023-06-21 09:28 UTC, JoosungKwon commented on src/main/java/org/programmers/java/calculation/Operator.java
> +        return Pattern.matches("[0-9]+",inputNumber);
[Pattern 객체가 생성비용이 크다](https://zhenxikim.tistory.com/m/79)는 사실 알고 계신가요? 꼭 그러한 상황이 아니더라도 상수화할 수 있는 부분이 있다면 상수화 혹은 캐싱해두는게 좋습니다!

2023-06-21 09:28 UTC, JoosungKwon commented on src/main/java/org/programmers/java/validator/Validator.java
> +                throw new IllegalArgumentException(Error.CALCULATE_VALIDATION.getMsg());
예외를 잡는 곳은 보이지 않네요! 요구사항에 나와 있지 않기 때문에 원하는 방향으로 구현하면 되지만, 잘못 입력해서 프로그램이 종료된다면 사용할 때 불편하지 않을까요?

2023-06-21 09:28 UTC, JoosungKwon commented on src/test/java/org/programmers/java/CalculationTest.java
> +     void checkZeroDivide() {
일반적인 상황을 가정하고 테스트하기 보다 정말 여러 상황(엣지케이스)에서 어떻게 동작하는지 말그대로 테스트해보기 위한 코드를 작성하면 좋을 것 같습니다. 예를 들어서 소수점 연산이 필요한 경우, 일정 범위 이상의 값이 주어질 때, 등등 이러한 부분이 구현되지 않아더라도 테스트를 통해서 계산하지 못한다는 것을 나타내주면 다른 사람이 프로그램을 좀 더 이해하는데 도움이 됩니다!

2023-06-21 09:31 UTC, merged

2023-06-21 11:51 UTC, Hchanghyeon reviewed
주성 서브멘토님! 2주동안 정말 많은 리뷰달아주셔서 짧은 기간동안 많은 것을 배울 수 있었던 것 같습니다! 앞으로 코드를 작성할 때는 멘토님께서 말씀하신 내용들을 최대한 반영해서 개선해볼 수 있도록 할게요! 너무너무 감사드립니다 :)

2023-06-21 11:51 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/Calculator.java
> +    private String formattingFormula(String inputFormula, String result){
DTO에 대한 고민을 전혀 하지 못했던 것 같습니다! 고민을 해보면 생각보다 DTO가 쓰일 수 있는 부분이 많은 것 같더라구요! 한 번 사용해서 수정하겠습니다!

2023-06-21 11:51 UTC, Hchanghyeon commented on src/main/java/org/programmers/java/repository/FormulaRepository.java
> +    Map<Long, String> getFormulaList();
앗..! 그렇네요 수정해야될 것 같습니다!!