1주차 계산기 구현 과제 제출합니다 !
prgrms-be-devcourse/java-calculator pull request #130
Opened 2023-06-08 08:24 UTC by 2jie0516

## 📌 과제 설명 

1주차 계산기 구현 과제입니다 !
아직 객체지향에  대한 개념이 부족한 상태이지만 최대한 객체지향 적인 설계를 지킬려고 노력하였습니다.

## 👩‍💻 요구 사항과 구현 내용 

- 객체지향적인 코드로 계산기 구현하기
    - [x]  더하기
    - [x]  빼기
    - [x]  곱하기
    - [x]  나누기
    - [x]  우선순위(사칙연산)
- [x]  테스트 코드 구현하기
- [x]  계산 이력을 맵으로 데이터 저장기능 만들기
    - 애플리케이션이 동작하는 동안 데이터베이스 외에 데이터를 저장할 수 있는 방법을 고안해보세요.
- [ ] 정규식 사용(아직 적용하지 않았습니다.)

#### 클래스 설명

Main
- 프로그램이 실행되면 가장 먼저 실행되는 메인 클래스입니다.
- Index 생성자에 필요한 객체들을 넣어줍니다.

Index
- 사용자가 옵션을 선택할 수 있습니다.
- 선택한 옵션에 맞게 switch 문으로 해당 옵션에 맞는 메소드를 호출합니다.

Console
- Index에서 사용자가 입력을 하면 해당 옵션에 맞는 메소드를 제공해줍니다.
- 만약 예외가 발생하면 오류 메세지를 출력합니다

Option
- 사용자가 선택할 수 있는 옵션을 가지고 있는 enum 클래스입니다.

Calculator
- 계산식을 받고 Operater 클래스로 넘겨줍니다.
- 계산 결과가 나오면 히스토리를 저장합니다. 

Operator
- 실질적인 계산을 담당합니다.

History
- 계산 내역을 저장하고 출력합니다.

## ✅ 피드백 반영사항  

## ✅ PR 포인트 & 궁금한 점

2023-06-08 14:42 UTC, dojinyou reviewed
전체적으로 유사한 코멘트가 나오는 부분도 있어서 같은 조의 다른 분들이 받은 리뷰를 참고해보시면 좋을 것 같아요! 그리고 [객체지향생활체조 원칙](https://catsbi.oopy.io/bf003ff6-2912-4714-8ac2-44eeb7becc93)도 준수해주시면 좋을 것 같아요

2023-06-08 14:42 UTC, dojinyou commented on .idea/.gitignore
`.idea` 폴더는 IntelliJ를 이용하면서 생기는 폴더인데요 `.gitignore`를 통해서 제외 시켜주시면 좋아요!
[gitignore.io](gitignore.io)는 손쉽게 필요한 값들이 채워진 `gitignore` 파일을 만들 수 있게 도와주는 사이트에요. 
자세한 건 [공식문서](https://git-scm.com/docs/gitignore)를 참고하시면 좋아요

2023-06-08 14:42 UTC, dojinyou commented on cal/Test/CalculatorTest.java
> +}
마지막 줄에는 개행 문자를 넣어주시면 좋아요! 간단한 설정으로 자동화할 수 있으니 참고해주세요.
[다른 pr에 관련 리뷰](https://github.com/prgrms-be-devcourse/java-calculator/pull/118#discussion_r1218136485)가 있으니 참고해주세요!

2023-06-08 14:42 UTC, dojinyou commented on cal/Test/CalculatorTest.java
> +        assertEquals(1,result);
동일한 형태의 코드가 반복되고 있어요! 구체적으로는 동일한 형태의 테스트에 파라미터와 결과값만 변경되어 검증이 일어나고 있어요.
이것 `@ParameterizedTest`를 통해서 개선할 수 있을 것 같아요!

2023-06-08 14:42 UTC, dojinyou commented on cal/Test/ConsoleTest.java
> +    Console console = new Console();
테스트 초기화 과정도 테스트로 관리할 수 있어요. `@BeforeEach` 혹은 `@BeforeAll` 같은 키워드를 찾아보시길 바래요

2023-06-08 14:42 UTC, dojinyou commented on cal/src/Console.java
> +    public void getHistory(History history) {
우선 `Console`이라는 클래스의 역할과 `getHistory`라는 메서드를 가지고 있는 게 적절한 지 한번 고민해보시면 좋을 것 같아요.

별개로 `getHistory` 메서드에서 기대하는 것은 `History 정보를 가져온다.`일 것 같아요. 그러나 실제로 하는 행위는 다른 것 같아서 적절한 네이밍을 붙여보는 걸 추천 드려요.

마지막으로 `Console`이 아닌 `html`이나 `json`, `excel` 등의 다양한 형태로 입출력이 변경 된다면 내 코드가 유연하게 변경될 수 있는 지도 고민하면 좋을 것 같아요. 적절한 추상화를 통해서 설계과 구현을 분리해보세요

2023-06-08 14:42 UTC, dojinyou commented on cal/src/Index.java
> +    private Operator operator;
해당 멤버 필드들을 `불변(final)`으로 처리하지 않은 이유가 뭘까요?

2023-06-08 14:42 UTC, dojinyou commented on cal/src/Index.java
> +                case 1:
[매직 넘버 관련 pr 리뷰](https://github.com/prgrms-be-devcourse/java-calculator/pull/114#discussion_r1217485717) 참고 해주세요!

2023-06-08 14:42 UTC, dojinyou commented on cal/src/model/Operator.java
> +    public Integer operate(String inputString) {
해당 멤버 필드들이 외부에 공개된 이유가 있을까요?? 이렇게 된다면 어떤 문제가 생길 수 있을 지 고민해보시면 좋을 것 같아요

2023-06-08 16:07 UTC, 2jie0516 commented on .idea/.gitignore
넵 알겠습니다 
다른 분들 코멘트 참고해서 객체지향 적인 부분 보완하겠습니다 !

2023-06-08 16:07 UTC, 2jie0516 commented on cal/Test/CalculatorTest.java
> +}
앗 그렇군요 .. 참고하겠습니다 !

2023-06-08 16:07 UTC, 2jie0516 commented on cal/Test/CalculatorTest.java
> +        assertEquals(1,result);
넵 알겠습니다 
테스트 코드에 대해서 더 알아보고 수정하겠습니다.. !

2023-06-08 16:07 UTC, 2jie0516 commented on cal/Test/ConsoleTest.java
> +    Console console = new Console();
넵 다음 pr 때 수정 후 반영하겠습니다 !

2023-06-08 16:07 UTC, 2jie0516 commented on cal/src/Console.java
> +    public void getHistory(History history) {
네이밍적인 부분을 미처 신경쓰지 못했네요 .. 
추상화 같은 부분도 최대한 보완하겠습니다

2023-06-08 16:07 UTC, 2jie0516 commented on cal/src/Index.java
> +    private Operator operator;
아 미처 거기까지는 생각을 못한 것 같습니다 
수정하겠습니다 !

2023-06-08 16:07 UTC, 2jie0516 commented on cal/src/Index.java
> +                case 1:
넵 참고하겠습니다 !

2023-06-08 16:07 UTC, 2jie0516 commented on cal/src/model/Operator.java
> +    public Integer operate(String inputString) {
넵 최대한 고민해보고 수정 후 반영하겠습니다 !

2023-06-08 16:18 UTC, seung-hun-h requested changes
세한님 요구사항 빠르게 반영해주셔서 감사합니다!
리뷰 간단하게 남겼으니 확인해주세요

2023-06-08 16:18 UTC, seung-hun-h commented on sub_cal/sub_cal/src/main/java/exception/InputStringException.java
> +//}
사용하지 않는 클래스는 제거해주세요

2023-06-08 16:18 UTC, seung-hun-h commented on sub_cal/sub_cal/src/main/java/model/Calculator.java
> +// 계산 결과가 나오면 히스토리를 저장합니다.
주석은 코드의 변경을 따라 갈 수 없습니다.
주석 보다는 메서드 명을 명확하게 작성해주시거나 테스트 코드를 짤 수 있을 것 같아요

2023-06-08 16:18 UTC, seung-hun-h commented on sub_cal/sub_cal/src/main/java/model/History.java
> +    static List<String> log = new ArrayList<>();
- 기본 접근 제어자를 사용하신 이유가 있을까요?
- `static` 키워드를 사용하면 인스턴스에서 `log`를 함께 공유하게 될 텐데 문제가 발생할 수 있지 않을까요?

2023-06-08 16:18 UTC, seung-hun-h commented on sub_cal/sub_cal/src/main/java/model/Calculator.java
> +    }
`History`에 연산 결과를 저장하는 로직이 계산하는 로직과 함께 있는게 조금 어색하네요 분리할 필요가 있을 것 같아요.

2023-06-08 16:18 UTC, seung-hun-h commented on sub_cal/sub_cal/src/main/java/model/Operator.java
> +    }
`1 + 2 - 1 * 3 - 2` 요렇게 하면 -2가 나와야할 거 같은데 2가 나오네요 확인해주세요

2023-06-08 16:18 UTC, seung-hun-h commented on sub_cal/sub_cal/src/main/java/model/Operator.java
> +            else if(word.equals("*") || word.equals("/")) calPriority(word,Integer.parseInt(st.nextToken()));
연산자는 Enum이나 상수로 관리할 수도 있을 것 같네요

2023-06-08 16:18 UTC, seung-hun-h commented on sub_cal/sub_cal/src/main/java/Index.java
> +                case 1:
1 보다는 의미있는 이름을 지어주는 것이 좋겠네요

2023-06-08 16:18 UTC, seung-hun-h commented on sub_cal/sub_cal/src/main/java/Index.java
> +                    BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
br인스턴스를 매번 새로 생성해줄 필요가 있을까요?

2023-06-09 04:22 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/exception/InputStringException.java
> +//}
넵 알겠습니다

2023-06-09 04:22 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/model/Calculator.java
> +// 계산 결과가 나오면 히스토리를 저장합니다.
아 그 부분은 미처 생각 못한거 같습니다 
메서드 명이나 테스트 코드를 작성하는 쪽으로 하겠습니다 !

2023-06-09 04:23 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/model/History.java
> +    static List<String> log = new ArrayList<>();
그 부분도 한번 고민해보고 개선하겠습니다 ... !

2023-06-09 04:24 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/model/Calculator.java
> +    }
넵 알겠습니다

2023-06-09 04:24 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/model/Operator.java
> +    }
앗.. 계산기 로직에 오류가 있었네요 ㅠ 수정하겠습니다

2023-06-09 04:24 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/model/Operator.java
> +            else if(word.equals("*") || word.equals("/")) calPriority(word,Integer.parseInt(st.nextToken()));
넵 알겠습니다 
연산자는 enum으로 관리하는 쪽으로 개선하겠습니다

2023-06-09 04:25 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/Index.java
> +                case 1:
그 부분을 미처 신경쓰지 못한 것 같습니다 
말씀해주신 대로 수정하겠습니다 !

2023-06-09 04:25 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/Index.java
> +                    BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
생각해보니까 메모리 낭비가 있을 수도 있겠네요 .. 그 부분 역시 개선하겠습니다

2023-06-14 14:41 UTC, seung-hun-h requested changes
세한님 리뷰남겼습니다.
자바에서는 보통 변수명을 줄이지 않습니다. 그리고 변수명이나 클래스명을 최대한 의미있게 지어주는 것이 좋아요

2023-06-14 14:41 UTC, seung-hun-h commented on sub_cal/sub_cal/src/main/java/Console.java
> +    //사용자가 1번(조회)를 선택하였을 시 실행
주석은 제거해주세요

2023-06-14 14:41 UTC, seung-hun-h commented on sub_cal/sub_cal/src/main/java/Console.java
> +    BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
접근 제어자를 추가해줘야 할 거 같아요
Scanner와 BufferedReader를 함께 사용하신 이유가 있을까요?

2023-06-14 14:41 UTC, seung-hun-h commented on sub_cal/sub_cal/src/main/java/Console.java
> +        Arrays.stream(Option.values()).forEach(o -> System.out.println(o.toString()));
명확한 이름을 지어줄 필요가 있겠네요. 그리고 toString은 직접 호출하지 않도록 변경해주세요

2023-06-14 14:41 UTC, seung-hun-h commented on sub_cal/sub_cal/src/main/java/Console.java
> +    public void ShowOptions() {
자바 메서드 네이밍 규칙을 지켜주세요~

2023-06-14 14:41 UTC, seung-hun-h commented on sub_cal/sub_cal/src/main/java/model/History.java
> +public class History {
history를 영속화 한다는 의미를 가진 이름으로 변경하면 좋겠네요

2023-06-14 14:41 UTC, seung-hun-h commented on sub_cal/sub_cal/src/main/java/global/ErrorMessage.java
> +}
상수 클래스는 지양하는 것이 좋아요. 클래스의 정보가 분산된다고 생각하기 때문이에요.
정말 전역적으로 사용하는 상수인지를 다시 생각해보는 것이 좋을 것 같아요

2023-06-14 14:41 UTC, seung-hun-h commented on sub_cal/sub_cal/src/main/java/model/History.java
> +    }
inputString 보다 명확한 이름을 지어주세요

2023-06-14 14:41 UTC, seung-hun-h commented on sub_cal/sub_cal/src/main/java/model/Operator.java
> +    }
[여기](https://github.com/prgrms-be-devcourse/java-calculator/pull/118/files/d6df7ce2705f2e212568ea604d0fbd4b1ba506e5#r1223751848) 를 확인해주세요

2023-06-14 14:41 UTC, seung-hun-h commented on sub_cal/sub_cal/src/main/java/model/Operator.java
> +                case "PLUS" : case "MINUS":
연산자 이름은 `OperatorList`에서 관리해줘도 좋겠네요

2023-06-14 14:41 UTC, seung-hun-h commented on sub_cal/sub_cal/src/main/java/model/OperatorList.java
> +public enum OperatorList {
이름을 변경 해야겠네요. 클래스 이름이라고 생각해보세요 PLUS라는 인스턴스의 타입이 OperatorList가 되는 것이 맞을까요?

2023-06-14 14:41 UTC, seung-hun-h commented on sub_cal/sub_cal/src/main/java/model/Operator.java
> +    }
메서드 이름을 보면 우선순위를 계산하는 것 같은데 그렇지 않네요.
num2를 변수로 넘기는 것 보다 스택에 담아서 pop 해주는 것이 더 좋을 것 같아요.
곱하기와 나누기만 수행하는데 메서드 이름에서는 드러나지 않네요

2023-06-14 14:41 UTC, seung-hun-h commented on sub_cal/sub_cal/src/main/java/model/Operator.java
> +    private void classify(StringTokenizer st){
classify는 계산을 수행하는 책임을 드러내지 못하는 것 같아요

2023-06-14 14:41 UTC, seung-hun-h requested changes
세한님 리뷰남겼습니다.
자바에서는 보통 변수명을 줄이지 않습니다. 그리고 변수명이나 클래스명을 최대한 의미있게 지어주는 것이 좋아요

2023-06-18 04:41 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/Console.java
> +    //사용자가 1번(조회)를 선택하였을 시 실행
넵 일단 주석은 제거하고 메소드 이름을 구체적으로 변경하였습니다 !
자바독스도 적용해보겠습니다

2023-06-18 04:43 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/Console.java
> +    BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
초반에 스캐너로 입력을 받았는데 나중에 BufferedReader 로 바꾸면서 미처 지우지 못한 것 같습니다.
현재는 모두 BufferedReader를 사용하도록 수정하였습니다 !

2023-06-18 04:43 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/Console.java
> +        Arrays.stream(Option.values()).forEach(o -> System.out.println(o.toString()));
넵 알겠습니다

2023-06-18 04:44 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/Console.java
> +    public void ShowOptions() {
앗 알겠습니다.
메소드 이름 변경하였습니다

2023-06-18 04:44 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/model/History.java
> +public class History {
historyEntity로 클래스 이름을 변경하였습니다.

2023-06-18 04:45 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/global/ErrorMessage.java
> +}
넵 상수 클래스는 지양하고 오류 메세지를 출력하도록 하겠습니다 !

2023-06-18 04:45 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/model/History.java
> +    }
넵 inputExpression으로 변수명을 변경하였습니다 ..!

2023-06-18 04:45 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/model/Operator.java
> +    }
넵 확인하고 수정하였습니다 !

2023-06-18 04:45 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/model/Operator.java
> +                case "PLUS" : case "MINUS":
넵 알겠습니다

2023-06-18 04:46 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/model/OperatorList.java
> +public enum OperatorList {
미처 생각을 못한 것 같습니다 
현재는 Operator 로 enum 클래스 이름을 변경하였습니다.

2023-06-18 04:46 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/model/Operator.java
> +    }
넵 알겠습니다 !

2023-06-18 04:47 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/model/Operator.java
> +    private void classify(StringTokenizer st){
메소드에서 명확한 책임이 드러나도록 이름을 변경하겠습니다 .. !

2023-06-18 04:47 UTC, 2jie0516 commented on sub_cal/sub_cal/build/classes/java/main/Console.class
넵 gitignore 를 추가하여 관리하도록 하였습니다

2023-06-18 04:48 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/Console.java
> +    }
output의 역할이 다른 곳에서 수행 되는 코드를 찾아서 수정하였습니다 !

2023-06-18 04:48 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/Index.java
> +public class Index implements Runnable{
Index 에서 App으로 변경하였습니다 .. !

2023-06-18 04:48 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/Index.java
> +                    System.out.print("계산식을 입력해주세요 : ");
넵 수정하였습니다

2023-06-18 04:50 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/Index.java
> +                        int result = calculator.cal(inputString);
기존에 int 형으로 값을 받아서 소수점이 출력이 안됐는데 bigdcimal을 이용하여 정확한 값이 나오도록 하였습니다

2023-06-18 04:50 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/model/Calculator.java
> +
앗 공백은 삭제하였습니다 .. !

2023-06-18 04:50 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/model/Operator.java
> +                    numberStack.push(-1*Integer.parseInt(word));
넵 매직 넘버 적용하였습니다 !

2023-06-18 12:46 UTC, seung-hun-h commented on sub_cal/sub_cal/src/main/java/App.java
> +        while (true) {
true도 의미있는 변수를 사용해주세요
+ 애플리케이션 종료 기능은 없나요?

2023-06-18 12:46 UTC, seung-hun-h commented on sub_cal/sub_cal/src/main/java/io/Input.java
> +    String inputExpression() throws IOException;
Checked Exception을 throws 하는 특별한 이유가 없다면 인터페이스에서 제거하고 구현체에서 RuntimeException으로 변환해주거나 적절한 처리를 해주면 좋을 것 같아요.

https://cheese10yun.github.io/checked-exception/

2023-06-18 12:46 UTC, seung-hun-h commented on sub_cal/sub_cal/src/main/java/App.java
> +            }
```suggestion
            } catch (NoSuchElementException | IOException e1){
                continue;
            }
```
같은 일을 한다면 이렇게 해주면 좋을 것 같아요

2023-06-18 12:46 UTC, seung-hun-h commented on sub_cal/sub_cal/src/main/java/App.java
> +                    if (!(output.showResultHistory(historyEntity.getHistory()))) output.historyEmptyError();
`showResultHistory` 는 History를 출력해주고 boolean 값을 반환해주어 두 가지 일을 하고 있는 것 같아요.
만약 출력에 실패했다면 예외를 던지는 것이 좋아보여요

2023-06-18 12:46 UTC, seung-hun-h commented on sub_cal/sub_cal/src/main/java/App.java
> +                        inputString = input.inputExpression();
```suggestion
                    try {
                        String inputString = input.inputExpression();
```

2023-06-18 12:46 UTC, seung-hun-h commented on sub_cal/sub_cal/src/main/java/Console.java
> +        return true;
bool 값을 반환해주는 것 보다. 리스트가 비어있는 경우와 그렇지 않은 경우를 나눠서 메시지를 출력해줘도 좋을 것 같네요

2023-06-18 12:46 UTC, seung-hun-h commented on sub_cal/sub_cal/src/main/java/model/Calculator.java
> +        String result = operation.operate(expression);
단순히 `Operation`에 위임하고 있고, `Operation` 을 외부에서 주입받고 있는 형식도 아니니 `Operation`의 로직을 `Caculator`로 가져와도 좋을 것 같네요. 그러면 `Operation`은 제거될 것 같구요

2023-06-18 12:46 UTC, seung-hun-h commented on sub_cal/sub_cal/src/main/java/model/HistoryEntity.java
> +        return log;
원본을 그대로 전달해주기보다 방어적 복사본을 전달해주는 것이 좋아보여요.

https://velog.io/@injoon2019/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C-%EC%9E%90%EB%B0%94-%EC%95%84%EC%9D%B4%ED%85%9C-50.-%EC%A0%81%EC%8B%9C%EC%97%90-%EB%B0%A9%EC%96%B4%EC%A0%81-%EB%B3%B5%EC%82%AC%EB%B3%B8%EC%9D%84-%EB%A7%8C%EB%93%A4%EB%9D%BC

2023-06-18 12:46 UTC, seung-hun-h commented on sub_cal/sub_cal/src/main/java/model/Operation.java
> +            switch (operator != null ? operator : operator.NULL){
`getOperator`에서 NULL을 반환하고 있는데 굳이 null인지 검사할 필요가 있을까요?
Optional을 반환하는 것이 아니라 항상 Operator을 반환할 수 있도록 하면될 것 같아요

```suggestion
            Operator operator = Operator.getOperator(word);
            switch (operator){
```

2023-06-18 12:46 UTC, seung-hun-h commented on sub_cal/sub_cal/src/main/java/model/Operation.java
> +    private static final int CONVERTTONEGATIVE = -1;
```suggestion
    private static final int CONVERT_TO_NEGATIVE = -1;
```

자바 상수 네이밍에서는 띄어쓰기의 경우 `_`로 구분합니다.

2023-06-18 12:46 UTC, seung-hun-h commented on sub_cal/sub_cal/src/main/java/model/Operation.java
> +                    break;
```suggestion
                case MULTIPLY : case DIVIDE:
                    numberStack.push(Double.parseDouble(st.nextToken()));
                    calculateMultiplyOrDivide(operator);
                    break;
                case PLUS : case MINUS:
                    operStack.add(operator);
                    break;
                case NULL:
                    if(operStack.isEmpty() || Operator.isPlus(operStack.pop())){
                        numberStack.push(Double.parseDouble(word));
                        break;
                    }

                    numberStack.push(CONVERTTONEGATIVE*Double.parseDouble(word));
                    break;
```

이렇게 작성해주면 좋을 것 같아요.

2023-06-18 12:46 UTC, seung-hun-h commented on sub_cal/sub_cal/src/main/java/model/Operation.java
> +        if(word.equals("MULTIPLY")) numberStack.push(num1*num2);
```suggestion
        if(Operator.isMultiply(word)) numberStack.push(num1*num2);
```

2023-06-18 12:46 UTC, seung-hun-h commented on sub_cal/sub_cal/src/test/java/ConsoleTest.java
> +    private static HistoryEntity historyEntity;
```suggestion
    private HistoryEntity historyEntity;
```
static은 제거해도 좋겠네요

2023-06-18 14:26 UTC, dojinyou commented on sub_cal/sub_cal/src/main/java/Index.java
> +                        int result = calculator.cal(inputString);
bigdecimal은 간단한 계산기에 쓰기에는 무거운 타입일 수도 있을 것 같은데 어떻게 생각하시나요?

2023-06-18 14:39 UTC, dojinyou commented on sub_cal/sub_cal/src/main/java/model/Operation.java
> +        classifyOperatorAndNumber(st);
굳이 `StringTokenizer`를 외부에서 생성한 후에 파라미터로 넣어주는 이유가 있을까요?
파라미터로 expression을 받고 함수 내부에서 `StringTokenizer`를 생성하는 것과 어떤 차이점이 있을까요?

2023-06-18 14:39 UTC, dojinyou commented on sub_cal/sub_cal/src/main/java/model/Operation.java
> +            if(numberStack.size() == 1) break;
```suggestion
        while(numberStack.size() > 1){
```

`while(true)` 후 `break`보다는 적절한 조건을 넣어주는 건 어떨까요?

2023-06-18 14:39 UTC, dojinyou commented on sub_cal/sub_cal/src/main/java/validation/InputValidation.java
> +        return false;
[nit]
```suggestion
        if(expression.isBlank()){
            return true;
        }
        return false;
```

empty는 공백 값(white space)가 들어있는 문자열을 체크하지 못해서 `isBlank`를 고려해보는 것도 좋을 것 같아요!

2023-06-18 14:39 UTC, dojinyou commented on sub_cal/sub_cal/src/test/java/ConsoleTest.java
> +    @ParameterizedTest
```suggestion
    }

    @ParameterizedTest
```

2023-06-18 14:39 UTC, dojinyou commented on sub_cal/sub_cal/src/test/java/ConsoleTest.java
> +    @ValueSource(strings = {"1","2","3"})
ParameterizedTest 활용하신 건 좋은 것 같아요! 👍

2023-06-18 14:39 UTC, dojinyou commented on sub_cal/sub_cal/src/test/java/model/CalculatorTest.java
> +    }
👍

2023-06-18 14:39 UTC, dojinyou commented on sub_cal/sub_cal/src/test/java/model/CalculatorTest.java
> +        result = calculator.calculate(expression);
```suggestion
        String result = calculator.calculate(expression);
```

혹시 줄바꿈을 한 다른 이유가 있을까요?

2023-06-18 14:39 UTC, dojinyou commented on sub_cal/sub_cal/src/test/java/model/HistoryEntityTest.java
> +        historyEntity.getHistory();
이 함수는 왜 호출되어야 하는 걸까요?

2023-06-18 14:39 UTC, dojinyou commented on sub_cal/sub_cal/src/test/java/model/HistoryEntityTest.java
> +        assertEquals(historyList,historyEntity.getHistory());
[nit]
```suggestion
				// given
        List<String> expectedList = new ArrayList<>();
        expectedList.add("1 + 1 = 2");
        expectedList.add("1 * 3 + 6 = 9");
        
        // when
        List<Sring> result = historyEntity.getHistory();
        
        // then
        assertEquals(expectedList, result);
```

위와 같은 형태로 작성해보는 건 어떨까요?

2023-06-24 09:47 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/Index.java
> +                        int result = calculator.cal(inputString);
정확한 값을 내고 싶어서 사용하였는데 무겁다는 단점도 있는 것 같습니다..
bigdecimal을 쓰지 않고 정확한 값을 낼수 있는 방법도 고민해보겠습니다 .. !

2023-06-24 09:48 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/App.java
> +        while (true) {
true를 IS_RUNNING 으로 변경하였습니다 ! 
추가로 종료기능까지 만들었습니다.

2023-06-24 09:50 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/io/Input.java
> +    String inputExpression() throws IOException;
좋은 글 공유해주셔서 감사합니다 !
본문에 나온 내용대로 처리해보겠습니다 
지금은 인터페이스에서 throw를 없애고 구현체에서 처리하는 방식으로 변경하였습니다 .. !

2023-06-24 09:50 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/App.java
> +            }
넵 수정하였습니다

2023-06-24 09:51 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/App.java
> +                    if (!(output.showResultHistory(historyEntity.getHistory()))) output.historyEmptyError();
넵 수정하였습니다 !

2023-06-24 09:52 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/App.java
> +                        inputString = input.inputExpression();
넵 알겠습니다
해당 코드로 수정하였습니다 .. !

2023-06-24 09:54 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/Console.java
> +        return true;
넵 말씀해주신대로 리팩토링 해보겠습니다 !

2023-06-24 09:55 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/model/Calculator.java
> +        String result = operation.operate(expression);
Operation 에 있는 코드를 Calculator 와 통합하였습니다 !

2023-06-24 09:55 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/model/HistoryEntity.java
> +        return log;
방어적 복사본은 처음 들어보는데 이번 기회에 공부해보겠습니다 !
감사합니다 !

2023-06-24 09:56 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/model/Operation.java
> +            switch (operator != null ? operator : operator.NULL){
말씀해주신대로 수정하였습니다 .. !

2023-06-24 09:57 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/model/Operation.java
> +    private static final int CONVERTTONEGATIVE = -1;
앗 알겠습니다 
해당 부분도 조심하겠습니다

2023-06-24 09:58 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/model/Operation.java
> +                    break;
말씀해주신대로 수정하겠습니다 !

2023-06-24 09:58 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/model/Operation.java
> +        if(word.equals("MULTIPLY")) numberStack.push(num1*num2);
코드 수정하였습니다 !

2023-06-24 09:59 UTC, 2jie0516 commented on sub_cal/sub_cal/src/test/java/ConsoleTest.java
> +    private static HistoryEntity historyEntity;
넵 static 제거하였습니다 !
리뷰를 늦게 봐서 죄송합니다 
말씀해주신 내용들 최대한 반영하도록 하겠습니다

2023-06-24 10:02 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/model/Operation.java
> +        classifyOperatorAndNumber(st);
지금 생각해보면 StringTokenizer를 넘겨주는 것보다 expression 을 넘겨주는 게 더 바람직해 보이는 것 같습니다.
해당 방식으로 수정하였습니다!

2023-06-24 10:03 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/model/Operation.java
> +            if(numberStack.size() == 1) break;
while(true) 로 하는 게 습관이었는데 앞으로는 적절한 조건을 넣어주는 식으로 바꿔보겠습니다 !

2023-06-24 10:04 UTC, 2jie0516 commented on sub_cal/sub_cal/src/main/java/validation/InputValidation.java
> +        return false;
isEmpty만 알고있었는데 isBlank도 알아보겠습니다 !

2023-06-24 10:04 UTC, 2jie0516 commented on sub_cal/sub_cal/src/test/java/ConsoleTest.java
> +    @ParameterizedTest
앗 알겠습니다

2023-06-24 10:04 UTC, 2jie0516 commented on sub_cal/sub_cal/src/test/java/ConsoleTest.java
> +    @ValueSource(strings = {"1","2","3"})
감사합니다 !!

2023-06-24 10:04 UTC, 2jie0516 commented on sub_cal/sub_cal/src/test/java/model/CalculatorTest.java
> +    }
감사합니다 ~!

2023-06-24 10:06 UTC, 2jie0516 commented on sub_cal/sub_cal/src/test/java/model/CalculatorTest.java
> +        result = calculator.calculate(expression);
줄바꿈이 굳이 필요한 것 같지않은데 제가 신경을 못쓴것 같습니다.
해당 코드 수정하였습니다 !

2023-06-24 10:06 UTC, 2jie0516 commented on sub_cal/sub_cal/src/test/java/model/HistoryEntityTest.java
> +        historyEntity.getHistory();
앗 해당 코드 삭제하였습니다

2023-06-24 10:09 UTC, 2jie0516 commented on sub_cal/sub_cal/src/test/java/model/HistoryEntityTest.java
> +        assertEquals(historyList,historyEntity.getHistory());
해당 테스트 코드 수정하였습니다 !
앞으로도 테스트코드를 짤 때 given when then 으로 작성해보도록 노력하겠습니다

리뷰 남겨주셔서 감사합니다
말씀해주신 부분들 참고해서 리팩토링 진행하겠습니다

2023-07-02 16:11 UTC, merged