[4기 - 전선희] 1~2주차 과제 : 계산기 구현 미션 제출합니다.
prgrms-be-devcourse/java-calculator pull request #142
Opened 2023-06-09 09:58 UTC by funnysunny08

## 📌 과제 설명 
1~2주차 강의에서 배운 내용들을 최대한 활용할 수 있도록 계산기 구현하였습니다!
## 👩‍💻 요구 사항과 구현 내용 
### 요구 사항
- 객체지향적인 코드로 계산기 구현하기
    - [X]  더하기
    - [X]  빼기
    - [X]  곱하기
    - [X]  나누기
    - [X]  우선순위(사칙연산)
- [ ]  테스트 코드 구현하기
- [X]  계산 이력을 맵으로 데이터 저장기능 만들기
- [ ] (선택) 정규식 사용
<br>
### 구현 내용
```
📁 engine 
|_ 📁 io 
    |_ 🗂 Input.java
    |_ 🗂 Output.java
|_ 📁 model
    |_ 🗂 Result.java
|_ 🗂 JavaCalculator.java    
🗂 App.java 
🗂 BasicCalculator.java 
🗂 Console.java      
```
- 입출력: `Input`, `Output` 인터페이스를 `Console`에서 구현하여 메뉴 입력받기, 수식 입력받기, 메뉴 출력하기, 에러 메시지 출력하기 기능을 구현했습니다.
- 계산 결과값 저장 및 출력: `Result`에서 계산 결과 값을 저장할 map을 선언하고 결과값 저장하기, 결과값들 출력하기 기능을 구현했습니다.
- 계산: `BasicCalculator`에서 수식을 입력받고 결과값을 출력하도록 하였습니다.
- 계산기 실행: `JavaCalculator`에서 계산기를 실행할 수 있도록 하였습니다.

## ✅ 피드백 반영사항  

## ✅ PR 포인트 & 궁금한 점 
- 객체지향적으로 구현이 잘 된걸까요..?🥲
- `Result.java`에서 결과값을 담을 map을 선언하고 관련 함수들을 같이 선언했는데 이게 좋은 방법인지 궁금합니다!
- 제가 테스트 코드에 익숙하지 않아 계산기 구현 먼저 PR 올렸습니다! 테스트도 더 추가해서 빠르게 올리겠습니다!!!

2023-06-09 13:07 UTC, dojinyou commented on src/main/java/com/programmers/engine/JavaCalculator.java
> +            switch (input.selectMenu()) {
[객체지향생활체조 원칙](https://catsbi.oopy.io/bf003ff6-2912-4714-8ac2-44eeb7becc93)도 준수해주시면 좋을 것 같아요

2023-06-11 11:39 UTC, seung-hun-h requested changes
안녕하세요 선희님 리뷰남겼습니다.
지금은 `BasicCalculator`에 거의 모든 로직이 담겨있는데요, 어떻게하면 분리할 수 있을지 고민해보시면 좋을 것 같네요

2023-06-11 11:39 UTC, seung-hun-h commented on src/main/java/com/programmers/BasicCalculator.java
> +package com.programmers;
`BasicCalculator` 클래스가 여기에 위치한 이유가 뭔가요?

2023-06-11 11:39 UTC, seung-hun-h commented on src/main/java/com/programmers/BasicCalculator.java
> +        System.out.println(answer);
출력하는 책임은 `Console`에 있는 것이 좋을 것 같네요.
예를 들어, `System.out.println`이 아니라 다른 클래스 혹은 방식으로 출력을 해야한다면, 고쳐야할 곳이 여러군데 분산되어있을 것 같아요

2023-06-11 11:39 UTC, seung-hun-h commented on src/main/java/com/programmers/BasicCalculator.java
> +        else if (operator.equals("+") || operator.equals("-")) return 1;
연산자의 String value, Priority 등 연관성이 높은 것들은 Enum으로 관리해도 좋을 것 같네요

2023-06-11 11:39 UTC, seung-hun-h commented on src/main/java/com/programmers/BasicCalculator.java
> +                case ")" -> {
"(", ")"이 입력되는 경우가 있나요?

2023-06-11 11:39 UTC, seung-hun-h commented on src/main/java/com/programmers/BasicCalculator.java
> +    private int toPostfix(String str) {
메서드의 이름은 일반적으로 동사 혹은 동사구로 작성해요. 다른 적절한 이름을 지어주는 것이 좋을 것 같네요

2023-06-11 11:39 UTC, seung-hun-h commented on src/main/java/com/programmers/BasicCalculator.java
> +        for (int i = 0; i < strArr.length; i++) {
인덱스로 접근할 필요가 없으므로 [for-each](https://wikidocs.net/264)문을 사용해보는 것도 좋겠네요!

2023-06-11 11:39 UTC, seung-hun-h commented on src/main/java/com/programmers/BasicCalculator.java
> +    public int getResult(ArrayList<String> list) {
추상체(`List`)에 의존하는 것이 좋겠네요

2023-06-11 11:39 UTC, seung-hun-h commented on src/main/java/com/programmers/engine/model/Result.java
> +    }
지금은 삭제하는 로직이 없지만, 중간에 어떤 데이터가 삭제된다면 기존에 저장되어 있는 데이터가 대체될 수 있겠네요

2023-06-12 09:57 UTC, funnysunny08 commented on src/main/java/com/programmers/engine/model/Result.java
> +    private final Map<Integer, String> results = new HashMap<>();
사실 List 형태를 사용하는 게 좋지 않을까 생각하기도 했었는데 과제 조건에 map을 이용하라는 것이 있어 사용하였습니다...!🥲

2023-06-12 09:59 UTC, funnysunny08 commented on src/main/java/com/programmers/engine/JavaCalculator.java
> +            switch (input.selectMenu()) {
넵 리뷰 모두 확인했습니다!! 참고해서 수정해보겠습니다 감사합니다!!! :)

2023-06-12 10:04 UTC, funnysunny08 commented on src/main/java/com/programmers/BasicCalculator.java
> +package com.programmers;
저번주 곰튀김님 강의의 야구 게임 실습 강의 중에서 "우리가 사용하는 핵심 비즈니스 로직은 어떤 것에도 외부 dependency가 없도록 설계하고 코드를 유지하는 것이 좋다!" 라고 하신 말씀을 듣고 저기에 위치시킨 것인데 제가 조금 다르게 받아들인 것 같아욤..!

2023-06-12 10:07 UTC, funnysunny08 commented on src/main/java/com/programmers/BasicCalculator.java
> +                case ")" -> {
혹시 몰라 괄호도 입력값으로 들어올 수 있다 가정하고 짰습니다..!

2023-06-12 10:09 UTC, funnysunny08 commented on src/main/java/com/programmers/engine/model/Result.java
> +    }
넵!! 리뷰 모두 확인했습니다. 반영해서 다시 PR 올리겠습니다. 감사합니다!!! ☺️

2023-06-12 12:28 UTC, merged