[4기 - 신범철] 1~2주차 과제 : 계산기 구현 미션 제출합니다.
prgrms-be-devcourse/java-calculator pull request #143
Opened 2023-06-09 11:46 UTC by beombu

## 📌 과제 설명 
- `(interface) Input` : 계산기의 입력을 담당하는 인터페이스입니다.
- `(interface) Output` : 계산기의 출력을 담당하는 인터페이스입니다.
- `Console` : Input와 Output을 implement 받아 구현한 구현체입니다.
- `(Enum) ExceptionMessage` : 예외 메세지를 관리하는 Enum 입니다. 

## 👩‍💻 요구 사항과 구현 내용 

## ✅ 피드백 반영사항  

## ✅ PR 포인트 & 궁금한 점 
- 제가 만든 Console이 OOP적인 코드인지 궁금합니다.
- Console 내에서 Exception처리를 해주었는데 맞는지 잘 모르겠습니다.

2023-06-09 13:49 UTC, devcourse-ray reviewed
Console 이라는 이름을 가진다면 계산기와 관련없이 입/출력만 있는게 맞지 않을까 싶어요.
만약 계산기 관련된 입/출력이 존재해야한다면 CalculatorConsole 과 같이 디테일한 구현체가 나와야하지 않을까요??

2023-06-09 13:49 UTC, devcourse-ray commented on src/main/java/Application.java
> +        System.out.println();
요녀석은 왜 들어가있는걸까요?

2023-06-09 14:35 UTC, beombu reviewed
빠른 리뷰 감사합니다!!🙇‍♂️🙇‍♂️

추상적인 클래스로 두고 싶어서 네이밍을 추상적으로 하다보니 목적을 알맞지 않는 네이밍을 한 것 같습니다. 추상적인 것과 구체적인 것을 다시 생각해보고 수정하도록 하겠습니다!!

2023-06-09 14:35 UTC, beombu commented on src/main/java/Application.java
> +        System.out.println();
프로젝트를 시작하면서 실행이 되는지를 확인하려고 만들었는데 PR에 들어가있었네요!
삭제하도록 하겠습니다!!💨

2023-06-09 14:35 UTC, beombu commented on src/main/java/exception/ExceptionMessage.java
> +    }
에러는 의미하는 `BASE_MESSAGE`의 **중복을 제거**하기 위해 상수로 두고 생성자에서 문자열을 합쳐주었습니다!

2023-06-10 07:19 UTC, beombu commented
Test Code를 작업하면서 어려움이 있어 조언을 구하고 싶습니다..
`InputButton`이라는 클래스는 1 or 2를 제외하고는 모두 `IllegalArgumentException`을 던지도록 구현하였습니다.
하지만 Test를 작업하면 기대와는 다르게 `NoSuchElementException`을 계속 반환합니다..

```java
String input = sc.next();
```
해당 부분의 값이 존재하지 않는 문제라고 생각하는데 해결이 되지 않아 글을 남깁니다ㅠㅠ..
저의 테스트 코드는 아래와 같습니다.

```java
class CalculatorConsoleTest {
    private static CalculatorConsole calculatorConsole;

    @BeforeEach
    public void setup() {
        calculatorConsole = new CalculatorConsole();
    }

    @Test
    @DisplayName("1 또는 2을 입력하지 않는 경우 테스트")
    void inputButton() {
        assertThrows(IllegalArgumentException.class, () -> {
            String input = "3";
            InputStream inputStream = new ByteArrayInputStream(input.getBytes());
            System.setIn(inputStream);

            calculatorConsole.inputButton();
        });
    }
}

2023-06-11 08:33 UTC, devcourse-ray commented on src/main/java/exception/ExceptionMessage.java
> +    }
BASE_MASSAGE 와 message를 구분해서 따로 만들고 붙여주는건 불필요한 작업같습니다.
필요하다면 getter에서 처리해주거나 해당 enum의 정체성을 확실하게 가져가도록 BASE_MESSAGE를 없애도 될 것 같네요

2023-06-11 09:26 UTC, beombu commented on src/main/java/exception/ExceptionMessage.java
> +    }
감사합니다!
수정하도록 하겠습니다!

2023-06-11 16:06 UTC, ICCHOI requested changes
안녕하세요 범철님! 
IO와 관련된 기능만 쪼개서 잘 올려주셨어요! 
코멘트가 좀 늦은 거 같은데, 확인 부탁드려요! 다음에는 더 빠르게 남겨보겠습니다 ㅠㅠ

2023-06-11 16:06 UTC, ICCHOI commented on src/main/java/validation/InputValidationImpl.java
> +        if (!BUTTON_PATTERN.matcher(input).matches()) {
좀 더 가독성을 살려 개선하면 어떨까요?

2023-06-11 16:06 UTC, ICCHOI commented on src/main/java/validation/InputValidationImpl.java
> +    }
validate를 성공했는데 false를 반환하는건 조금 부자연스럽게 느껴져요.
추가로 위의 button validate와 (예외 메시지를 제외하면) 똑같은 구조를 가지고 있는 것 같은데 굳이 구분할 필요가 있을까요?

2023-06-11 16:06 UTC, ICCHOI commented on src/test/java/validation/InputValidationImplTest.java
> +        });
given - when - then 패턴을 사용해서 테스트 코드를 작성해주시면 좋을 것 같아요!

2023-06-11 16:06 UTC, ICCHOI commented on src/main/java/io/CalculatorScannerInput.java
> +        validation.validateButton(input);
메소드는 boolean을 반환하는데, 그 후 아무 행동도 하지 않는 건 어색하게 보여요
해당 결과 값으로 이후의 행동을 진행하거나, 메소드가 void type인 편이 자연스러워 보여요

2023-06-11 16:06 UTC, ICCHOI commented on src/main/java/io/CalculatorPrintOutput.java
> +    private static final String RECORD_MESSAGE = "%s = %d";
ExceptionMessage는 enum으로 만드셨던데, Output에 사용되는 메시지는 enum이 아닌 이유가 있을까요?

2023-06-12 08:40 UTC, beombu commented on src/main/java/exception/ExceptionMessage.java
> +}
`ExceptionMessage`를 enum으로 구현한 이유는 예외에 대한 메세지를 한 곳에서 관리하면 편리하다고 생각하였습니다.
하지만 인창님이 말씀하신 것처럼 enum에서의 역할이 메세지를 출력해주는 것 이외에는 기능이 없습니다. 또 생각해보니 모든 기능의 예외 메세지를 하나의 enum에서 관리하는 것 역시 맞지 않다는 생각을 하게 되었습니다.
삭제하고 상수로 관리하도록 하겠습니다🤩🤩

2023-06-12 08:43 UTC, beombu commented on src/main/java/validation/InputValidationImpl.java
> +    }
정규표현식을 파라미터로 빼주어 최대한 코드의 중복을 없애는 방식으로 변경하였습니다!

2023-06-12 08:48 UTC, beombu commented on src/test/java/validation/InputValidationImplTest.java
> +        });
테스트 코드가 익숙하지 않아 given - when - then 패턴으로 구현하고 싶었으나 when & then이 묶여 구현하는 방식으로 변경 하였습니다ㅠㅠ
혹시 테스트 코드에 관한 글을 추천해주실 수 있나요...?

2023-06-12 08:49 UTC, beombu commented on src/main/java/io/CalculatorScannerInput.java
> +        validation.validateButton(input);
감사합니다!! 변경하였습니다!

2023-06-13 05:30 UTC, ICCHOI approved these changes
범철님, 피드백을 받은 후 엄청 개선하셨네요!
네이밍도 명시적으로 잘 지어주신 것 같고, 객체의 역할과 책임도 적절하게 잘 분배해주신 거 같아요!
이대로 진행하시면 될 것 같습니다 :) 👍

2023-06-13 13:10 UTC, devcourse-ray approved these changes
👍 코드가 깔끔하네요!
값이 입력되는 부분을 잘 만들어뒀으니 이제 계산기가 어떤 기능을 하는지에 집중해서 다음도 진행해주세요~

2023-06-13 15:50 UTC, merged