[4기 - 조재현] 자바 계산기 구현 미션 2번쨰 pr입니다.
prgrms-be-devcourse/java-calculator pull request #160
Opened 2023-06-11 04:21 UTC by HandmadeCloud

## 📌 과제 설명
- [x] 사칙연산 구현 (우선순위 o)
- [x] 계산
- [x] 연산 결과를 저장 및 조회
- [ ] 테스트코드
- [ ] 예외케이스 정리

## ✅ 피드백 반영사항 
1. 기본 규칙 수정
 (gitignore, 프로젝트 기본 생성 형식, 접근지정자, 주석처리, 향상된 for문 등)
2. null문제에 대한 에외 처리 (차후에 추가 수정 예정)

## ✅ PR 포인트 & 궁금한 점
팀원들과 rbf 계산기 이야기를 하면서 조회와 연산의 기능 앞에 인터페이스를 두어 처리한 점이 기억에 남았습니다.
그리고 금요일엥 수강한 강의에서도 input,output을 인터페이스로 만들고 이를 상속하는 구현 클래스로 어플리케이션을 설계하였습니다.

제가 지금 설계한 프로젝트에서도 인터페이스를 추가하여 어플리케이션을 변경에 유연하게 설계를 개선하는 것이 좋을 지 여쭤보고 싶습니다!

2023-06-11 07:22 UTC, HyoungUkJJang reviewed
재현님 PR 반영하시느라 고생하셨습니다 :) 

몇가지 의견을 남겨보았는데 재현님도 의견을 자유롭게 남겨주시면 좋을 것 같아요 👍🏻
고생하셨습니다 🙂

2023-06-11 07:22 UTC, HyoungUkJJang commented on src/main/java/org/example/view/InputView.java
> +        if(REGEX_EXPRESSION.matcher(expression).matches()){
matcher를 Validation의 책임으로 만들어 줄 수 있지 않을까요? 재현님의 생각은 어떠신가요 ~?

2023-06-11 07:22 UTC, HyoungUkJJang commented on src/main/java/org/example/view/InputView.java
> +        if(REGEX_SELECT.matcher(workNum).matches()){
matcher를 Validation의 책임으로 만들어 줄 수 있지 않을까요? 재현님의 생각은 어떠신가요 ~?

2023-06-11 07:22 UTC, HyoungUkJJang commented on src/main/java/org/example/domain/Console.java
> +            }
selectWorks() 메서드를 확인해 봤을 때 null 값이 넘어오지 않을 것 같은데 어떻게 생각하시나요 ~?

2023-06-11 07:22 UTC, HyoungUkJJang commented on src/main/java/org/example/domain/Console.java
> +    }
Console이 모두 "구현체"에 의존하고 있는 것 같은데 따로 생성자를 통해 주입하시는 이유가 있으실까요?

2023-06-11 07:22 UTC, HyoungUkJJang commented on src/main/java/org/example/repository/Records.java
> +    public static List<String> arithmeticRecords = new ArrayList<>();
Records는 어떻게 보면 중요한 "저장소"역할을 하는 것 같습니다.
이것을 public static으로 열어도 되는가? 에 대한 의문이 조금 생기는 것 같아요. 재현님의 생각은 어떠신지 의견을 들어보고 싶어요 🙂

2023-06-11 07:22 UTC, HyoungUkJJang commented on src/main/java/org/example/domain/Console.java
> +    public void selectOption(SelectTypeView selectType) {
메서드 네이밍이 조금은 어색한 것 같아요. 
옵션을 선택해야할 것 같은데 사실 선택된 옵션에 대한 로직을 처리하고 있는 것으로 보입니다.

2023-06-11 07:22 UTC, HyoungUkJJang commented on src/main/java/org/example/domain/CalculateType.java
> +    }
CalculateType.values()로 명시하신 이유가 있으실까요?

2023-06-11 07:22 UTC, HyoungUkJJang commented on src/main/java/org/example/domain/Calculator.java
> +                    calculateType.getPriority() < CalculateType.findBySymbol(operatorStack.peek()).getPriority()) {
while 안에 검증 조건이 다소 복잡해 보이네요 별도의 메서드로 분리하는건 어떻게 생각하시나요?

2023-06-11 07:48 UTC, Jo-GyuHyeon requested changes
안녕하세요 재현님 😄 
형욱님이 먼저 코드리뷰를 잘해주셨네요. 👍 

### 🌵 CHECK
해당 PR은 이전 PR 의 피드백에 수정되지 않은 부분이 있어서 확인 부탁 드려요.
- https://github.com/prgrms-be-devcourse/java-calculator/pull/115

.idea 폴더 하위 혹은 .DS_Store 파일 같은 경우 형상 관리에 필요하지 않는 파일 및 폴더라 .gitignor 로 등록하시면 좋을것 같아요.

### 🙏 PR
https://github.com/prgrms-be-devcourse/java-calculator/pull/115#pullrequestreview-1464124093 해당 코멘트 내용중 다음 PR 에서 진행 해보면 어떨지에 대해 제가 답변은 드렸는데요. 
이때 다음 PR 이라고 말씀드린 부분은  Approve 처리 후 PR Merge 하여 새로운 내용의 리뷰를 하는 다음 PR 을 의미하였는데 커뮤니케이션에 오류가 있었던것 같아요.

새롭게 시작한 프로젝트를 생성 하신것 같은데 커밋 메시지의 prefix 가 fix 로 되어 있어서 어색한것 같아요.
대부분 리뷰 피드백은 보통 리뷰를 한 PR 에서 진행 햐게 되는 편인것 같아요.

이전 PR 을 CLOSE 처리 하시는게 좋을까요? 
CLOSE 하신다면 이유에 대한 코멘트를 남겨주시면 함께 참여하시는 분들에게 상황 인지하는데에 도움이 될것 같아요.


### 🙇 END
이번 PR 은 지난번 PR 과 같은 내용으로 인지하고 있어요. 리뷰 내용이 많기에 걱정이 되기도 해요.
고생 많으셨습니다. 🙇

2023-06-11 07:48 UTC, Jo-GyuHyeon commented on src/main/java/org/example/domain/Console.java
> +            }
현재 로직을 보았을때 null 이 발생 할 수 없을것 같아요. 
정규식에 해당하지 않을때 마지막으로 null 이 아닌 문자열이 리턴되는 것을 확인 하였어요.

현재 시점 기준으로 selectWorks() 코드를 첨부해 드려요.
```
    public String selectWorks() {
        String workNum = sc.nextLine();
        if(REGEX_SELECT.matcher(workNum).matches()){
            return workNum;
        }
        sc.nextLine();
        return "넌틀렸어";
    }
```

2023-06-11 07:48 UTC, Jo-GyuHyeon commented on src/main/java/org/example/domain/Console.java
> +            outputView.printRecords(Records.arithmeticRecords);
SelectTypeView 중 GET_LOG 도 좋지만 Records 클래스의 이름과 통일감을 주면 좋을것 같은데 어떻게 생각하시나요?

---

단순히 boolean 처럼 참,거짓으로 양방향으로만 나뉘는 경우는 이처럼 표현 하는 것이 좋다고 생각하는데, 메뉴 같은 경우는 switch 문이 더 적합하다고 생각해요.
selectOption 는 SelectTypeView 에 의존 하지만 SelectTypeView 가 몇개로 구성되어 있는지 모른다고 생각이 들어요.

2023-06-11 07:48 UTC, Jo-GyuHyeon commented on src/main/java/org/example/domain/Console.java
> +            Records.arithmeticRecords.add(infixExpression.toString() + " = " + result);
Records 의 List 타입의 정적  변수인 arithmeticRecords 를 접근 하기 보다 메서드로 기능을 제공 하는 방식을 적용 하면 어떨까요?
그렇게 된다면 자연스럽게 객체지향 생활체조의 디미터 법칙 또한 지킬수 있을것 같아요.
[dl.acm.org/doi/10.1145/62084.62113](https://dl.acm.org/doi/10.1145/62084.62113)

2023-06-11 07:48 UTC, Jo-GyuHyeon commented on src/main/java/org/example/domain/Validation.java
> +}
해당 클래스는 정규식만 가지고 있군요? 그렇다면 열거형 타입을 고려해보는 것은 어떨까요?
한편으로는 별도의 열거 타입이 필요 할지 고민 해보는것도 좋은것 같아요.

2023-06-11 07:48 UTC, Jo-GyuHyeon commented on src/main/java/org/example/repository/Records.java
> +    public static List<String> arithmeticRecords = new ArrayList<>();
정적 변수를 사용하는 이유는 무엇인까요???

2023-06-11 07:48 UTC, Jo-GyuHyeon commented on src/main/java/org/example/view/InputView.java
> +        return "넌틀렸어";
return 구문 이전에는 개행 처리 제안드려요.

2023-06-11 07:48 UTC, Jo-GyuHyeon commented on src/main/java/org/example/view/InputView.java
> +        return "수식이 잘못됐습니다.";
if, return 구문 이전에는 개행 처리 제안드려요.

2023-06-11 07:48 UTC, Jo-GyuHyeon commented on src/main/java/org/example/view/OutputView.java
> +        System.out.print("선택 : ");
https://github.com/prgrms-be-devcourse/java-calculator/pull/115/files#r1218809585 해당 리뷰가 반영되지 않은것 같아요. 확인 부탁 드려요.

2023-06-11 07:48 UTC, Jo-GyuHyeon commented on src/main/java/org/example/view/SelectTypeView.java
> +    }
이번 Java 강의에 나왔던 Stream 을 이용해보면 더욱 가독성이 좋아 질것이라 생각해요.

2023-06-11 07:48 UTC, Jo-GyuHyeon commented on src/main/java/org/example/view/OutputView.java
> +
불필요한 개행은 제거 부탁 드려요.

2023-06-11 07:48 UTC, Jo-GyuHyeon commented on src/main/java/org/example/repository/Records.java
> +
불필요한 개행은 제거 부탁 드려요.

2023-06-11 07:48 UTC, Jo-GyuHyeon commented on src/main/java/org/example/domain/Calculator.java
> +                    calculateType.getPriority() < CalculateType.findBySymbol(operatorStack.peek()).getPriority()) {
https://github.com/prgrms-be-devcourse/java-calculator/pull/115/files#r1218816436 해당 리뷰가 반영되지 않은것 같아요. 확인 부탁 드려요.

---

반복문에 있는 조건들을 의미 있는 변수로 할당 해보면 어떨까요? 그렇게 된다면 가독성이 증가 될거라 기대해요.

2023-06-11 08:45 UTC, HandmadeCloud commented on src/main/java/org/example/view/OutputView.java
> +    public void start(){
ㅋㅋㅋㅋ 넵 알겠습니다!

2023-06-11 08:47 UTC, HandmadeCloud commented on src/main/java/org/example/view/SelectTypeView.java
> +    private  int num;
final 키워드를 신경써서 처리하지는 않았는데 사용할 때마다 한번씩 생각해봐야겠네요!

2023-06-11 08:48 UTC, HandmadeCloud commented on src/main/java/org/example/view/SelectTypeView.java
> +    }
이부분은 나중에 예외처리를 하려고 합니다!
Stream으로 한번 더 개선해볼 수 있을 것 같습니다 👍

2023-06-11 08:48 UTC, HandmadeCloud commented on src/main/java/org/example/view/OutputView.java
> +        }
모든 for문은 stream으로 바꿀 수 있다고 하던데... 연습겸 가능하다면 해봐야겠습니다!

2023-06-11 08:49 UTC, HandmadeCloud commented on src/main/java/org/example/repository/Records.java
> +
조금 정리가 필요하긴 할 것 같습니다! 두줄이상 빈줄이 있는 건 특별한 의미가 없는한 주의해서 정리하라는 피드백을 받았던 기억이 있는데 pr 전에 조금 더 신경써야겠네요 ㅎㅎ

2023-06-11 08:50 UTC, HandmadeCloud commented on src/main/java/org/example/view/InputView.java
> +        if(REGEX_SELECT.matcher(workNum).matches()){
한번 해봐야겠습니다..! 굳이 여기서 해줄 필요는 없을 것 같네요 :)

2023-06-11 08:55 UTC, HandmadeCloud commented on src/main/java/org/example/domain/Console.java
> +            }
아무 입력을 사용자가 하지 않는 상황을 생각해서 저런 조건문을 넣었습니다!
오류처리에 대한 부분은 더 고민하고 구현해야할 것 같습니다 :)

2023-06-11 09:00 UTC, HandmadeCloud commented on src/main/java/org/example/repository/Records.java
> +    public static List<String> arithmeticRecords = new ArrayList<>();
팀원들과 이야기해보면서 저도 이 부분에 의문이 있었습니다!
static을 언제 사용해야하는 지 명확한 기준이 없어서 "객체를 생성하지 않고 사용해야한다?"라는 생각으로 사용했던 것 같습니다

형욱 멘토님의 가르침이 필요합니다 ㅎㅎ

2023-06-11 09:01 UTC, HandmadeCloud commented on src/main/java/org/example/domain/Calculator.java
> +                    calculateType.getPriority() < CalculateType.findBySymbol(operatorStack.peek()).getPriority()) {
조금 더 알아보기 쉬운 방법으로 개선해보겠습니다 :)

2023-06-11 09:04 UTC, HandmadeCloud commented on src/main/java/org/example/domain/CalculateType.java
> +    }
음.. 탐색이 '연산자 기호'가 아닌, 'add, subtract와 같은 타입' 으로 순회를 하게 된다고 생각했습니다.
그래서 이 차이를 이해하고 사용하기 위해서 사용했던 것 같습니다!

2023-06-11 09:06 UTC, HandmadeCloud commented on src/main/java/org/example/domain/CalculateType.java
> +    });
오류처리는 이번 pr 이후 모아서 생각해보려고 했습니다.
하지만 이부분을 정확하게 명시해서 이번 pr 메세지에 담지 않았네요... 앞으로는 pr주신 내용과 비교해보면서 개선한 사항과 그러지 않았던 부분을 정리해서 말씀드리겠습니다!

2023-06-11 09:08 UTC, HandmadeCloud commented on src/main/java/org/example/domain/Console.java
> +            String option = inputView.selectWorks();
변수명을 고려하는 경우에 이런 부분은 신경쓰겠습니다!

2023-06-11 09:09 UTC, HandmadeCloud commented on src/main/java/org/example/domain/Console.java
> +    }
사실 명확한 기준이 없었습니다..
일단 돌아가게 만들려고 해보면서 돌아가게 된 순간, 질문해야하는 부분을 명확하게 정리하지 못했습니다!

2023-06-11 09:10 UTC, HandmadeCloud commented on src/main/java/org/example/domain/Console.java
> +            outputView.printRecords(Records.arithmeticRecords);
switch문은 거의 사요해보지 않았는데 이런 경우에 사용될 수 있다는 점을 배우게 되네요 👍

2023-06-11 09:12 UTC, HandmadeCloud commented on src/main/java/org/example/domain/Validation.java
> +}
저도 팀원들과 이야기해보면서 Validation 처럼 독립적으로 관리하는 것이 좋은 방법인지, 이 정규식들이 필요한 부분마다 두어 관리하는 것이 적절할 지 고민하는 과정에 있었습니다. 아직은 명확한 생각이 없는 것 같아요 :(

2023-06-11 09:13 UTC, HandmadeCloud commented on src/main/java/org/example/repository/Records.java
> +    public static List<String> arithmeticRecords = new ArrayList<>();
없었습니다...! 정적변수를 사용하는 것에 학습이 더 필요할 것 같습니다!

2023-06-11 09:17 UTC, HandmadeCloud commented on src/main/java/org/example/domain/Calculator.java
> +                    calculateType.getPriority() < CalculateType.findBySymbol(operatorStack.peek()).getPriority()) {
여기서 사실 불필요한 조건이 하나 있어서 제거를 해서 정리를 했었습니다 ㅎㅎ
하지만 이번 pr을 통해서 멘토님이 어떤 부분을 생각하셨던 건지 명확하게 알 것 같습니다 다시 한 번 수정해보겠습니다!

2023-06-12 06:02 UTC, HandmadeCloud commented
첫번째 커밋 : 7158332
1. 변수명, 메서드 네이밍 수정
2. final 키워드 반영
3. for문 -> stream으로 변경
4. 개행처리
5. Records클래스에 대한 생각 그리고 수정
-> records클래스는 계산 기록을 가지고 있다. public으로 설정할 경우 여러 곳에서 이 기록에 대한 접근이 가능(임의로 수정될 우려가 있음, 개인정보인 경웅 더더욱 중요)
기록을 private으로 관리해 외부에서 접근하지 못하도록 하고, 계산 결과를 전달받아서 저장함으로써 캡슐화가 이루어질 수 있도록 더 객체지향적으로 사용할 수 있겠다..!
6. Console의 null발생 예외 삭제
7. Validation 클래스 삭제 -> 각 클래스마다 정규식 변수를 둠

2023-06-12 06:02 UTC, HandmadeCloud commented
두번째 커밋 : eb97e87
1. calculateType의 나눗셈 리뷰 아직 반영x -> calculate 메소드로 옮김
2. 종료 기능 처리 -> case 추가, console의 loop변수를 활용해 처리
3. .idea등 gitignore처리가 되었다고 생각했지만, 아직은 적절한 처리가 아니었다. 재수정 필요 -> 삭제 했지만, push이후 재확인 필요
4. Calculator의 조건문 정리 x -> 1번째 리뷰를 잘 이해하지 못해서 생긴 일, 수정완료

2023-06-12 06:04 UTC, HandmadeCloud commented on src/main/java/org/example/view/OutputView.java
> +    public void start(){
71583321f9672dbca02d6c09e70a9725e87d38db 에 반영

2023-06-12 06:05 UTC, HandmadeCloud commented on src/main/java/org/example/view/SelectTypeView.java
> +    private  int num;
71583321f9672dbca02d6c09e70a9725e87d38db 에 반영 ✅

2023-06-12 06:05 UTC, HandmadeCloud commented on src/main/java/org/example/view/SelectTypeView.java
> +    }
https://github.com/prgrms-be-devcourse/java-calculator/commit/71583321f9672dbca02d6c09e70a9725e87d38db 에 반영 ✅

2023-06-12 06:06 UTC, HandmadeCloud commented on src/main/java/org/example/view/OutputView.java
> +
https://github.com/prgrms-be-devcourse/java-calculator/commit/71583321f9672dbca02d6c09e70a9725e87d38db 에 반영 ✅

2023-06-12 06:06 UTC, HandmadeCloud commented on src/main/java/org/example/view/OutputView.java
> +        }
https://github.com/prgrms-be-devcourse/java-calculator/commit/71583321f9672dbca02d6c09e70a9725e87d38db 에 반영 ✅

2023-06-12 06:06 UTC, HandmadeCloud commented on src/main/java/org/example/repository/Records.java
> +
https://github.com/prgrms-be-devcourse/java-calculator/commit/71583321f9672dbca02d6c09e70a9725e87d38db 에 반영 ✅

2023-06-12 06:06 UTC, HandmadeCloud commented on src/main/java/org/example/domain/Console.java
> +            }
https://github.com/prgrms-be-devcourse/java-calculator/commit/71583321f9672dbca02d6c09e70a9725e87d38db 에 반영 ✅

2023-06-12 06:06 UTC, HandmadeCloud commented on src/main/java/org/example/repository/Records.java
> +    public static List<String> arithmeticRecords = new ArrayList<>();
https://github.com/prgrms-be-devcourse/java-calculator/commit/71583321f9672dbca02d6c09e70a9725e87d38db 에 반영 ✅

2023-06-12 06:06 UTC, HandmadeCloud commented on src/main/java/org/example/domain/CalculateType.java
> +    }
https://github.com/prgrms-be-devcourse/java-calculator/commit/71583321f9672dbca02d6c09e70a9725e87d38db 에 반영 ✅

2023-06-12 06:07 UTC, HandmadeCloud commented on src/main/java/org/example/domain/Console.java
> +            String option = inputView.selectWorks();
https://github.com/prgrms-be-devcourse/java-calculator/commit/71583321f9672dbca02d6c09e70a9725e87d38db 에 반영 ✅

2023-06-12 06:07 UTC, HandmadeCloud commented on src/main/java/org/example/domain/Console.java
> +            }
https://github.com/prgrms-be-devcourse/java-calculator/commit/71583321f9672dbca02d6c09e70a9725e87d38db 에 반영 ✅

2023-06-12 06:07 UTC, HandmadeCloud commented on src/main/java/org/example/domain/Console.java
> +            outputView.printRecords(Records.arithmeticRecords);
https://github.com/prgrms-be-devcourse/java-calculator/commit/71583321f9672dbca02d6c09e70a9725e87d38db 에 반영 ✅

2023-06-12 06:07 UTC, HandmadeCloud commented on src/main/java/org/example/domain/Console.java
> +            Records.arithmeticRecords.add(infixExpression.toString() + " = " + result);
https://github.com/prgrms-be-devcourse/java-calculator/commit/71583321f9672dbca02d6c09e70a9725e87d38db 에 반영 ✅

2023-06-12 06:07 UTC, HandmadeCloud commented on src/main/java/org/example/repository/Records.java
> +    public static List<String> arithmeticRecords = new ArrayList<>();
https://github.com/prgrms-be-devcourse/java-calculator/commit/71583321f9672dbca02d6c09e70a9725e87d38db 에 반영 ✅

2023-06-12 06:07 UTC, HandmadeCloud commented on src/main/java/org/example/view/SelectTypeView.java
> +    }
https://github.com/prgrms-be-devcourse/java-calculator/commit/71583321f9672dbca02d6c09e70a9725e87d38db 에 반영 ✅

2023-06-12 06:08 UTC, HandmadeCloud commented on src/main/java/org/example/view/InputView.java
> +        if(REGEX_EXPRESSION.matcher(expression).matches()){
eb97e87a0eab41f42a96152839f36ccad0378604

2023-06-12 06:09 UTC, HandmadeCloud commented on src/main/java/org/example/domain/Console.java
> +    }
https://github.com/prgrms-be-devcourse/java-calculator/commit/eb97e87a0eab41f42a96152839f36ccad0378604 에 반영 ✔️

2023-06-12 06:09 UTC, HandmadeCloud commented on src/main/java/org/example/domain/Calculator.java
> +                    calculateType.getPriority() < CalculateType.findBySymbol(operatorStack.peek()).getPriority()) {
https://github.com/prgrms-be-devcourse/java-calculator/commit/eb97e87a0eab41f42a96152839f36ccad0378604 에 반영 ✔️

2023-06-12 06:09 UTC, HandmadeCloud commented on src/main/java/org/example/domain/CalculateType.java
> +    });
https://github.com/prgrms-be-devcourse/java-calculator/commit/eb97e87a0eab41f42a96152839f36ccad0378604 에 반영 ✔️

2023-06-12 06:09 UTC, HandmadeCloud commented on src/main/java/org/example/domain/Validation.java
> +}
https://github.com/prgrms-be-devcourse/java-calculator/commit/eb97e87a0eab41f42a96152839f36ccad0378604 에 반영 ✔️

2023-06-12 06:09 UTC, HandmadeCloud commented on src/main/java/org/example/view/OutputView.java
> +        System.out.print("선택 : ");
https://github.com/prgrms-be-devcourse/java-calculator/commit/eb97e87a0eab41f42a96152839f36ccad0378604 에 반영 ✔️

2023-06-12 06:11 UTC, HandmadeCloud commented on src/main/java/org/example/domain/Calculator.java
> +                    calculateType.getPriority() < CalculateType.findBySymbol(operatorStack.peek()).getPriority()) {
https://github.com/prgrms-be-devcourse/java-calculator/commit/eb97e87a0eab41f42a96152839f36ccad0378604 에 반영 ✔️

2023-06-13 05:20 UTC, Jo-GyuHyeon requested changes
재현님 고생하셨습니다. 🙇 
커밋 메시지 내용과, 커밋 단위애 대해 고민 해보시면 좋을것 같아요.
관련된 내용은 따로 슬랙에서 공유 드렸기에 한번 고민 해주시면 좋을것 같아요.

리뷰 내용이 아직 많기에, 피드백 반영 까지 작업 후 리뷰 요청을 하면 어떨까 생각하고 있어요.

2023-06-13 05:20 UTC, Jo-GyuHyeon commented on src/main/java/org/example/Main.java
> +
메서드 첫줄은 개행을 제거 해는 것을 제안 드려요.

2023-06-13 05:20 UTC, Jo-GyuHyeon commented on src/main/java/org/example/domain/Console.java
> +            case GET_RECORD -> view.printRecords(Records.exportRecord());
switch 문 위,아래로 개행을 제거 해도 좋을것 같아요.

2023-06-13 05:20 UTC, Jo-GyuHyeon commented on src/main/java/org/example/view/SelectTypeView.java
> +        Integer workNum = Integer.valueOf(num);
SelectTypeView 의 num 도 숫자형 타입인데 혹시 파라미터 타입도 int 타입으로 변경 하여도 좋을것 같아요.
num 을 위해 변환 하는 것은 해당 메서드에서 꼭 필요한 행위 혹은 책임을 가질수 있을까? 라고 생각 해보시면 어떨까요?

2023-06-13 05:20 UTC, Jo-GyuHyeon commented on src/main/java/org/example/view/SelectTypeView.java
> +                .filter(stv -> stv.num == (workNum))
불필요한 괄호는 제거 하는 것이 좋은것 같아요.

2023-06-13 05:20 UTC, Jo-GyuHyeon commented on src/main/java/org/example/view/SelectTypeView.java
> +                .orElse(null);
null 을 리턴 한다면 Optional 을 이용해보는 것은 어떨까요?
리턴되는 타입은 명확한것이 좋을것 같아요.

해당 메서드에서 null 이 나올 수 있다는 불신을 갖기보다 명확이 알려주는 것이 좋은것 같아요.
그렇지 않으면 매번 메서드를 사용할때 마다 구현체를 확인해서 null 이 나올수 있는 가능성을 확인해야 해요.
(책임에 있어서 불확실성을 갖는다고 생각해요)

2023-06-13 05:20 UTC, Jo-GyuHyeon commented on src/main/java/org/example/domain/Calculator.java
> +            while (!operatorStack.isEmpty() && typePriority < expressionPriority) {
typePriority < expressionPriority 둘만 보았을땐 이해하기 어려운것 같아요.
둘다 격국 CalculateType 의 타입의 우선순위로 이해 하고 있어요. 의미 있는 네이밍을 하번더 고민 해볼까요?

2023-06-13 05:20 UTC, Jo-GyuHyeon commented on src/main/java/org/example/domain/Console.java
> +    private static boolean loop = false;
정적 변수로 선언 하는 이유는 무엇인가요?
loop 보다 의미 있는 네이밍은 어떨까요?

2023-06-13 05:20 UTC, Jo-GyuHyeon commented on src/main/java/org/example/view/View.java
> +    public String selectWork() {
selectWork -> select 가 조금더 자연스러운 네이밍인것 같아요.
다른 네이밍을 고려해도 좋아요.

2023-06-13 05:20 UTC, Jo-GyuHyeon commented on src/main/java/org/example/view/View.java
> +    }
if 문 조건을 return 값으로 바로 사용하게 되면 인덴트를 줄이고 가독성을 증가 시킨다고 생각해요.

2023-06-13 05:20 UTC, Jo-GyuHyeon commented on src/main/java/org/example/view/View.java
> +    }
if 문 조건을 return 값으로 바로 사용하게 되면 인덴트를 줄이고 가독성을 증가 시킨다고 생각해요.

2023-06-13 05:20 UTC, Jo-GyuHyeon commented on src/main/java/org/example/view/View.java
> +    }
예외 메시지와 return 값으로 기대 되는 것은 구분이 되어야 될것 같아요.

2023-06-13 05:20 UTC, Jo-GyuHyeon commented on src/main/java/org/example/domain/Calculator.java
> +            }
특정 연산, 조건에 대한 예외가 추가 될때마다 해당 로직에서 if 문이 증가 되면 혼란 스러울것 같아요.

2023-06-13 15:44 UTC, HandmadeCloud commented on src/main/java/org/example/view/SelectTypeView.java
> +        Integer workNum = Integer.valueOf(num);
e6d6a72bf7b622954804d68782a5f623f6bde7e7 에 반영

- 파라미터 타입을 int로 변경했습니다. 연관되는 view class의 select의 리턴 관련해서 자체 pr을 했는데, 아래 pr에서 설명드리겠습니다 !

2023-06-13 15:45 UTC, HandmadeCloud commented on src/main/java/org/example/view/SelectTypeView.java
> +                .filter(stv -> stv.num == (workNum))
https://github.com/prgrms-be-devcourse/java-calculator/commit/e6d6a72bf7b622954804d68782a5f623f6bde7e7 에 반영

2023-06-13 15:47 UTC, HandmadeCloud commented on src/main/java/org/example/view/SelectTypeView.java
> +                .orElse(null);
233733cebd170c873ac49b446c90ddfe3679c345 에 반영

❓ 질문
- returnType을 사용하게 되면서 Console 클래스에서 
selectOption(selectType.orElse(null)); 로 여기서 null처리를 해주었습니다. 최대한 간결하게 하기 위해서 이렇게 변경을 해주었는데, if문으로 null 여부를 확인해주는 것이 맞을까요?

2023-06-13 15:49 UTC, HandmadeCloud commented on src/main/java/org/example/domain/Calculator.java
> +            while (!operatorStack.isEmpty() && typePriority < expressionPriority) {
831f9fdf6e42a4a214e6345c3ddf5a10c6031c5e 에 반영

❓ 질문
- 상대적인 것 같아서 이런 식으로 변경했습니다.. 조금 더 좋은 표현이 있을까요?

2023-06-13 15:50 UTC, HandmadeCloud commented on src/main/java/org/example/domain/Console.java
> +    private static boolean loop = false;
2d7aa9492582b863ceb3cc9223d05d8b29f15d85 에 반영
- static 굳이 필요한 부분은 아니었던 것 같습니다..!

2023-06-13 15:51 UTC, HandmadeCloud commented on src/main/java/org/example/view/View.java
> +    public String selectWork() {
89858b6e41213fbc96bc4ace0c524179d274eac0 에 반영

❓ 질문
- select보다 더 자연스러운 네이밍을 생각해보는 게 좋을까요?

2023-06-13 15:52 UTC, HandmadeCloud commented on src/main/java/org/example/view/View.java
> +    }
8f14b1bfdb03a03f3515c39425cf30928bc93cd7 에 반영

2023-06-13 15:55 UTC, HandmadeCloud commented on src/main/java/org/example/view/View.java
> +    }
02dcaf5cc57f6cd0ec3f7b28f293419ad2a3d969 에 반영

❓ 질문
- 여기에서 에러를 던지게 했습니다. 의도하신 수정이 맞는 지 궁금합니다 !
 (형욱멘토님께 어떤 메소드가 어디에서 에러를 던지는 게 좋은 지, 프로그램이 중단되지 않고 지속되려면 어떻게 해야 하는지에 대해서 생각해보라는 조언을 들었습니다. 추가로 에러와 예외 checked/unchecked에 대해서 조금 더 공부를 해볼 계획입니다.)

2023-06-13 15:59 UTC, HandmadeCloud commented
#### 지금까지 받은 pr을 바탕으로 지금 제 코드에 어떤 부분이 문제가 있는지 자체적으로 pr을 진행해봤습니다

#### View ✔️ 
- select메소드에서  return 이 -1인 부분이 수정되야 함
- inputExpression에서 returna이 String인 점을 수정해야 함
- validateSelectioin에서 regex_select라고 해서 1,2,3을 설정했는데 마음에 들지 않음

#### Records ✔️ 
- private이라는 접근지정자를 썼지만, static을 사용하지 않아도 무방한지 -> 기록이 처음부터 생성되고 저장되어야한다는 생각에 static 사용

#### SelectTypeView ✔️ 
- findByNum 메소드에서 SelectypeView 삭제해도 될 것 같습니다.

#### CalculateType ✔️ 
- findBySymbol 이 static일 필요가 있는가?
- findBySymbol optional로 변경 필요

아직 놓치고 있거나 생각하지 못하고 있는 부분은 더 보완해 나가보도록 하겠습니다!

2023-06-13 19:17 UTC, Jo-GyuHyeon commented on src/main/java/org/example/Main.java
> +
@HandmadeCloud  말씀하셧던 부분이 저의 의도대로 이해해주신것 같아요.
개행을 적절히 잘 사용하면 구분감을 주기에 읽기 좋은것 같아요.

2023-06-13 19:19 UTC, Jo-GyuHyeon commented on src/main/java/org/example/view/View.java
> +    }
불필요한 주석을 제거 하면 더욱 좋을것 같아요.
(의도한 바가 맞아요)

2023-06-13 19:21 UTC, Jo-GyuHyeon commented on src/main/java/org/example/domain/Calculator.java
> +            }
의도한 바가 아닌것 같아요. 메서드를 분리 하기 보다 나누기에 대한 책임이 누구에게 있는지 파악 한 후 담당하도록 해주면 좋을것 같아요.

2023-06-13 19:24 UTC, Jo-GyuHyeon commented on src/main/java/org/example/view/OutputView.java
> +        System.out.print("선택 : ");
의도한 바가 아닌것 같아요. SelectTypeView 를 이용해 보면 어떨까요?

2023-06-13 19:37 UTC, Jo-GyuHyeon reviewed
안녕하세요 재현님 😸 
간단한 코드 리뷰들을 남겼어요. 
피드백 반영한것 까지 코드 수정한 후 리뷰 요청 처리 해주시면 좋을것 같아요.

2023-06-13 19:37 UTC, Jo-GyuHyeon commented on src/main/java/org/example/view/View.java
> +        System.out.print("선택 : ");
https://github.com/prgrms-be-devcourse/java-calculator/pull/160#discussion_r1228598329 댓글을 확인 해주세요.

2023-06-13 19:37 UTC, Jo-GyuHyeon commented on src/main/java/org/example/view/View.java
> +        int[] regex_select = {1, 2, 3}; // 형변환 시 이루어진 영향으로 추가, 1,2,3의 의미를 파악하기 어려워 개선 필요
SelectTypeView 의 열거 항목이 더 늘어날때 해당 코드도 수정해야 되지 않을까요?
혹시 영향을 줄일 수 있는 방법은 어떤것 기 있을까요?

2023-06-13 19:37 UTC, Jo-GyuHyeon commented on src/main/java/org/example/view/SelectTypeView.java
> +    public static Optional<SelectTypeView> findByNum(int workNum){
workNum 보다 여기서는 SelectTypeNum 이 어울리는 것 같아요.

2023-06-13 19:37 UTC, Jo-GyuHyeon commented on src/main/java/org/example/view/View.java
> +public class View implements Input,Output{
Input,Output 를 인터페이스로 만들고 View 에서 합친 이유가 무엇인가요? 어떠한 이점이 있나요?

2023-06-13 19:37 UTC, Jo-GyuHyeon commented on src/main/java/org/example/repository/Records.java
> +    }
Records 를 인스턴스화 하지 않고 static 으로 하는 이유는 무엇인가요??

2023-06-13 19:37 UTC, Jo-GyuHyeon commented on src/main/java/org/example/domain/Calculator.java
> +    }
해당 코드도 return 으로 줄일수 있을것 같아요.

2023-06-13 19:37 UTC, Jo-GyuHyeon reviewed
안녕하세요 재현님 😸 
간단한 코드 리뷰들을 남겼어요. 
피드백 반영한것 까지 코드 수정한 후 리뷰 요청 처리 해주시면 좋을것 같아요.

2023-06-14 00:28 UTC, HandmadeCloud commented on src/main/java/org/example/view/View.java
> +        System.out.print("선택 : ");
810808d5aea4408c079d9762ee5278d648a6f910 에 반영
- selectViewType을 활용해서 수정했습니다!

2023-06-14 00:29 UTC, HandmadeCloud commented on src/main/java/org/example/view/View.java
> +        int[] regex_select = {1, 2, 3}; // 형변환 시 이루어진 영향으로 추가, 1,2,3의 의미를 파악하기 어려워 개선 필요
9982ef91f32958081d8352462a8a355db68ad765 에 반영
- 마찬가지로 SelectViewType을 활용해 수정했습니다!

2023-06-14 00:30 UTC, HandmadeCloud commented on src/main/java/org/example/domain/Calculator.java
> +    }
66161e53e4177f1270f7edf366c53307952a1721 에 반영

2023-06-14 00:35 UTC, HandmadeCloud commented on src/main/java/org/example/repository/Records.java
> +    }
d766559cb5ce62bf3f1e7930a8634a904ab47730 에 반영
- records는 어플리케이션이 실행되면서 존재해야 할 것 같다고 생각해 사실 static을 사용했습니다.  초기에는 인스턴스화를 고민했었지만, 한번만 사용된다는 점에서 고민을 하다가 이렇게 결정을 하게 되었습니다..!
- 이 부분에 대해서는 확장가능성?을 기준으로 생각해야 하는 것인지 질문드리고 싶은 부분이 있습니다!

2023-06-14 00:45 UTC, HandmadeCloud commented on src/main/java/org/example/view/View.java
> +public class View implements Input,Output{
사실 변경에 유연하게 대처하기 위해 이렇게 만든 부분이 있었습니다! (곰튀김님 강의 참고)
기존에는 console에 input과 output 구현체를 그대로 의존하였습니다.
그러다보니 변경사항이 발생할 경우, 구현체를 직접 수정하다보니 결합도가 높다는 생각을 하게 되었습니다.
그래서  input과 output을 인터페이스로 만들어 추상체를 만들고, View 구상체로 새로 만들어 책임을 분리하는 방법으로 생각했습니다.
현재는 과제에서는 output과 input의 로직이 크게 늘어날 것 같다고 생각하지 않아 View가 input,output을 모두 상속받아 구현한 부분은 있습니다.

2023-06-14 00:58 UTC, HandmadeCloud commented on src/main/java/org/example/view/SelectTypeView.java
> +                .orElse(null);
https://github.com/prgrms-be-devcourse/java-calculator/commit/21efcc2ddedabe9eeeec0f91024cf44a59ff6bd2 에 재수정  selectOption 메소드에서 null값을 처리하도록 함

2023-06-14 00:58 UTC, Jo-GyuHyeon commented on src/main/java/org/example/repository/Records.java
> +    }
static 관련 하여 간단하게 링크 첨부만 해보아요. 🧚

https://dev-coco.tistory.com/175

https://unabated.tistory.com/m/1041

2023-06-14 01:03 UTC, HandmadeCloud commented on src/main/java/org/example/domain/Calculator.java
> +            }
이부분은 수정 전에 질문을 한번 더 드리고 싶습니다! @Jo-GyuHyeon 
고민을 해보니 나눗셈에 대한 책임은 CalculateType의 calculate메소드에 있다고 생각합니다.
그렇다면 calculate메소드 안에 내부 메소드를 만들어서 0 나눗셈문제를 해결하는 것이 좋을까요?

2023-06-14 01:22 UTC, Jo-GyuHyeon commented on src/main/java/org/example/view/View.java
> +        System.out.print("선택 : ");
@HandmadeCloud 단순히 순회만 한다면 stream 보다 향상된 for 문 (for each loop) 를 사용해보면 어떨까요?
stream 의 foreach 와 비교 하여 어떠한 차이가 있을까요?

2023-06-14 01:46 UTC, Jo-GyuHyeon commented on src/main/java/org/example/view/View.java
> +        int[] regex_select = {1, 2, 3}; // 형변환 시 이루어진 영향으로 추가, 1,2,3의 의미를 파악하기 어려워 개선 필요
Console.run() 에서도 SelectViewType 객체를 이용하고 있어요.
View, Console 두 객체에서 이용하기 보다 한곳으로 몰아줄수 있을것 같아요.

2023-06-14 02:32 UTC, Jo-GyuHyeon commented on src/main/java/org/example/domain/Calculator.java
> +            while (!operatorStack.isEmpty() && typePriority < expressionPriority) {
@HandmadeCloud 이전보다 더 좋은것 같은데요? 😄 
이전, 혹은 다음 연산자가 현재 연산자 보다 우선인가? 를 비교 하고 있는것 맞을까요???
그렇다면 이전, 다음, 현재? 라는 단어가 들어가는 건 어떨까요?

2023-06-15 02:36 UTC, Jo-GyuHyeon reviewed
간단하게 추가리뷰 드렸어요.
PR 설명에도 Read Me 에 사용하신 이미지도 사용하시고, 설명도 최신 반영 해주시면 좋을것 같아요.

2023-06-15 02:36 UTC, Jo-GyuHyeon commented on src/main/java/org/example/view/View.java
> +                        .forEach(view -> System.out.println(view.getNum() + " " + view.getOption()));
단순히 순회만 한다면 stream 보다 향상된 for 문 (for each loop) 를 사용해보면 어떨까요?
stream 의 foreach 와 비교 하여 어떠한 차이가 있을까요?

2023-06-15 02:36 UTC, Jo-GyuHyeon commented on src/main/java/org/example/view/View.java
> +    }
단순히 순회만 한다면 stream 보다 향상된 for 문 (for each loop) 를 사용해보면 어떨까요?
stream 의 foreach 와 비교 하여 어떠한 차이가 있을까요?

2023-06-15 02:36 UTC, Jo-GyuHyeon commented on src/main/java/org/example/domain/Console.java
> +            selectOption(selectType);
Optional 에 대한 분기 처리는 여기서 해주는 것이 더 적합하다고 생각해요.

2023-06-15 02:36 UTC, Jo-GyuHyeon commented on src/main/java/org/example/domain/Calculator.java
> +    private final Pattern REGEX_NUM = Pattern.compile("[0-9]+");
정적 변수로 사용 하는 것은 어떨까요?

2023-06-15 02:36 UTC, Jo-GyuHyeon commented on src/main/java/org/example/domain/Calculator.java
> +    }
실제로 계산(연산) 을 하는 곳에서 책임이 일어 나야 될것 같아요.
enum 생성자에 로직이 너무 늘어 나는 것을 우려 해서 고민 해보라고 했던 부분이였어요.
혹시 다른 방법은 없을까? 라는 고민을 유도 하고 싶었어요.
(지금도 고민을 한번 더 해보시고, 아니면 기존처럼 하셔도 좋을것 같아요.)

2023-06-15 02:40 UTC, Jo-GyuHyeon commented on src/main/java/org/example/domain/Console.java
> +            Optional<SelectTypeView> selectType = SelectTypeView.findByNum(option);
https://github.com/prgrms-be-devcourse/java-calculator/pull/160#discussion_r1228878458
해당 리뷰에 아직 반영이 안된것 같아요.

2023-06-15 06:09 UTC, HandmadeCloud commented on src/main/java/org/example/view/View.java
> +        System.out.print("선택 : ");
stream을 사용하면 가독성에 장점이 있습니다. 지금까지는 그 사실만 알고 함수형 프로그래밍 사용에 열을 올리면서 위와 같은 부분은 아직 파악을 못했던 것 같습니다. ✏️ 
이번에 공부를 해보니 stream보다 향상된 for문을 활용해야 하는 경우가 있었습니다.
1. stream에서 foreach를 사용할 경우 비효율이 발생한다.
 -> 최종연산으로 활용하는 것이라면 ok, 하지만 이마저도 효율적인 동작은 아니다
 2. foreach를 사용한다면 stream의 목적과는 맞지 않는다.
 -> foreach내부에 로직이 추가된다면, 동시성 보장도 어려워 지고 가독성이 떨어진다. 
 이런 두가지 단점을 알고 필요한 경우를 잘 생각해서 스트림을 사용해야겠다는 점을 배웠습니다 👍

2023-06-15 06:11 UTC, HandmadeCloud commented on src/main/java/org/example/view/View.java
> +        int[] regex_select = {1, 2, 3}; // 형변환 시 이루어진 영향으로 추가, 1,2,3의 의미를 파악하기 어려워 개선 필요
fe2622e265efc7ae5c3d8cf6f3175eb08b9bf9d3 에 반영
사실 이부분을 조금 생각하다가 하루가 지났던 것 같습니다
어떻게 해줘야하나 고민했는데 생각보다 쉬운 수정이었습니다. 객체를 사용하지 않도록 이번 pr에서 수정했습니다.

2023-06-15 06:13 UTC, HandmadeCloud commented on src/main/java/org/example/view/View.java
> +public class View implements Input,Output{
필요에 따라 판단할 줄 아는 능력이 필요한 것 같습니다.
Input, output이라는 정의는 항상 필요하고 변하지 않는다는 점을 생각하면 굳이 느슨한 결합을 만들 필요는 없었던 것 같습니다.

그리고 view도 비슷한 이유로 한 곳에  두 클래스의 로직을 넣으면 간단한 프로그램도 복잡하게 변할 수 있다는 점을 느낀 것 같습니다. 클래스를 나누는 데에도 명확한 자기만의 기준이 필요하다는 점을 배웠습니다 👍

2023-06-15 06:14 UTC, HandmadeCloud commented on src/main/java/org/example/view/View.java
> +                        .forEach(view -> System.out.println(view.getNum() + " " + view.getOption()));
74d04b8d0e784712bbeb4bc8d478ee3b50f4ce2b 에 반영
https://github.com/prgrms-be-devcourse/java-calculator/pull/160#discussion_r1230479759 에 코멘트를 달았습니다!

2023-06-15 06:14 UTC, HandmadeCloud commented on src/main/java/org/example/view/View.java
> +    }
https://github.com/prgrms-be-devcourse/java-calculator/commit/74d04b8d0e784712bbeb4bc8d478ee3b50f4ce2b 에 반영
https://github.com/prgrms-be-devcourse/java-calculator/pull/160#discussion_r1230479759 에 코멘트를 달았습니다!

2023-06-15 06:15 UTC, HandmadeCloud commented on src/main/java/org/example/domain/Console.java
> +            selectOption(selectType);
ffec117033aff88c4d4708583d53b95e154f05b6
생각해보니 여기서는 selectOption에게 불필요한 책임을 넘겼다는 사실을 알았습니다.
null 값이 들어갔는지 판단하는 과정에서 .get()메소드를 활용하는 방법을 다시 공부하면서 알게 되어서 해결했습니다 👍

2023-06-15 06:16 UTC, HandmadeCloud commented on src/main/java/org/example/domain/Calculator.java
> +    private final Pattern REGEX_NUM = Pattern.compile("[0-9]+");
83d8dfbbb3c8b2e4b4597bb5c0309a12c64ee5ad
다시 보니 커밋 메세지를 더 명확하게 작성하면 좋았겠다는 아쉬움이 있습니다.

2023-06-15 06:18 UTC, HandmadeCloud commented on src/main/java/org/example/domain/Calculator.java
> +    }
e77325f9506af6429b36d1d4ccf87e69a071f4f6
사실 위에서 해결 전 질문을 남겼었지만, calculate메소드에서 처리하는 것이 맞는 것 같아 메소드를 수정했습니다.
수정하면서 전체 로직에도 문제가 있었던 것 같아 문제가 있던 부분을 찾아 수정했습니다 :)
(고민의 결과가 충분히 의미있었습니다 감사합니다 🙇‍♂️ )

2023-06-15 06:21 UTC, HandmadeCloud commented on src/main/java/org/example/domain/Console.java
> +            Optional<SelectTypeView> selectType = SelectTypeView.findByNum(option);
fe2622e265efc7ae5c3d8cf6f3175eb08b9bf9d3 에 반영
https://github.com/prgrms-be-devcourse/java-calculator/pull/160#discussion_r1230481460
pr을 보내기 전 고민한 시간이 조금 길어져 한번 더 피드백을 주신 것 같습니다 ㅎㅎ
처음에는 View가 selectTypeView을 의존하는 것이 맞는지 생각했습니다. 하지만 console쪽에서 의존하는 것이 더 문제가 크다고 생각한 이후로 수정이 한결 쉬워졌습니다. 그림으로 정리해보면서 이 문제는 해결해나갈 수 있었던 것 같습니다 🙇‍♂️

2023-06-15 06:23 UTC, HandmadeCloud commented
**[6번쨰 PR]**
책임과 역할의 분리 + stream을 활용하는 기준 + 클래스를 분리하고 통합하는 기준에 대해 생각해볼 수 있는 시간이었습니다 ❗

2023-06-15 06:23 UTC, Jo-GyuHyeon commented on src/main/java/org/example/domain/Console.java
> +            selectOption(selectType);
isPresent(), get() 을 사용하기 보다 map(), else(), orElseThrow(),  ifPresentOrElse() 를 사용 해보면 어떨까요?

형욱님이 @HyoungUkJJang  주신 [Java Optional 바르게 쓰기 ](https://homoefficio.github.io/2019/10/03/Java-Optional-%EB%B0%94%EB%A5%B4%EA%B2%8C-%EC%93%B0%EA%B8%B0/) 를 자세히 보시면 좋을것 같아요.

2023-06-15 08:42 UTC, HandmadeCloud commented on src/main/java/org/example/domain/Console.java
> +            selectOption(selectType);
완전히 오해했다는 생각이 드네요...
orElse(null)에 대해서 좋은 표현 방법이 아니라는 생각을 가지고 있었습니다.

2023-06-15 09:33 UTC, Jo-GyuHyeon commented on src/main/java/org/example/view/View.java
> +    }
validateSelection() 은 의미가 없을것 같아요. (중복 효과가 있는것 같아요)

SelectTypeView.findByNum() 의 리턴 값은 Optional 이기에 조금더 Optional 스럽게 활용 하면 좋을것 같아요.
형욱님이 @HyoungUkJJang 주신 [Java Optional 바르게 쓰기 ](https://homoefficio.github.io/2019/10/03/Java-Optional-%EB%B0%94%EB%A5%B4%EA%B2%8C-%EC%93%B0%EA%B8%B0/)를 자세히 보시면 좋을것 같아요.

해당 메서드인 select() 의 리턴타입이 Optional 이여야 할까요?

2023-06-16 14:22 UTC, HandmadeCloud commented
**[7번째 마지막 PR]**
마지막으로 코멘트 주신 거 수정하고 테스트코드를 해보려다가 끝났습니다 ㅎㅎ
감사했습니다!

2023-06-26 12:12 UTC, merged