[4기 - 김민정] 1~2주차 과제: 계산기 구현 미션 제출합니다.
prgrms-be-devcourse/java-calculator pull request #162
Opened 2023-06-11 07:38 UTC by pushedrumex

## 📌 과제 설명 
계산기의 기본 연산인 덧셈과 뺄셈 기능을 추가

## 👩‍💻 요구 사항과 구현 내용 
switch문과 queue를 사용해서 덧셈과 뺄셈 기능 구현

## ✅ 피드백 반영사항  

## ✅ PR 포인트 & 궁금한 점

2023-06-11 20:41 UTC, ICCHOI requested changes
안녕하세요 민정님! 코멘트 남겼습니다 :)
아직 절차지향적인 느낌이 조금 강한데요, 하나하나씩 리팩토링 해보시죠!

2023-06-11 20:41 UTC, ICCHOI commented on src/main/java/Calculator.java
> +        int answer = basicCalculate(new ArrayDeque<>(List.of(problem.split(" "))));
입력된 문자열을 자른 후, 리스트로 바꾸고, 또 덱으로 바꾸는 거 군요?
요구사항이 조금만 변해도 코드가 바뀔 수 있어서 기능을 분리하는 편이 좋아보입니다.

2023-06-11 20:41 UTC, ICCHOI commented on src/main/java/Calculator.java
> +        }
앞에 validate를 진행하였기 때문에, 이 식은 잘 작동할 것 같아요.
그러나 calculate라는 기능이 validate와 강하게 결합되어, validate의 요구사항이 변하면 calculate의 로직도 변하게 되요.
그런 일을 피하려면 validate가 없더라도 calculate 자체로 하나의 기능을 수행할 수 있게 로직을 구현해야한다고 생각해요.

2023-06-12 08:16 UTC, pushedrumex commented on src/main/java/Calculator.java
> +        int result = Integer.parseInt(deque.removeFirst());
두 피연산자와 연산자를 받아 계산하는 로직으로 수정해보았습니다.

2023-06-12 13:18 UTC, ICCHOI approved these changes

2023-06-12 14:36 UTC, pushedrumex commented on src/main/java/Calculator.java
> +    }
1 + 12 + 5일 경우 deque = [1, +, 12, +, 5]를 저장하고 deque removefirst를 하면 answer에 1이들어갑니다. 이젠 deque에 남아있는 것들은 연산자 -> 피연산자 -> 연산자 .. 가 반복되므로 연산자와 피연산자를 꺼내면서 연산합니다

2023-06-13 09:35 UTC, pushedrumex commented
> ## 📌 과제 설명
> 계산기의 사칙연산 기능을 추가
> 
> ## 👩‍💻 요구 사항과 구현 내용
> * Calculator Adapter사용하여 Option별로 핸들러 호출
> * Calculate Handler에서는 Calculator Engine을 통해 사칙 연산에 해당하는 핸들러 호출
> 
> ## ✅ 피드백 반영사항
> ## ✅ PR 포인트 & 궁금한 점
> Calculator Adapter을 도입하여 재설계를 해봤습니다. 피드백 부탁드립니다..! 
<img width="739" alt="스크린샷 2023-06-13 오후 6 31 46" src="https://github.com/prgrms-be-devcourse/java-calculator/assets/97938489/194435e1-94f6-4035-bc3d-8803526d385b">

### 실행 과정
1. Calculator에서 옵션(1,2)을 입력 받고 Calculator Adapter를 통해 핸들러 호출
2. 계산 옵션(2)일 경우 해당 핸들러에서 파싱하고 Calculator Engine을 통해 기본 연산 수행
3. Calculator Engine에서는 연산자에 해당하는 Operation Handler를 호출하여 계산 수행
4. Calculator는 결과를 반환받고 출력

2023-06-13 13:06 UTC, devcourse-ray commented on src/main/java/calculator/adapter/CalculateHandler.java
> +            answer = result.orElseThrow(() -> new IllegalArgumentException(ErrorMessage.INVALID_OPERATOR));
여기도 재할당을 안하도록 하는 방법이 어떤게 있을까요?
Stream 을 잘 쓰면 불변을 보장하면서 가독성도 챙길 수 있어요

2023-06-13 13:17 UTC, pushedrumex commented on src/main/java/calculator/engine/CalculatorEngine.java
> +        throw new ArithmeticException(ErrorMessage.DIVISION_BY_ZERO);
```
if (o2 == 0) {
    throw new ArithmeticException(ErrorMessage.DIVISION_BY_ZERO);
}
return o1 / o2;
```
로 되고 언제 예외가 터지는지 명확하게 알 수 있을 것 같습니다!

2023-06-13 13:38 UTC, devcourse-ray commented on src/main/java/calculator/adapter/LookupHandler.java
> +    public String process() {
넵 그러면 보통 n개의 String이 조회되고 그걸 n개를 한 번에 잘 출력하는건 누구의 책임일까요?
조회를 했을 때 n개의 결과가 조회될 거라고 생각하고 해당 메소드를 실행했는데 n개의 String이 하나의 String으로 합쳐져서 반환될 걸 예상할 수 있을까요??

2023-06-13 13:41 UTC, devcourse-ray commented on src/main/java/calculator/engine/CalculatorEngine.java
> +        throw new ArithmeticException(ErrorMessage.DIVISION_BY_ZERO);
어제 예시를 들었던 것 처럼 if가 길어진다면 밑에서 throw를 보고 이 에러는 어떤 조건에서 발생하지? 하고 다시 위로 올라가서 조건을 봐야겠죠?
단순하게 생각하면서 봐도 막힘없이 쭉 읽히는게 가독성이 높은 코드라고 생각해요

2023-06-14 00:37 UTC, ICCHOI requested changes
안녕하세요 민정님! 코멘트 남겼습니다 ;)
Calculator Adapter와 Handler들의 관계가 요구사항과 너무 강하게 결합 되어 있다는 느낌을 받았어요.
LookUp Handler의 기능은 계산기가 아니더라도 재사용 할 수 있지 않을까요?

2023-06-14 00:37 UTC, ICCHOI commented on src/main/java/calculator/adapter/CalculatorAdapter.java
> +    CALCULATE("2", new CalculateHandler(new ConsoleInput()));
이런 로직이면 new CalculateHandler는 무조건 new ConsoleInput()을 사용해야하게 되어
CalculateHandler가 ConsoleInput에 강한 의존성을 가지게 되겠네요

2023-06-14 00:37 UTC, ICCHOI commented on src/main/java/calculator/adapter/CalculatorAdapter.java
> +    }
생성자를 통해서 CalculatorAdapter를 생성하지 않는 걸로 보이는데, 코드에서 생성자가 어떤 역할을 할 수 있을까요?

2023-06-14 00:37 UTC, ICCHOI commented on src/main/java/calculator/adapter/CalculatorAdapter.java
> +}
handle 메소드가 handler.process()와 강하게 결합 되어 있기 때문에, 단위 테스트를 작성하기 어려워 보여요

2023-06-14 00:37 UTC, ICCHOI commented on src/main/java/calculator/adapter/CalculateHandler.java
> +    private Input input;
입력에 대한 의존성이 CalculateHandler, Calculator등 여러 계층에서 사용 되고 있어요.
입력 처리가 변하면 CalculateHandler도 영향을 받겠네요

2023-06-14 00:37 UTC, ICCHOI commented on src/main/java/calculator/adapter/CalculateHandler.java
> +    }
parseRawProblem은 어떻게 테스트 할 수 있을까요?

2023-06-14 16:08 UTC, pushedrumex commented on src/main/java/calculator/adapter/CalculateHandler.java
> +            answer = result.orElseThrow(() -> new IllegalArgumentException(ErrorMessage.INVALID_OPERATOR));
```
    private int calculate(String[] problem) {
        int initNum = Integer.parseInt(problem[0]);
        return IntStream.range(0, problem.length)
                .filter(i -> i % 2 != 0)
                .reduce(initNum, (acc, next) -> CalculatorEngine.execute(acc, Integer.parseInt(problem[next+1]), problem[next])
                        .orElseThrow(() -> new IllegalArgumentException(ErrorMessage.INVALID_OPERATOR)));

    }
```

Stream을 사용해서 수정해보았습니다

2023-06-15 17:15 UTC, pushedrumex commented on src/main/java/calculator/adapter/CalculatorAdapter.java
> +    CALCULATE("2", new CalculateHandler(new ConsoleInput()));
input을 Calculator에서만 의존성을 갖도록 수정해보겠습니다!

2023-06-15 17:16 UTC, pushedrumex commented on src/main/java/calculator/adapter/CalculatorAdapter.java
> +    }
enum 인스턴스를 만들 때 사용됩니다!

2023-06-15 17:17 UTC, pushedrumex commented on src/main/java/calculator/adapter/CalculateHandler.java
> +    }
parse한 것을 리턴하도록 수정하면 테스트할 수 있을 것 같습니다!

2023-06-16 12:28 UTC, ICCHOI requested changes
민정님! 코멘트 남겼습니다.
후딱 살펴보시고 수정 진행하시면 될 것 같아요 :)
계산쪽의 로직이 전반적으로 이해하기 어려운 것 같아요 ㅠㅠ
로직을 만든 후, 테스트 코드로 검증하면서 로직을 점검해보는 건 어떨까요?

2023-06-16 12:28 UTC, ICCHOI commented on src/main/java/calculator/engine/CalculatorEngine.java
> +    DIV(Operator.DIV, (o1, o2) -> {
굳이 다른 클래스로 나눠야 했을까? 생각이 들어요. 이런 구조에서 Operator class는 어떤 객체라고 할 수 있을까요?

2023-06-16 12:28 UTC, ICCHOI commented on src/main/java/calculator/constant/ModelKey.java
> +    public static final String ANSWER = "answer";;
```suggestion
    public static final String ANSWER = "answer";
```

2023-06-16 12:28 UTC, ICCHOI commented on src/main/java/calculator/constant/Option.java
> +    public static final String CALCULATE = "2";
static final로 된 문자만 가지고 있고, 역할이나 행위가 없다면 객체지향이라고 할 수 있을까요?

2023-06-16 12:28 UTC, ICCHOI commented on src/main/java/calculator/vo/OptionVO.java
> +}
Option과 OptionVO를 분리한 이유를 알 수 있을까요?

2023-06-16 12:28 UTC, ICCHOI commented on src/main/java/calculator/handlermanager/CalculatorHandlerManager.java
> +    public final Map<String, CalculatorHandler> handlerMap = new HashMap<>();
option과 해당 동작들을 Map으로 관리하면 얻을 수 있는 이점이 있을까요?

2023-06-16 12:28 UTC, ICCHOI commented on src/main/java/calculator/vo/ProblemVO.java
> +    }
VO는 어떤 뜻을 가지고 있나요?

2023-06-16 12:28 UTC, ICCHOI commented on src/main/java/calculator/handler/CalculateHandler.java
> +        model.put(ModelKey.ANSWER, calculate(parseRawProblem(param.get(ParamKey.PROBLEM))));
한 줄에 너무 많은 정보를 담고 있어서, 해석하기 어려워요.
여러 줄이 되더라도 분리하는 편이 좋아보여요.

2023-06-16 12:28 UTC, ICCHOI commented on src/main/java/calculator/handler/CalculateHandler.java
> +    }
```suggestion

    }
```
줄 바꿈에 주의해주세요

2023-06-16 12:28 UTC, ICCHOI commented on src/main/java/calculator/handler/CalculateHandler.java
> +        Deque<String> deque2 = new ArrayDeque<>();
명시적인 네이밍을 사용해주세요

2023-06-16 12:28 UTC, ICCHOI commented on src/main/java/calculator/handler/CalculateHandler.java
> +    private String[] priorityCalculate(String[] problem) {
priorityCalculate는 어떤 기능을 하는 메서드인가요?

2023-06-16 12:28 UTC, ICCHOI commented on src/main/java/calculator/handler/CalculateHandler.java
> +                        .orElseThrow(() -> new IllegalArgumentException(ErrorMessage.INVALID_OPERATOR)));
basicCalculate는 어떤 로직으로 계산을 진행하고 있나요?

2023-06-16 12:28 UTC, ICCHOI commented on src/main/java/calculator/Calculator.java
> +        handlerManager.registerHandler(Option.CALCULATE, new CalculateHandler());
Option이 늘어날때마다 Handlers에 추가해줘야겠네요

2023-06-16 12:28 UTC, ICCHOI commented on src/main/java/calculator/Calculator.java
> +    }
마찬가지로 옵션이 늘어날때마다 메서드도 하나씩 늘어나겠네요

2023-06-16 12:52 UTC, devcourse-ray commented on src/main/java/calculator/Calculator.java
> +        handlerManager.registerHandler(Option.CALCULATE, new CalculateHandler());
여기 두 Handler는 Calculator 안에서 직접 생성하는 이유가 있을까요?

2023-06-16 12:52 UTC, devcourse-ray commented on src/main/java/calculator/Calculator.java
> +                        executeLookupHandler(param, model);
여기서 param 은 어떤 값인가요?

2023-06-16 12:52 UTC, devcourse-ray commented on src/main/java/calculator/constant/Operator.java
> +}
enum 안에 값을 다시 따로 정의한 이유가 있나요?

2023-06-16 12:52 UTC, devcourse-ray commented on src/main/java/calculator/engine/CalculatorEngine.java
> +    private final BiFunction<Integer, Integer, Integer> handler;
fyi
BinaryOperator 라는 것도 있어용

2023-06-16 12:52 UTC, devcourse-ray commented on src/main/java/calculator/engine/CalculatorEngine.java
> +    }
value 조회와 실행 두 가지 역할이 들어가있어요

2023-06-16 12:52 UTC, devcourse-ray commented on src/main/java/calculator/handler/CalculateHandler.java
> +        model.put(ModelKey.ANSWER, calculate(parseRawProblem(param.get(ParamKey.PROBLEM))));
외부에서 받아온 model 을 수정하게되면 값을 예상하기 어려워져요

2023-06-16 12:52 UTC, devcourse-ray commented on src/main/java/calculator/handler/CalculateHandler.java
> +        return deque2.stream().toArray(String[]::new);
deque API 를 더 살펴보세요

2023-06-16 12:52 UTC, devcourse-ray commented on src/main/java/calculator/handler/CalculateHandler.java
> +            String temp = deque1.removeFirst();
변수명도 신경써주세요

2023-06-16 12:52 UTC, devcourse-ray commented on src/main/java/calculator/vo/OptionVO.java
> +public class OptionVO {
suffix가 꼭 붙어야할까요?

2023-06-16 14:32 UTC, pushedrumex commented on src/main/java/calculator/vo/ProblemVO.java
> +    }
VO는 값을 지닌 객체이고 특징이은 불변성, 값 동등성이 있으며 유효성 검사를 통해 값의 유효성을 체크하고 객체를 생성합니다

2023-06-16 14:33 UTC, pushedrumex commented on src/main/java/calculator/handler/CalculateHandler.java
> +    private String[] priorityCalculate(String[] problem) {
곱셈과 나눗셈 연산을 먼저 해주는 메서드입니다

2023-06-16 15:01 UTC, pushedrumex commented on src/main/java/calculator/handler/CalculateHandler.java
> +                        .orElseThrow(() -> new IllegalArgumentException(ErrorMessage.INVALID_OPERATOR)));
덧셈과 뺄셈만 존재하는 식을 계산해주며 초기값인 initNum에 값을 더하거나 빼면서 계산합니다

2023-06-16 15:03 UTC, pushedrumex commented on src/main/java/calculator/Calculator.java
> +        handlerManager.registerHandler(Option.CALCULATE, new CalculateHandler());
외부에서 등록하여 Calculator가 핸들러 구현체를 알 수 없도록 해보겠습니다

2023-06-16 15:04 UTC, pushedrumex commented on src/main/java/calculator/Calculator.java
> +                        executeLookupHandler(param, model);
핸들러에게 필요한 데이터를 넘겨주는 역할입니다

2023-06-16 15:05 UTC, pushedrumex commented on src/main/java/calculator/engine/CalculatorEngine.java
> +    }
조회하는 로직을 따로 빼보겠습니다!

2023-06-16 15:11 UTC, pushedrumex commented on src/main/java/calculator/vo/OptionVO.java
> +}
vo의 유효성을 검사하고 값을 보관하기 위해 따로 생성했습니다

2023-06-17 16:16 UTC, merged