[4기 - 김민희] 1~2주차 과제 : 계산기 구현 미션 제출합니다.
prgrms-be-devcourse/java-calculator pull request #176
Opened 2023-06-12 18:54 UTC by KimMinheee

## 📌 과제 설명 
- 우선 과제 코드 먼저 올리고 리뷰 받아야 할 것 같아 구현 후 pr 올렸습니다. 테스트코드는 빠른 시일 내 작성해 추가하도록 하겠습니다!

### 요구사항
- 콘솔로 구현입니다.(스윙으로 구현하시는 분들 계실까봐) 
- 객체지향적인 코드로 계산기 구현하기
    - [x]  더하기
    - [x]  빼기
    - [x]  곱하기
    - [x]  나누기
    - [x]  우선순위(사칙연산)
- [ ]  테스트 코드 구현하기
- [x]  계산 이력을 맵으로 데이터 저장기능 만들기
    - 애플리케이션이 동작하는 동안 데이터베이스 외에 데이터를 저장할 수 있는 방법을 고안해보세요.
- [x] (선택) 정규식 사용

## 👩‍💻 요구 사항과 구현 내용 

[Feat : 메뉴 입력 기능 구현] 
- 존재하는 메뉴를 출력 후 사용자가 menu를 입력할 수 있도록 하는 기능을 구현했습니다. Menu는 Enum클래스로 작성하였고 3을 입력하면 종료하도록 임의의 메뉴를 추가했습니다.

[Feat : 메뉴 입력 예외 처리] / [Feat : 식 입력 예외 처리 추가]
- 정수인지 여부와 메뉴의 값이 1,2,3 중 하나인지 확인하는 작업을 추가했습니다. 
- 계산식 공백 처리 & 정수(0-9), 사칙연산(+,-,*,/)로 구성되었는지 확인하는 작업을 추가했습니다. 

[Feat : 중위 표기식 -> 후위 표기식으로 변환 함수 구현] / [Feat : 후위 표기식 계산하여 정수형 변수 반환]
1. 중위 표현식 -> 후위 표현식으로 변환
2. 후위 표현식을 이용해 사칙연산 계산

[Feat : 계산 결과 repository에 저장]
- db는 Map<Integer,CalculatorDto>로 map의 key값은 pk 형식의 integer가 들어가고, value에 CalculatorDto(식,정답)이 들어가도록 구현했습니다. 
- IdGenerator 클래스를 활용해 저장할 때 마다 key 값 +1이 되도록 구현했습니다. 

[Feat : 조회(메뉴1)시 기록된 전체 데이터 출력 기능 구현]
- repository에서 List<CalculatorDto> 반환하는 findAll()함수를 구현했습니다.
- Service에서 repository의 findAll() 함수 사용하는 getHistories() 함수를 구현했습니다.

## ✅ PR 포인트 & 궁금한 점 
- 최대한 MVC 구조를 가져가려고 노력해봤는데 적절히 나눠진 건지 궁금합니다!
- 예외 처리를 할 때 throw 하면 try-catch로 잡아서 종료하지 않고 다시 입력받는 방식으로 구현했는데 이 방법이 적절한 방법인지, 더 나은 방법이 있는지 궁금합니다!
- repository에 저장할 때 Map의 value 값으로 CalculatorDto클래스를 만들어 저장하도록 했습니다. 이때 클래스명이 CalculatorDto로 해도 적절한 방법일까요?(이 클래스는 추후에 출력시에도 사용합니다)
- 제가 할 수 있는 한 책임을 나눠보려고 했는데 Util패키지의 클래스들을 이런 방식으로 나누는 것이 맞는지 고민됩니다. OOP적인 설계측면에서 개선해야할 점과 조언을 받고 싶습니다 :)

2023-06-12 22:03 UTC, JoosungKwon reviewed
민희님 고생 많으셨습니다~! 👍 리뷰 확인하고 테스트 마무리해주시면 될 것 같습니다~~ 😄

> 예외 처리를 할 때 throw 하면 try-catch로 잡아서 종료하지 않고 다시 입력받는 방식으로 구현했는데 이 방법이 적절한 방법인지, 더 나은 방법이 있는지 궁금합니다!

- 요구 사항에 따라 다를 것 같습니다! 다만, 이번 과제의 경우 구체적인 요구사항이 나와 있지 않기 때문에 사용자 입장에서 고려해보시면 어떤 방식이 좋을 지 고민해보셨으면 좋겠습니다~!!

> 이때 클래스명이 CalculatorDto로 해도 적절한 방법일까요?(이 클래스는 추후에 출력시에도 사용합니다)
- 좀 더 명확하게 인지할 수 있는 이름이면 더 좋을 것 같아요!!

> 제가 할 수 있는 한 책임을 나눠보려고 했는데 Util패키지의 클래스들을 이런 방식으로 나누는 것이 맞는지 고민됩니다. 

- 보통 프로젝트 진행시 여러 클래스에서 공통적으로 사용되는 메서드 중에 관련된 메서드들끼리 모아서 클래스로 만드는 경우를 Utility Class라고 합니다!

- 유틸성 클래스를 두면 중복 코드를 제거할 수 있다는 장점이 있지만 유지보수하기 어렵기 때문에 객체지향적이라고 보기 어렵습니다! 장단점을 공부해보시고 적절한 활용방안을 좀 더 고민해보시면 좋을 것 같습니다!! 

만약 어려움을 느끼신다면 주변 동료나 멘토님들께 물어봐도 좋습니다~~😄

2023-06-12 22:03 UTC, JoosungKwon commented on src/main/java/com/programmers/service/CalculatorService.java
> +        int result = CalculatorHelper.calculateExpression(postfixExpression);
`CalculatorHelper`를 왜 Static으로 하셨는지 궁금합니다! 어떤 장단점이 있다고 생각하세요?

2023-06-13 03:54 UTC, graygreat requested changes
안녕하세요 민희님 :)
과제 하느라 고생하셨습니다 💯 
많이 고민하신게 코드에 보이네요!

질문 남겨주신 것에 대한 답을 해보자면,
> 최대한 MVC 구조를 가져가려고 노력해봤는데 적절히 나눠진 건지 궁금합니다!

패키지는 잘 나눠져있는데, 객체 자체를 잘 나눴는지에 대한건 아직 부족한 것 같습니다.
특정 객체는 너무 많은 역할을 하고 있다고 생각이 들어요.
역할과 책임에 대해 생각해보시고 다시 한번 리팩토링 해보면 좋을 것 같아요.

> 예외 처리를 할 때 throw 하면 try-catch로 잡아서 종료하지 않고 다시 입력받는 방식으로 구현했는데 이 방법이 적절한 방법인지, 더 나은 방법이 있는지 궁금합니다!

주성님이 말씀주신대로 try-catch 안에서 다시 시작을 하고 있는 방식은 좋지 않습니다.
더 좋은 방법은 없을까 고민해보시면 좋을 것 같아요.

> repository에 저장할 때 Map의 value 값으로 CalculatorDto클래스를 만들어 저장하도록 했습니다. 이때 클래스명이 CalculatorDto로 해도 적절한 방법일까요?(이 클래스는 추후에 출력시에도 사용합니다)

직역하면 계산기dto인데, 정확히 어떤 의미를 나타내는지는 잘 모르겠어요.
하지만 어떤 느낌인지는 알 것 같기 때문에 큰 문제는 없을 것 같지만, 더 좋은 네이밍이 없을까? 고민해보는 것도 좋을 것 같습니다.
추가로 dto를 만드신 이유가 무엇일까요?

> 제가 할 수 있는 한 책임을 나눠보려고 했는데 Util패키지의 클래스들을 이런 방식으로 나누는 것이 맞는지 고민됩니다. 

Util 클래스의 목적이 무엇일까요?
IdGenerator는 util성 클래스의 역할을 하지 않고 있는 것 같아요.

> OOP적인 설계측면에서 개선해야할 점과 조언을 받고 싶습니다 :)

코드를 짤 때, 내 코드가 앞으로 어떻게 확장할 수 있을까?를 생각해보시면 좋을 것 같아요.
현재 구조에서 갑자기 기획자가 console이 아닌 ui를 통해서 받아야한다고 하면 민희님의 현재 구조에서 굉장히 많은 코드를 고쳐야할 것 같아요.
추가로 메모리에 저장하는게 아닌 db에 저장해야한다고 하면 그 또한 많은 변경을 해야겠죠.
변경에 대해서 취약한 코드를 작성하고 있는 것 같아서 객체지향의 특성을 잘 생각해보시고 리팩토링 해보면 좋을 것 같습니다.


추가로 몇 가지 궁금한 게 있습니다. 답변 해주시면 감사하겠습니다.
* 현재 요구사항과 구현 내용을 보면 커밋 단위로 적어주신 것 같은데, 커밋이 많아지면 해당 내용들을 다 적을 수 있을까요? 절대 다 적지 못하겠죠... 그렇다면 어떤 식으로 요구사항을 작성해보는게 좋을까요?

* 민희님이 생각하시는 객체지향에서의 역할과 책임은 무엇이라고 생각하시나요?

2023-06-13 03:54 UTC, graygreat commented on src/main/java/com/programmers/Main.java
> +        CalculatorController controller = new CalculatorController(new CalculatorService(new CalculatorRepository()));
개발을 할 때, 오해하는 것 중 하나가 무조건 라인을 짧게 가져가면 좋다. 인 것 같아요.
지금처럼 생성자 파라미터 안에 객체 생성, 생성자 파라미터 안에 객체 생성 하면 가독성이 안좋아 보여요!
적절한 변수를 사용해서 수정해주시면 좋을 것 같습니다.

2023-06-13 03:54 UTC, graygreat commented on src/main/java/com/programmers/controller/CalculatorController.java
> +            if (menu.isHistory()) {
객체에게 물어보는 방식 좋네요 👍

2023-06-13 03:54 UTC, graygreat commented on src/main/java/com/programmers/domain/Menu.java
> +        if (this.num == 1) return true;
가독성 측면에서 중괄호를 사용해주시는게 좋을 것 같아요.

2023-06-13 03:54 UTC, graygreat commented on src/main/java/com/programmers/domain/Menu.java
> +        return Arrays.stream(Menu.values()).filter(m -> m.num == num).findAny().get();
stream 사용할 때, 한 라인에 . 하나만 있는게 좋습니다~

2023-06-13 03:54 UTC, graygreat commented on src/main/java/com/programmers/repository/CalculatorRepository.java
> +    private final Map<Integer, CalculatorDto> calculatorRepository = new LinkedHashMap<>();
LinkedHashMap을 사용하신 이유가 있으실까요?
HashMap과 LinkedHashMap의 차이는 무엇인가요?

2023-06-13 03:54 UTC, graygreat commented on src/main/java/com/programmers/repository/CalculatorRepository.java
> +    private final IdGenerator idGenerator = new IdGenerator();
현재 IdGenerator가 매번 객체 생성이 되고 1로 초기화 되는 것 같아요.
그렇게 여러명의 유저가 사용할 때, id 값이 중복될 수 있지 않을까요?

2023-06-13 03:54 UTC, graygreat commented on src/main/java/com/programmers/service/CalculatorService.java
> +public class CalculatorService {
CalculatorService를 만드신 이유가 무엇일까요?

2023-06-13 03:54 UTC, graygreat commented on src/main/java/com/programmers/service/CalculatorService.java
> +
불필요한 개행

2023-06-13 03:54 UTC, graygreat commented on src/main/java/com/programmers/util/CalculatorHelper.java
> +        for (String token : tokens) {
현재 depth가 2인데, 1로 줄여볼 수 없을까요?
(depth가 2라는 얘기는, for문 안에 if문이 있다는 얘기입니다. for문만 있으면 1)

2023-06-13 03:54 UTC, graygreat commented on src/main/java/com/programmers/util/CalculatorHelper.java
> +public class CalculatorHelper {
CalculatorHelper 객체 이름이 명확하지 않은 것 같아요.
계산기 도우미? 같은 것이 필요할까 싶네요.

2023-06-13 03:54 UTC, graygreat commented on src/main/java/com/programmers/util/CalculatorHelper.java
> +        String[] tokens = postfix.split("");
현재는 1+2+3 이런 식으로 데이터가 들어올텐데 어느 날 기획자가 "1 + 2 + 3 으로 입력을 바꿔주시죠!" 라고 한다면, 
민희님 동료 분들은 어떤 파일을 젤 먼저 볼 것 같으신가요?

2023-06-13 03:54 UTC, graygreat commented on src/main/java/com/programmers/util/CalculatorHelper.java
> +    public static int performOperation(String operator, int operand1, int operand2) {
해당 메소드는 따로 분리해보는게 낫지 않을까요?

2023-06-13 03:54 UTC, graygreat commented on src/main/java/com/programmers/view/Input.java
> +        if (!Validator.check123(menuNum)) {
check123은 무슨 의미인지 모르겠네요.

2023-06-13 03:54 UTC, graygreat commented on src/main/java/com/programmers/view/Input.java
> +public class Input {
Input 클래스의 역할이 무엇인가요?

2023-06-13 06:05 UTC, KimMinheee commented on src/main/java/com/programmers/repository/CalculatorRepository.java
> +    private final IdGenerator idGenerator = new IdGenerator();
프로그램을 실행하는 순간 db에 값이 저장될 때 자동으로 id가 1씩 증가하는 방식 구현하기 위해 위와 idGenerator를 작성했습니다!
여러명의 유저가 사용할 때를 고려하여 코드를 작성하는 부분을 놓쳤던 것 같습니다. 이 부분 고민해보고 코드 수정해보겠습니다 :)

2023-06-13 06:07 UTC, KimMinheee commented on src/main/java/com/programmers/util/Converter.java
> +            else {
else 지양해야하는데 이 부분 놓쳤던 것 같습니다! if(Character.isDigit()) 활용하여 코드 수정해보겠습니다. 감사합니다!!

2023-06-13 06:45 UTC, KimMinheee commented on src/main/java/com/programmers/service/CalculatorService.java
> +        int result = CalculatorHelper.calculateExpression(postfixExpression);
CalculatorHelper의 경우 '후위 표기식을 계산'하는 메소드들을 구현했습니다!
CalculatorHelper 클래스는 필드, 속성, 상태값이 따로 존재하지 않아 method를 Static으로 구현해 바로 함수만 호출하기 위해 Static을 사용했습니다. 

Static을 사용하지 않고 클래스의 객체를 생성한다면 특정 객체의 상태나 데이터를 처리하는데 동시에 다룰 수 있을 것 같습니다. 
Static을 사용한다면 객체의 상태에 의존하지 않는 독립적인 기능을 제공할 때 유리합니다.
다만 Static은 전역변수로 상태를 공유하기때문에 다른 메소드에 영향을 주거나 다중 스레드 상황에서 유의하여 사용해야 할 것 같습니다!!

2023-06-13 06:46 UTC, KimMinheee commented on src/main/java/com/programmers/Main.java
> +        CalculatorController controller = new CalculatorController(new CalculatorService(new CalculatorRepository()));
한 줄에 깔끔하게 하려다 보니 너무 중첩되어 있는 것 같네요..!
객체 생성하여 생성자 파라미터 안에 넣는 방식으로 코드 수정하도록 하겠습니다 :)

2023-06-13 06:54 UTC, KimMinheee commented on src/main/java/com/programmers/view/Input.java
> +public class Input {
메뉴 번호, 표현식을 입력 받는 함수를 구현한 클래스입니다.
계산기 실행 시 입력에 관한 책임을 가지는 클래스가 필요할 것 같아 구현했습니다!

2023-06-13 06:58 UTC, KimMinheee commented on src/main/java/com/programmers/view/Input.java
> +        if (!Validator.check123(menuNum)) {
제가 생각했던 계산기서비스의 메뉴는 1(조회), 2(계산), 3(종료) 3가지로 구성되어 있어 이 외의 메뉴가 입력되었는지 확인하기 위해 구현한 메소드 입니다!
메소드 명이 한 눈에 이해하기엔 모호한 부분이 있는 것 같습니다! 적절한 메소드명으로 수정해보겠습니다 :)

2023-06-13 07:04 UTC, KimMinheee commented on src/main/java/com/programmers/util/CalculatorHelper.java
> +public class CalculatorHelper {
CalculatorManager와 CalculatorHelper와 고민하다가 CalculatorHelper를 선택했습니다..!
혹시 더 좋은 클래스명이 있을까요?

2023-06-13 07:07 UTC, KimMinheee commented on src/main/java/com/programmers/service/CalculatorService.java
> +public class CalculatorService {
계산기의 두 가지 기능 (조회, 계산)에 관해 controller에서 실행하는 함수를 작성하기 위해 위와 같이 CalculatorService를 만들었습니다!

2023-06-13 07:09 UTC, KimMinheee commented on src/main/java/com/programmers/util/Converter.java
> +    public static String convertToPostFix(String infix) {
넵! converToPostFix의 내 코드들을 적절하게 메소드로 분리하면 된다고 이해했는데 제가 이해한게 맞을까요:)?

2023-06-13 16:33 UTC, JoosungKwon commented on src/main/java/com/programmers/service/CalculatorService.java
> +        int result = CalculatorHelper.calculateExpression(postfixExpression);
만약, 후위 표기식이 아닌 방식으로 계산해야하는 요구사항이 주어지면 어떻게 될까요?

2023-06-16 17:10 UTC, JoosungKwon reviewed
민희님 고생 많으셨습니다~!!! 👍

리뷰 확인하시고 원하실 때 머지하셔도 좋습니다~

> IdGenerator 클래스가 Util에 속하는게 맞는지?
-> 코멘트 남겨주셔서 고민해봤는데 저는 repository 패키지에 넣기에는 DB 관련 기능과 거리가 멀고 단순히 숫자가 증가하는 기능만 가지고 있는 클래스라 Util 패키지에 유지하였습니다. 혹시 IdGenerator는 일반적으로 어떻게 관리하는지 궁금합니다!:)

- 저는 `IdGenerator` 클래스가 필요한 이유를 잘 모르겠습니다..😢  보통은 DB의 Auto Increment 기능을 사용하기 때문에 따로 관리하지 않습니다! 

- 혹시 메서드 내에서 일반적으로 증가시키지 않으시는 이유가 있나요? 만약, 여러 사용자를 고려하셨다면 유틸 클래스에 있어도 괜찮다고 생각이 들지만 동시성에 대한 고려가 필요할 것 같습니다! 

> 현재 depth가 2인데, 1로 줄여볼 수 없을까요? (depth가 2라는 얘기는, for문 안에 if문이 있다는 얘기입니다. for문만 있으면 1)
-> 이 부분을 고민해봤는데 아직 해결하지 못했습니다. split()하여 글자를 돌며 진행하는 방식을 생각하고 코드를 작성했는데 이 부분을 더 클린하게 개선할 수 있는 방법이 있을까요?

- 리뷰에 남겼습니다~ 정답은 절대 아니고 이런 방식으로도 생각해볼 수 있구나 정도로만 참고만 해주세요!

> try-catch문 의  catch 내에서 함수를 재 호출 하면 StackOverFlow 발생 가능성 고려
->상태 변수(boolean)을 이용해 while문으로 수정해 보았습니다. 이 방법은 적절한 방법인지 궁금합니다

- 방법 자체에는 문제가 없다고 느껴집니다! 다만 중복을 어떻게 제거할 수 있을지 생각해보시면 좋겠습니다. 통합적으로 처리할 수 있을 것 같습니다~😄

2023-06-16 17:10 UTC, JoosungKwon commented on src/main/java/com/programmers/util/CalculatorProcessor.java
> +    }
```suggestion
    public static int calculateExpression(String postfix) throws ArithmeticException {

        String[] tokens = postfix.split("");

        for (String token : tokens) {
            //연산자
            pushOperator(token);
            //숫자
            pushOperands(token);
            // 우선 순위 연산
            higherPriorityCalculate();
        }
        //남은 일반 연산
        lowerPriorityCalculate();

        return operands.pop();
    }

    private static void lowerPriorityCalculate() {
        while (!operators.isEmpty()) {
            int result = calculate();
            operands.push(result);
        }
    }

    private static void higherPriorityCalculate() {
        while (isHigherPriorityInStack()) {
            int result = calculate();
            operands.push(result);
        }
    }

    private static boolean isHigherPriorityInStack() {
        return !operators.isEmpty() && Operator.isHigherPriority(operators.peek());
    }

    private static void pushOperands(String token) {
        if (Validator.isInteger(token)) {
            operands.push(Integer.parseInt(token));
        }
    }

    private static void pushOperator(String token) {
        if (Validator.isOperator(token)) {
            Operator operator = Operator.getOperator(token);
            operators.push(operator);
        }
    }
```

이게 맞는지 잘 모르겠지만 메서드로 한번 분리해봤습니다!

2023-06-21 10:08 UTC, JoosungKwon commented
@KimMinheee 
안녕하세요 민희님 더이상 커밋이 없어서 리팩터링이 끝났다고 판단하여 해당 PR은 머지하도록 하겠습니다!! 😄
지금까지 과제하시느라 고생많으셨습니다 👍👍 앞으로도 지금처럼 화이팅하시길 바랍니다~!!

2023-06-21 10:08 UTC, merged