[4기 - 박세영] 1~2주차 과제 : 계산기 구현 미션 제출합니다.
prgrms-be-devcourse/java-calculator pull request #177
Opened 2023-06-13 03:34 UTC by SY97P

## 📌 과제 설명 
* `Calculator` : 모든 작업 요청, 결과가 이뤄지는 클래스
* `Validator` : 검증 인터페이스
* `Converter` : 후위변환 인터페이스
* `Computer` : 계산 인터페이스
* `Historian`   : 계산 기록, 출력 클래스
* `Input` : 입력 인터페이스
* `Output` : 출력 인터페이스
* `Operator` : 연산자 관련 enum 클래스
* `InvalidInputException` : 표현식 검증 Exception 클래스

![diagram](https://github.com/prgrms-be-devcourse/java-calculator/assets/54990890/af5e8512-35ec-4953-88ec-517d6a28d03f)
![seq_diagram](https://github.com/prgrms-be-devcourse/java-calculator/assets/54990890/e03e82fe-1167-43a2-8a6e-90efcfb7501d)

<hr/>
## 👩‍💻 요구 사항과 구현 내용 
- #### 기능 구현
- [x] 검증
    - [x] 정규식
    - [x] 소수점 -> (?:) 패턴으로 부적절한 소수점 숫자 버림
- [x] 계산 -> BiFunction 을 갖는 enum 클래스(Operator)
    - [x] 더하기 -> Operator.PLUS
    - [x] 빼기 -> Operator.MINUS
    - [x] 곱하기 -> Operator.MULTIPLY
    - [x] 나누기 -> Operator.DIVIDE (0 나누기 예외처리)
- [x] 우선순위 (사칙연산)
    - [x] 괄호 -> Operator enum 클래스에 괄호 추가(우선순위 적용)
- [x] 이력 -> HashMap 활용
    - [x] 계산이력 저장
    - [x] 계산이력 조회 -> 조회할 기록이 없는 경우 예외처리

- #### 테스트
- [x] 계산 기능
    - [x] 검증
    - [x] 우선순위
    - [x] 계산결과
- [x] 이력 기능
    - [x] 이력 저장
    - [x] 이력 조회

<hr/>
## ✅ 피드백 반영사항  

<hr/>
## ✅ PR 포인트 & 궁금한 점 
1. 테스트 코드
    * 테스트 완료한 메소드의 결과를 테스트해야할 메소드의 인자로 주어도 되는지 궁금합니다.
2. OOP 생활체조
    * App 클래스에서 Calculator 클래스로 필요한 모든 클래스를 주입했습니다.
      * Calculator 생명주기와 다른 클래스들의 생명주기가 같다고 판단해서 설계했는데, OOP를 위반하는 방식인지 궁금합니다.
    * 기능별로 클래스를 잘 분리했는지 궁금합니다.

2023-06-15 14:10 UTC, hongbin-dev requested changes
안녕하세요 세영님!
계산들에 들어갈 요소가 어떤게 있을지 생각하시면서 작성한 노력이 보이는군요..!

우선 io를 제외하면 모두 model 패키지에 들어갈 수 있을 거 같네요.
또 validator라는게 조금 모호한 상태같아요. 검증하는 객체인데, 검증도하고 변환도 하고 있어요.

수식 객체 -> 후위 수식객체 -> computer객체 -> computer 객체 연산 

이런식으로 객체를 나눠보는건 어떨까요?

2023-06-15 14:10 UTC, hongbin-dev commented on src/main/java/com/devcourse/engine/validator/SimpleValidator.java
> +        branketCount = 0;
이 값은 생성자에 들어가는게 더 일반적일거같네요~

validate인데 초기화하는 기능이 들어가는거 같아요

2023-06-15 14:10 UTC, hongbin-dev commented on src/main/java/com/devcourse/engine/historian/Historian.java
> +public class Historian {
```suggestion
public class Histories {

```
라는 이름은 어떨까요?

2023-06-15 14:10 UTC, hongbin-dev commented on src/test/java/engine/computer/ComputerTest.java
> +        String expression = "1 +2 * 5- 8/4";
@ParameterizedTest를 이용하시면 테스트코드의 중복을 많이 줄일 수 있겠네요!

2023-06-16 04:20 UTC, SY97P commented on src/main/java/com/devcourse/engine/Calculator.java
> +        label:
```

    @Override
    public void run() {
        label:
        while (true) {
            String menu = input.inputMenu();

            try {
                validMenuCheck(menu);

                switch (menu) {
                    case "0":
                        output.endGame();
                        break label;
```

switch 문에서 case "0"일 때 (EXIT 메뉴를 입력했을때)
while 문을 종료하는 break를 실행하고 싶어서 넣은 구문입니다.

향상된 switch문을 사용하거나,
while 조건을 바꿔서 제거해보겠습니다.

2023-06-16 08:47 UTC, SY97P commented on src/main/java/com/devcourse/engine/Calculator.java
> +        label:
향상된 switch문으로 변경하면서 label 문구를 제거했습니다.
switch문을 통해 리턴값을 받고 싶어서 yield 키워드를 사용했습니다.

2023-06-16 08:48 UTC, SY97P commented on src/main/java/com/devcourse/engine/Calculator.java
> +                        break;
Menu enum 클래스를 생성해서 사용자 입력을 받도록 했습니다.

향상된 switch 문으로 break; 키워드를 제거했습니다.

2023-06-16 08:49 UTC, SY97P commented on src/main/java/com/devcourse/engine/computer/SimpleComputer.java
> +        }
수정했습니다!

2023-06-16 08:50 UTC, SY97P commented on src/main/java/com/devcourse/engine/computer/SimpleComputer.java
> +                    )
stack.pop() 해서 얻은 결과는 `operand` 변수로 따로 추출했습니다.

또한, pop한 operand를 이용해서 stack에 넣는 해당 코드도 따로 메소드에 분리했습니다.

2023-06-16 08:51 UTC, SY97P commented on src/main/java/com/devcourse/engine/converter/Converter.java
> +}
의존성에 대해서 잘못 알고 있어서 그랬던 것 같습니다.
리팩토링하면서 불필요한 추상화라고 생각해 제거했습니다.

2023-06-16 08:52 UTC, SY97P commented on src/main/java/com/devcourse/engine/converter/PostfixConverter.java
> +                return;
모든 블록에 중괄호 추가했습니다!

2023-06-16 08:53 UTC, SY97P commented on src/main/java/com/devcourse/engine/historian/Historian.java
> +    }
`Histories` 클래스에서는 매개변수 그대로 Map에 저장하는 방식으로 변경했습니다.
말씀해주신 대로 `Histories` 클래스의 Map을 `OutputConsole` 클래스에서 가져와 원하는 형태의 문자열로 변경해서 출력하도록 수정했습니다.

2023-06-16 08:53 UTC, SY97P commented on src/main/java/com/devcourse/engine/io/Input.java
> +}
제거했습니다.

2023-06-16 08:53 UTC, SY97P commented on src/main/java/com/devcourse/engine/model/Operator.java
> +            throw new InvalidInputException(ZERO_DIVIDE);
감사합니다. 추가했습니다.

2023-06-16 08:54 UTC, SY97P commented on src/main/java/com/devcourse/engine/model/Operator.java
> +    CLOSE_BRANKET(")", 0, (b, a) -> 0.0);
operand가 아닌 것은 모두 operator로 보았습니다.
괄호는 enum에 추가하지 않고, 

 새로운 enum 클래스로 만들거나, 
그냥 String으로 비교하는게 좋을까요?

2023-06-16 08:55 UTC, SY97P commented on src/main/java/com/devcourse/engine/model/Operator.java
> +                .get(0);
NPE 발생하지 않도록 .orElse로 exception 날리도록 변경했습니다.

2023-06-16 08:55 UTC, SY97P commented on src/main/java/com/devcourse/engine/validator/SimpleValidator.java
> +        branketCount = 0;
생성자에서 초기화할 수 있도록 수정했습니다.

2023-06-16 08:55 UTC, SY97P commented on src/main/java/com/devcourse/engine/historian/Historian.java
> +public class Historian {
수정했습니다.

2023-06-16 08:56 UTC, SY97P commented on src/test/java/engine/computer/ComputerTest.java
> +        );
given, when, then 형태에 맞춰 수정했습니다.

다만, assertThrow 의 경우에는 
when이 then과 함께 있게 되는 것 같습니다.

2023-06-16 08:57 UTC, SY97P commented on src/test/java/engine/computer/ComputerTest.java
> +        String expression = "1 +2 * 5- 8/4";
@ParameterizedTest를 알고나니 막힌 속이 시원합니다.
효자 annotation인 것 같습니다.

2023-06-18 12:33 UTC, hongbin-dev commented on src/main/java/com/devcourse/engine/model/Operator.java
> +    CLOSE_BRANKET(")", 0, (b, a) -> 0.0);
우선 의미상 맞지 않는거 같고, 계산을 위한 `operatorFunction` 요 상태도 OPEN_BRANKET, CLOSE_BRANKET 에게는 불필요한 상태라고 생각했어요.

넵 우선 enum에서는 분리하는게 좋을 거 같습니다!

2023-06-18 12:35 UTC, hongbin-dev approved these changes
세영님 고생 많으셨습니다!
요기서 merge할게요!

2023-06-18 12:35 UTC, hongbin-dev commented on src/main/java/com/devcourse/engine/model/unit/Menu.java
> +    CALCULATE("2", "계산");
👍

2023-06-18 12:36 UTC, merged