Yiseull
prgrms-be-devcourse/java-calculator pull request #179
Opened 2023-06-13 06:43 UTC by Yiseull

## 📌 과제 설명

- OOP를 활용하여 사칙 연산 계산기를 구현하였습니다.
- 추가적인 테스트 코드나 예외 처리는 PR 올리고 이어서 할 예정입니다.

## 요구사항

- 콘솔로 구현입니다.(스윙으로 구현하시는 분들 계실까봐)
- 객체지향적인 코드로 계산기 구현하기
    - [ ]  더하기
    - [ ]  빼기
    - [ ]  곱하기
    - [ ]  나누기
    - [ ]  우선순위(사칙연산)
- [ ]  테스트 코드 구현하기
- [ ]  계산 이력을 맵으로 데이터 저장기능 만들기
- 애플리케이션이 동작하는 동안 데이터베이스 외에 데이터를 저장할 수 있는 방법을 고안해보세요.
- [ ] 정규식 사용

## 👩‍💻구현 내용

0️⃣ 공통 사항
- 확장성을 고려하여 Interface를 구현하였습니다.

1️⃣ 메뉴 선택 기능
- 메뉴에 관한 상태 & 행위를 한곳에서 관리하기 위하여 Enum 을 사용해하였습니다.
- 종료 메뉴까지 추가하였습니다.
- Map을 활용하여 Enum 요소를 캐싱하였습니다. 메뉴를 찾을 때 해시를 통해 한 번에 조회하고, 메뉴판을 만들 때 메뉴 순서대로 입력하기 위해 LinkedHashMap을 활용하였습니다.

2️⃣ 사칙연산 기능
- PostfixExpressionConverter 에서 후기표기법으로 전환하고 계산까지 하여 반환하는 걸로 구현하였습니다.

2️⃣ 계산 이력 저장 기능
- Repository에서 LinkedHashMap를 사용하여 계산 이력을 순서대로 저장하였습니다.

3️⃣ 계산 이력 조회 기능
- LinkedHashMap를 사용하여 계산 이력을 순서대로 저장하였습니다.

## 클래스 다이어그램

![image](https://github.com/prgrms-be-devcourse/java-calculator/assets/98391539/2e5dc4c7-a9a1-471c-9598-5d84c4ec21e5)

## ✅ PR 포인트 & 궁금한 점
- 객체를 책임에 따라 분리하려고 노력했는데 적절하게 나눈 것인지 궁금합니다 🧐
- 표기법마다 변환과 계산 과정이 다릅니다. 그래서 후에 사칙연산 계산을 전위표기법으로 확장하는 것을 고려하여 ExpressionConverter에서 변환과 계산까지 모두 하도록 설계하였습니다. 이렇게 설계를 하면서도 과연 계산을 ExpressionConverter에서 하는 것이 맞는지 의문이 들었습니다. 이 부분에 대해서 멘토님들의 생각을 듣고 싶습니다!
- 개선할 점에 대해 매운 맛으로 부탁드리겠습니다🔥

2023-06-13 17:45 UTC, JoosungKwon reviewed
이슬님 고생 많으셨습니다! 👍 리뷰 확인하시고 테스트까지 마무리 하시면 될 것 같습니다!! 😄

질문에 답변을 하자면

> 객체를 책임에 따라 분리하려고 노력했는데 적절하게 나눈 것인지 궁금합니다 🧐

- 책임에 따라 분리하시려고 고민하신게 느껴집니다! 대부분 적절하게 나눈것 같다고는 느껴집니다만, `Service` 객체나 `Conveter`객체와 같이 약간은 역할이 모호한 객체들이 남아 있는 것 같습니다~!

> 대부분의 클래스를 인터페이스로 추상화하였습니다. 추상화가 굳이 필요하지 않는 부분까지 추상화한 곳은 없는지 궁금합니다‼️ 🧐

- 인터페이스가 꼭 필요한지 좀 더 생각해보면 좋을 것 같습니다~! 예를 들어, Service 같은 경우 기능이 추가 혹은 변경이 되면 그에 따라 인터페이스까지 같이 변경되어야 할 것 같은데 그렇다면 필요한 이유가 있을까요?

> 표기법마다 변환과 계산 과정이 다릅니다. 그래서 후에 사칙연산 계산을 전위표기법으로 확장하는 것을 고려하여 ExpressionConverter에서 변환과 계산까지 모두 하도록 설계하였습니다. 이렇게 설계를 하면서도 과연 계산을 ExpressionConverter에서 하는 것이 맞는지 의문이 들었습니다. 이 부분에 대해서 멘토님들의 생각을 듣고 싶습니다!

- 객체지향 설계 원칙 중 단일책임원칙(SRP)에 위배되는 것 같습니다! 표기법이 변경되더라도 계산하는 데는 변경이 없을 수 있도록 분리해보면 좋을 것 같습니다!

2023-06-13 17:45 UTC, JoosungKwon commented on src/main/java/com/programmers/java/calculator/io/Output.java
> +    void inputError(String message);
`inputError` 보다 `printError` 가 더 통일성있고 명확하지 않을까요..?

2023-06-13 17:45 UTC, JoosungKwon commented on src/main/java/com/programmers/java/calculator/model/Calculator.java
> +package com.programmers.java.calculator.model;
레이어드 아키텍처를 적용하신 거라면 `Calculator`가 `model` 패키지에 있는게 적절한 위치가 아닌 것 같습니다~!

2023-06-14 07:07 UTC, Yiseull commented on src/main/java/com/programmers/java/calculator/entity/History.java
> +    private String expression;
항상 속성에만 final을 붙이다가 class에도 final을 붙일 수 있다는 것을 처음 알았습니다! 말씀해주신대로 계산 이력은 한 번 값이 세팅된 후 변하지 않으니 불변 객체로 만드는 것이 좋은 것 같습니다!👍

2023-06-14 07:38 UTC, Yiseull commented on src/main/java/com/programmers/java/calculator/converter/PostfixExpressionConverter.java
> +        return String.valueOf(new BigDecimal(stack.pop()));
확실히 result에 결과를 담아서 반환하는 게 더 명확하고 가독성이 좋은 것 같습니다!

2023-06-14 07:59 UTC, Yiseull commented on src/main/java/com/programmers/java/calculator/CalculatorApplication.java
> +        CalculatorService calculatorService = new CalculatorServiceImpl(new PostfixExpressionConverter(), new MemoryCalculatorRepository());
저도 한 줄이 너무 길어지면 한 눈에 파악하기 어려운 것 같습니다!

읽기 쉽게 하기 위하여 `PostfixExpressionConverter`와 `MemoryCalculatorRepository`의 인스턴스를 별도의 변수로 생성하는 것이 좋을지, 아니면 줄바꿈을 하는 것이 좋을 지 고민이 됩니다..🤔 열심히 고민해보고 읽기 쉽게 고치도록 하겠습니다!!

2023-06-14 09:38 UTC, Yiseull commented on src/test/java/com/programmers/java/calculator/CalculationTest.java
> +        @Test
`@DIsplayName` 을 사용하니까 어떤 테스트인지 한 눈에 알아볼 수 있어서 좋은 것 같습니다!!

2023-06-14 09:54 UTC, Yiseull commented on src/main/java/com/programmers/java/calculator/converter/PostfixExpressionConverter.java
> +    private static Pattern pattern = Pattern.compile("-?\\d+(\\.\\d+)?");
헉!! 깜빡하고 안적은 것 같습니다!! 얼른 수정하겠습니다😅😅

2023-06-14 10:29 UTC, Yiseull commented on src/main/java/com/programmers/java/calculator/model/Calculator.java
> +        while (true) {
종료 조건 변수를 설정하는 방법이 있었군요!! 감사합니다👍👍

2023-06-14 11:01 UTC, Yiseull commented on src/test/java/com/programmers/java/calculator/CalculationTest.java
> +    CalculatorService calculatorService = new CalculatorServiceImpl(new PostfixExpressionConverter());
헉 전에 자바 버전 변경할 때 잘못 건들였나봅니다😭😭 확인해보고 실행되는 코드로 올리겠습니다!!

2023-06-14 15:07 UTC, Yiseull commented on src/main/java/com/programmers/java/calculator/model/Operator.java
> +        }
`Operator`도 `HashMap`으로 만들어야지 하다가 까먹은 것 같습니다...😅 `HashMap`으로 리팩토링 하겠습니다 :)

여기서 `Operator`는 `HashMap`으로 만들고, `MenuType`은 `LinkedHashMap`으로 만든 이유는 있습니다! `MenuType`은 콘솔창에 보여줄 메뉴를 만들 때 `Enum`에 저장된 순서대로 보여주기 위해서 `LinkedHashMap`으로 캐싱 하였습니다!

2023-06-15 04:22 UTC, graygreat requested changes
안녕하세요 이슬님~

과제 잘 구현해주셔서 크게 리뷰할 게 없었네요 👍 


> 객체를 책임에 따라 분리하려고 노력했는데 적절하게 나눈 것인지 궁금합니다 🧐
잘 나누신 것 같아요~ 다만 mvc에 대해서 조금 더 학습을 해보면 좋겠다는 생각이 듭니다!
entity, converter, io 같은 패키지들이 필요할까요?

> 대부분의 클래스를 인터페이스로 추상화하였습니다. 추상화가 굳이 필요하지 않는 부분까지 추상화한 곳은 없는지 궁금합니다‼️ 🧐

나중에 이 프로젝트가 어떻게 확장될 지, 새로운 요구사항이 들어왔을 때 변경을 최소화 할 수 있을지 중요한 것 같아요.
이슬님이 스스로 느끼기에 인터페이스를 사용해서 요구사항에 대한 대처를 잘 할 수 있다는 확신이 있다면 좋은 구조인 것 같아요!

> 표기법마다 변환과 계산 과정이 다릅니다. 그래서 후에 사칙연산 계산을 전위표기법으로 확장하는 것을 고려하여 ExpressionConverter에서 변환과 계산까지 모두 하도록 설계하였습니다. 이렇게 설계를 하면서도 과연 계산을 ExpressionConverter에서 하는 것이 맞는지 의문이 들었습니다. 이 부분에 대해서 멘토님들의 생각을 듣고 싶습니다!

Converter에서 계산이 일어나는 것은 좋은 구조가 아닌 것 같아요!
팀 동료가 이슬님 코드를 인수인계 받아서 계산 로직을 찾는데, 변환 해주는 객체에 있으면 당황스럽겠죠?
변환은 변환대로 계산은 계산대로 진행하고 이 로직을 어디서 처리할 수 있을지 고민해보는게 좋은 방향인 것 같네요!

2023-06-15 04:22 UTC, graygreat commented on src/main/java/com/programmers/java/calculator/entity/CalculationHistory.java
> +    public static CalculationHistory of(Long id, String expression, String result) {
정적 팩토리 메소드 패턴을 사용하신 이유가 있으실까요?

메소드명을 of로 하신 이유는 무엇인가요? (of vs from 차이도 궁금합니다.)

2023-06-15 04:22 UTC, graygreat commented on src/main/java/com/programmers/java/calculator/model/Calculator.java
> +                String inputMenuType = input.input(MenuType.getMenu());
Input 클래스 안에 input 메소드가 있어서 뭔가 어색해 보이네요 ㅎ

2023-06-15 04:22 UTC, graygreat commented on src/main/java/com/programmers/java/calculator/model/MenuType.java
> +            Collections.unmodifiableMap(Stream.of(values()).collect(
전체적으로 가독성이 안좋다고 느껴지는데, 어떻게 높일 수 있을까요?

2023-06-15 04:22 UTC, graygreat commented on src/main/java/com/programmers/java/calculator/model/Operator.java
> +    private static final Map<String, Operator> OPERATOR_MAP =
해당 필드를 상수처럼 선언하시려고 한 것 같은데 그러한 이유가 있을까요?

2023-06-15 04:22 UTC, graygreat commented on src/main/java/com/programmers/java/calculator/model/Operator.java
> +        throw new IllegalArgumentException("잘못 입력되었습니다");
"잘못 입력되었습니다" 와 같은 것도 다 상수로 표현되어도 될 것 같네요

2023-06-15 04:22 UTC, graygreat commented on src/main/java/com/programmers/java/calculator/service/CalculatorService.java
> +public interface CalculatorService {
service를 인터페이스로 구현하신 이유는 무엇인가요?

2023-06-15 04:22 UTC, graygreat commented on src/test/java/com/programmers/java/calculator/CalculationTest.java
> +        void additionTest() {
동일한 코드가 계속 반복되고 있는데, 주성님이 말씀주신대로 Parameterized Test 보시고 수정해보시면 좋을 것 같아요.

2023-06-15 04:22 UTC, graygreat commented on src/main/java/com/programmers/java/calculator/entity/CalculationHistory.java
> +package com.programmers.java.calculator.entity;
entity가 무엇인가요?

2023-06-15 04:22 UTC, graygreat commented on src/main/java/com/programmers/java/calculator/model/Operator.java
> +public enum Operator {
Operator에 대한 테스트도 필요하지 않을까요?

2023-06-15 04:22 UTC, graygreat commented on src/main/java/com/programmers/java/calculator/converter/PostfixExpressionConverter.java
> +    public String convert(String expression) {
convert에서 calculate도 일어나고 있는데, 역할을 분리해보면 어떨까요?

2023-06-15 04:22 UTC, graygreat commented on src/main/java/com/programmers/java/calculator/validation/Validator.java
> +public interface Validator {
Validator는 한 군데에서만 사용하고 있는 것 같은데, 따로 빼신 이유가 있을까요?

2023-06-15 06:01 UTC, Yiseull commented on src/main/java/com/programmers/java/calculator/service/CalculatorServiceImpl.java
> +        return new History(expression + " = " + result);
지금 보니 `History`에서 `expression`에 식과 결과 모두 저장하고, 서비스에서 `expression`과 `result`를 합쳐 하나의 히스토리를 만드는 것이 잘못 설계됐던 것 같습니다! `expression`과 `result` 각각 필드로 두고 `toString`을 재정의하니까 훨씬 코드가 간결해지고 확장성 있는 코드가 되었습니다! 감사합니다😆😆

2023-06-15 11:39 UTC, Yiseull commented on src/test/java/com/programmers/java/calculator/MenuSelectionTest.java
> +    @Test
감사합니다!! 반복적인 코드가 많았는데 `Parameterized Test `를 적용해서 개선해보겠습니다!😊

2023-06-15 11:42 UTC, Yiseull commented on src/main/java/com/programmers/java/calculator/converter/Converter.java
> +public interface Converter<T, U> {
칭찬 감사합니다:) 다른 코드도 칭찬받을 수 있도록 더 열심히 코드 작성해보겠습니다!!!🔥

2023-06-15 11:47 UTC, Yiseull commented on src/test/java/com/programmers/java/calculator/CalculationTest.java
> +        void additionTest() {
넵😊 `Parameterized Test` 적용해서 반복적인 코드 개선해보겠습니다!

2023-06-15 15:33 UTC, Yiseull commented on src/main/java/com/programmers/java/calculator/converter/PostfixExpressionConverter.java
> +        for (String str : exp) {
확실히 depth가 2이고, 메서드가 길어서 한 눈에 알아보기 힘든 거 같습니다! 
메서드 당 한 가지 일만 하도록 메서드를 분리해서 depth를 줄여보겠습니다!! 😊

2023-06-16 07:09 UTC, Yiseull commented on src/main/java/com/programmers/java/calculator/model/Operator.java
> +    private static final Map<String, Operator> OPERATOR_MAP =
해당 필드는 초기화 이후 데이터의 변경이 일어나지 않는다고 생각하여서 상수로 선언했습니다!

2023-06-16 07:22 UTC, Yiseull commented on src/main/java/com/programmers/java/calculator/model/MenuType.java
> +            Collections.unmodifiableMap(Stream.of(values()).collect(
초기화 코드가 길고 복잡해서 가독성을 떨어뜨린다고 생각합니다! static 블록을 사용하여 초기화 코드를 분리하고, stream 대신 foreach를 사용해서 가독성을 높일 수 있을 것 같습니다!!

2023-06-18 07:09 UTC, Yiseull commented on src/main/java/com/programmers/java/calculator/model/Operator.java
> +        throw new IllegalArgumentException("잘못 입력되었습니다");
상수로 표현하는 것에 대해서 더 자세히 말씀해 주실 수 있을까요?? Enum으로 따로 빼라는 말씀이 맞을까요!?

2023-06-18 09:28 UTC, Yiseull commented on src/main/java/com/programmers/java/calculator/entity/CalculationHistory.java
> +    public static CalculationHistory of(Long id, String expression, String result) {
객체 생성을 캡슐화 하기 위하여 정적 팩토리 메소드 패턴을 사용하였습니다!

정적 팩토리 메소드 네이밍 규칙을 제대로 알지 못해서 찾아보았습니다. `of` 와 `from` 은 객체를 생성하기 위해 필요한 매개 변수의 개수에 따라 구분할 수 있습니다. `of` 는 여러 개의 매개 변수를 받아서 객체를 생성할 때, `from` 은 하나의 매개 변수를 받아 객체를 생성할 때 쓰입니다! 🙂

2023-06-18 17:59 UTC, Yiseull commented on src/main/java/com/programmers/java/calculator/validation/Validator.java
> +public interface Validator {
처음 설계를 할 때 Validator 라는 역할을 분리하기 위해서 패키지를 따로 만들었습니다! 하지만 막상 식을 입력할 때만 사용되기 때문에 서비스의 메소드로 들어가는게 좋을을 것 같다는 생각이 듭니다!🙂

2023-06-18 18:10 UTC, Yiseull commented on src/main/java/com/programmers/java/calculator/converter/PostfixExpressionConverter.java
> +    public String convert(String expression) {
넵!! 계산 기능을 어디에서 처리해야 하는지 고민해서 역할을 분리해보겠습니다!! :)

2023-06-18 18:25 UTC, Yiseull commented on src/main/java/com/programmers/java/calculator/service/CalculatorService.java
> +public interface CalculatorService {
Spring 개발을 할 때 했던 습관처럼 서비스 추상화를 했던 것 같습니다! 웹 개발을 할 때는 유연한 대처와 틀을 잡아놓는다는 이점으로 추상화를 하였지만, 계산기에서는 Service가 크게 확장될 일도, 메소드가 복잡한 것도 아니여서 추상화를 해야 하나 라는 의문이 들긴 했습니다..🤔

2023-06-18 18:47 UTC, Yiseull commented on src/main/java/com/programmers/java/calculator/entity/CalculationHistory.java
> +package com.programmers.java.calculator.entity;
entity를 단순히 저장되고 관리되어야 하는 객체로 생각해서 사용했습니다! 하지만 보통 entity는 DB에서 사용되는 객체를 의미하니까 `Map` 으로 저장하는 계산기에서는 entity 라고 부르기 어색한 것 같습니다🥹

2023-06-18 18:57 UTC, Yiseull commented on src/main/java/com/programmers/java/calculator/model/Calculator.java
> +package com.programmers.java.calculator.model;
지금 보니 `Calculator`가 `model` 패키지에 있는 게 적절하지 않은 것 같습니다! 전체적으로 패키지 구조를 다시 설계할 때 이 부분도 고려해서 적잘한 위치에 있도록 고쳐보겠습니다!! :)

2023-06-21 10:04 UTC, JoosungKwon approved these changes
@Yiseull
안녕하세요 이슬님! 리팩터링이 끝난것 같아서 간단한 리뷰만 남기고 해당 PR은 Merge하도록 하겠습니다!
꾸준히 리팩터링하시는 모습이 정말 대단하신 것 같아요!! 👍 앞으로의 과제도 시간에 얽매이기 보다 꾸준히 연습의 도구로 활용하셨으면 좋겠습니다!! 😄

남긴 리뷰는 간단하게만 확인하고 남겼습니다~ 잘하신것 같아서 조언드릴만한게 많지 않았네요. 전부 사소한 내용이니 참고만 해주세요! 

마지막으로 약간의 아쉬운 점을 이야기하자면 계산기 과제는 POJO의 방식으로 객체지향을 연습하기 위한 목적이 있습니다. 하지만, 이슬님은 레이어드 아키텍처를 활용하는 방식으로 구현하셨더라고요.

아마도 스프링을 활용하는 방식에 익숙해져서 그런 것 같아요! 잘못된건 아니지만 제 개인적인 생각은 계산기에는 적합한지 잘 모르겠습니다! 어떤 상황에 무엇을 사용하는게 적합한지 고려하시면서 개발하시면 더 좋을 것 같습니다~!(잔소리가 길어서 죄송합니다.!!)

앞으로의 과제도 잘해내시길 바랍니다~!ㅎㅎ 화이팅..!!😄

2023-06-21 10:05 UTC, merged