[4기 - 김혜민] 1~2주차 과제 : 계산기 구현 미션 제출합니다.
prgrms-be-devcourse/java-calculator pull request #181
Opened 2023-06-13 14:38 UTC by hyee0715

## 📌 과제 설명 
- 덧셈, 뺄셈, 곱셈, 나눗셈 기능의 계산기를 구현하였습니다. 
- 사용자로부터 조건에 맞지 않는 입력을 받았을 경우 `에러 메시지`를 출력하고, 조건에 맞는 입력을 받을 때까지 반복적으로 입력을 받도록 하였습니다. 
- 메뉴에 `3. 종료`를 추가하여 사용자가 종료 기능을 선택할 수 있게 하였습니다.
- 각 기능 구현 후에 테스트 코드를 작성하였습니다.

## 👩‍💻 요구 사항과 구현 내용 

기능목록을 작성하였습니다.
### 기능 목록
- [X] 메뉴 출력 기능 구현
   `1. 조회 / 2. 계산 / 3. 종료`

- [X] 메뉴 번호를 입력받는 기능 구현

- [X] 메뉴 번호 입력 예외처리 기능 구현
  `예외1. 금액이 입력되지 않은 경우`
  `예외2. 메뉴 입력이 형식에 맞지 않은 경우 : 입력이 1, 2, 3이 아닌 경우`
 

> 2번(계산)을 입력받은 경우
- [X] 계산식을 입력받는 기능 구현

- [X] 계산식 입력 예외처리 기능 구현 `정규식 사용`
  `예외1. 계산식이 입력되지 않은 경우`
  `예외2. 계산식 형식이 어긋나는 경우 : 연산자와 숫자가 아닌 문자가 입력되었을 경우`

- [X] 계산식을 요소별로 나누는 기능 구현

- [X] 요소별로 나눈 계산식 예외처리 기능 구현
  `예외1. 요소(토큰)들의 개수가 짝수 개수인 경우`
  `예외2. 계산식 형식(숫자 - 연산자 - 숫자)에 어긋나는 경우`
  `예외3. 0으로 나누는 경우`

- [X] 중위표기식에서 후위표기식으로 변경하는 기능 구현 `우선순위 반영`

- [X] 후위표기식 계산 기능 구현

- [X] 계산식 결과 저장 기능 구현

> 1번(조회)을 입력받은 경우
- [X] 계산 기록 조회 기능 구현

> 3번(종료)을 입력받는 경우
- [X] 종료 메시지 출력 기능 구현

## ✅ PR 포인트 & 궁금한 점 
- 객체지향적으로 구현하려고 노력하였으나, 맞게 구현한 것인지 감이 잘 오지 않습니다..😖..어긋나는 부분이 있다면 말씀 부탁드립니다!

- 패키지별로 클래스를 잘 나누어 배치한 것인지 확신이 들지 않습니다.🤔

- Calculator.class의 run() 메소드가 깔끔하게 정리가 되지 않아 많이 길어졌습니다. 조금 더 가독성있게 만들 방법이 있을까요?

- PostfixConverter.class의 convertInfixToPostfix 메소드도 중간에 긴 for문 때문에 정리가 어려워서 길어졌습니다.  이 메소드도 깔끔하게 정리할 방법이 있을까요?

- 테스트 코드 작성시에 given, when, then으로 나누었는데 어떤 상황에서 어떤 코드를 작성해야 하는지 헷갈립니다... 각 상황에 맞게 작성이 된 건지 잘 모르겠습니다. 고쳐야 하는 부분이 있다면 말씀 부탁드립니다!

- 기능을 먼저 구현하고 후에 테스트 코드를 작성하였는데, TDD로 구현하게 된다면 테스트 코드를 먼저 작성하는 것으로 알고있습니다. 계산기를 구현하는 경우에는 어떠한 방식으로 구현할 수 있는지 궁금합니다!

- 테스트 코드에서 @DisplayName을 사용하는 것이 더 나을지, 메소드에 한글로 적는 것이 나을지 잘 모르겠습니다. 주로 어떤 방식을 사용하시나요?

- 그 외에 고쳐야 할 부분이 있다면 피드백 부탁드리겠습니다! 코드리뷰는 처음이라 떨리네요... 잘 부탁드리겠습니다! 감사합니다. ☺

2023-06-15 15:13 UTC, hongbin-dev commented
### 객체지향적으로 구현하려고 노력하였으나, 맞게 구현한 것인지 감이 잘 오지 않습니다..😖..어긋나는 부분이 있다면 말씀 부탁드립니다!

도메인의 책임이 너무 없는 거 같아요. 다른 객체 신경쓰지말고 Controller, Model, View 정도만 신경써주세요.
혜민님 코드에서는 명령어(1 + 2 + 3 4), 후위표현값, 계산기 이런 객체가 나오면 좋을 거 같아요.
또 코멘트처럼 Validator를 모두 제거하고, 각 객체 생성자에 넣어보시면 좋을 거 같네요.

### 패키지별로 클래스를 잘 나누어 배치한 것인지 확신이 들지 않습니다.🤔
지금 단계에서는 model, view, controller 세개로만 나눠보시는걸 추천드립니다.

### Calculator.class의 run() 메소드가 깔끔하게 정리가 되지 않아 많이 길어졌습니다. 조금 더 가독성있게 만들 방법이 있을까요?
코멘트에 남겼지만 enum으로 분리해볼 수 있고, 무한 반복되는 부분이라서 메서드로 더 빼는방법밖에 생각나질 않군요 🥲

### 테스트 코드 작성시에 given, when, then으로 나누었는데 어떤 상황에서 어떤 코드를 작성해야 하는지 헷갈립니다. 각 상황에 맞게 작성이 된 건지 잘 모르겠습니다. 고쳐야 하는 부분이 있다면 말씀 부탁드립니다!

전반적으로 잘작성해주신거같고, 어색한부분은 코멘트 남겼습니다.

### 테스트 코드에서 @DisplayName을 사용하는 것이 더 나을지, 메소드 이름을 한글로 적는 것이 나을지 잘 모르겠습니다. 주로 어떤 방식을 사용하시나요?

둘중에 하나만 사용해도 괜찮다고 생각하는편입니다. 다만 메서드명에는 _를 써야해서 Displayname을 선호하고 있어요.

2023-06-15 15:14 UTC, hongbin-dev requested changes
혜민님~ 테스트코드를 꼼꼼하게 잘 작성해주셨네요!

전반적인 코드리뷰 남겼으니 확인부탁드려요~!

2023-06-15 15:14 UTC, hongbin-dev commented on src/test/java/com/programmers/domain/PostfixConverterTest.java
> +    }
여기도 마찬가지요
```suggestion
        assertThat(result).containsExactly("5", "2", "7", "/", "+");
    }
```

2023-06-17 03:07 UTC, hyee0715 commented on src/main/java/com/programmers/domain/Calculator.java
> +    private static int TERMINATE = 3;
네! 기능들을 선택하고 로직을 진행하는 역할을 하는 것 같아서 Calculator Controller를 새로 생성해서 해당 메소드를 배치했습니다!

2023-06-17 03:07 UTC, hyee0715 commented on src/main/java/com/programmers/domain/Calculator.java
> +        int menuSelection = calculatorService.getValidatedMenuSelection();
menu enum타입을 새로 생성해서 그 안에서 Menu에 맞는 메소드와 유효성검사를 할 수 있도록 했습니다! 감사합니다 ㅎㅎ

2023-06-17 03:08 UTC, hyee0715 commented on src/main/java/com/programmers/domain/Calculator.java
> +            }
Menu enum 타입과 switch문을 이용해서 더욱 가독성 있게 바꾸었습니다. 바꾸니까 한 눈에 들어오고 훨씬 깔끔해져서 좋네요!

2023-06-17 03:08 UTC, hyee0715 commented on src/main/java/com/programmers/domain/CalculatorRepository.java
> +    }
감사합니다 👍

2023-06-17 03:09 UTC, hyee0715 commented on src/main/java/com/programmers/domain/ExpressionValidator.java
> +
유효성 검사를 한다는 것에만 집중한 나머지 두 가지 일을 한다는 생각을 못했습니다 ㅠㅠㅠ 조언해주신대로 validator 클래스는 아예 없애고 각 도메인에 유효성 기능을 배치해봤습니다😃

2023-06-17 03:09 UTC, hyee0715 commented on src/main/java/com/programmers/domain/ExpressionValidator.java
> +    }
다시 보니 불필요한 것 같은 메소드인 것 같네요! ExpressionValidator 클래스는 지우고 Expression 도메인을 새로 생성하여 Expression 객체를 생성할 때 생성자에서 내부 필드인 String input에서 empty 여부를 검사할 수 있도록 수정해보았습니다! 😊

2023-06-17 03:10 UTC, hyee0715 commented on src/main/java/com/programmers/domain/Operator.java
> +public enum Operator {
감사합니다 👍

2023-06-17 03:10 UTC, hyee0715 commented on src/main/java/com/programmers/domain/Operator.java
> +                .orElseThrow(() -> new IllegalArgumentException("연산자를 찾을 수 없습니다. = " + input));
감사합니다 👍

2023-06-17 03:10 UTC, hyee0715 commented on src/main/java/com/programmers/domain/PostfixConverter.java
> +            }
PostfixConverter 클래스의 addTokenToPostfix 메소드를 새로 생성하여 들여쓰기를 줄여보았습니다ㅎㅎ 다만 이렇게 구현하면서 스택을 메소드 바깥으로 (클래스 필드로) 꺼내게 되었는데, 괜찮은 것인지 멘토님의 의견이 궁금합니다 !

2023-06-17 03:10 UTC, hyee0715 commented on src/main/java/com/programmers/domain/PostfixConverter.java
> +            String token = tokens.get(i);
for (String token : tokens) 의 방식으로 변경했습니다! 평소에 for (int i = 0; i < tokens.size(); i++) 의 방식을 자주 사용하다 보니 무의식적으로 사용한 것 같습니다. 컬렉션의 for-loop를 사용하는 것이 로직을 구성하는 데 훨씬 가독성이 있다고 생각하는데, 앞으로는 인덱스가 필요하지 않은 경우에는 조금 더 주의를 기울이겠습니다!

2023-06-17 03:11 UTC, hyee0715 commented on src/main/java/com/programmers/domain/SelectionValidator.java
> +    }
Validator를 모두 없애고, 각 도메인객체의 생성자에 넣어주세요.
응집도가 떨어져서 더 복잡하다고 생각되네요
-> 조언해주신대로 validator클래스를 모두 제거하고 
도메인 객체의 생성자에 추가해서 유효성 검사를 하거나(-> Expression 클래스 생성자)
해당 enum타입을 찾을 때 유효성 검사를 하도록 (-> Menu Enum타입의 findMenu메소드)
변경하였습니다!

2023-06-17 03:12 UTC, hyee0715 commented on src/main/java/com/programmers/exception/ExpressionDividedByZeroException.java
> +public class ExpressionDividedByZeroException extends IllegalArgumentException {
감사합니다 👍

2023-06-17 03:12 UTC, hyee0715 commented on src/main/java/com/programmers/service/CalculatorService.java
> +public class CalculatorService {
다시 보니 service라고 생성하고 마구잡이로 기능들을 추가한 것 같습니다..😫 각 기능에 맞게 도메인을 생성하여 CalculatorService클래스에 있던 메소드들을 다시 배치하였습니다!

2023-06-17 03:12 UTC, hyee0715 commented on src/main/java/com/programmers/service/CalculatorService.java
> +        int result = calculatePostfix(postfix);
넵! 해당 로직은 Calculator 도메인에 맞는 기능이라고 생각해서 옮겼습니다!

2023-06-17 03:13 UTC, hyee0715 commented on src/main/java/com/programmers/service/CalculatorService.java
> +        System.out.println(result + "\n");
조언해주신대로 console 객체에 result를 출력하는 기능을 새로 생성하여 console 객체를 통해서 출력하도록 변경하였습니다.

2023-06-17 03:13 UTC, hyee0715 commented on src/main/java/com/programmers/util/ExpressionProcessor.java
> +
ExpressionProcessor 이름 자체가 계산식을 다루는 클래스인데, util 패키지에 넣는 것이 맞지 않다는 생각이 드네요..!!! 해당 클래스는 삭제하고 parse 메소드는 Expression 클래스에 배치했고, removeSpace는 Console 클래스에 배치하여 입력을 받고 바로 빈 칸을 제거하도록 코드 구조를 재건하였습니다!

2023-06-17 03:13 UTC, hyee0715 commented on src/test/java/com/programmers/domain/OperatorTest.java
> +        assertThat(operator.name()).isEqualTo("ADDITION");
고쳐주신 방식대로 Menu 테스트도 비슷하게 테스트 코드를 작성해보았습니다! 😊

2023-06-17 03:13 UTC, hyee0715 commented on src/test/java/com/programmers/domain/ExpressionValidatorTest.java
> +    @ParameterizedTest
감사합니다 👍

2023-06-17 03:13 UTC, hyee0715 commented on src/test/java/com/programmers/ApplicationTest.java
> +        System.setIn(new ByteArrayInputStream(String.join("\n", inputs).getBytes()));
감사합니다 👍

2023-06-17 03:14 UTC, hyee0715 commented on src/test/java/com/programmers/domain/OperatorTest.java
> +        assertThat(result).isEqualTo(expected);
expected 위치에 바로 숫자를 넣으니 더 가독성 있는 것 같습니다! 변경할 수 있는 다른 테스트 코드도 변경했습니다~

2023-06-17 03:14 UTC, hyee0715 commented on src/test/java/com/programmers/domain/PostfixConverterTest.java
> +    }
containsExactly를 사용해서 검사할 수 있는 부분을 새로 적용해보았습니다! 감사합니다!

2023-06-17 03:19 UTC, hyee0715 commented
조언해주신대로 코드 리팩토링 해보았습니다! 

도메인을 나누고 클래스별로 기능을 나누는 점이 가장 미숙했던 것 같습니다. 그래서 도메인들을 새로 만들고 기능별로 메소드를 많이 재배치한 것 같습니다. 과거에도 이러한 과제를 했을 때 피드백을 받아본 적이 없어서 잘 만들고 있는 것이 맞는지 확신에 차지 않았는데, 꼼꼼하게 코드리뷰 해주셔서 고쳐야 할 부분을 많이 알게 되었습니다! 

코드 리팩토링을 하면서 validator를 지우고 클래스 객체를 생성할 때 생성자에서 유효성 검사를 하도록 바꿔봤는데, 이러한 방식으로 구현해도 괜찮을지 잘 모르겠습니다 ㅎㅎ 멘토님의 의견이 궁금합니다!

더 추가하거나 고쳐야 할 부분이 있다면 조언 부탁드리겠습니다!! 바쁘신 와중에도 코드리뷰 해주셔서 감사합니다!😊

끝으로 코드 리팩토링한 내용과 기타 변동 사항을 대략적으로 정리해보았습니다!

<details>
<summary> 피드백 반영 사항 및 기타 변동 사항</summary>

### 1. 도메인 새로 생성
- 패키지는 controller, domain, exception, io로 구성되도록 변경하였습니다.

- domain으로 Calculator, Expression 클래스와 Menu enum을 생성했습니다.

- CalculatorController를 생성하여 로직들을 상호작용하는 기능을 하던 Calculator의 run() 메소드를 CalculatorController로 옮겼습니다.

- CalculatorService를 제거하고 CalculatorService에 있던 메소드들을 각 도메인의 기능별로 다시 배치했습니다.

- util 패키지와 ExpressionProcessor 클래스를 제거하고, util 패키지에 있던 ExpressionProcessor 클래스의 메소드들을 각 도메인의 기능별로 다시 배치했습니다.


### 2. Validator 클래스 제거
- 응집도를 떨어지게 했던 기존의 SelectionValidator, ExpressionValidator 클래스를 제거하고, 각 Validator 클래스에서 진행하던 유효성 검사 기능을 도메인 기능에 맞게 재배치했습니다.

- SelectionValidator : Menu Enum의 findMenu 메소드에서 유효성 검사를 하도록 변경했습니다.

- ExpressionValidator : Expression 클래스의 객체를 생성할 때 생성자에서 필드인 String input을 검증하도록 변경했습니다. 객체를 생성한 후 요소들을 나눌 때는 Expression 클래스의 getValidatedTokens 메소드를 이용하여 한 번 더 유효성 검사를 하도록 구현하였습니다.


### 3. CalculatorController
- Menu Enum과 switch문을 이용하여 계산기 기능 진행 코드를 가독성있게 수정하였습니다.
- TERMINATE를 입력받으면 boolean activated값을 false로 변경하여 계산기를 종료하도록 while 반복문을 변경하였습니다.


### 4. Calculator
- 후위표현식의 계산을 진행할 수 있도록 메소드를 구성하였습니다.
- 계산된 결과값을 Repository에 저장할 수 있는 기능들을 추가하였습니다.

### 5. CalculatorRepository
- 해당 클래스의 Map과 key에 static을 추가하지 않아서 key의 기능을 제대로 하지 못하고 있는 것을 인지하였습니다. static을 추가하여 계산 결과 값을 추가할 때마다 key의 값을 증가시키고 map에 추가할 수 있도록 변경하였습니다.

### 6. Expression
- 기존에 계산식을 다루던 기능들을 Expression 클래스에 모았습니다.
- 입력받은 계산식을 유효성 검사하고, 각 요소별로 나누는 기능으로 구성하였습니다.
- 계산식을 요소별로 나누는 parse() 메소드에서 StringTokenizer를 이용하여 조금 더 가독성 있게 요소를 나눌 수 있도록 하였습니다.

### 7. Menu
- 계산기 메뉴를 enum 타입으로 구성하였습니다.
- findMenu 메소드를 이용하여 사용자로부터 입력받은 input을 유효성 검증하고, 검증을 통과하면 Menu를 반환하는 findMenu 메소드를 추가하였습니다.

### 8. Operator
- findOperator, findImportance의 Error 메시지 앞에 "[ERROR]"를 추가하였습니다.

### 9. PostfixConverter
- 기존에 길었던 convertInfixToPostfix 메소드를 분리하여 보다 가독성 있게 하였습니다.

### 10. Console
- 기존의 ExpressionProcessor와 CalculatorService에 있던 메소드 중 입력과 출력 관련한 메소드를 해당 클래스에 재배치하였습니다.


### 11. 테스트 코드
- 앞서 리팩토링한 클래스들에 맞추어서 테스트코드들을 모두 수정하였습니다.
- CalculatorControllerTest, ExpressionTest, MenuTest가 추가되었습니다.
- 멘토님께서 조언해주신 대로 result를 비교하는 방식을 조금씩 수정하였습니다.

</details>

2023-06-18 12:44 UTC, hongbin-dev commented on src/main/java/com/programmers/domain/PostfixConverter.java
> +            }
그전엔 유틸클래스처럼 사용했다고 생각했는데 상태필드가 추가되어서 애매해진 거 같아요.

또 단순 convertInfixToPostfix() 메서드에서만 사용해야한다면 상태로 사용하기보단, 파라미터로 이동하시는걸 추천드립니다.

1. 해당 메서드를 동시에 접근하면 문제가 발생할 수 있어요.
2. 지금은 addTokenToPostfix() 메서드에서 모두 pop을 해주지만, 만약 코드가 잘못되어서 스택이 남아있는경우가 발생하고, 또 그 메서드를 호출하면 디버깅이 굉장히 어려워질 수 있습니다

2023-06-18 12:45 UTC, hongbin-dev commented on src/main/java/com/programmers/domain/PostfixConverter.java
> +            String token = tokens.get(i);
아무래도 NPE방지나, 반복문중에 element를 삭제했을때도 안전하게 사용할 수 있어요!

2023-06-18 13:37 UTC, hongbin-dev approved these changes
혜민님!
코드가 많이 깔끔해졌네요. 이만 머지하도록하겠습니다.

수고많으셨어요!

2023-06-18 13:37 UTC, hongbin-dev commented on src/main/java/com/programmers/domain/CalculatorRepository.java
> +    private static Long key = 0L;
CalculatorRepository당 하나씩 상태를 가질 수 있도록 스태틱은 제거하시는게 좋을 거 같아요.

2023-06-18 13:37 UTC, hongbin-dev commented on src/main/java/com/programmers/domain/Expression.java
> +    }
👍

2023-06-18 13:37 UTC, hongbin-dev commented on src/main/java/com/programmers/domain/Calculator.java
> +    }
이건 출력객체가 담당하는게 좋을 거 같아요~

2023-06-18 13:37 UTC, hongbin-dev commented on src/main/java/com/programmers/domain/Calculator.java
> +    }
도메인은 콘솔을 갖지않도록 작성해주세요. 지금 상황이면 컨트롤러로 옮기는게 좋겠네요.

만약 콘솔을 제어하고 웹 프로젝트로 전환한다면, 이 클래스는 그대로 사용하지 못하겠네요

2023-06-18 13:37 UTC, hongbin-dev commented on src/main/java/com/programmers/domain/Menu.java
> +    }
👍

2023-06-18 13:37 UTC, merged