[4기 - 신범철] 1~2주차 과제: 계산기 구현 미션 제출합니다.
prgrms-be-devcourse/java-calculator pull request #184
Opened 2023-06-13 18:33 UTC by beombu

## 📌 과제 설명 
- `calculatoion` : 후위연산식을 계산해주는 서비스입니다.
- `converter` : input으로 받은 수식을 후위연산식으로 변환해주는 서비스입니다.
- `vo.CalculationResult` : 수식의 결과를 반환해주는 vo입니다.
- `CalculatorController` : 전체적인 작업을 조정해주는 컨트롤러입니다.
- `constant.MenuType` : 입력 받은 메뉴를 나열해둔 enum입니다.
- `constant.Operator` : 연산자와 우선순위를 나열해둔 enum입니다.

## ✅ 피드백 반영사항  

## ✅ PR 포인트 & 궁금한 점 
1. 코드를 구현하다보니.. 절차지향적(?)으로 전체 코드를 구현하고 부분 부분 나누고 커밋하는 코드를 작성했습니다.... 객체지향적으로 코드를 구현하고 싶은데 잘 안되는 상황입니다ㅠㅠ 혹시 객체지향적으로 코딩하는 팁이 있을까요..?
2. vo을 통해 원시값를 포장하였습니다. 근데 vo의 역할에 맞게 사용하였는지 궁금합니다.🙇‍♂️🙇‍♂️ class 사이에서 값을 한 번 넘겨주고 사용이 끝이 나는 상황입니다.

2023-06-14 07:15 UTC, ICCHOI requested changes
안녕하세요 범철님! 
전체적으로 객체지향적으로 구현이 잘 되어 가고 있어 보여요!
다만 가끔 [메서드 네이밍](https://tecoble.techcourse.co.kr/post/2020-04-26-Method-Naming/)이 너무 길어지는 경우가 있어 글을 한 번 참고해보셔도 좋을 거 같아요!

1. 절차지향적으로 짜고 객체지향적으로 수정 하는 것도 좋다고 생각이 들어요.
지금까지 해온 절차지향적 사고방식이 한 번에 바뀌기는 어렵기 때문에, 연습과 반복으로 점점 익숙해지면 객체지향이 익숙해 질 거에요!
좀 더 빠르게 배우고 싶다면 객체지향과 관련된 여러 책(조영호님 저서 ㅎㅎ..)을 읽거나 객체지향과 관련된 여러 규칙들을 공부하는 것도 좋아보여요.

2. VO를 통해 원시값을 포장하는 행위는 객체를 좀 더 명시적으로 표현해주고, 행위를 표현할 수 있어 아주 좋다고 생각이 들어요. 그런데 외부에 값을 전달하는 역할만 하고 있다면 해당 객체의 역할에 대해서 조금 더 고민해보면 좋을 것 같아요.

2023-06-14 07:15 UTC, ICCHOI commented on src/main/java/model/calculation/CalculationImpl.java
> +        }
계산 로직과 stack을 채우는 로직을 별개로 분리하면 더 좋을 것 같아요.
calculatePostfixExpression에서 여러 동작을 수행하게 된다면 테스트 하기 어려워 질거에요

2023-06-14 15:14 UTC, devcourse-ray requested changes
PostfixConverter 클래스를 보면 메소드명도 복잡한데 로직도 같이 복잡하니 이해하기가 어려워요
연산 부분 로직 개선에 고민을 많이 해보세요

2023-06-14 15:14 UTC, devcourse-ray commented on src/main/java/model/converter/PostfixConverter.java
> +    }
Operator 인지 아닌지는 Operator가 알고 판단해주는게 좋지 않을까요?

2023-06-14 21:02 UTC, beombu commented on src/main/java/model/converter/PostfixConverter.java
> +    }
감사합니다! 기능을 다시 분리해본 뒤 다시 로직을 구현해보겠습니다!

- Converter
  - 연산식의 공백을 없애고 배열로 만드는 기능
  - 연산식의 조각이 숫자인지 연산자인지 판별하는 기능
    - 숫자인 경우
      - 숫자를 후위식에 넣어주는 기능
    - 연산자인 경우
      - 연산자의 우선순위를 비교하는 기능
      - 연산자의 우선순위가 낮은 것이 있는 때까지 스택에서 빼 후위식에 넣어주는 기능
      - 연산자를 스택에 넣는 기능
  - 남아있는 연산자를 모두 후위식에 넣는 기능

2023-06-15 12:34 UTC, ICCHOI requested changes
범철님 새벽까지 고생하셨습니다!
엄청 개선되고 있는게 느껴집니당 :) 거의 마무리 하신 것 같은데 테스트 코드도 한 번 작성 해보시죠!

2023-06-15 12:34 UTC, ICCHOI commented on src/main/java/constant/Operator.java
> +    }
```suggestion
    public static boolean isOperator(String textSegment) {
    return Arrays.stream(values())
            .map(Operator::getSignature)
            .anyMatch(textSegment::equals);
}
```
이런 방식은 어떨까요?

2023-06-15 12:34 UTC, ICCHOI commented on src/main/java/constant/Operator.java
> +    }
계산 기능이 굳이 find에 의존적을 필요는 없을 것 같아요.
사용하는 쪽에서 String Operator와 findOperator 메서드를 통해 Operator를 구한 후, calculate를 호출하면 어떨까요?

2023-06-15 12:34 UTC, ICCHOI commented on src/main/java/controller/CalculatorController.java
>      }
get - 보다는 메서드 내에서 행하고 있는 로직을 좀 더 잘 표현해주는 이름이면 좋을 것 같아요.

2023-06-15 12:34 UTC, ICCHOI commented on src/main/java/model/converter/PostfixConverter.java
> +            postfixList.add(textSegment);
continue를 쓰는 것 보다는 isOperand()를 구현하는 건 어떨까요?
```suggestion
            if (isOperator(textSegment)) {
                Operator operator = Operator.findOperator(textSegment);
                processLowPriorityOperators(postfixList, operator);
                operatorStack.push(operator);
                continue;
            }
            if (isOperand(textSegment)) {
                 postfixList.add(textSegment);
            }
```

2023-06-15 17:47 UTC, beombu commented on src/main/java/constant/Operator.java
> +    }
감사합니다!
가독성도 좋고 작업이 명시적으로 표현되어 말씀해주신 방식이 더 좋은 것 같습니다! stream을 잘 활용할 수 있도록 노력하겠습니다🙇‍♂️🙇‍♂️

2023-06-15 17:47 UTC, beombu commented on src/main/java/constant/Operator.java
> +    }
감사합니다! calculate가 온전히 하나의 기능만을 수행하는 것처럼 느껴집니다🤩🤩

### 변경
```java
    public static Integer calculate(Operator operator, Integer operand1, Integer operand2) {
        return operator.operation.apply(operand1, operand2);
    }
```

2023-06-15 17:47 UTC, beombu commented on src/main/java/model/converter/PostfixConverter.java
> +            postfixList.add(textSegment);
`else`와 `continue`을 어떻게 지양해야 하는지 어려웠는데 알려주셔서 감사합니다!🙇‍♂️🙇‍♂️

### 변경
```java
    private boolean isOperand(String textSegment) {
        return textSegment.matches(IS_NUMBER_PATTERN);
    }
```

2023-06-16 14:57 UTC, devcourse-ray commented on src/main/java/constant/Operator.java
> +    }
Operator 를 받아와야하나요?

2023-06-16 14:57 UTC, devcourse-ray commented on src/main/java/controller/CalculatorController.java
> +        return calculationResult;
여긴 그냥 합쳐줘도 되겠네요

2023-06-16 14:57 UTC, devcourse-ray commented on src/main/java/model/calculation/CalculationImpl.java
> +    }
메소드는 실행 순서대로 작성해주면 가독성이 높아져요

2023-06-16 14:57 UTC, devcourse-ray commented on src/main/java/model/calculation/CalculationImpl.java
> +        Integer number2 = numberStack.pop();
같은 Integer 값이라 calculateArithmetic를 통해 계산할 때 헷갈릴 여지가 있어요
+, * 는 순서가 상관 없지만 -, / 는 순서를 헷갈리면 안되겠죠?
이쪽 부분만 봐도 명확하게 판단이 되도록 표현하는게 중요해요

2023-06-18 08:42 UTC, beombu commented on src/main/java/model/calculation/CalculationImpl.java
> +        Integer number2 = numberStack.pop();
감사합니다..!! 순서를 알아볼 수 있도록 네이밍 해보도록 하겠습니다🙇‍♂️🙇‍♂️

2023-06-18 08:42 UTC, beombu commented on src/main/java/model/calculation/CalculationImpl.java
> +    }
실행 순서대로 정렬하였습니다✅✅ 감사합니다!

2023-06-18 08:42 UTC, beombu commented on src/main/java/constant/Operator.java
> +    }
Operator를 사용하지 않고 연산을 수행하도록 수정하겠습니다!!🙇‍♂️🙇‍♂️

2023-06-22 08:11 UTC, ICCHOI commented on src/main/java/constant/Operator.java
>      });
범철님이 짜신 계산 순서 로직이랑, 이 Operator 클래스의 계산 함수가 강하게 결합 되어 있다고 생각이 드네요.

2023-06-22 08:13 UTC, ICCHOI commented on src/main/java/model/calculation/CalculationImpl.java
>      private static final Stack<Integer> numberStack = new Stack<>();
```suggestion
    private final Stack<Integer> numberStack = new Stack<>();
```

2023-06-22 08:21 UTC, ICCHOI reviewed
수고하셨습니다!

2023-07-14 15:06 UTC, merged