[2기-강완수] 1주차 java-calculator 미션 제출입니다.
prgrms-be-devcourse/java-calculator pull request #29
Opened 2022-03-28 04:31 UTC by dhkstnaos

## 📌 과제 설명 
### 요구사항
- 객체지향적인 코드로 계산기 구현하기
    - [x]  더하기
    - [x]  빼기
    - [x]  곱하기
    - [x]  나누기
    - [x]  우선순위(사칙연산)
- [x]  테스트 코드 구현하기
- [x]  계산 이력을 맵으로 데이터 저장기능 만들기
    - 애플리케이션이 동작하는 동안 데이터베이스 외에 데이터를 저장할 수 있는 방법을 고안해보세요.
- [x] 정규식 사용
## 👩‍💻 요구 사항과 구현 내용 
![Screen Shot 2022-03-28 at 12 42 15 PM](https://user-images.githubusercontent.com/58693617/160322765-4c946874-901e-4028-a023-dc80578dfd42.png)
Input,InputImpl -> 입력 담당 메소드
Output, OutputImpl -> 출력 담당 메소드
Operator -> 사칙연산 담당 Enum
Option -> 옵션 담당 Enum
CalculatorRepository, CalculatorRepositoryImpl -> DB 저장(LinkedHashMap)
ServiceImpl -> 계산기 동작을 담당하는 메소드
CalculatorService,CalculatorServiceImpl ->  계산 및 조회를 담당
Validator, ValidatorImpl -> 검증 인터페이스 및 구현체

## 테스트 케이스
![Screen Shot 2022-03-28 at 12 45 29 PM](https://user-images.githubusercontent.com/58693617/160323030-df128c24-b1f8-43a0-8d47-b82b72abd2a7.png)

## 예외 처리 내역
ArithmeticException -> 0으로 나눌때 발생
EmptyStackException -> 숫자, 연산의 비율이 맞지 않을때
IllegalArgumentException -> 사칙연산이 연속해서 입력됐을때,사칙연산이 아닌 문자가 입력됐을때
NoSuchElementException -> 메뉴 옵션 중 1,2,3이 아닌 수를 입력했을때
NumberFormatException -> 1,2,3이 아닌 문자를 입력했을때

## 계산기 시연
![Screen Shot 2022-03-28 at 13 27 43 PM](https://user-images.githubusercontent.com/58693617/160326663-38f40071-2050-47b6-a999-a93ec221e1c7.png)

## ✅ 피드백 반영사항  

## ✅ PR 포인트 & 궁금한 점 
1. 테스트를 진행하면서 몇몇 중복된 테스트가 있었는데 이런 경우는 어쩔 수 없는 부분인지 궁금합니다.
2. ServiceImpl에서 run 메소드의 테스트 방법이 궁금합니다.
3. 현재 EmptyStackException이라는 예외가 있는데 메시지를 넣으려면 커스텀 클래스를 따로 만들어 넣어야 했습니다. 그러다 보니 하나의 예외처리를 위해 여러 메소드에 throws Exception이 추가되어 지저분한 느낌이었습니다. EmptyStack같이 예외를 특정할 수 있다면 굳이 커스텀 메시지를 안해도 될까요?

2022-03-28 10:57 UTC, woogiekim commented
*.class, *.iml 등과 같은 설정 혹은 바이너리코드는 올리지 않아야합니다.

File Changes 가 100개 에요 저걸 다 볼수없어요 ㅠ

설정파일, 빌드 된 파일들 모두 제외하고 다시 리뷰 요청해주세요!

2022-03-28 14:50 UTC, woogiekim requested changes
연산자와 피연산자 사이에 공백을 두는 것으로 봤는데,
그부분은 차치하고 리뷰했습니다.

코드작성으로 끝내지마시고, 차근차근 이야기하듯이 코드를 읽어보는 시간을 갖는게 어떨까 싶습니다.
개발할때 본인은 해당 도메인이나 로직이나 그런부분들이 되게 명확하고 잘 알고있는 상태에서 개발하기때문에
중요한 디테일을 놓쳐버리거나 변수, 메소드, 클래스의 이름이 중요 로직을 제대로 설명하지 못하는 경우가 생길수 있는거 같습니다.

2022-03-28 14:50 UTC, woogiekim commented on calculator/src/main/java/io/InputImpl.java
> +public class InputImpl implements Input {
흔히 인터페이스 구현체를 만들때 suffix로 Impl 을 사용하는 것을 하는 편이기도 하죠

그런식으로 사용하는것과 아닌것에는 어떤 차이가 있는지 조사해보고 어떤 장단점이있는지 찾아보세요

2022-03-28 14:50 UTC, woogiekim commented on calculator/src/main/java/Main.java
> +        Validator validator=new ValidatorImpl();
사소하지만 
`Validator validator=new ValidatorImpl();` 

이렇게 통일성을 깨는 컨벤션은 좋지 않습니다.

2022-03-28 14:50 UTC, woogiekim commented on calculator/src/main/java/io/OutputImpl.java
> +    public final String PRINT = "메뉴를 선택하세요\n1. 조회\n2. 계산\n3. 종료\n선택:";
PRINT 라는 이름은 메뉴를 선택해달라는 내용과 맞지않는 이름인거같습니다.

2022-03-28 14:50 UTC, woogiekim commented on calculator/src/main/java/model/Operator.java
> +        switch(operation) {
priority를 그냥 enum 나열할때 정해줘도 되지않을까요?

2022-03-28 14:50 UTC, woogiekim commented on calculator/src/main/java/model/Operator.java
> +                .orElseThrow(() -> new NoSuchElementException("올바른 수식을 입력해야 합니다."));
NoSuchElementException 와 올바른 수식을 입력해야 합니다.

이 두가지가 매칭이 되는거 같지 않습니다.

2022-03-28 14:50 UTC, woogiekim commented on calculator/src/main/java/model/Option.java
> +        /* 자바8 버전: switch문 Enum 에러 발생
switch case 로 작성하다가 어떤 에러가 발생해서 결국 if 문으로 대체했다는거 인거같은데,
구체적인 상황이없어서 이해하기 어렵습니다.

2022-03-28 14:50 UTC, woogiekim commented on calculator/src/test/java/service/CalculatorServiceImplTest.java
> +        boolean plus_minus = calculatorService.checkPriority(plus, minus);
자바에서는 카멜케이스를 이용해 변수명을 명명하는것이 관례입니다.

자바 명명규칙에 대해서 조사해보세요

2022-03-28 14:50 UTC, woogiekim commented on calculator/src/test/java/service/CalculatorServiceImplTest.java
> +        Assertions.assertThat(toPostFix).isEqualTo("[12.0, 22.0, 6.0, *, +]");
`assertThat(toPostFix).containsExactly(12.0, 22.0, 6.0, "*", "+")`

이런식의 검증이 더 좋을거같습니다.

2022-03-28 14:50 UTC, woogiekim commented on calculator/src/test/java/service/CalculatorServiceImplTest.java
> +                .hasMessage("숫자를 입력하세요");
메시지를 주실거라면 전체를 주시고, 아니면 안주는게 좋을거같습니다.

2022-03-28 14:50 UTC, woogiekim commented on calculator/src/main/java/service/ServiceImpl.java
> +public class ServiceImpl implements Runnable {
서비스라는게 뭘 말하는것인지 의미가 명확하지 않은거같습니다.

2022-03-28 14:50 UTC, woogiekim commented on calculator/src/test/java/service/ValidatorImplTest.java
> +    void 짝수_리스트_사이즈() {
테스트명이 어떤걸 검증하고 싶은 건지 표현해주지 못하고 있는거같습니다.

2022-03-29 10:44 UTC, woogiekim approved these changes
고생하셨습니다.

Array<Object> 부분에 대한 코멘트를 했는데
개선해볼 방법이 있는지 생각해보는 시간 갖으면 좋을거같습니다!

2022-03-29 10:44 UTC, woogiekim commented on calculator/src/main/java/service/Calculator.java
> +        ArrayList<Object> postFix = new ArrayList<>();
오브젝트가 와버리면 뭐가 오든 상관없게 되버려서 상당히 위험할거같아요

2022-03-29 10:44 UTC, merged

2022-03-29 11:11 UTC, dhkstnaos commented on calculator/src/main/java/service/Calculator.java
> +        ArrayList<Object> postFix = new ArrayList<>();
@woogiekim array도 저렇게 있으면 안될거 같네요 따로 반영해보도록 하겠습니다!! 부족함을 많이 느꼈습니다 감사합니다 !~!~😄👍