[2기-황승한] 1주차 java-calculator 미션 제출
prgrms-be-devcourse/java-calculator pull request #30
Opened 2022-03-28 05:06 UTC by jk05018

📌 과제 설명

객체 지향적인 코드로 계산기 만들기

전체적인 도메인을 결정한 뒤 TDD의 개발 순서에 따라 개발을 진행해 보았습니다.

Service와 Repository는 Interface를 사용하여 참조하도록 설정하여 교체가 용이하도록 했으며

Parser(해독기), ArithmeticUnit(연산기)같은 경우 인스턴스를 생성할 필요성을 느끼지 못해 static 메서드로 제공하였습니다.

계산기에 사용되는 값은 int, double을 사용하는 것보다 새로운 불변객체(Value)를 생성해 연산을 진행했으며 BigDecimal을 필드로 가지고 있어 정확한 실수 연산을 제공하도록 하도록 했습니다.

제가 느낀 미흡한점들은 아래 궁금한 점에서 여쭈어 보겠습니다!

👩‍💻 요구 사항과 구현 내용

객체지향적인 코드로 계산기 구현하기

더하기
빼기
곱하기
나누기
우선순위(사칙연산)
테스트 코드 구현하기
계산 이력을 맵으로 데이터 저장기능 만들기
정규식 사용
🍔클래스 설명

Application Layer와 Engine Layer를 나눠 Application Layer에서는 입출력을 Engine Layer에서는 핵심 로직을 구현하였습니다.

Application Layer

Console : 입출력을 담당하는 클래스(Input, Output 인터페이스 상속)
Parser : formula(공식)이 올바른 패턴으로 입력되었는지 정규 표현식을 사용하여 검증하는 클래스
Calculator : 외부와 상호작용하고 Engine의 핵심 로직을 호출하는 클래스
Engine Layer

Menu : 메뉴에 대한 정보를 제공하고 해당하는 service를 호출하는 enum 클래스
CalculatorService(Interface) : 계산기의 핵심 기능을 제공하는 interface
InquiryService : 조회 서비스 제공
CalculateService : 계산 서비스 제공
ClearService : 현재까지 기록 초기화 서비스 제공
CalculatorRepository(Interface) : repository에 접근하는 메서드 제공
MemoryCalculatorRepository : Map을 이용한 Repository
ArithmeticUnit : 연산기. 입력된 formula(공식)을 연산하고 답을 반환
Value(불변 객체) : 계산에 사용하는 값 객체(BigDecimal을 사용하고 있어 실수연산도 제공)
Operator(연산자,Enum) : +, -, * % 연산 제공
클래스 다이어그램

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/68465557/160329601-c3a58802-cff3-422e-a07d-57263d6424e9.png">

✅ PR 포인트 & 궁금한 점

커밋 단위에 대해서 여쭈어보고 싶습니다
이번에 개발을 진행하다 보면 기존의 작성했던 코드들에서 문제점을 발견하고 재수정하는 일이 빈번하게 발생했습니다.

재수정한 내용들은 따로 커밋 메세지를 작성하여 새로운 커밋을 제공해야 하는지 아니면 기존의 코드에서 재수정한 내용들을 개발을 진행하던 커밋에 추가시켜 언급해 주는 것으로 충분한지 궁금합니다.

Enum
Operator같은 경우 Enum을 사용하면 좋겠다라는 확신이 있습니다.

제가 여쭈어보고 싶은 점은 Menu도 Enum을 사용해서 작성하였는데 이 방법이 과한 사용인지 적절한 사용인지 빅토리님의 생각이 궁금합니다.

결합도
처음에 Service마다 동일한 Repository를 제공하고 싶었습니다.

Repository를 Singleton으로 만들어 제공해보면 어떨까라는 생각을 해보았지만 Repository는 무상태가 아니가 때문에 Singleton으로 제공하면 안된다라고 결론을 내렸습니다.

고민을 계속 해보다 좋은 생각이 나지 않아 Calculator에서 Service마다 메서드에 동일한 Repository를 넘겨주는 선택을 하였고, 이 선택은 결합도를 높였다고 생각합니다.

CalculatorService 인터페이스를 상속받은 각각의 구현체 클래스 InquiryService, CalculateService, ClearService에서 동일한 repository를 제공할 수 있는 방법 혹은 생각나시는 디자인 패턴이 있는지 궁금합니다.

2022-03-30 04:25 UTC, VictoryPark requested changes
커밋 단위에 대해서 여쭈어보고 싶습니다
이번에 개발을   진행하다 보면 기존의 작성했던 코드들에서 문제점을 발견하고 재수정하는 일이 빈번하게 발생했습니다.

재수정한 내용들은 따로 커밋 메세지를 작성하여 새로운 커밋을 제공해야 하는지 아니면 기존의 코드에서 재수정한 내용들을 개발을 진행하던 커밋에 추가시켜 언급해 주는 것으로 충분한지 궁금합니다.

- => 제 개인적인 경험으로는 커밋은 쌓이는 것에 의미가 있는 것 같습니다. 그래서 새로 커밋을 쌓는 것이 맞다고 생각하고, 새로운 커밋 메세지에서 이전 커밋의 아이디를 언급해주면 좋겠죠.

Enum
Operator같은 경우 Enum을 사용하면 좋겠다라는 확신이 있습니다.

제가 여쭈어보고 싶은 점은 Menu도 Enum을 사용해서 작성하였는데 이 방법이 과한 사용인지 적절한 사용인지 빅토리님의 생각이 궁금합니다.

- => Menu 클래스에서 제가 언급했다시피, 승한님도 말씀하셨다시피 확신이 없이 작성한 코드라는 생각이 듭니다. 왜 Enum으로 작성하였는지 한번 다시 고민해보시고 다른 방법으로 풀 수 있는 방법은 없는지 고민해볼 수 잇는 좋은 기회가 될 것 같습니다!!

결합도
처음에 Service마다 동일한 Repository를 제공하고 싶었습니다.

Repository를 Singleton으로 만들어 제공해보면 어떨까라는 생각을 해보았지만 Repository는 무상태가 아니가 때문에 Singleton으로 제공하면 안된다라고 결론을 내렸습니다.

고민을 계속 해보다 좋은 생각이 나지 않아 Calculator에서 Service마다 메서드에 동일한 Repository를 넘겨주는 선택을 하였고, 이 선택은 결합도를 높였다고 생각합니다.

CalculatorService 인터페이스를 상속받은 각각의 구현체 클래스 InquiryService, CalculateService, ClearService에서 동일한 repository를 제공할 수 있는 방법 혹은 생각나시는 디자인 패턴이 있는지 궁금합니다.

- => 승한님이 말씀하신 'repository가 무상태가 아니다' 라는 개념에 대해서 더 들어보고 싶네요.
사실 이번 과제에서 Service과 Repository의 레이어드 아키텍쳐가 나올 줄은 몰랐습니다. ㅎㅎ
객체 지향의 역할과 책임과는 조금 다를 수 있기 때문에..
일단 승한님이 repository를 메소드에 넘김으로써 결합도를 높였다고 생각하셨는데, 오히려 결합도를 낮췄다고 볼 수 있습니다. 결합도와 응집도의 예시 코드를 작성하시면서 더 고민해보셔야 될것 같아요.

그리고 전체적으로 테스트 코드와 클래스별 역할 분리를 많이 고민하신것 같아요!!
매우 칭찬드립니다^0^
그러나 한가지 아쉬운 점은, console에서 입력되는 값에 대해 validate 하는 부분이 없어서
Exception이 날 수 있는 가능성이 있습니다.
어떻게 입력되면 계산이 안될 수 있는지, 한번 더 고민해보셔도 좋을 것 같아요!
고생하셨습니다 ㅎㅎ

2022-03-30 04:25 UTC, VictoryPark commented on src/main/java/com/programmers/calculator/engine/util/ArithmeticUnit.java
> +	public static String calculate(String formula) {
calculate 가 어느정도 util 성 특징을 갖고 있는 것은 맞지만,
계산기 구현이라는 과제에서 봤을때, ArithmeticUnit의 객체에 종속되어있는 것이 맞지 않을까 생각되네요..

2022-03-30 04:25 UTC, VictoryPark commented on src/main/java/com/programmers/calculator/engine/service/CalculateService.java
> +		if (repository.alreadyCalculated(formula)) {
오 미리 저장되어있는 연산이 있는지 확인하는 로직은 매우 좋다고 생각합니다!!😊

2022-03-30 04:25 UTC, VictoryPark commented on src/main/java/com/programmers/calculator/engine/util/ArithmeticUnit.java
> +		calculateByType(values, operators, Operator.PriorityType.HIGH);
PriorityType을 굳이 이곳에서 method를 순차적으로 부르는데 쓰일 수 밖에 없었을까요?

2022-03-30 06:30 UTC, jk05018 commented on src/main/java/com/programmers/calculator/engine/repository/MemoryCalculatorRepository.java
> +		StringBuilder builder = new StringBuilder();
갑사합니다!!

2022-03-30 06:38 UTC, jk05018 commented on src/main/java/com/programmers/calculator/engine/util/ArithmeticUnit.java
> +		assert type != null;
메서드에 잘못된 매개변수가 들어오면 에러가 날 확률이 높기 때문에 무조건 유효한지 검사해야 한다고 알고있습니다!
그래서public이나 protected와 같은 public API는 Objects.requireNonNull()을 통해 Null인지 아닌지 검사를 실시했으며
private와 같은 경우도 유효한 값이 넘어간다는 것을 보증하기 위해 assert를 사용하였습니다!

아직 미숙하지만 매개변수가 잘못 들어올 수 있다는 가정을 하고 개발하는 습관을 들이면 좋을 것 같아서 사용한것 같습니다!

2022-03-30 06:39 UTC, jk05018 commented on src/main/java/com/programmers/calculator/engine/util/Operator.java
> +	public enum PriorityType {
외부 Operator 클래스에서만 쓰이므로 Public이 아니어도 괜찮을거같네요! 감사합니다!

2022-03-30 06:39 UTC, jk05018 commented on src/test/java/com/programmers/calculator/CalculatorApplicationTests.java
> +@SpringBootTest
앜 처음에 생성된 테스튼거같습니다!

2022-03-30 06:39 UTC, jk05018 commented on src/main/java/com/programmers/calculator/engine/Parser.java
> +public class Parser {
감사해요!!!

2022-03-30 06:40 UTC, jk05018 commented on src/main/java/com/programmers/calculator/engine/Menu.java
> +	public static Menu fineMenu(String buttonName) {
넵 findMenu를 잘못 사용한것 같습니다! 하하

2022-03-30 06:52 UTC, jk05018 commented on src/main/java/com/programmers/calculator/engine/service/CalculateService.java
> +		if (repository.alreadyCalculated(formula)) {
하하 감사합니다!

2022-03-30 06:52 UTC, jk05018 commented on src/main/java/com/programmers/calculator/engine/util/ArithmeticUnit.java
> +		calculateByType(values, operators, Operator.PriorityType.HIGH);
calculate하는 로직저도 많이 부실하다고 생각했어요,,
좀 더 좋은 로직을 생각해 보겠습니다!

2022-03-30 06:53 UTC, jk05018 commented on src/main/java/com/programmers/calculator/engine/util/ArithmeticUnit.java
> +	public static String calculate(String formula) {
아 이렇게도 생각이 가능하네요!! 좋은 insight인 것 같습니다! 감사해요!

2022-03-30 06:55 UTC, jk05018 commented on src/main/java/com/programmers/calculator/engine/Menu.java
> +public enum Menu {
네 가장 애매하다고 생각되던 부분이 이 메뉴부분이었는데 많은 고민을 해 봐야할 것 같습니다!

2022-03-31 13:01 UTC, VictoryPark commented on src/main/java/com/programmers/calculator/engine/util/ArithmeticUnit.java
> +		assert type != null;
말씀하신대로 매개변수의 유효성을 검사하는것은 매우 중요합니다!
그러나 매번 유효한지 검사하는 것은 비즈니스 로직 코드와 항상 혼재하기 때문에 정말 매개변수에 대한 검증이 필요할때만 사용하는 것을 권장합니다.
현재 사용하신 메소드는 사용하는 메소드의 흐름상, null이 들어올 가능성이 없는 것으로 보여지네요 🙂
assert의 사용 범위에 대해서도 한번 조사해보시는 것도 좋을 것 같아용!!

2022-04-29 10:13 UTC, merged