[2기-박우진] 1주차 java-calculator 미션 제출합니다.
prgrms-be-devcourse/java-calculator pull request #33
Opened 2022-03-28 15:16 UTC by dbslzld15

## 📌 과제 설명 
* 객체지향적인 코드로 계산기 구현하기
- [x] 더하기
- [x] 빼기
- [x] 곱하기
- [x] 나누기
- [x] 우선순위(사칙연산)
- [x] 테스트 코드 구현하기
- [x] 계산 이력을 맵으로 데이터 저장기능 만들기
- [x] 정규식 사용
## 👩‍💻 요구 사항과 구현 내용 
### 프로젝트 구조
![image](https://user-images.githubusercontent.com/47207658/160413556-873c970a-deb9-437d-8a27-c09f2912701e.png)
* io 패키지는 콘솔에 대한 입출력을 담당하도록 구성하였습니다. 
    * Console 클래스는 Input, Output 인터페이스를 상속합니다.

* model 패키지는 Calculator 클래스와 Expression 클래스로 구성하였습니다.
   * Calculator(계산기) 클래스는 사칙연산을 수행 후 결과값을 반환하도록 하였습니다.
   * Expression(수식) 클래스는 수식 필드와 수식에 대한 결과값 필드를 갖도록 구성하였습니다.
   * 생성자를 통해 Expression 클래스 생성 시 해당 수식이 유효한지 정규식을 통해 검증합니다.

* repository 패키지는 Expression 클래스를 저장할 수 있는 저장소입니다.
    * MemoryExpressionRepository 클래스는 ExpressionRepository 인터페이스를 상속하며 해시맵을 통해 값을 저장하고 꺼내옵니다.

* service 패키지는 연산에 대한 비즈니스 로직을 담당하는 클래스로 구성되어 있습니다.
    *  ExpressionService에서는 콘솔로 입력받은 수식을 통해 Expression 객체 생성 및 검증, 사칙연산 수행 후 메모리에 저장, 결과값을 return 해주는 로직으로 구현했습니다.

### 연산 동작 과정 설명
1. 콘솔로부터 수식을 입력 받으면 Expression 객체를 생성하며 해당 수식이 유효한지 검증합니다.
만약, 해당 수식이 유효하지 않으면 IllegalArgumentException 예외를 발생시킵니다. 

2. 빈 공백(" ")을 기준으로 입력된 수식을 split합니다. split된 배열을 순회하며 곱셈 및 나눗셈 연산을 수행합니다.
해당 연산은 exprResults이라는 리스트에 곱셈, 나눗셈이 수행된 연산자(덧셈, 뺄셈), 피연산자(숫자)를 저장하는 방식으로 구현하였습니다.

3. 덧셈, 뺄셈 연산자와 숫자가 담긴 exprResults를 순회하며 연산자를 기준으로 덧셈 뺄셈을 수행합니다.

4. 최종 연산 결과는 Expression 객체에 결과값 필드인 calcResult를 set해 넣어줍니다.

### 수식 검증 로직
수식 검증 로직은 Expression 생성자에 들어가 있습니다.

1. 정규식을 이용해 연산자와 피연산자의 개수를 확인합니다. 수식은 피연산자의 개수가 항상 연산자의 개수보다 하나 많아야한다 라는 가정하에 검증 로직을 구성해보았습니다.
2. 정규식을 이용해 연산자 혹은 피연산자만 입력되었는지 확인합니다.

## ✅ PR 포인트 & 궁금한 점 
1. 현재 Calculator라는 클래스가 필드를 가지지 않고 계산을 하는 메소드로만 구성이 되어있는데 model 패키지 보단 service 패키지 내에 두는게 나을지 궁금합니다!
2. Expression 클래스 생성자에 검증 로직을 넣었는데 이 부분을 분리해야 할까요? 따로 Validator라는 클래스를 만들어서 검증 로직을 넣는게 OOP 관점에서 더 적절한건지 궁금합니다.
3.  OOP 관점에서 설계가 제대로 되었는지 궁금합니다.. 패키지 구조나 클래스들을 보면 뭔가 스프링의 구조를 따라가려고 한거같네요..
4. 테스트 코드에서 더 추가되야 할 사항이 있을까요? 테스트 코드를 작성하면서도 옳게 작성이 된 건지... 의구심이 생겼습니다..
5. 연산을 수행하는 로직에서 제가 너무 복잡한게 구현한게 아닌지 궁금합니다. 추후 유지보수 측면에서 스택을 사용한 후위연산을 사용하는게 더 바람직할까요?
6. 연산을 수행하거나 Expression 생성자 검증로직에서 콘솔로부터 입력받은 수식을 split을 하게 되는데 이 부분은 Parser라는 클래스를 따로 두어서 파싱하도록 하는게 OOP 관점이나 확장성 측면에서 더 적절할지 궁금합니다.

코드를 보다보니 제대로 코드를 작성 하고 있는건지 의구심만 늘어나는거 같네요 ㅎㅎ.. 멘토님의 소중한 의견 기다리고 있겠읍니다 (_ _)

2022-03-29 12:13 UTC, SeokRae requested changes
![image](https://user-images.githubusercontent.com/17922700/160602641-ec9e5c60-5f64-4684-8dae-b53216007c08.png)

1. 자바 패키지 구조를 갖도록 하는 것이 프로젝트를 이해하기에 좋을 듯 싶습니다. [패키지](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html)

2. 어느정도 구현하신 뒤 테스트 코드를 짜게 되면 이를 리펙토링 하기가 쉽지 않습니다.
TDD가 쉽지 않으시다면 작게 구현하고 테스트 코드를 작성하는 식으로 점차 개선해나가는 방법이 좋아보입니다.

천천히 같이 고민해보면서 개선해나가보시죠!

2022-03-29 12:13 UTC, SeokRae commented on src/main/java/service/ExpressionService.java
> +public class ExpressionService {
해당 클래스의 역할은 무엇일까요?

2022-03-29 12:13 UTC, SeokRae commented on src/main/java/service/ExpressionService.java
> +        Calculator calculator = new Calculator();
각각의 메서드에서 Calculator를 생성하는 중복 코드를 제거하는 것부터 시작해 보는 것도 좋을 것 같습니다.

2022-03-29 12:13 UTC, SeokRae commented on src/main/java/service/ExpressionService.java
> +        Calculator calculator = new Calculator();
위 내용과 동일합니다. Calculator 객체 생성 중복 코드

2022-03-29 12:31 UTC, SeokRae commented
> ## 📌 과제 설명
> * 객체지향적인 코드로 계산기 구현하기
> 
> * [x]  더하기
> * [x]  빼기
> * [x]  곱하기
> * [x]  나누기
> * [x]  우선순위(사칙연산)
> * [x]  테스트 코드 구현하기
> * [x]  계산 이력을 맵으로 데이터 저장기능 만들기
> * [x]  정규식 사용
> 
> ## 👩‍💻 요구 사항과 구현 내용
> ### 프로젝트 구조
> ![image](https://user-images.githubusercontent.com/47207658/160413556-873c970a-deb9-437d-8a27-c09f2912701e.png)
> 
> * io 패키지는 콘솔에 대한 입출력을 담당하도록 구성하였습니다.
>   
>   * Console 클래스는 Input, Output 인터페이스를 상속합니다.
> * model 패키지는 Calculator 클래스와 Expression 클래스로 구성하였습니다.
>   
>   * Calculator(계산기) 클래스는 사칙연산을 수행 후 결과값을 반환하도록 하였습니다.
>   * Expression(수식) 클래스는 수식 필드와 수식에 대한 결과값 필드를 갖도록 구성하였습니다.
>   * 생성자를 통해 Expression 클래스 생성 시 해당 수식이 유효한지 정규식을 통해 검증합니다.
> * repository 패키지는 Expression 클래스를 저장할 수 있는 저장소입니다.
>   
>   * MemoryExpressionRepository 클래스는 ExpressionRepository 인터페이스를 상속하며 해시맵을 통해 값을 저장하고 꺼내옵니다.
> * service 패키지는 연산에 대한 비즈니스 로직을 담당하는 클래스로 구성되어 있습니다.
>   
>   * ExpressionService에서는 콘솔로 입력받은 수식을 통해 Expression 객체 생성 및 검증, 사칙연산 수행 후 메모리에 저장, 결과값을 return 해주는 로직으로 구현했습니다.
> 
> ### 연산 동작 과정 설명
> 1. 콘솔로부터 수식을 입력 받으면 Expression 객체를 생성하며 해당 수식이 유효한지 검증합니다.
>    만약, 해당 수식이 유효하지 않으면 IllegalArgumentException 예외를 발생시킵니다.
> 2. 빈 공백(" ")을 기준으로 입력된 수식을 split합니다. split된 배열을 순회하며 곱셈 및 나눗셈 연산을 수행합니다.
>    해당 연산은 exprResults이라는 리스트에 곱셈, 나눗셈이 수행된 연산자(덧셈, 뺄셈), 피연산자(숫자)를 저장하는 방식으로 구현하였습니다.
> 3. 덧셈, 뺄셈 연산자와 숫자가 담긴 exprResults를 순회하며 연산자를 기준으로 덧셈 뺄셈을 수행합니다.
> 4. 최종 연산 결과는 Expression 객체에 결과값 필드인 calcResult를 set해 넣어줍니다.
> 
> ### 수식 검증 로직
> 수식 검증 로직은 Expression 생성자에 들어가 있습니다.
> 
> 1. 정규식을 이용해 연산자와 피연산자의 개수를 확인합니다. 수식은 피연산자의 개수가 항상 연산자의 개수보다 하나 많아야한다 라는 가정하에 검증 로직을 구성해보았습니다.
> 2. 정규식을 이용해 연산자 혹은 피연산자만 입력되었는지 확인합니다.
> 
> ## ✅ PR 포인트 & 궁금한 점
> 1. 현재 Calculator라는 클래스가 필드를 가지지 않고 계산을 하는 메소드로만 구성이 되어있는데 model 패키지 보단 service 패키지 내에 두는게 나을지 궁금합니다!
> 2. Expression 클래스 생성자에 검증 로직을 넣었는데 이 부분을 분리해야 할까요? 따로 Validator라는 클래스를 만들어서 검증 로직을 넣는게 OOP 관점에서 더 적절한건지 궁금합니다.
> 3. OOP 관점에서 설계가 제대로 되었는지 궁금합니다.. 패키지 구조나 클래스들을 보면 뭔가 스프링의 구조를 따라가려고 한거같네요..
> 4. 테스트 코드에서 더 추가되야 할 사항이 있을까요? 테스트 코드를 작성하면서도 옳게 작성이 된 건지... 의구심이 생겼습니다..
> 5. 연산을 수행하는 로직에서 제가 너무 복잡한게 구현한게 아닌지 궁금합니다. 추후 유지보수 측면에서 스택을 사용한 후위연산을 사용하는게 더 바람직할까요?
> 6. 연산을 수행하거나 Expression 생성자 검증로직에서 콘솔로부터 입력받은 수식을 split을 하게 되는데 이 부분은 Parser라는 클래스를 따로 두어서 파싱하도록 하는게 OOP 관점이나 확장성 측면에서 더 적절할지 궁금합니다.
> 
> 코드를 보다보니 제대로 코드를 작성 하고 있는건지 의구심만 늘어나는거 같네요 ㅎㅎ.. 멘토님의 소중한 의견 기다리고 있겠읍니다 (_ _)


## 1. 현재 Calculator라는 클래스가 필드를 가지지 않고 계산을 하는 메소드로만 구성이 되어있는데 model 패키지 보단 service 패키지 내에 두는게 나을지 궁금합니다!

-> 스프링의 레이어드 아키텍처는 각각의 레이어가 하는 역할 및 관심사가 있고 그 안에 도메인과 관련 된 내용들이 흩어지게 되어 과제의 목적인 객체지향에서 멀어지게 됩니다. 

## 2. Expression 클래스 생성자에 검증 로직을 넣었는데 이 부분을 분리해야 할까요? 따로 Validator라는 클래스를 만들어서 검증 로직을 넣는게 OOP 관점에서 더 적절한건지 궁금합니다.

-> Validator 라는 유틸성 클래스는 전역에서 사용할 수 있도록 static 메서드로 제공하게 되는데요. 여기저기서 공통으로 사용하는 용도로 존재하는 경우에는 유틸성 클래스를 만들 수도 있으나, 특정 객체의 고유한 유효성 검사를 하는 경우에는 그 객체에 책임을 다하는 것이 맞다고 생각됩니다.

## 3. OOP 관점에서 설계가 제대로 되었는지 궁금합니다.. 패키지 구조나 클래스들을 보면 뭔가 스프링의 구조를 따라가려고 한거같네요..

-> 이는 위에서 말씀 드렸습니다. ! 나 ~ 중을 위해서 라도 다시 고민해보시고 리펙토링 해보시죠 !

## 4. 테스트 코드에서 더 추가되야 할 사항이 있을까요? 테스트 코드를 작성하면서도 옳게 작성이 된 건지... 의구심이 생겼습니다..

-> 테스트가 깨지지 않는 상태를 유지하면서 리펙토링을 할 수 있는 코드인지 고민해보는 것이 좋을 것 같습니다.
테스트의 목적은 단순히 연산이 되는지, 내가 작성한 코드가 잘 돌아가는지 검증 하는 것 뿐만아니라 리펙토링을 통해 점차 객체지향적인 코드를 만드는 것이 목적입니다.

## 5. 연산을 수행하는 로직에서 제가 너무 복잡한게 구현한게 아닌지 궁금합니다. 추후 유지보수 측면에서 스택을 사용한 후위연산을 사용하는게 더 바람직할까요?

-> 로직적인 부분은 자유입니다. !

## 6. 연산을 수행하거나 Expression 생성자 검증로직에서 콘솔로부터 입력받은 수식을 split을 하게 되는데 이 부분은 Parser라는 클래스를 따로 두어서 파싱하도록 하는게 OOP 관점이나 확장성 측면에서 더 적절할지 궁금합니다.

-> 클래스 다이어그램을 보면서 한번 고민해보시죠. !  입력받는 곳에서 식을 검증하여 연산을 담당하는 객체에 전달하여 처리할 수 있게 할 것인지 지금 처럼 연산을 하기 전에 식을 검증할 것인지.. 구현한 내용의 객체 또는 메서드의 역할을 잘 하고 있는지 확인해보시죠!.

2022-03-30 08:42 UTC, dbslzld15 reviewed
전체적으로 리팩토링이 필요할거같네요 ㅎㅎ.. 말씀해주신 부분들 하나씩 수정해보겠습니다.
TDD도 적용해보면서 리팩토링 해보겠습니다!

2022-03-30 08:42 UTC, dbslzld15 commented on src/main/java/service/ExpressionService.java
> +    public double calculateExpression(String exprInput) {
제가 생각했었을땐 해당 메소드가 `계산`이라는 역할만 갖고 수행한다고 생각해서 
역할을 많이 갖는다는 생각은 못했었는데 다시 보니 모든게 집약되어 있네요
항상 역할은 잘게 분리하는게 좋은걸까요? 분리해보겠습니다!

2022-03-30 08:42 UTC, dbslzld15 commented on src/main/java/model/Calculator.java
> +public class Calculator {
가장 고민이 많이 되는 부분이네요.. 구글링 해봤을때  enum 타입을 사용하기도 하더라구요
enum을 사용할 줄은 사실 생각도 못한 부분이었습니다

2022-03-30 08:42 UTC, dbslzld15 commented on src/main/java/service/ExpressionService.java
> +    private void multiplyAndDivide(Expression expression, List<String> exprResults) {
`Calculator` 객체를 생성하는 부분, 수식을 `split()` 하는 부분 등을 분리하는 정도면 될까요..? 아니면 for문 안에 있는 전체적인 로직을 분리할 수 있을만큼 분리해야 할까요?

2022-03-30 15:33 UTC, SeokRae commented on src/main/java/io/Console.java
> +    public Console(Scanner scanner) {
스캐너만 봤을때는 클라이언트에서 주입하여 사용해야 할 만큼 기능이 필요해보이지 않아서 해당 클래스 내에서 선언하는 것이 좋아보이네요.!

2022-03-30 15:36 UTC, SeokRae commented on src/main/java/model/Calculator.java
> +public class Calculator {
이 부분이 핵심 내용이긴 합니다. 계산에 대한 내용을 상태와 행위를 함께 관리할 수 있는 enum이라는 객체로 관리할 수도 있고, 인터페이스를 통해 각각의 연산을 클래스로 만들어서 관리할 수도 있을 것 같습니다. 
고민을 해야 하는 부분은 이렇게 관리를 했을 때 객체지향 원칙의 어떤 내용으로 설명을 할 수 있을까? 이지 않을까 생각됩니다.

2022-03-30 15:43 UTC, SeokRae commented on src/main/java/model/Expression.java
> +    private Double calcResult = null;
변수는 primitive type 과 reference type, 두 가지가 존재합니다.
각각의 변수와 값의 범위, 그 값들이 저장되는 메모리까지 공부해보시면 좋을 것 같습니다.
그리고 선언되는 위치인 클래스 변수, 인스턴스 변수, 지역 변수에 대해서 한번 짚고 넘어가는 것도 좋아보입니다.
그 위치에 따라 초기화가 되는지 안되는지도 알 수 있거든요. !

2022-03-30 15:45 UTC, SeokRae commented on src/main/java/service/ExpressionService.java
> +    public double calculateExpression(String exprInput) {
현재 과제에서 이것저것 도전해보도록 하는 것이 목적이라 저는 다양하게 작성해보시는 것을 추천드립니다.

2022-04-03 07:21 UTC, dbslzld15 commented
멘토님 안녕하세요! 말씀해주신 부분 전체적으로 수정해보았습니다

변경사항에 대해 말씀드리자면..

* 기존에 있던 Calculator 클래스를 Operator Enum 클래스로 변경하였습니다.
* 기존에 있던 CalculatorService 클래스를 Calculator로 변경하였습니다.
* util 패키지 내에 StringUtils 클래스를 추가해 문자열 자르기(split) 메소드를 제공하도록 하였습니다.
* Expression 클래스 내 splitExpressions라는 문자열 배열 필드를 갖도록 하였습니다.
* MemoryExpressionRepository 클래스의 경우 기존 Map에서 List를 갖도록 변경하였습니다.
* 자바 패키지 구조를 갖도록 수정했습니다.

말씀해주신대로 너무 많은 역할을 가지지않도록 유의하면서 수정해보았습니다!

다만, Calculator 클래스 내에 `multiplyAndDivide()` 메소드에서 아직도 많은 역할을 가지고 있는거 같아서 고민이네요..
멘토님의 소중한 리뷰 기다리고 있겠습니다 감사합니다!

2022-04-04 16:31 UTC, SeokRae reviewed
![image](https://user-images.githubusercontent.com/17922700/161590305-ff61c5d5-87a7-4b56-b320-a0825d42cc41.png)


1. 기능 별로 테스트 코드 작성 하신 것 좋습니다. @DisplayName, @ValueSource 등등 사용할 만한 내용은 아닐 수도 있지만 학습 해보시는 것이 좋을 것 같습니다.

2. 커멘트로 남기긴 했지만 유틸 클래스가 불가항력으로 생성되는 경우 private 생성자를 통해 외부에서 불필요하게 객체를 생성하는 것을 막는 것이 좋습니다.

## 궁금한거

> 다만, Calculator 클래스 내에 multiplyAndDivide() 메소드에서 아직도 많은 역할을 가지고 있는거 같아서 고민이네요..

식에 대한 파싱, 연산 처리, 저장까지 한 번 에 하다 보니 어쩔 수 없는 부분인 것 같네요. 저도 고민이 되네요. 😂

2022-04-04 16:31 UTC, SeokRae commented on src/main/java/com/programmers/model/Expression.java
> +    private Double calcResult;
Double를 사용하신 이유가 궁금합니다. !

2022-04-05 02:13 UTC, dbslzld15 reviewed
코멘트 주신 부분 다시 수정하겠습니다!

2022-04-05 13:32 UTC, SeokRae commented
![image](https://user-images.githubusercontent.com/17922700/161760175-782864f2-0812-4f7c-ab32-5cc6cfcf4874.png)

계속 고민해서 수정하시는 노력에 감탄합니다.!

어느정도 기본적인 부분이 정리가 되어 다른 시각으로 접근해보기 위한 피드백을 드리고자 합니다.
`계산기` 라는 전체적인 프로그램이지만 다이어그램을 보시면서 객체들의 역할과 그에 따라 상호작용해야 하는 클래스가 연결되어있는지 고민해보는 시간을 갖는 것도 좋을 것 같습니다.
현재는 대부분 클래스가 Expression이라는 클래스에 의존하고 있습니다.

고민해 볼 만한 내용은 
예를 들어 `Expression`이라는 객체는 식이라는 필드와 그 식이 Split된 배열 필드가 존재합니다.
`Console`에서 입력받은 문자열 값을 Expression를 통해 유효성 검사 후에 
`Calculator`에게 `연산자`와 `피연산자`라는 인자 값만 넘겨서 연산 후 반환받는 `반복적인 처리를 해주는 객체`가 있다면 보다 역할이 분리된 구조를 갖게 되지 않을까? 라는 고민도 할 수 있을 것 같습니다.

> 첫번째로는 테스트코드 작성 시 제가 작성한 것처럼 테스트 메소드를 한글로 작성하기보단 영문 메소드명 + @DisplayName을 활용해서 작성하는게 조금 더 명시적이고 좋은 방법인지 궁금합니다! 보통 실무에서는 어떤 방식으로 사용하나요?

이 부분은 회사마다 다를 수가 있다고 생각되는데요. 우리 회사에서는 이렇게 쓴다 하면서 테스트 메서드 명을 한글로 쓰는 블로그도 많이 보이고, @DisplayName을 사용하는 글도 많이 본 것 같습니다.
저는 개인적으로 어노테이션을 활용합니다.

> 두번째로는 테스트코드에서 given을 통해 주어지는 입력 값을 선언하는 것 보다는 @valuesource를 사용해 입력 값을 선언하는 편이 나을지 궁금합니다!

우선 위 어노테이션에 다수의 값을 넣을 수 있기 때문에 비슷한 유형에 대한 테스트를 한 번에 할 수 있습니다.
빈 값 또는 Null에 대한 값을 테스트 할 수 있는 @NullAndEmptySource
다양한 타입의 데이터를 넣어 테스트 할 수 있는 @ValueSource
단순한 값이 아니라 더 복잡한 값들을 테스트 할 수 있는 @MethodSource
등등 유용한 어노테이션이 있어서 이 부분은 필수로 학습이 필요해보입니다.

[참고](https://junit.org/junit5/docs/current/user-guide/)

2022-04-06 15:48 UTC, dbslzld15 commented
꼼꼼하고 소중한 리뷰 감사합니다!! 

남겨주신 리뷰중에 `Calculator에게 연산자와 피연산자라는 인자 값만 넘겨서 연산 후 반환받는 반복적인 처리를 해주는 객체`에 대해서 말씀해주시고 코드를 어떻게 작성해야 할지 고민해보았는데요...

만약 그렇게 한다면 사칙연산의 우선순위까지 보장하면서 처리가 가능할지에 대해서 궁금합니다..! 사칙연산 우선순위까지 보장하면서 처리하려면 로직이 생각보다 복잡해질꺼같은데 괜찮을까요?

2022-04-07 12:04 UTC, SeokRae commented
> 꼼꼼하고 소중한 리뷰 감사합니다!!
> 
> 남겨주신 리뷰중에 `Calculator에게 연산자와 피연산자라는 인자 값만 넘겨서 연산 후 반환받는 반복적인 처리를 해주는 객체`에 대해서 말씀해주시고 코드를 어떻게 작성해야 할지 고민해보았는데요...
> 
> 만약 그렇게 한다면 사칙연산의 우선순위까지 보장하면서 처리가 가능할지에 대해서 궁금합니다..! 사칙연산 우선순위까지 보장하면서 처리하려면 로직이 생각보다 복잡해질꺼같은데 괜찮을까요? 물론 저의 생각의 한계일 수도 있습니다..
> 
> 말씀해주신 테스트 관련 어노테이션들이랑 Junit 레퍼런스도 봐야겠네요 ㅎㅎ 감사합니다!!

고민을 해보는 것부터가 시작인 것 같습니다. 

![image](https://user-images.githubusercontent.com/17922700/162193511-4458e001-2c99-4980-a6a0-00ad53881949.png)

제가 고민해본 구현 순서는 
1. 연산자(ArithmeticOperators), 피연산자(double)에 대한 wrapper 클래스를 만들어 유효성 검사 또는 형변환에 대한 책임을 위임
2. 식이라는 클래스를 통해 해당 식에 대한 유효성 검사하고 연산에 대한 정렬 후 연산자와 피연산자를 분리하여 저장할 자료구조를 필드로 저장
3. 이후 식 이라는 클래스 내에 저장된 연산자와 피 연산자를 하나씩 꺼내 모두 처리 될 때까지 반복하여 연산

일단은 제가 위에서 말씀 드렸던 부분에 대한 구조를 생각한 내용입니다.
우선순위 처리를 하는 역할은 `식 안에서 먼저 처리`할 수도 있고, `그 전에 처리`해서 이미 순서가 정렬된 채로 식 이라는 객체에 넘어가게 할 수 있을 것 같다는 생각을 했습니다.
만약이 이러한 구조가 과한 객체지향일 것 같다는 생각이 드신다면 그런 의견 또한 맞을 수도 있다고 생각합니다. 

한번 나눌 수 있을 만큼 나눠보자 라는 생각으로 의견을 드린 것이기 때문에 부담 느끼지 않으셔도 됩니다. !
이제 과제에 대한 리펙토링을 멈추겠다고 하시면 머지하도록 하겠습니다.
우진님의 소중한 피드백 부탁드립니다. ! 🥹🥹

2022-04-08 09:11 UTC, dbslzld15 commented
아하.. 다시 한번 생각해보겠습니다! 힌트 주신 내용을 토대로 더 깊게 고민해봐야겠네요 ㅎㅎ
과한 객체지향은 지금 저한테 필요한 부분이어서.. 힌트가 필요하면 다시 찾아오겠습니다 ㅋㅋㅋㅋ

2022-04-08 16:09 UTC, SeokRae commented
> 아하.. 다시 한번 생각해보겠습니다! 힌트 주신 내용을 토대로 더 깊게 고민해봐야겠네요 ㅎㅎ
> 객체지향은 지금 저한테 필요한 부분이어서.. 힌트가 필요하면 다시 찾아오겠습니다 ㅋㅋㅋㅋ

많이 고민해보시고 의견주세요 !! 👏🏻👏🏻

2022-08-16 15:24 UTC, merged