[2기-C]방은혁 '계산기 TDD, OOP로 만들기'과제 코드리뷰 부탁드려요!
prgrms-be-devcourse/java-calculator pull request #41
Opened 2022-03-29 10:39 UTC by hyuk0309

안녕하세요!

첫 번째 미션 제출해요. 나름 고민 되게 많이 하면서 설계했습니다. 부족하더라도 이해해주세요. 앞으로 더 발전하겠습니다!! 

코드 리뷰 받는게 처음이라 떨리네요:sweat_smile:

###  :punch: 과제설명

- 계산기 TDD, OOP로 만들기

### 👨‍💻 요구 사항과 구현 내용

기존에 있던 요구사항을 구현하기 위해 세분화 했어요.

- UI

  - 입력
    - [x] 메뉴 입력
      - [x] 정상 입력
      - [x] 1, 2 이외의 입력 예외처리
    - [x] 계산식 입력
      - [x] 정상 상황 입력 
      - [x] 정규식 사용해 예외처리
  - 출력
    - [x] 메뉴 출력
    - [x] 계산 결과 출력
    - [x] 조회 결과 출력

- 핵심기능 

  - 사칙연산
    - 사칙연산(우선순위)
      - [x] 덧셈
      - [x] 뺄셈
      - [x] 나눗셈
      - [x] 곱셈
      - [x] 문자열 수식을 후위 표기법으로 바꾸기
      - [x] 후위 표기식 계산하기
  - [x] 계산 이력을 맵으로 데이터 저장 기능

  

### 🛠 설계도

![설계도](https://user-images.githubusercontent.com/29492667/160593453-0e8e6e50-3916-4947-87d4-41b2bc76c0ae.png)

- 간략한 설명

  저는 크게 App, Controller, Service Repository 계층으로 나눠봤어요.

  - App : 어플리케이션 동작에 필요한 구현체를 생성하고, Controller를 실행시켜줘요.
  - Controller : 사용자의 입력과 출력을 받아, 핵심 비지니스 로직이 필요하면 Service 계층으로 작업을 넘겨줘요.
  - Service : 핵심 비지니스 로직을 수행해요. 이곳에서 계산기 객체를 이용해 계산을 수행해줘요.
  - Repository : 저장소가 있는 계층이예요. 

​	사용자 입력과 출력 그리고 저장소는 인터페이스로 설계해 필요하면 새로운 구현체를 만들고 바꿀 수 있도록 설계해봤어요. 

### 🙋‍♂️ PR 포인트 & 궁금한 점

- 개발 시작 단계

  저 설계도가 나오기까지 너무 많은 리펙토링을 한 것 같아요. 멘토님은 어느 정도까지 설계하시고 개발을 진행하시나요?

  

- 저의 설계

  제 나름대로 객체지향적으로 설계하려고 노력했어요. 혹시 멘토님이 보시기에 어떤 점이 부족해 보이나요? 그리고 객체의 책임을 나누는 팁이 있을까요?

  

- 테스트

  1. 제가 작성한 단위 테스트가 잘 작성한 단위 테스트인지 알고 싶어요. 
  2. 개발하는 모든 기능에 대해 테스트 코드를 작성해야 하나요? 아니면 핵심적인 기능 위주로 테스트코드를 작성하면 되나요?
  3. 통합 테스트는 특정 시나리오 밖에 테스트를 못하는데, 통합 테스트를 작성하지 않고 직접 시연해보는게 더 좋은 방법 아닐까요?

  

- 커밋 메시지 단위

  개발을 하다보면 개발하려던 기능을 개발하다 그 외적으로 수정할 부분이 보여서 수정을 하게 되요. 이렇게 되면 하나의 커밋에 다양한 내용이 들어가는 것 같아서 아닌 것 같다가도, 또 너무 사소한 이유로 커밋을 나누면 커밋이 너무 많아질 것 같아서 고민 했어요. 이부분은 어떻게 생각하시나요?

그 외 피드백도 환영입니다!😀

2022-03-29 15:05 UTC, ksy90101 requested changes
안녕하세요 :) 은혁님
간단한 피드백을 남겼으니 확인해주시면 감사하겠습니다~

2022-03-29 15:05 UTC, ksy90101 commented on src/main/java/hyuk/calculator/Calculator.java
> +        return token.matches("^[0-9]*$");
matches는 비싼 행위입니다.
이런경우에는 어떻게 할까요?
한번 찾아보세요.

2022-03-29 15:05 UTC, ksy90101 commented on src/main/java/hyuk/controller/CalculatorController.java
> +                String menu = inputView.selectMenu(new Scanner(System.in));
과연 Scanner를 컨트롤러에서 넣어주는게 맞을까요?

2022-03-29 15:05 UTC, ksy90101 commented on src/main/java/hyuk/entity/Log.java
> +public class Log {
Log는 일반적으로 개발하면서 정보를 알기 위해 사용하는 것이라고 생각이 드는데요.
다른 단어로 한번 변경해보면 어떨까요?

2022-03-29 15:05 UTC, ksy90101 commented on src/main/java/hyuk/repository/MemoryRepository.java
> +    }
데이터베이스를 getter가 필요한가요?
log가 필요하다면 넘겨줘야 하지 않을까요?

2022-03-29 15:05 UTC, ksy90101 commented on src/main/java/hyuk/service/CalculatorService.java
> +public class CalculatorService {
단순히 콘솔 프로그램인데 서비스가 필요하다고 생각이 드시나요?

2022-03-29 23:52 UTC, hyuk0309 commented
피드백 감사합니다:)
하나하나 생각해 보고 수정해 볼게요!

2022-04-03 06:25 UTC, ksy90101 requested changes
안녕하세요 :) 은혁님
간단한 피드백을 남겼으니 한번 더 수정해보시면 어떨까요?
아울러 미션을 하나 드리겠습니다.
모든 메서드들에 대해 1depth를 유지해주시면 좋을거 같아요.
그렇다면 좀 더 책임 분리가 쉬워질것입니다 :)

2022-04-03 06:25 UTC, ksy90101 commented on build.gradle
> +    id 'java'
java version을 명시해주는게 어떨까요?

2022-04-03 06:25 UTC, ksy90101 commented on build.gradle
> +    testImplementation 'org.mockito:mockito-junit-jupiter:3.11.2'
mockito가 굳이 필요한 테스트가 있었나요?

2022-04-03 06:25 UTC, ksy90101 commented on src/main/java/hyuk/calculator/Operator.java
> +        }
익명메서드가 아닌 람다로 하는게 더 깔끔해 보일거 같은데 어떻게 생각하실까요?

2022-04-03 06:25 UTC, ksy90101 commented on src/main/java/hyuk/calculator/Operator.java
> +    public static Operator of(final String symbol) {
👍

2022-04-03 06:25 UTC, ksy90101 commented on src/main/java/hyuk/calculator/Operator.java
> +    public abstract Integer apply(int firstOperand, int secondOperand);
함수형 인터페이스를 사용하는게 어떨까요?

2022-04-03 06:25 UTC, ksy90101 commented on src/main/java/hyuk/controller/CalculatorController.java
> +    private final CalculatorService calculatorService;
콘솔프로그램에 Service가 필요할까요?

2022-04-03 06:25 UTC, ksy90101 commented on src/main/java/hyuk/controller/CalculatorController.java
> +                System.out.println(e.getMessage() + "\n");
Controller에서 print를 하는게 아니라 outputView에서 error 메시지를 print하게 하면 어덜까요?

2022-04-03 06:25 UTC, ksy90101 commented on src/main/java/hyuk/entity/Record.java
> +    public static Record createRecord(String formula, Result result) {
정적메서드를 사용한 이유가 무엇일까요?

2022-04-03 06:25 UTC, ksy90101 commented on src/main/java/hyuk/repository/MemoryRepository.java
> +    private Map<Long, Record> records = new HashMap<>();
불변 및 멀티스레드에 방어적이여야 할꺼같은데 어떻게 생각하실까요?

2022-04-03 06:25 UTC, ksy90101 commented on src/main/java/hyuk/calculator/PostOrderFormula.java
> +        String[] tokens = formula.split(" ");
" " 매직 스트링 :)

2022-04-03 11:10 UTC, hyuk0309 commented
### 👨‍💻 2차 피드백

- [x] build.gradle 관리
  - java version 관리
  - 사용하지 않는 라이브러리 제거 (Mockito는 ConsoleOutputViewTest에서 사용합니다!)

<br/>

- [x] 람다 활용하기

<br/>

- [x] 함수형 인터페이스 활용하기

<br/>

- [x] Service 없애기

  Service를 없애면 Controller가 너무 많은 책임을 가질 것 같았어요. 그런데 없애고 메소드를 분리하니 코드가 더 깔끔해진 것 같아요.

<br/>

- [x] Error 출력을 outputView에서 출력

<br/>

- [x] 정적 메서드를 사용한 이유?

단순히 이름을 표현할 수 있어 사용했습니다. 하지만 생각해보니 생성자를 하나만 만들면 굳이 정적 팩토리 메서드를 이용할 필요가 없는 것 같아요.

<br/>

- [x] 불변 및 멀티스레드에 생각

<br/>

- [x] 문자열 상수로 바꾸기

🙋 모든 문자열을 상수로 바꾸는게 좋나요? 무조건 바꾸면 클래스의 static final 맴버 변수가 너무 많아져 제 생각에는 오히려 지저분해 보이는 것 같아요. 

<br/>

- [x] 모든 메서드 1depth로 리팩토링

2022-04-04 00:14 UTC, ksy90101 commented on src/main/java/hyuk/calculator/Calculator.java
> +    public Result calculates(PostOrderFormula postOrderFormula) {
메서드명이 오타인가요?

2022-04-04 00:17 UTC, ksy90101 approved these changes
안녕하세요 은혁님 :) 
훨씬 더 깔끔한 코드가 된거 같네요.
고생 많으셨습니다~
점점 코딩을 하다 보면 자신만의 철학이나 설계같은것들도 생기게 될텐데, 지금 부족하다고 해서 실망하지 마시고 계속해서 꾸준히 해 나가다 보면 괜찮을거라고 생각을 합니다 :) 경험이 깡패거든요 ㅎㅎ
계산기 미션은 이만 마무리 하겠습니다!
혹시 질문이 있다면 언제든지 슬랙을 이용해 연락주세요~

2022-04-04 00:17 UTC, ksy90101 commented on src/main/java/hyuk/calculator/PostOrderFormula.java
> +            || topOperator.equals("-"));
```suggestion
        return (pushOperator.equals("*") || pushOperator.equals("/")) && 
        (topOperator.equals("+")|| topOperator.equals("-"));
```
이런식으로 묶음에 맞춰서 개행을 하는게 더 좋을거 같아요.

2022-04-04 00:17 UTC, ksy90101 commented on src/main/java/hyuk/util/PatternValidator.java
> +public class PatternValidator {
해당 인스턴스가 생성되지 않도록 private으로 기본생성자를 막는게 어떨까요?
https://github.com/Meet-Coder-Study/book-effective-java/blob/main/2%EC%9E%A5/3_private%20%EC%83%9D%EC%84%B1%EC%9E%90%EB%82%98%20%EC%97%B4%EA%B1%B0%20%ED%83%80%EC%9E%85%EC%9C%BC%EB%A1%9C%20%EC%8B%B1%EA%B8%80%ED%84%B4%EC%9E%84%EC%9D%84%20%EB%B3%B4%EC%A6%9D%ED%95%98%EB%9D%BC_%EA%B9%80%EB%B3%B4%EB%B0%B0.md

2022-04-04 00:17 UTC, ksy90101 commented on src/main/java/hyuk/view/ConsoleInputView.java
> +        if (tokens.length % 2 == 0) {
2는 매직넘버!

2022-04-04 00:17 UTC, merged