[2기-C] 박상혁 코드 리뷰 부탁드립니다!
prgrms-be-devcourse/java-calculator pull request #42
Opened 2022-03-29 12:43 UTC by park0503

프로젝트 생성, 사용할 class들 생성하고 처음 기능선택 부분 까지만 만든 뒤 TDD 방식으로 테스트 코드 먼저 작성해봤습니다. 간단히 class들 설명 드리자면
- Calculator : 계산기 내의 계산, 조회 전체를 포괄하는 class입니다.
- Calculation : 계산 기능을 담당하는 class입니다.
- HistoryStore : 조회 기능을 담당하는 class입니다.
- History : 조회 시 보이는 계산 식의 정보를 담을 class 입니다.
- Formula : 입력 받은 식을 계산 기능에서 사용할 수 있도록 파싱한 정보들을 담을 class입니다.
- Input : 입력 담당 인터페이스 입니다.
- Output : 출력 담당 인터페이스 입니다.
- Console : input과 output을 상속받는 구상class입니다. 
- App : 계산기(Calculator class)를 실행 시킬 main 메소드가 있는 class입니다.

각 커밋들을 설명 드리자면
- 프로젝트 생성 : gradle 프로젝트 생성 후 App 클래스를 생성했습니다.
- 기본 구조 작성 : 사용할 class들을 만든 뒤 기능 선택 flow까지 진행되도록 코드를 작성했습니다.
- Calculation 테스트 코드 작성 : calculation 클래스에서 수행하는 기능을 테스트하는 코드입니다. tdd 방식으로 구현해보려 calculation 클래스의 구현보다 먼저 시작했습니다.

이렇게 객체지향적으로 코드를 작성해보려고 하는게 처음인지라 이렇게 하는게 맞는지 확신이 안섭니다.
테스트 코드도 마찬가지고... 방향성을 잘 잡았을까요?

2022-03-29 13:35 UTC, woogiekim commented
설정파일을 빼고 다시 요청해주세요!

2022-03-29 13:36 UTC, woogiekim commented
내장 그래들까진 괜찮다고 생각하지만

.idea 디렉토리 하위에 있는 파일들은 제외시켜주세요

2022-03-29 14:05 UTC, park0503 commented
idea 전체 제외시켰습니다!

2022-03-30 05:14 UTC, woogiekim requested changes
코멘트 남긴부분 확인해보시고, 고민해서 수정한번해보세요!

2022-03-30 05:14 UTC, woogiekim commented on src/test/java/com/programmers/java/calculator/engine/CalculationTest.java
> +    void calculate() {
테스트 호흡이 너무 긴거같습니다.

테스트 케이스를 잘게 쪼개보세요

2022-03-30 05:14 UTC, woogiekim commented on src/main/java/com/programmers/java/calculator/engine/HistoryStore.java
> +public class HistoryStore {
이렇게 비어 있으면 제대로 작동하는지 안하는지 알수가없습니다.

```
show(...) {
    throw new RuntimeException("아직 미구현");
}
```

혹은

```
show(...) {
    //TODO: 아직 미구현
}
```

같은게 필요할거같습니다.

혼자작업한다고 생각하고 하지마시고, 같이한다는 생각과 리뷰어가 봤을때 어떨까를 생각하면 더 좋을거같습니다.

2022-03-30 05:14 UTC, woogiekim commented on src/main/java/com/programmers/java/calculator/engine/Calculator.java
> +
공백은 생각보다 중요한 요소입니다.

의미없이 공백을 마구 넣는건 좋지않을거같습니다.

2022-03-30 05:14 UTC, woogiekim commented on src/main/java/com/programmers/java/calculator/Console.java
> +}
당장 사용하지않을 클래스를 미리 만들어둘 이유가 없을거같습니다.

2022-03-30 09:09 UTC, park0503 commented
피드백 감사합니다!
우선 말씀해 주신대로 테스트 코드를 세분화 시켰고,
의미없는 공백을 일부 제거했으며,
비어있는 곳에 주석으로 TODO를 추가했습니다.
또 실행이 가능하도록 코드를 작성해, 사용되지 않던 App이나 Console클래스들도 모두 사용되도록 만들었습니다.

그 후 Calculation 기능을 구현했습니다.
컴퓨터가 중위식을 계산할 때처럼, 중위식을 후위식을 변환한 뒤 해당 후위식을 풀이하는 방식으로 구현했습니다.
그에 따라 Formula 클래스를 인터페이스로 전환하고 Infix 및 Postfix 구상체를 만들었습니다.
추가로 중위식 -> 후위식 변환 작업을 수행할 클래스인 PostfixConverter 클래스도 생성했습니다.
계산 후 조회를 위한 기록의 생성이나, 들어온 계산식의 유효성 검증은 아직 구현하지 못해 TODO로 표시해 놨습니다.

과제를 수행 중 2가지 질문점이 생겼습니다.
1. 테스트코드의 경우 각 상황별로 세분화시키긴 했지만 테스트 케이스가 빈약한것 같은데 랜덤 넘버 생성 등으로 고도화 시킬 필요가 있을까요?
2. 현재 코드에서 들어온 문자열을 파싱할 때 해당 문자열이 숫자인지 파악하는 방법으로 Integer.parseInt() 메소드를 이용해서 NumberFormatException이 발생하면 문자, 발생하지 않으면 숫자로 인식하고 처리하고 있습니다. 해당 방법이 괜찮은 방법일까요?

늘 고생 많으십니다 멘토님!

2022-03-30 16:07 UTC, park0503 commented
멘토님의 짧은 예외처리 강연을 듣고 기존 구현한 코드를 대폭 수정한 뒤 조회 기능또한 추가했습니다.
정규식을 여러군데 활용해 검증 기능을 수행하고 문제가 생기는 부분들에서는 custom exception인 inputException과 CalculatorException을 throw 해 줬습니다. 각 exception들은
- inputException : 유저가 입력을 잘못 했을 시 생기는 예외입니다.
- CalculatorException : 계산기의 로직상 잘못된 부분이 있을 때 생기는 예외입니다. 이게 발생하면, 제가 바로 고쳐야됩니다.
둘 모두 Calculator 클래스의 run 메소드 내에서 최종적으로 catch됩니다.

말씀하셨던 Postfix 리스트 내의 숫자와 기호의 혼용은 불가피하게 유지되었는데, 후위식으로 계산을 진행하려면 숫자와 기호를 나누기 힘들기 때문이었습니다. 따라서 그대로 유지하는 대신 계산 전 정규식을 통한 postfix의 유효성 검증과 계산 도중 문제가 생길시 예외처리를 추가해 줌으로써 안정성을 확보하려 했습니다.

이로써 요구사항에 주어진 기능은 모두 구현을 했는데, 구조가 맞는지, 테스트 코드를 잘 짰는지는 확신이 안서네요... ㅎㅎ 코드리뷰 해주시면 감사하겠습니다!

2022-03-31 11:45 UTC, woogiekim approved these changes
고생많이하셨습니다.

한 가지 말씀드리고 싶은게 있어서 적어봅니다.

`assertThrows(InputException.class, () -> calculation.calculate((question)));`

보다는

`assertThatThrownBy(() -> calculation.calculate((question)) ).isExactlyInstanceOf(InputException.class);`

와 같은 검증을 일반적으로 더 많이 쓰는거 같습니다.

그 이유는 처음 계산기 프로젝트 시작 할 때 말씀드린대로

일반적으로 검증 라이브러리를 assertJ 로 통일 시켜서 일관성 유지 하게 하는 것을 선호합니다.

2022-03-31 11:45 UTC, merged

2022-03-31 11:54 UTC, park0503 commented
넵! 앞으로 테스트 코드 작성 때 해당 부분 신경 쓰겠습니다. 감사합니다!