[2기-C] 유도진 코드 리뷰 요청
prgrms-be-devcourse/java-calculator pull request #45
Opened 2022-03-29 14:52 UTC by dojinyou

## 📌 과제 설명
console을 통한 사용자와의 상호작용을 이용하여, 사칙 연산이 포함된 계산식을 입력 받고 이에 대한 결과를 출력하는 프로그램입니다. 또한 데이터베이스 역할을 하는 클래스를 만들어 계산 기록을 저장, 출력 가능하도록 해야합니다.

## 👩‍💻 요구 사항과 구현 내용 

- 사용자 인터페이스 구현하기
  - [x] 콘솔을 이용하여 출력
  - [x] 콘솔을 이용하여 입력
- 계산 기능 구현하기
  - [x]  더하기
  - [x]  빼기
  - [x]  곱하기
  - [x]  나누기
  - [x]  우선순위(사칙연산)
- 테스트 코드 작성하기
  - [x] 테스트 코드 구현하기
- 데이터 저장소 구현하기
  - [x] 계산 이력 저장하기
  - [x] 계산 이력 불러오기

## ✅ PR 포인트 & 궁금한 점 
1. test code를 작성하는 기술이 아직 많이 부족한 것 같습니다. 주요 로직에만 테스트 코드를 적용하였고, UI나 Database 등에는 적용이 되지 않았습니다. 제 눈에도 여러 모로 개선점이 많아 보여서 찾아보며 개선 중에 있습니다. 이 부분에 대해서 많은 지적 부탁 드립니다.
2. Interface나 상속을 사용하지 않았습니다. 이 부분에 대해서 명확하게 사용 해야 될 부분을 찾지 못하거나 필요성을 못 느꼈던 것 같습니다. 이 부분에 대해서 많은 지적 부탁 드립니다!
3. 클래스들의 역할 분배가 적절 했는 지 잘 모르겠습니다. 이 부분에 대해서도 많은 지적 부탁 드립니다.
4. 예외처리 전략을 별도로 세우지 않았습니다. illegalargumentexception 중심으로 에러를 발생시키고 한번에 처리하였습니다. 이 부분에 대한 조언이나 좋은 방법이 있다면 알려주시기 바랍니다.
5. 아직 Java 사용에 익숙하지 않은 것 같습니다. 코드 속 더 좋은 표현법이 있다면 조언해주시기 바랍니다.

2022-03-29 15:06 UTC, ksy90101 commented on .gitignore
> +.idea/*
여기서 .idea 전체를 gitignore를 하는데 아래 다른 것들이 필요할까요?
이 파일도 관리해야 하는 파일입니다!

2022-03-29 15:06 UTC, ksy90101 commented on app/build.gradle
> + * User Manual available at https://docs.gradle.org/7.4.1/userguide/building_java_projects.html
주석은 필요없다면 다 삭제해주시는게 좋습니다.

2022-03-29 15:06 UTC, ksy90101 commented on app/build.gradle
> +}
이렇게 되면 자바 버전은 몇을 사용하고 있는걸까요?

2022-03-29 15:07 UTC, ksy90101 commented on app/src/main/java/calculator/Calculator.java
> +    }
이걸 enum으로 관리하면 전략패턴 처럼 사용이 가능할꺼 같은데요.
https://rutgo-letsgo.tistory.com/167
이글을 한번 참고해보시겠어요?

2022-03-29 15:07 UTC, ksy90101 commented on app/src/main/java/calculator/InputParser.java
> +        if (!inputValidator.valid(splittedInputFormula)) throw new IllegalArgumentException();
한줄로 작성하는 것은 가독성을 너무 떨어트립니다 ㅠㅠ
아울러 예외를 사용할땐, 예외 메시지를 작성해주시는게 좋습니다.

2022-03-29 15:07 UTC, ksy90101 commented on app/src/main/java/calculator/InputParser.java
> +        this.seperator = " ";
이건 충분히 상수로 관리 가능하겠는데요?

2022-03-29 15:08 UTC, ksy90101 commented on app/src/main/java/calculator/InputParser.java
> +    private InputValidator inputValidator;
이것도 불변으로 가능하겠네요.

2022-03-29 15:08 UTC, ksy90101 commented on app/src/main/java/calculator/InputValidator.java
> +        return true;
한줄은 최대한 피해서 작성해주세요.
아울러 지금 내부에 if이 많다는것은 그만큼 책임이 많고 각 if문의 조건을 알기가 어려워집니다.
메서드로 분리해서 작성하면 메서드명으로 이름을 지을수 있고 쉽게 알수 있지 않을까요?

2022-03-29 15:11 UTC, ksy90101 commented on settings.gradle
> +include('app')
이걸 멀티모듈로 할 필요가 1도 없습니다.
멀티모듈 제거해주세요.

2022-03-30 04:22 UTC, dojinyou commented on settings.gradle
> +include('app')
삭제하였습니다

2022-03-30 04:22 UTC, dojinyou commented on .gitattributes
> +*.bat           text eol=crlf
> 이건 왜 올라왔을까요?

이 파일이 언제 생성됐는 지 정확히 체크하지 못 했습니다. 삭제 하도록 하겠습니다

2022-03-30 04:24 UTC, dojinyou commented on .gitignore
> +.idea/*
> 여기서 .idea 전체를 gitignore를 하는데 아래 다른 것들이 필요할까요? 이 파일도 관리해야 하는 파일입니다!

gitignore file 정리하겠습니다

2022-03-30 04:27 UTC, dojinyou commented on app/src/test/java/calculator/InputParserTest.java
> +        assertThat(inputParser.parse("1 * 2 + 3 / 0")).isEqualTo(new String[]{"1", "2", "*", "3", "0", "/", "+"});
> @ParamterziedTest를 사용하면 이렇게 안적어도 되겠는데요!?

Test code에 ParameterizedTest 적용하겠습니다!

2022-03-30 04:43 UTC, dojinyou commented on app/src/main/java/calculator/OPERATOR.java
> +public enum OPERATOR {
enum class명 수정 하겠습니다!

2022-03-30 04:45 UTC, dojinyou commented on app/src/main/java/calculator/InputValidator.java
> +        return true;
> 한줄은 최대한 피해서 작성해주세요. 아울러 지금 내부에 if이 많다는것은 그만큼 책임이 많고 각 if문의 조건을 알기가 어려워집니다. 메서드로 분리해서 작성하면 메서드명으로 이름을 지을수 있고 쉽게 알수 있지 않을까요?

관련해서 메소드로 뺴서 리팩토링 하도록 하겠습니다!

2022-03-30 04:47 UTC, dojinyou commented on app/src/main/java/calculator/Calculator.java
> +    }
전략 패턴 

> 이걸 enum으로 관리하면 전략패턴 처럼 사용이 가능할꺼 같은데요. https://rutgo-letsgo.tistory.com/167 이글을 한번 참고해보시겠어요?

전략패턴 적용해보도록 하겠습니다!

2022-03-30 05:41 UTC, dojinyou commented on app/build.gradle
> + * User Manual available at https://docs.gradle.org/7.4.1/userguide/building_java_projects.html
> 주석은 필요없다면 다 삭제해주시는게 좋습니다.

네 정리하도록 하겠습니다!

2022-03-30 05:42 UTC, dojinyou commented on app/build.gradle
> +}
> 이렇게 되면 자바 버전은 몇을 사용하고 있는걸까요?

버전 표기 및 plugin도 자바로 변경하겠습니다

2022-03-30 05:43 UTC, dojinyou commented on app/src/main/java/calculator/InputParser.java
> +    private InputValidator inputValidator;
> 이것도 불변으로 가능하겠네요.

넵 final keyword 추가하겠습니다!

2022-03-30 05:48 UTC, dojinyou commented on app/src/main/java/calculator/InputParser.java
> +    InputParser() {
> default 접근제어자를 사용하는 이유가 있나요?

특별한 이유 없는 것 같습니다. class의 접근 제어자와 동일한 수준으로 변경하는 것이 좋을 것 같습니다

2022-03-30 05:51 UTC, dojinyou commented on app/src/main/java/calculator/InputParser.java
> +        this.seperator = " ";
> 이건 충분히 상수로 관리 가능하겠는데요?

상수로 관리해보겠습니다!

2022-03-30 05:53 UTC, dojinyou commented on app/src/main/java/calculator/InputParser.java
> +        if (!inputValidator.valid(splittedInputFormula)) throw new IllegalArgumentException();
> 한줄로 작성하는 것은 가독성을 너무 떨어트립니다 ㅠㅠ 아울러 예외를 사용할땐, 예외 메시지를 작성해주시는게 좋습니다.

예외메시지 추가하고 줄 바꿈 처리하도록 하겠습니다

2022-03-30 11:09 UTC, ksy90101 commented on .gitignore
> +.idea/*
아직 .idea 폴더의 파일들이 남아 있는거 같은데요?

2022-03-30 11:14 UTC, ksy90101 requested changes
도진님. 안녕하세요 :)
위에서부터 리뷰를 하다가, 세가지의 미션을 드리는게 더 좋을거 같아서 미션을 드립니다.
1. 모든 메서드에서 로직은 1depth를 유지하도록 작성해주세요.
2. if문 for문 모두 한줄이 아닌 가독성있도록 { } 괄호로 관리해주세요.
3. 예외를 boolean이 아닌 진짜 예외로 처리할수 잇도록 변경해주세요.

총 3가지를 모두 완료하시면 다시 리뷰 요청주시면 감사하겠습니다 :)

2022-03-30 11:14 UTC, ksy90101 commented on app/build.gradle
> +    // Use JUnit Jupiter for testing.
이 파일에 주석이 필요할까요?

2022-03-30 11:14 UTC, ksy90101 commented on app/build.gradle
> +    implementation 'com.google.guava:guava:30.1.1-jre'
굳이 guava를 쓸정도는 아니라고 생각이 드는데요.
해당 의존성은 왜 존재할까요?

2022-03-30 11:14 UTC, ksy90101 commented on app/build.gradle
> +    implementation 'org.assertj:assertj-core:3.22.0'
해당 의존성은 test일때만 가져오는게 좋을거 같아요.

2022-03-30 11:14 UTC, ksy90101 commented on app/build.gradle
> +}
아직도 멀티모듈의 잔재가 남아있네요.

2022-03-30 11:14 UTC, ksy90101 commented on app/build.gradle
> +}
app폴더를 가지는것자체가 잘못되었다고 생각이 들어요.
바로 src가 나오는게 모노레포방식으로 가는게 좋지 않을까요?

2022-03-30 11:14 UTC, ksy90101 commented on app/src/main/java/calculator/Calculator.java
> +        }
익명클래스가 아닌 람다로 작성하는게 더 깔끔하다고 생각이 드는데 도진님은 어떻게 생각할까요?

2022-03-30 11:14 UTC, ksy90101 commented on app/src/main/java/calculator/Calculator.java
> +    public static int getPriority(String textOperator) {
```suggestion
    }

    public static int getPriority(String textOperator) {
```

2022-03-30 11:14 UTC, ksy90101 commented on app/src/main/java/calculator/Calculator.java
> +        if (operator == null) throw new IllegalArgumentException("올 바르지 않은 연산자입니다.");
한줄코딩은 멈춰주세요.

2022-03-30 11:14 UTC, ksy90101 commented on app/src/main/java/calculator/Calculator.java
> +    }
예외를 boolean으로 관리하는게 올바를까요?>

2022-03-30 11:14 UTC, ksy90101 commented on app/src/main/java/calculator/InputParser.java
> +            throw new IllegalArgumentException();
여기도 예외메시지를 작성해주세요.

2022-03-30 11:14 UTC, ksy90101 commented on app/src/main/java/calculator/InputValidator.java
> +        ) return true;
한줄 코딩은 멈춰주세요.

2022-03-30 11:14 UTC, ksy90101 commented on app/src/main/java/calculator/InputValidator.java
> +            if (i % 2 == 1 && !isOperator(element)) return false;
depath가 2라는 이유는 해당 메서드에 굉장히 많이 책임을 가지고 있다는 의미입니다.
메서드 분리를 해보시면 어떨까요?

2022-03-30 11:14 UTC, ksy90101 commented on app/src/main/java/calculator/InputValidator.java
> +        return splittedInputFormula.length >= 3 && splittedInputFormula.length % 2 != 0;
매직넘버!

2022-03-30 11:14 UTC, ksy90101 commented on app/src/main/java/calculator/OPERATOR.java
> +public enum Operator {
굳이 여기서 또 중복으로 작성할 필요가 있나요?
외에 있는거 같은데요!?

2022-04-17 07:28 UTC, merged