[2기-류영준 ] 1주차 java-calculator 미션 제출합니다.
prgrms-be-devcourse/java-calculator pull request #47
Opened 2022-03-30 05:35 UTC by ecvheo1

# 📌 과제 설명 
- 콘솔로 사용자의 입력을 받아 사칙연산을 수행하는 정수형 계산기
- 객체지향적인 코드로 구현하기
- 테스트 코드 구현하기

# 👩‍💻 요구 사항과 구현 내용 
- 초기 메뉴 선택은 1, 2 중 하나만 입력한다.
- 1을 입력했을 때 (조회)
    - 계산 이력을 순서대로 출력한다.
- 2를 입력했을 때 (계산)
    - 계산식을 입력한다. → 다음 줄에 계산한 결과를 출력한다.
        - 연산자와 피연산자를 공백 구분하여 입력한다.
            - ex) 1 + 1, 2   *  -2
        - 연산자는 +, -, *, / 만 사용한다.
        - 피연산자가 음수인 경우에도 계산식에 연산자를 반드시 포함한다.

# 😀  구조
- AppConfig 애플리케이션 설정 클래스을 구현하여 애플리케이션 전체의 사용영역과 구성영역을 구분하였다.
- 계산 이력을 저장하기 위해 인메모리 저장 방식을 사용하였다.

## AppConfig

- 애플리케이션의 전체 구동 방식을 구성하기 위해, 실제 동작에 필요한 구현 객체를 생성하고 연결하는 책임을 가지는 별도의 설정 클래스
- 구현 객체 생성
    - `Calculator`, `Console`, `CalculateServiceImpl`, `HistoryServiceImpl`, `MemoryRepository`, `ValidatorImpl`, `TokenizerImpl` 구현 객체를 생성한다.
- 생성한 객체 인스턴스의 참조를 생성자를 통해서 주입
    - `Calculator` → `Console`, `Console`, `CalculateServiceImpl`, `HistoryServiceImpl`, `ValidatorImpl`
    - `CalculateServiceImpl` → `TokenizerImpl`
    - `ValidatorImpl` → `ToeknizerImpl`

## Calculator

- 정수형 계산기 메인 로직 클래스
- Input, Output에 의존하여 입출력을 수행한다.

## Calculation

- String 타입의 계산식과 계산 결과를 담은 이력을 담은 Entity 클래스

## ErrorMessage

- 에러 메시지를 모아둔 Enum 클래스

## Operator

- 연산자 Enum 클래스
- calculate 메서드는 연산자와 숫자 2개를 파라미터로 입력 받으면 사칙연산을 진행한다.
- 단순 사칙연산을 switch문이 아닌 Operator Enum 클래스를 구현함으로써 책임을 Operator Enum으로 전가하였다.

## Input

- 입력 담당 인터페이스

## Output

- 출력 담당 인테페이스

## Console

- Input, Output 인터페이스를 상속 받아 입출력을 수행하는 구현체 클래스

## HistoryServiceImpl

- 계산식과 계산 결과를 저장하고, 계산 이력을 순서대로 담은 객체 반환을 수행하는 클래스

## CalculateServiceImpl

- 계산식(중위표기식)을 파라미터로 받고 후위표기식으로 변환 후 계산하는 로직을 담은 클래스

## MemoryRepository

- 계산 이력 저장소 구현체
- 계산 이력을 인메모리 저장하기 위해 ArrayList 자료구조를 사용하였다.

## TokenizerImpl

- String 타입의 계산식을 List 객체로 토큰화 시키는 클래스

## ValidatorImpl

- 입력 받은 계산식의 유효성 검사를 담당하는 클래스
- 유효성 검사 로직을 메서드로 구현하였다.

# ✅ PR 포인트 & 궁금한 점 
- 애플리케이션 구조를 OOP, 객체지향적으로 설계했는지 잘 모르겠습니다.
- 클래스들의 역할 분배가 적절 했는지 잘 모르겠습니다.

2022-03-30 09:30 UTC, WooSungHwan requested changes
코멘트 확인해주세요! ㅎㅎ 충분히 잘 작성하셨습니다.

2022-03-30 09:30 UTC, WooSungHwan commented on src/main/java/com/programmers/java/AppConfig.java
> +    }
왜 얘네만 private인가요??

2022-03-30 09:30 UTC, WooSungHwan commented on src/main/java/com/programmers/java/AppConfig.java
> +    }
계산기 뺴고 다 private 해도 될것같은데 확인해보세요 ㅎㅎ

2022-03-30 09:30 UTC, WooSungHwan commented on src/main/java/com/programmers/java/Calculator.java
> +        }
1. 메소드 tab depth 너무 깊습니다. 적절히 분리하여 run 메소드를 읽을 때 구현로직을 읽어야 하는 것이 아닌 메소드 이름으로 유추가 가능하도록 추상화해주세요.
2. case문에 String 상수를 넣기보단 유효한 입력의 Enum 클래스로 정의해보세요.

2022-03-30 09:30 UTC, WooSungHwan commented on src/main/java/com/programmers/java/enums/ErrorMessage.java
> +
여기에 `@Getter` 붙여도 됩니다 ㅎㅎ

2022-03-30 09:30 UTC, WooSungHwan commented on src/main/java/com/programmers/java/enums/Operator.java
> +                .filter(o -> o.operator.equals(operator))
NullPointerException을 예방하기 위해 Objects 클래스의 기능을 사용해보시는건 어떨까요?

2022-03-30 09:30 UTC, WooSungHwan commented on src/main/java/com/programmers/java/service/CalculateServiceImpl.java
> +            if (!token.equals("-") && token.matches(regex)) {
하이픈이 전체 시스템에서 약속한 값이라면 별도로 상수로 빼시는건 어떤가요??

2022-03-30 09:30 UTC, WooSungHwan commented on src/main/java/com/programmers/java/service/CalculateServiceImpl.java
> + */
이런거 남기지 말아주세요.

2022-03-30 09:30 UTC, WooSungHwan commented on src/main/java/com/programmers/java/service/CalculateServiceImpl.java
> +                opStack.push(infixFormulaList.get(i));
분기문 안에서 새로운 루프가 돌아야한다면 별도로 의미를 부여한 private 메소드로 쪼개주세요. else문에서 뭐하는구나 코드만 훑어보고 알 수 있도록이요!

2022-03-30 09:30 UTC, WooSungHwan commented on src/main/java/com/programmers/java/validator/ValidatorImpl.java
> +public class ValidatorImpl implements Validator {
유효성 클래스는 잘 작성하셨네요 ㅎㅎ 근데 별도로 Validator로 추상화한 이유가 있나요?

2022-03-30 09:30 UTC, WooSungHwan commented on src/test/java/com/programmers/java/service/HistoryServiceImplTest.java
> +        Assertions.assertThat(resultList.get(0).getResult()).isEqualTo(result2);
이런경우는 먼저 resultList의 NotEmpty를 보장하는 단언문과 resultList.get(0)의 NotNull을 보장하는 단언문이 추가되면 좋을 것 같네요.

2022-03-30 09:30 UTC, WooSungHwan commented on src/test/java/com/programmers/java/validator/ValidatorImplTest.java
> +        Exception e3 = assertThrows(NullPointerException.class, ()-> validator.validateNull(formula3));
ㅎㅎ 잘하셨습니다.

2022-03-30 09:30 UTC, WooSungHwan commented on src/test/java/com/programmers/java/validator/ValidatorImplTest.java
> +        IllegalArgumentException e = assertThrows(IllegalArgumentException.class, () -> validator.validateLength(formulaList));
사실 이런부분은 when과 then의 경계가 없어요. 실무에서도 이런경우가 종종있는데 헷갈린다면 assert가 들어가면 대부분 then이라고 보시면 됩니다.

2022-03-30 09:32 UTC, WooSungHwan commented
1. 애플리케이션 구조를 OOP, 객체지향적으로 설계했는지 잘 모르겠습니다. -> 개발자마다 구조도 다르고 답은 없으니 스스로 불만족스러우신 부분이 있다면 어느부분인지 알려주세요 ㅎㅎ
2. 클래스들의 역할 분배가 적절 했는지 잘 모르겠습니다. -> 이것도 마찬가지로 어느부분이 역할분배가 잘 안됐다고 생각되는지 알려주세요.

과제하느라 고생하셨습니다. 마무리까지 최선을 다해보아요!

2022-03-30 10:00 UTC, ecvheo1 commented on src/main/java/com/programmers/java/validator/ValidatorImpl.java
> +public class ValidatorImpl implements Validator {
Validator을 객체로 분리를 시켜야하는지에 대해서 고민이 많았습니다.
제 생각은 계산기 구현에서 계산식의 유효성 검증에 대한 것이 중요한 역할을 한다고 생각을 하였습니다.
그래서 Validator로 적절하게 추상화하여 유효성 검증에 대한 책임을 할당하였습니다.
감사합니다!

2022-03-31 07:44 UTC, ecvheo1 commented
# ✅ 피드백 반영사항

1. AppConfig.java : 인스턴스 생성 메서드의 접근지정자를 private로 수정하였습니다.
2. Calculator:java : case 문에 값을 상수로 두어 정의하였습니다.
3. ErrorMessage.java : Enum 객체에 @Getter 추가
4. Operator.java : NullPointerException을 예방하기 위해 Objects 클래스의 nonNull 메서드를 사용하여 filter 처리를 구현하였습니다.
5. CalculateServiceImpl.java : 하이픈(”-”) 값을 상수로 두어 정의하였습니다.
6. CalculateServiceImpl.java : 분기문 내의 반복문을 private 메서드로 분리하여 가독성을 높였습니다.
7. HistoryServiceImplTest.java : resultList의 NotEmpty를 보장하는 단언문과 resultList.get(0)의 NotNull을 보장하는 단언문이 추가하였습니다.
8. ValidatorImplTest.java : 예외 처리와 관련한 단언문에서 when과 then을 통합시켰습니다.

# ✅ 궁금한 점

- 코드리뷰에서 흑구님이 “case 문에 String 상수를 넣기보단 유효한 입력의 Enum 클래스로 정의해보세요.”라고 말씀하셨는데, Enum 클래스로 따로 분리를 하면 이점이 있는지 궁금합니다. 저는 피드백 반영사항 2번으로 구현하였습니다.
- Validator를 따로 추상화한 이유를 물어보셔서 답변을 드렸는데, 제가 생각한 방향이 옳은지 잘 모르겠습니다...
- 모든 클래스는 하나의 책임만 가지며 클래스는 그 책임을 완전히 캡슐화를 해야한다고 알고있습니다. 한 객체 안에 여러가지 기능의 메서드가 있다면, 그 메서드들은 객체의 책임과 역할에 해당하는 의미를 가지고 있어야하는건가요?

2022-04-04 00:50 UTC, ecvheo1 reviewed
/

2022-04-05 14:23 UTC, WooSungHwan approved these changes
일단 리뷰가 많이 늦어져서 죄송합니다.ㅠㅠ 과제수행하시느라 고생 많이하셨습니다!ㅎㅎ

2022-04-05 14:30 UTC, WooSungHwan commented
1. 코드리뷰에서 흑구님이 “case 문에 String 상수를 넣기보단 유효한 입력의 Enum 클래스로 정의해보세요.”라고 말씀하셨는데, Enum 클래스로 따로 분리를 하면 이점이 있는지 궁금합니다. 저는 피드백 반영사항 2번으로 구현하였습니다.

- Enum이라는 클래스는 대부분 특정한 상황에서 정의될 수 있는 상수 클래스로 볼수도 있습니다. 해당 case문의 경우 1번과 2번을 제외한 모든 입력을 예외로 처리되어야하기 때문에 1 과 2를 Enum에 정의하여 해당 상황에 맞는 범위를 설정할 수 있게되는 것이지요. 근데 실무에서는 지금같이 단순한 상황만을 case문에 태우는 것은 아닙니다. 그럼 그때마다 "1" "2" 이런식으로 써야될텐데 그렇게 된다면 그게 무슨의미인지 알 수 없는 시점이 반드시 도달하게 됩니다. 그래서 Enum으로 관리해야만 될 때가 오게 되어 있을거에요. `SELECT("1", "조회")`, `CALCULATE("2", "계산")`  결국은 이러한 enum클래스정의가 필요하게 되겠지요. 단순히 과제의 구현과 객체지향 프로그래밍의 목적도 좋지만 이런 유지보수 측면에서도 고려를 해봤으면 좋겠어서 드린 피드백입니다 ㅎㅎ

2022-04-05 14:34 UTC, WooSungHwan commented
Validator를 따로 추상화한 이유를 물어보셔서 답변을 드렸는데, 제가 생각한 방향이 옳은지 잘 모르겠습니다...

- 단순히 궁금해서 드린 질문입니다만.. 깊게 고민하실줄은 몰랐습니다. ㅎㅎ 제 경험상 유효성 검증의 클래스가 추상화가 되는 일이 그렇게 많지는 않을텐데 어떤 고민을 하셨길래 인터페이스를 별도로 두어 구현을 한건지 여쭤본거였구요! 개념적으로 추상화를 하신건지 다형성의 목적을 위한 추상화였는지 혹은 다른 생각이 있으셨던건지 ㅎㅎ 일단은 개념적 추상화라고 받아들였습니다. ㅎㅎ 잘하셨어요. 그렇게 개념의 추상화를 많이 해보시다보면 어떤게 오버 코딩인지 내가 적절히 했는지 판단하는 감이 서실거에요. 지금은 잘했는지 못했는지 신경쓰는것도 좋지만 많이많이 되도록 추상화 개념에 대해서도 고민해보시길 바랍니다! 

일단 저는 유효성 추상화는 안할것 같네요!

2022-04-05 14:45 UTC, WooSungHwan commented
모든 클래스는 하나의 책임만 가지며 클래스는 그 책임을 완전히 캡슐화를 해야한다고 알고있습니다. 한 객체 안에 여러가지 기능의 메서드가 있다면, 그 메서드들은 객체의 책임과 역할에 해당하는 의미를 가지고 있어야하는건가요?

객체지향에서 지향하는 이상적인 하나의 클래스에 어느정도의 기능을 가지느냐에 대해서는 저도 많이 고민을 해봐야겠지만.. 굉장히 어려운 질문이군요 ㅎㅎㅎㅎ 저라면 최대한 클래스 하나에 대한 기능정의를 모두 때려넣은 뒤에 개념적으로 분리되어야 할 객체, 개발 상에서 가상으로(실제 현실에서는 없는 객체라는 개념) 필요한 개념의 객체.. 이런식으로 리팩토링을 해나갸아 할 것 같습니다. 처음부터 완벽한 구조가 나오는 것이 비현실적이라 제가 경험한건 이 정도까지인것 같아요. 근데 그와중에 어떤 클래스가 어떤 책임을 가지고 이 클래스가 저 책임을 가지고 이런것을 구분하는게 아직은 많이 어려우실겁니다. 책임이란 개념을 우선 클래스까지에만 고민을 해보시면 좋을 것 같아요.

메소드에 의미를 부여한다는건 제 관점에서는 객체지향과는 조금은 다른 가독성의 문제로 보고 있습니다. 그 기능을 제대로 표현하지 못하는 이름 혹은 의미를 가진 메소드는 피해야 하니까요ㅎㅎ 예컨데 setXXX인데 내부 컬렉션의 어떤 요소를 지운다던가.. 

제 생각은 이렇습니다! ㅎㅎ

사실 질문 두가지가 섞인 것 같아서 제대로 대답한것인지는 모르겠네요 ㅎㅎ

2022-04-05 16:35 UTC, ecvheo1 commented
1. 명확한 의미 부여와 유지보수 측면에서의 Enum 클래스 이점을 알게되었습니다!
2. Validator 클래스는 개념적 추상화에 가까운 것 같습니다. 추상화 개념에 대해서 고민해보겠습니다.
3. 답변 감사합니다! 우선 책임이란 개념을 클래스까지에만 고민해보면서 학습해보도록 하겠습니다!

2022-04-07 14:12 UTC, ecvheo1 commented
# ✅ 2차 피드백 반영사항

- Operator.java : o.operator 변수가 null이 들어갈 가능성이 있기 때문에, `o -> Objects.*equals*(o.operator, operator)` 로 필터링 처리를 하였습니다.
- HistoryServiceImplTest.java : assertThat 메서드를 활용하여 not null 테스트를 수행하였습니다.
- Calculator.java, Menu.java : 유효한 입력인 1과 2를 Enum으로 정의하여 관리하도록 리팩토링하였습니다.

2022-10-19 12:37 UTC, merged