[2기-C] 김산 1주차 java-calculator 미션 제출
prgrms-be-devcourse/java-calculator pull request #48
Opened 2022-03-30 05:40 UTC by waterfogSW

## 📌 과제 설명 

자바 계산기 구현 미션입니다.

## 👩‍💻 요구 사항과 구현 내용

- 사용자 인터페이스 구현하기
  - [x] 콘솔을 이용하여 출력
  - [x] 콘솔을 이용하여 입력
- 계산 기능 구현하기
  - [x] 더하기
  - [x] 빼기
  - [x] 곱하기
  - [x] 나누기
  - [x] 우선순위(사칙연산)
- 테스트 코드 작성하기
  - [x] 테스트 코드 구현하기
- 데이터 저장소 구현하기
  - [x] 계산 이력 저장하기
  - [x] 계산 이력 불러오기
- [x] 정규표현식 사용

![image](https://user-images.githubusercontent.com/28651727/160759017-b250fb60-44a3-4b85-b601-38409a69dcac.png)

## ✅ 피드백 반영사항

- 사용 용도가 불분명한 상수명을 용도를 알 수 있도록 변경하였습니다.
  - ex) regex -> FORMULA_REGEX, regex -> MENU_REGEX, regex -> SPLIT_REGEX
  - interface로 상수를 따로 분류해 두는것은 인터페이스의 사용 목적을 곡해하는것이라 생각하여 유틸리티 클래스로 따로 만들어 모아 두었습니다. (`ErrorMessage`, `ValidationRegex` )
- `Calculator.java` 클래스의 if else문을 switch문으로 변경하였습니다.
- `CalculateServiceImpl`의 사칙연산을 `Operator`의 Bifunction을 통해 처리하였습니다.
- `HistoryService`의 인덱스 필드(id)를 `CalculationRepository`로 옮겨 저장소가 인덱스를 처리하도록 하였습니다.
- 코드 주석들을 추가하였습니다.

## ✅ PR 포인트 & 궁금한 점

- 메서드 명으로 기능을 쉽게 파악할 수 있다 생각되는 메서드들에 대해서도 주석을 달아주는것이 좋나요?
  - 주석이 많으면 많을수록 좋은것인지 궁금합니다
- 제 유틸리티 클래스 (`ErrorMessage`, `ValidationRegex` )의 활용이 적절한지 궁금합니다.
- `Calculator`의 try catch문에서 발생한 예외에 따라 catch()문이 많이 만들어 지는것 같습니다. 만약 추후 예외가 많이 만들어 진다면 catch문이 더 많아저 코드의 가독성이 떨어질것 같은데 실무에서는 어떻게 처리하는지 궁금합니다.
- `PostfixConverter`의  25 Line `op.equals(Operator.LPR.symbol)`는 `Operator` enum 클래스를 사용하여 문자열을 처리하도록 하였습니다.  앞서 말씀드린 유틸리티 클래스(`OP`)를 추가적으로 만들어 상수로 처리한다면 `op.equals(OP.LPR)`과 같이 짧게 코드를 작성할 수 있을것 같은데 비슷한 역할의 클래스가 생긴다는 점이 걸려  `op.equals(Operator.LPR.symbol)`로 처리하였습니다. 어떠한 방식이 더 좋을지, 지금의 방식도 나쁘지 않은것인지 궁금합니다.

2022-03-30 09:04 UTC, WooSungHwan requested changes
코멘트 확인 부탁드릴게요 ㅎㅎ

2022-03-30 09:04 UTC, WooSungHwan commented on src/main/java/com/waterfogsw/repository/MemoryCalculationRepository.java
> +        incrIdx();
더 나아가서 말씀드리자면
calIdx 변수 삭제하시고 store에서 조회하여 max 취해주세요. 단일스레드 환경이지만 이런 변수선언으로 인해 치명적인 오류가 발생할 수 있습니다. 
여유가 되신다면 두 스레드가 save 메소드에 동시에 접근하는 경우를 고려해보시고 어떻게 해결할수 있을지 고민해보세요.

2022-03-30 09:04 UTC, WooSungHwan commented on src/main/java/com/waterfogsw/service/CalculationServiceImpl.java
> +                String result = calculate(ZERO, x, Operator.MIN.symbol);
이런경우 차라리 calculate 메소드를 Operator 타입의 파라미터로 선언하고 메소드를 내부에서 symbol을 꺼내 쓰시는건 어떠세요? symbol은 getter로 접근하구요!

2022-03-30 09:10 UTC, WooSungHwan commented
1. 주석이 많으면 많을수록 좋은것인지 궁금합니다 -> 개발자 스스로 애매하다고 판단되는 부분, 히스토리로서 필요한 부분, 코드의 흐름을 망치지 않는 한의 최소한의 주석이 좋긴합니다. if문 조건에 적절한 주석을 기재해주는 것 정도는 좋지만 그안의 흐름까지 설명해줄 필요는 없습니다.
2. 제 유틸리티 클래스 (ErrorMessage, ValidationRegex )의 활용이 적절한지 궁금합니다. -> 적절히 잘 활용하셨습니다. 정답은 없으니 다른 방법이 생각다면 다양하게 시도해보세요.
3. Calculator의 try catch문에서 발생한 예외에 따라 catch()문이 많이 만들어 지는것 같습니다. 만약 추후 예외가 많이 만들어 진다면 catch문이 더 많아저 코드의 가독성이 떨어질것 같은데 실무에서는 어떻게 처리하는지 궁금합니다. -> 실무에서는 개발자들이 생각보다 많이 프레임워크의 도움을 많이 받고 있는게 사실입니다. 하지만 직접 예외처리를 하는 경우도 있긴 해요. 보통 어플리케이션의 데이터는 데이터베이스에 의존하고 있다보니 데이터베이스의 데이터를 무결하게 유지하기 위해서는 Exception 상황시 해당 데이터를 커밋할지 롤백할지에 대한 예외처리가 대부분인데 해당 과제도 마찬가지입니다. 계산 결과를 insert 하였는데 추후 로직에서 에러가 발생하여 넣은 데이터를 어떻게 처리할지에 대한 고민부터 시작해보시고 최대한 많은 파라미터 케이스에 대비하는게 그래서 중요합니다.
4. 4번째 질문은 리뷰에 달아놓았습니다.

수고하셨습니다!

2022-04-01 14:57 UTC, waterfogSW commented
## ✅ 피드백 반영사항

### 1. Calculator의 run메소드

내부의 메뉴 입력부분을 private method로 분리하여 depth를 줄여보았습니다.

### 2. LPR, RPR 괄호 연산자

LPR, RPR은 계산기 민션에서 정의된 연산자가 아니므로, 별도의 enum클래스로 분리하였습니다. 
다만, 괄호가 수학적으로는 연산자라는 그룹에 묶이고, -+*/와 같은 대수적 연산자와 우선순위를 비교를 해야하므로, 

operator라는 인터페이스를 정의하고
- operator를 상속하는 대수적연산자[-, +, *, /] enum 클래스
- operator를 상속하는 괄호 연산자[ ( , ) ]
둘로 나누어 보았습니다. 

operator라는 인터페이스는 int getPriority() 메서드를 정의하여 대수 연산자든 괄호 연산자든 getPriority()만 호출하면 연산자의 우선순위를 얻어 비교할 수 있도록 만들어 보았습니다.

어떻게 보면 enum클래스를 interface를 통해 그룹화 한듯한데 이러한 방식이 옳은지는 잘 모르겠습니다.

### 3. Operator.java

isOperator 메서드의 경우에는 filter(Objects::nonNull)을 통해 Null인 경우를 필터링 해주었는데요, 
피드백해주신 의도대로 한건지 잘 모르겠습니다.

### 4. 사용자 정의 예외

RuntimeException을 상속하지 않는 클래스는 CheckedException이 되는것으로 알고있는데
CheckedException 생성하여 예외처리가 강제되도록 구현하라 라는 말은 잘 이해를 못했습니다. ㅠㅠ

### 5. ErrorMessage의 접근제어자

ErrorMessage의 접근제어자 private으로 지정해 주었습니다.

### 6. MemoryCalculationRepository - thread safety

처음에는 클래스 멤버변수에 AtomicLong으로 인덱스를선언하여 관리 하려고 했으나, store.put하는 과정까지 atomic해야 된다고 생각해서 save메서드에 syncronized 키워드를 정의하였습니다.

### 7. CalculationServiceImpl.java

연산자를 입력받는 3번째 파라미터같은 경우 다시 생각해보니 Operator.MIN.symbol으로 고정할게 아니라 token으로 변경하였습니다.

2022-04-04 00:39 UTC, WooSungHwan approved these changes
과제하시느라 고생하셨습니다!!

2022-04-04 00:39 UTC, WooSungHwan commented on src/main/java/com/waterfogsw/Calculator.java
> +        }
화살표 스위치 진짜 깔끔하네요.. bb

2022-04-04 00:39 UTC, WooSungHwan commented on src/main/java/com/waterfogsw/domain/Algebraic.java
> +    DIV("/", 3, (x, y) -> {
좀더 나아가서 우선순위도 별도로 enum으로 분리해서 로직을 고민해보시기 바랍니다.ㅎㅎ

2022-04-13 00:52 UTC, closed without merging