[2기-C] 정해민 1주차 java-calculator 미션 제출합니다.
prgrms-be-devcourse/java-calculator pull request #53
Opened 2022-03-30 15:32 UTC by haemin-jeong

## 📌 과제 설명 
사칙 연산 계산기를 콘솔로 구현

기능
1. 계산 이력 출력하기
    - 계산 이력이 없는 경우 안내 메시지 출력
3. 수식을 입력받아 계산 결과 출력하기
    -  잘못된 수식이 입력되는 경우 에러 메시지 출력
 
## 👩‍💻 요구 사항과 구현 내용 
### 구현 내용
- 콘솔로 구현
- 객체지향적인 코드로 계산기 구현하기
    - [x]  더하기
    - [x]  빼기
    - [x]  곱하기
    - [x]  나누기
    - [x]  우선순위(사칙연산)
- [x]  테스트 코드 구현하기
- [x]  계산 이력을 맵으로 데이터 저장기능 만들기

### 예외처리
- 잘못된 메뉴를 선택
- 비어있는 수식이 입력
- 숫자와 연산자의 순서가 올바르지 않음
- 숫자와 사칙 연산자 외에 다른 문자가 수식에 포함
- 0으로 나누는 연산
- 계산 이력이 없는 경우
## ✅ 피드백 반영사항  

## ✅ PR 포인트 & 궁금한 점 
- 클래스 또는 메서드를 어떤 기준, 단위로 분리해야 하는 것인지 잘 모르겠습니다.
    - 메서드의 경우 코드의 깊이가 깊어진다고 생각되거나(코드의 깊이는 어느 정도까지 괜찮다고 볼 수 있을까요?🤔), 어떤 코드가 무슨 역할을 하는지 명시적으로 표현하고 싶은 경우 분리하였습니다.  
- 패키지를 어떤 식으로 나눠야 할지 감이 잘 잡히지 않습니다.
- 예외처리 코드를 올바르게 작성하고 있는 것인지 궁금합니다.
- 어떤 기준으로 주석을 작성하는 것이 좋은지 궁금합니다. 가능하다면 대부분의 메서드, 클래스에 최대한 자세히 주석을 달아놓는 것이 좋을까요?
- 아직 모르는 게 너무 많아서 무엇을 궁금해야 할지, 잘못된 점이 무엇인지 잘 모르겠습니다🥺 마구마구 피드백 부탁드립니다😀

2022-03-31 01:57 UTC, WooSungHwan requested changes
굉장히 잘해주셨습니다 해민님!ㅎㅎ 코멘트 확인 부탁드려요~

2022-03-31 01:57 UTC, WooSungHwan commented on src/main/java/com/caculator/Calculator.java
> +            }
깔끔하네요 ㅎㅎ 잘 정리하셨어요!

2022-03-31 01:57 UTC, WooSungHwan commented on src/main/java/com/caculator/Calculator.java
> +        return history.size() == 0;
history != null 정도가 간단히 추가되면 좀더 안심될것 같네요.

2022-03-31 01:57 UTC, WooSungHwan commented on src/main/java/com/caculator/ErrorMessage.java
> +}
잘하셨어요. 근데 인터페이스 보다는 class안에 public static final로 선언하는게 좀더 개념상 맞을것 같아요.

2022-03-31 01:57 UTC, WooSungHwan commented on src/main/java/com/caculator/Operator.java
> +        throw new IllegalArgumentException("연산자(+, -, *, /)가 아닙니다.");
이거 equals 와 ||를 활용하지 않도록 고민해보세요.

2022-03-31 01:57 UTC, WooSungHwan commented on src/main/java/com/caculator/util/PostfixConverter.java
> +        if (isEmptyExpression(split)) throw new IllegalArgumentException();
이런부분도 과연 if문을 써서 표현해야만 할 수 있을까? 한번 고민해보세요 ㅎㅎ

2022-03-31 01:57 UTC, WooSungHwan commented on src/main/java/com/caculator/util/PostfixConverter.java
> +        return expressions.length == 0;
여기도 마찬가지로 expressions 인스턴스가 null인지 선행체크 해야될것 같아요.

2022-03-31 02:04 UTC, WooSungHwan commented
1. 어떤 코드가 무슨 역할을 하는지 명시적으로 표현하고 싶은 경우 분리하였습니다. -> 네 그렇게 시작하시면 됩니다. 먼저 클래스 분리부터 시작하게 된다면 많이 어려워요. 요구사항이나 글만읽고서 클래스분리부터 생각한다면 이미 경험치가 많이 쌓인거에요. 코드한줄 한줄 작성해보고 분리를 하는게 나쁜게 아닙니다. 원래 그렇게 시작하는거에요 ㅎㅎ
2. 패키지를 어떤 식으로 나눠야 할지 감이 잘 잡히지 않습니다. -> 제 방법이긴한데 저는 그냥 루트패키지에 죄다 만들어놓고 그냥 적절히 나중에 커밋할때 쪼개기도 하는데 그렇게 백지상태에서 패키지를 한번 쪼개보시는것도 좋은 방법이라고 생각해요. 이게 조금 시야가 트이면 본인만의 혹은 추후 만나게될 팀의 구조내에서 수월하게 하실거에요.
3. 예외처리 코드를 올바르게 작성하고 있는 것인지 궁금합니다. -> 네 잘 작성하셨습니다. 코멘트에 있는 내용한번 확인하고 리팩토링 해보세요.
4. 어떤 기준으로 주석을 작성하는 것이 좋은지 궁금합니다. 가능하다면 대부분의 메서드, 클래스에 최대한 자세히 주석을 달아놓는 것이 좋을까요?
-> 주석은 필요한 곳에 최소로! 라는 게 제일 베스트이긴한데 이건 지나친 이상주의같고 저는 현재 `if문의 조건이 복잡하거나 로직을 읽어나가기에 애매해 보이는 경우`, `히스토리 관리가 필요한 경우`, `메소드 기능 명시` 이런 상황에만 쓰고 있어요.

2022-03-31 07:44 UTC, haemin-jeong commented on src/main/java/com/caculator/Calculator.java
> +        return history.size() == 0;
안녕하세요 흑구님!
`history != null && history.size() == 0`과 같이 단순히 들어온 인자가 널이 아닌 경우에만 size를 확인하는 정도로만 수정을 해도 괜찮을까요?

2022-03-31 07:55 UTC, haemin-jeong commented on src/main/java/com/caculator/Calculator.java
> +        return history.size() == 0;
> history != null 정도가 간단히 추가되면 좀더 안심될것 같네요.

안녕하세요 흑구님!
`history != null && history.size() == 0`과 같이 단순히 들어온 인자가 널이 아닌 경우에만 size를 확인하는 정도로만 수정을 해도 괜찮을까요?

2022-04-04 00:24 UTC, WooSungHwan commented on src/main/java/com/caculator/Calculator.java
> +        return history.size() == 0;
@haemin-jeong 해당 메소드의 입장에서는 파라미터가 null인지 아닌지 판단할 근거가 부족하므로 개발자의 주관이 필요한 경우가 있기도 하겠으나 타인과 협업할 경우 불필요한 예외를 발생시킬 가능성은 최대한 피해주는게 좋을 것 같습니다.

2022-04-04 00:25 UTC, WooSungHwan commented on src/main/java/com/caculator/Calculator.java
> +        return history.size() == 0;
아 제가 잘못이해했네요; 해민님 판단하에 size를 볼지 해당 컬렉션의 isEmpty를 볼지 결정하셔도 됩니다.

2022-04-04 00:31 UTC, WooSungHwan approved these changes
ㅎㅎ과제하시느라 고생 많으셨습니다!

2022-04-04 00:31 UTC, WooSungHwan commented on src/main/java/com/caculator/ErrorMessage.java
> +public final class ErrorMessage {
클래스를 final로 한 이유가 뭔가요??

2022-04-04 00:31 UTC, WooSungHwan commented on src/main/java/com/caculator/util/Operator.java
> +    DIVIDE("/", 2,(n1, n2) -> n1 / n2);
추후에는 priority도 별도로 이넘으로 분리해서 관리해보세요. 많이쪼갤수록 좋은경우는 많이봤지만 덜 쪼갠다고 좋은경우 많이 못봤습니다.ㅎㅎ

2022-04-05 07:47 UTC, haemin-jeong commented on src/main/java/com/caculator/ErrorMessage.java
> +public final class ErrorMessage {
@WooSungHwan 해당 클래스가 단순히 메시지를 저장하는 용도의 클래스이기 때문에 다른 클래스에서 상속할 일이 없다고 생각되어  final 키워드를 사용했습니다!

2022-04-05 15:22 UTC, haemin-jeong commented
안녕하세요 흑구님! 피드백 주신 내용 수정해봤습니다. 감사합니다😀

### 피드백 반영 및 수정 사항
- 우선순위 계산 로직을 Enum으로 분리
- 예외를 생성할 때 예외 메시지 작성 -> 예외 메시지를 통해 어떤 이유로 예외가 던져진 것인지 알려주는 것이 좋을 것 같아서 추가했습니다.

2022-04-08 13:27 UTC, merged