[2기-P] 김현정 1주차 java-calculator 미션 제출합니다.
prgrms-be-devcourse/java-calculator pull request #55
Opened 2022-03-30 16:50 UTC by kkj0419

## 📌 과제 설명 
- TDD & OOP 를 고려한 계산기 프로그램

<br>

- double 자료형 피연산자들에 대하여 연산이 가능합니다.
- 후위 계산식을 이용하여 연산하였습니다.
- Console : 입출력
- Calculator : 연산 기능, 저장소 이용 기능
- CalculatorRepository : 계산 기록을 저장하는 저장소

## 👩‍💻 요구 사항과 구현 내용 

- 객체지향적인 코드로 계산기 구현하기
  - [x]  더하기
  - [x]  빼기
  - [x]  곱하기
  - [x]  나누기
  - [x]  우선순위(사칙연산)
- [x]  테스트 코드 구현하기
- [x]  계산 이력을 맵으로 데이터 저장기능 만들기
- [ ]  (선택) 정규식 사용(사용하지 않았습니다.)

## ✅ PR 포인트 & 궁금한 점 

- (1) 연산자의 우선순위를 비교하는 부분을 Operator로 넘겨 구현하였습니다. 이 부분을 다른 클래스로 나누어 구현하는 게 더 좋을지, 아니면 지금의 방식이 괜찮은 것인지 궁금합니다.

- (2) 계산식을 후위 표기법으로 바꾸는 과정의 코드의 가독성이 너무 떨어진다고 느낍니다. 이를 개선해 본다면 어느 부분을 바꾸는 게 좋을까요? 후위 표기로 변환하는 작업과 계산하는 작업을 동시에 하는 것보다, 둘을 분리하는 게 지금에서는 더 나은 방법인가요?

- (3) 테스트를 작성하는 데에 익숙하지 않아 간단한 테스트만 작성하게 되었습니다. 제가 한 방법이 괜찮은 것인지, 또 제가 작성한 테스트 이외에도 필수적으로 진행해야 할 테스트가 있다면 어떤 것인지 궁금합니다.

2022-03-31 14:50 UTC, SeokRae requested changes
![image](https://user-images.githubusercontent.com/17922700/161042865-16c28419-01d4-4956-a50b-14e13291e202.png)

순수 자바로 학습을 시작한다고 하면 두 개 의 의존성 정도만 추천 드립니다.
테스트 관련 의존성만으로 이것저것 해보는 것이 어떤 곳에서든지 도움이 되거든요. !
```
  testImplementation 'org.junit.jupiter:junit-jupiter:5.8.2'
  testImplementation 'org.assertj:assertj-core:3.22.0'
```

## 궁금한거

> (1) 연산자의 우선순위를 비교하는 부분을 Operator로 넘겨 구현하였습니다. 이 부분을 다른 클래스로 나누어 구현하는 게 더 좋을지, 아니면 지금의 방식이 괜찮은 것인지 궁금합니다.

연산 처리 하는 역할을 하고 있는 객체가 연산에 대한 우선순위를 정하는 것까지 맡아서 처리해야 하지 않을까 생각되네요. 저는 괜찮다고 생각됩니다.

> (2) 계산식을 후위 표기법으로 바꾸는 과정의 코드의 가독성이 너무 떨어진다고 느낍니다. 이를 개선해 본다면 어느 부분을 바꾸는 게 좋을까요? 후위 표기로 변환하는 작업과 계산하는 작업을 동시에 하는 것보다, 둘을 분리하는 게 지금에서는 더 나은 방법인가요?

연산에 대한 알고리즘은 여기 피드백에서는 드리지 못하는 점 죄송하게 생각합니다. !
왠만하면 현재 단계에서는 OOP에 대한 부분만 피드백드리려고 하고 있습니다.. 😂

> (3) 테스트를 작성하는 데에 익숙하지 않아 간단한 테스트만 작성하게 되었습니다. 제가 한 방법이 괜찮은 것인지, 또 제가 작성한 테스트 이외에도 필수적으로 진행해야 할 테스트가 있다면 어떤 것인지 궁금합니다.

숫자와 관련된 테스트는 가장자리에 있는 숫자들을 테스트 하는 것이 중요합니다.
이를테면 -1, 0, 1 그리고 타입에 따라 처리할 수 있는 범위를 벗어나는 값에 대해서는 어떻게 처리하는지?
현재는 값이 입력되는 부분이라고 머릿속에 생각하신 부분인 Calculator, CalculatorRepository에 대해서만 테스트를 진행하신 것처럼 보이는데 실질적으로 데이터를 처리하는 Operator 같은 부분은 필수적으로 작성하셔야 합니다.
커멘트 단 것 처럼 나누기 연산에 대한 예외는 처리가 안되어 있어, 이런부분의 검증이 필수이기 때문이죠!

2022-03-31 14:50 UTC, SeokRae commented on src/main/java/engine/Calculator.java
> +            double operand = Double.valueOf(formula[i + 1]);
```suggestion
            double operand = Double.parseDouble(formula[i + 1]);
```

valueOf와 parseDouble은 차이점이 조금 있는데요.
내용 한번 확인해보시면 좋을 듯 합니다.


[Double.valueOf(s) vs. Double.parseDouble [duplicate]](https://stackoverflow.com/questions/7255078/double-valueofs-vs-double-parsedouble)

2022-03-31 14:50 UTC, SeokRae commented on src/main/java/engine/repository/CalculatorRepository.java
> +public class CalculatorRepository implements Repository<Integer, String> {
설마 JPA의 영향일까요? 😱😭😭

2022-03-31 14:50 UTC, SeokRae commented on src/main/java/engine/Calculator.java
> +        while (true) {
Calculator라는 코어 로직이 있는 메서드에 `프로그램을 실행할 값을 입력을 받아 조건에 따라 수행한다.`
라는 절차적인 로직은 분리가 가능하지 않을까 싶긴합니다.

메서드 추출이라는 리펙토링 방식부터 시도해보면 어떨까요?

2022-04-04 14:10 UTC, kkj0419 commented on build.gradle
> +    implementation 'org.codehaus.groovy:groovy-all:3.0.5'
프로젝트 생성하는 와중에 잘못 추가되었네요...😅 수정하겠습니다~!!

2022-04-05 12:04 UTC, kkj0419 commented on src/main/java/engine/repository/CalculatorRepository.java
> +public class CalculatorRepository implements Repository<Integer, String> {
JPA에서 저렇게 배웠어서 관성적으로 작성한 게 맞습니다..ㅠㅠ
근데 이렇게 작성할 시 문제가 있을까요..??
제가 검색한 바로는 해답을 찾지 못하겠어서 질문드립니다.ㅠ

2022-04-06 06:28 UTC, kkj0419 commented on src/main/java/engine/repository/CalculatorRepository.java
> +public class CalculatorRepository implements Repository<Integer, String> {
설명해주신 부분 이해했습니다!!
그에 맞게 더 생각해보고 수정하도록 하겠습니다😢
답변 감사합니다😎😎

2022-08-16 15:22 UTC, merged