[2기-C] 이한주 1주차 java-calculator 미션 제출합니다.
prgrms-be-devcourse/java-calculator pull request #56
Opened 2022-03-30 19:00 UTC by yanJuicy

## 📌 과제 설명 
TDD & OOP를 이용한 계산기 작성

## 👩‍💻 요구 사항과 구현 내용 
- 객체지향적인 코드로 계산기 구현하기
    - [x]  더하기
    - [x]  빼기
    - [x]  곱하기
    - [x]  나누기
    - [x]  우선순위(사칙연산)
- [x]  테스트 코드 구현하기
- [x]  계산 이력을 맵으로 데이터 저장기능 만들기

## ✅ 피드백 반영사항  
1. History 클래스의 showHistory 부분 삭제 -> getMemory로 바꿔 Main 에서 실행 시 사용
2. Main 내에 if - else 문 switch 문으로 변환
3. Calculator 클래스 내에서 연산자를 Operator 클래스로 분리
4. switch 문의 case에 상수 변수를 사용
5. 사칙연산 말고 다른 게 나오는 경우 예외 처리
6. 테스트 코드 작성

## ✅ PR 포인트 & 궁금한 점 
1. 모든 클래스에 대해 테스트 코드를 작성해야하나요?
2. OOP가 잘 된건지 모르겠습니다.

2022-03-31 02:22 UTC, WooSungHwan requested changes
테스트코드도 잘 작성해주셨네요! 
코멘트 확인 부탁드립니다!

2022-03-31 02:22 UTC, WooSungHwan commented on src/main/java/me/programmers/calculator/Main.java
> +            }
굿굿 깔끔하네요.!!! 근데 최근 회화를 배우는 입장으로써 문제라는 단어를 Problem이 아닌 fomular라던가 다른 계산식과 관련된 단어로 명시하는게 어떨까요? 적절한 단어를 활용하여 메소드명을 작성하는 고민은 개발자에게 필수입니다. 한번 고민해보세요. ㅎㅎ

2022-03-31 02:22 UTC, WooSungHwan commented on src/main/java/me/programmers/calculator/engine/Calculator.java
> +    }
이 메소드 부분 최대한 정리/분리해서 메소드 뎁스 줄여보도록 하세요. 이 부분은 반드시 고민해보시기 바랍니다.

2022-03-31 02:22 UTC, WooSungHwan commented on src/main/java/me/programmers/calculator/engine/Calculator.java
> +    private final String DIV = "/";
이제 얘네들을 Operator  Enum으로 별도로 정의해보세요! 그리고 얘네들 가져다 쓰는 부분들 다 Operator Enum으로 활용하도록 해보세요!

2022-03-31 02:22 UTC, WooSungHwan commented on src/main/java/me/programmers/calculator/engine/Operator.java
> +public class Operator {
이 클래스가 Enum이 될거고 우선 플러스,마이너스,곱셈,나눗셈부터 정의하고 아래 static메소드들 수정해나가 보세요 !

2022-03-31 02:22 UTC, WooSungHwan commented on src/main/java/me/programmers/calculator/engine/excpetion/InputException.java
> +public class InputException extends RuntimeException {
런타임 으로 상속하신 이유가 있어요?ㅎㅎ

2022-03-31 02:22 UTC, WooSungHwan commented on src/main/java/me/programmers/calculator/engine/excpetion/Validator.java
> +public class Validator {
클래스가 깔끔하네요 ㅎㅎ 순서도 적절한것 같습니다.

2022-03-31 02:22 UTC, WooSungHwan commented on src/main/java/me/programmers/calculator/engine/model/History.java
> +    }
(선택) 현재 스레드풀에 관리되는 스레드가 10개가 있는 상황에서 어플리케이션이 동작되고 있고, saveMemory메소드에 동시에 두개의 스레드가 접근하여 memory에 값을 넣으려고 할때 map의 키값인 order가 과연 하나의 값만 삽입되는 코드인지 생각해보세요!

2022-03-31 02:22 UTC, WooSungHwan commented on src/main/java/me/programmers/calculator/Main.java
> +        }
key가 없는 경우도 있으니 keyset 메소드를 활용해보시기 바랍니다.

2022-03-31 05:02 UTC, yanJuicy commented on src/main/java/me/programmers/calculator/engine/excpetion/InputException.java
> +public class InputException extends RuntimeException {
입력 받은 계산식 문자열을 대상으로 하는 예외여서 RuntimeExcpetion을 상속했습니다.

2022-04-06 12:01 UTC, yanJuicy commented
✅ 피드백 반영사항
1. 메소드 이름 변경
2. enum 변수를 이용해 switch 문 변경
3. Calculator 클래스 내 fourOperations 메소드 크기 줄임
4. History 클래스 내 saveMemory 메소드 synchornized를 통한 동기화

2022-04-07 01:53 UTC, WooSungHwan approved these changes
과제하시느라 고생하셨습니다. ㅎㅎ

2022-04-07 01:53 UTC, WooSungHwan commented on src/main/java/me/programmers/calculator/Main.java
> +    private final String CALCULATE = "2";
제가 왜 이방법을 말씀드렸냐면.. 결국 여기에 입력이 늘어날수록 변수가 늘어나겠죠? 그럼 관리해야될 클래스로 별도로 뺄 생각을 하게되는데 그 별도로 뺄 클래스가 결과적으로 enum클래스가 될 가능성이 높습니다. enum에는 유틸적으로 제공해주는 상수성이 있기 때문이에요. enum에 대해서 아직 감이 잘 안잡히신다면 자바 서적 enum 부분에 대해 반드시 정독해보시는 걸 추천드려요.

2022-04-07 02:00 UTC, WooSungHwan commented
모든 클래스에 대해 테스트 코드를 작성해야하나요?
-> 제가 이 질문에 대해서 답변을 제대로 못드린것 같아서 코멘트 남깁니다.
일단 모든 클래스에 대해서 테스트코드를 추가해주면 best입니다. 하지만 각 팀마다 각 개발자마다의 업무 난이도 및 실력이 다를테므로 전체 개발자가 모두 실행하기는 어려운 형편일 것입니다. 이상은 이상일뿐이니까요. 그러니 본인의 기본 테스트 커버리지를 어느정도 생각해서 기본으로 가져가시고 사고를 확장해보시기 바랍니다. 어떻게 하면 설정클래스도 테스트코드로 설정이 적용됐는지 확인해볼 수도 있을 것 같고요. jpa repository에 내가 적용한 쿼리만 테스트하고싶은데 어떻게하면 별도로 쿼리만 테스트할 수 있을지.. 그 쿼리를 테스트하기 위해서는 어떤 사전 컨디션이 필요한지.. 등등 너무 많죠. 경험이 많이 필요한 부분이니 이번 코스를 통해 한주님의 개발 스타일에 맞는 테스트 영역을 우선 고려해보세요. 

개인적인 논점으로는 이미 많은 개발자들이 이 테스트 영역이 큰 사람을 좋아하긴 합니다. 그럼 사실 선택이라기보단 필수가 되어가는 중인것 같습니다. 스프링을 학습하면서 본인 코드를 많이 테스트해보세요. 눈으로 보지 마시고 눈으로 보는건 초록색 불 들어오는것만 확인하시면 됩니다.

2022-04-07 07:51 UTC, yanJuicy commented on src/main/java/me/programmers/calculator/Main.java
> +    private final String CALCULATE = "2";
아 입력이 늘어나는 것에 대한 경우는 생각하지 못했네요... enum에 대해 다시 공부하겠습니다. 감사합니다 :)

2022-10-19 12:36 UTC, merged