[코드리뷰요청] 1주차 2주차 java_calculator 미션 제출합니다
prgrms-be-devcourse/java-calculator pull request #60
Opened 2022-03-31 14:25 UTC by choi1204

## 📌 과제 설명 
스택을 활용하여서 우선순위를 고려하는 사칙연산 계산기를 만들었습니다.
또한 계산한 내역들을 저장해 어떤 계산들을 하였는지 조회하는 기능도 있습니다.

## 👩‍💻 요구 사항과 구현 내용 

feat : 기본 프로젝트 세팅 - > maven 프로젝트 생성
feat : 초기 프로젝트 구현 - > README 파일 변경
feat(calculate) : calculate 기능 구현  -> 실질적 계산역할을 담당하는 calculate와 enum Operation 구현
feat(IO) : 입출력 기능 구현 - > input, output 인터페이스와 그 구상체인 console 구현
feat(Record) : Record 구현 - > 계산이력을 저장하는 Record 구현
feat(Validator) : validator 구현 - > 입력된 수식의 유효성을 판단하는 validator 구현. 실 구상체는 정규표현식으로 유효성 판단
feat(Calculator) : Calculator 구현 - > 이 모든 기능을 사용하는 Calculator 구현.
feat(TestCode) : 테스트코드 구현 - > 테스트 코드 구현. 

## ✅ 피드백 반영사항  
save()내에서 동시성을 고려하여서 메소드 변경.
init()함수 내부에서 예외처리를 해주는 것이 아닌 array를 List로 변경하는 메소드내부에서 예외처리 진행. (split의 근본적 문제 해결x)
무한포문 탈출 구현.

## ✅ PR 포인트 & 궁금한 점 
Record - RecordMemoryRepository - save() 메소드의 동시성을 처리하기 위해서 synchronized를 활용하여서 이러한 방식이 맞는지 궁급합니다
Operation을 enum으로 활용하여서 구현을 하였는데 enum의 클래스 내부에 static영역으로 map을 통해 초기화하였는데 이러한 방식으로 할 경우의 장점과 단점, 멘토님이라면 어떠한 점을 고려하여서 어떤 방식으로 진행하였을지 궁금합니다
Calculator - calculatorProcess() 메소드의 switch문 내부에서 if문 사용이 depth가 깊어지고 지저분해 보여서 메소드화하여서 메소드를 사용하는 방식으로 진행하였는데 이러한 방식이 해결방안이 되는지 궁금합니다. 
Record의 id를 관리하는것이 Repository에서 관리하는게 옳다고 생각하여서 수정을 하였는데 Record 객체에서 id를 사용하는 부분이 없어서 클래스내부에 id필드를 제거하였는데 이런식으로 설계를 하는 것이 옳은지 궁금합니다

2022-04-04 00:21 UTC, WooSungHwan requested changes
깔끔하게 구현하였습니다. 지난번 리뷰에서 보다 성장을 위한 코멘트를 몇자 남겼으니 확인해보세요!

2022-04-04 00:21 UTC, WooSungHwan commented on src/main/java/Calculate/StackCalculate.java
> +    private void pushNumber(Iterator numberIter) {
Iterator를 받는게 아니라 iterator를 호출할 수 있는 컬렉션을 파라미터로 받는건 어떨까요?
그리고 이런 함수는 numberStack 같은 전역변수를 건드리는 것보다는 numberStack에 push한 결과를 별도로 만들어주는게 좀더 좋을 것 같습니다.
기왕 동시성도 이야기해드렸으니 이부분도 적용해보면 더 좋겠지요ㅎㅎ

2022-04-04 00:21 UTC, WooSungHwan commented on src/main/java/Calculate/StackCalculate.java
> +                .map(str -> str.replaceAll(" ",""))
String 상수들 static final 변수화 해주세요.

2022-04-04 00:21 UTC, WooSungHwan commented on src/main/java/Calculate/StackCalculate.java
> +    private Stack<Operation> operationStack;
얘네들 전역변수로 빼지 않고 해결할 수있는 방법을 고민해보세요.

2022-04-04 00:21 UTC, WooSungHwan commented on src/main/java/Calculator/Calculator.java
> +    }
일단 굉장히 깔끔하게 잘 진행된것 같습니다.ㅎㅎ 보기 좋네요.

2022-04-04 00:21 UTC, WooSungHwan commented on src/main/java/Calculator/Calculator.java
> +    }
다만 지난번에 try catch내에서 if문의 조회가 필요하다고 이야기했던 부분이 있는데..! 그부분은 프레임워크의 도움을 받는 과제가 아니기때문에 현재로써는 별도로 내부에 예외처리해야될 부분이 많이 필요하긴 해요. 하지만 catch문에 도달했을 때 별도로 정의해둔 클래스타입으로 Throwable을 넣어주고 hasError 식으로 switch문 아래에서 조건문을 처리하는 건 어떨까 생각해봤어요 ㅎㅎ

```
class Result {
 private Throwable error;
 public boolean hasError() { return this.error != null; }
}
```
뭐 이런 클래스가 있고
```
Result result = null;
switch() {
 case:A
  result = process(); // 에러가 났는지 뭐든지 일단 메소드는 정상종료. 안에서 throwable 넣어준다.
  break;
}

if (result.hasError) {
 // 예외처리공간.
}

```
대충 이런식인거죠!
여기까지하면 리팩토링해야될 부분이 많이 있으니까 내부 static class로 정의해두고 해당 switch 문에서만 진행해보세요.

2022-04-04 00:21 UTC, WooSungHwan commented on src/main/java/Calculator/Menu.java
> +    }
이런 value를 파라미터로 받고 맞는 enum 을 가져오는 메소드들은 대부분 동일한 패턴, 동일한 메소드명으로 추상화가 가능하고 추상화한 인터페이스에서 제네릭을 활용해서 처리할 수 있을거에요. 혹시 enum을 정형화해서 쓰고 싶으시다면 고민해보세요.

2022-04-04 00:21 UTC, WooSungHwan commented on src/main/java/Calculator/Menu.java
> +    }
https://github.com/WooSungHwan/demo-coin/blob/master/src/main/java/com/example/democoin/configuration/enums/EnumInterface.java

해당 클래스를 참조해보세요.

2022-04-04 00:21 UTC, WooSungHwan commented on src/main/java/Calculator/Operation.java
> +    DIV("/", (num1, num2) -> num1 / num2, 2);
사실 operator priority 같은 enum 클래스로 좀더 분리했으면 개념상 더 깊은 객체지향으로 뻗어나갈 수 있을 것 같습니다. 우선순위는 우선순위 이넘에 오퍼레이션 넘기면 인티저 받을 수 있는!

2022-04-04 00:21 UTC, WooSungHwan commented on src/main/java/Validator/Validator.java
> +        return contains;
validator 인터페이스가 자기 기본기능으로 가지기엔 애매합니다. 별도의 util 클래스를 정의해서 처리해야할 것 같습니다.

2022-04-08 12:10 UTC, choi1204 commented on src/main/java/Calculate/StackCalculate.java
> +    private void pushNumber(Iterator numberIter) {
안녕하세요 흑구님 iterator 관련해서 어떤식으로 수정해야할지 이해가 잘 가지 않아서 질문드립니다.

2022-04-08 12:16 UTC, choi1204 commented on src/main/java/Calculator/Operation.java
> +    DIV("/", (num1, num2) -> num1 / num2, 2);
> 사실 operator priority 같은 enum 클래스로 좀더 분리했으면 개념상 더 깊은 객체지향으로 뻗어나갈 수 있을 것 같습니다. 우선순위는 우선순위 이넘에 오퍼레이션 넘기면 인티저 받을 수 있는!

OperatorPriority를 만들면서 궁금했던 점이 있어서 질문드립니다.
OperatorPriority Enum 클래스의 인자를 Operator로 받아야할지 String 문자열로 받을지에 대해서 어떠한 점이 더 나을지에 더해서 질문드립니다.
ex)
public enum OperationPriority implements EnumInterface {
    ADD("+", 1),

vs

public enum OperationPriority implements EnumInterface {
    ADD(Operation, 1),

이러한 형식입니다.
전자의 경우 Operation클래스와 중복된 코드가 있다는 단점이 있어보이고 후자의 경우 다른 Enum클래스와 의존성을 맺고있어서 유연하지 못한 코드가 될 수 있을것 같다는 점들에 이러한 질문을 남깁니다

2022-10-19 12:36 UTC, merged