[2기-C] 김지웅 '계산기 TDD, OOP로 만들기' 과제 제출합니다.
prgrms-be-devcourse/java-calculator pull request #65
Opened 2022-04-01 05:02 UTC by wisehero

📌 과제 설명
계산기 TDD, OOP로 만들기
👩‍💻 요구 사항과 구현 내용
�스프링 기초 부분을 배웠던 때를 떠올리며 비슷하게 패키지 구조를 가져갔습니다.

model, repository, service로 나누었고 설정 파일 하나와 메인 애플리케이션을 실행하는 클래스를 두었습니다.

model

계산식을 저장하는 Expression 모델 정의
repository

해쉬맵을 사용하여 db 저장소로 사용하고 저장로직과 모든 연산 기록을 보여주는 기능을 만들었습니다.
service

UIService : 사용자에게 어떤 입력이 가능한 지 보여주고 입력에 따른 조회, 연산 기능을 수행하도록 작성
CaculateService: 연산자 우선순위를 고려한 연산 기능을 수행
✅ PR 포인트 & 궁금한 점
커밋 단위를 어떻게 가져가야할 지 아직 감이 잘 잡히지 않습니다. 중간에 수정해야할 부분이 또 보이면 너무 잦은 커밋을 하게 되는 것은 아닌지 걱정이 되는데 정답이 없는 문제인건지 혼란스럽습니다.

연산 기능이 제대로 동작하는 지에 대한 테스트만 작성했는데 문자열 출력 역시 의도대로 잘 되는지 테스트하는 코드는 어떻게 짜야할까요...?

UI Service와 계산 서비스를 구분해두긴 했는데 이게 의미있는 구분일지는 잘 모르겠습니다. 멘토님께서는 어떻게 생각하시는지 궁금합니다.

일요일부터 수요일까지 역병때문에 조금 힘들어서 부족한 부분이 많아 지적할 부분이 너무 많아 힘드실 수 있지만 주시는 피드백 최대한 반영하여 퀄리티를 높여보도록 하겠습니다. 감사합니다. TGIF!

## 📌 과제 설명 

## 👩‍💻 요구 사항과 구현 내용 

## ✅ 피드백 반영사항  

## ✅ PR 포인트 & 궁금한 점

2022-04-03 05:30 UTC, ksy90101 requested changes
안녕하세요 지웅님 : )
간단한 피드백을 남겼으니 한번 확인해보시면 좋을거 같습니다~
수정 후 다시 리뷰 요청주세요~

2022-04-03 05:30 UTC, ksy90101 commented on .gitattributes
> +*.bat           text eol=crlf
이 파일은 무엇일까요!?

2022-04-03 05:30 UTC, ksy90101 commented on app/build.gradle
> +    id 'application'
1. 필요없는 주석은 없애주시는게 좋을거 같아요.
2. java version을 명시해주면 어떨까요?

2022-04-03 05:30 UTC, ksy90101 commented on app/build.gradle
> +    implementation 'com.google.guava:guava:30.1.1-jre'
굳이 이게 필요할까요?

2022-04-03 05:30 UTC, ksy90101 commented on app/src/main/java/model/Expression.java
> +    private final String input;
식인거 같은데, 식에 과연 어떤 상태값이 있어야 할지 다시 한번 고민해보세요.

2022-04-03 05:30 UTC, ksy90101 commented on app/src/main/java/repository/ResultRepository.java
> +        // 저장 로직
굳이 주석이 필요할까요?

2022-04-03 05:30 UTC, ksy90101 commented on app/src/main/java/repository/ResultRepository.java
> +    private static Map<Long, Expression> db = new HashMap<>();
```suggestion
public class ResultRepository {

    private static Map<Long, Expression> db = new HashMap<>();
```

2022-04-03 05:30 UTC, ksy90101 commented on app/src/main/java/repository/ResultRepository.java
> +        for (Long key : db.keySet()) {
```suggestion
    public void showRecord() {
        for (Long key : db.keySet()) {
```

2022-04-03 05:30 UTC, ksy90101 commented on app/src/main/java/repository/ResultRepository.java
> +            System.out.println(db.get(key).getExpressionWithResult());
Repositioty에서 출력하는게 맞을까요?

2022-04-03 05:30 UTC, ksy90101 commented on app/src/main/java/service/CalculateService.java
> +public class CalculateService {
콘솔 프로그램에서 Service가 필요할까요?

2022-04-03 05:30 UTC, ksy90101 commented on app/src/main/java/service/CalculateService.java
> +            }
이게 과연 여기 있는게 맞을까요?
도메인 로직 같은데요!?

2022-04-03 05:30 UTC, ksy90101 commented on app/src/main/java/service/CalculateService.java
> +    public double CalValue(String userInput) {
전체적으로 메서드가 길어진다면 책임이 많다는 의미입니다.
한번 해당 로직을 분리해보세요.

2022-04-03 05:30 UTC, ksy90101 commented on app/src/main/java/service/CalculatorUIService.java
> +
View는 따로 빼놓는게 좋지 않을까요?

2022-04-03 05:30 UTC, ksy90101 commented on app/src/main/java/service/CalculatorUIService.java
> +            int number = Integer.parseInt(scanner.nextLine());
숫자가 아닌 값이 들어오면 어떻게 될까요?

2022-04-03 05:30 UTC, ksy90101 commented on app/src/main/java/service/CalculatorUIService.java
> +            if (number != 1 && number != 2) {
number가 아니라 menu이거나 command일거 같은데 enum으로 관리해보면 어떨까요?

2022-04-03 05:30 UTC, ksy90101 commented on app/src/test/java/service/CalculateService.java
> +class CalculateServiceTest {
테스트 코드가 너무 부족하네요.
도메인 분리가 제대로 되어 있지 않아서 그런대요.
이전에 미팅할때 이야기 했던 방식으로 도메인 분리를 해볼까요?

2022-04-03 05:30 UTC, ksy90101 commented on .gitignore
> +/.idea/
아직 이 폴더의 파일이 남아 있는거 같아요.

2022-04-06 10:40 UTC, wisehero commented on app/src/main/java/service/CalculateService.java
> +            }
@ksy90101 혹시 도메인 로직의 정확한 의미를 알 수 있을까요?!

2022-04-08 01:12 UTC, closed without merging