[2기-P 마지영] java-calculator 과제 제출합니다.
prgrms-be-devcourse/java-calculator pull request #69
Opened 2022-04-01 13:30 UTC by JiyoungMa

## 📌 과제 설명 

- 최대한 계산 관련 부분은 TDD로 구현하려고 노력했습니다.
- +, -, *, / 관련된 class는 OPP를 살려서 구현하기 위해 상속을 사용했습니다.
- Float 자료형을 사용해서 실수 계산도 가능할 수 있게 구현했습니다.
- Stack을 이용해서 우선순위 계산을 구현했습니다.

- arithmetic 패키지 : 덧셈, 뺄셈, 곱셈, 나눗셈 관련 클래스
- console 패키지 : input, output 관련 클래스 & input으로 받은 string을 다루는 클래스
- save 패키지 : 맵으로 저장하는 기능 관련 클래스
- MainClass : 메인 클래스

## 👩‍💻 요구 사항과 구현 내용 

- [x] 객체지향적인 코드로 계산기 구현하기
- [x]  더하기
- [x]  빼기
- [x]  곱하기
- [x]  나누기
- [x]  우선순위(사칙연산)
- [x]  테스트 코드 구현하기
- [x]  계산 이력을 맵으로 데이터 저장기능 만들기

## ✅ PR 포인트 & 궁금한 점 

- 테스트 코드를 잘 적었는지 궁금합니다. 막상 테스트 코드를 쓰고 구현을 하다보니, 비교를 해야 하는데 테스트 코드와 구현 코드가 거의 비슷해져서 이런 식으로 하는 게 맞는지 궁금합니다.
- 사칙 연산 관련해서 상속을 사용했는데, 혹시 더 좋은 방법이 있는지, 아니면 해당 방법은 별로 좋지 않은 방법인지 궁금합니다.
- 최대한 나눌 수 있는 기능들을 최대한 나누려다 보니 제 생각보다 코드가 조잡해진 것 같습니다. 혹시 이렇게 하나하나 다 구분을 하는 게 맞을까요?
- 기능을 나누다 보니 서로가 서로의 메소드를 실행하는 경우가 많은데, 이를 개선할 수 있는 방법이 있을까요?

2022-04-02 07:11 UTC, SeokRae requested changes
<img width="938" alt="image" src="https://user-images.githubusercontent.com/17922700/161367688-8b030643-12db-4666-bc69-1b6424bb5175.png">

테스트 코드를 작성하는데 많은 고민한 모습이 보이네요.!
커멘트 참고 부탁드립니다.

1. 객체에 Class라는 이름을 붙이는 것은 자바라는 프로그래밍 언어에 고정된 느낌이 있네요. 
자바 클래스명은 기본적으로 명사로 짓는 것이 컨벤션이기도 하고 객체지향적인 프로그래밍을 한다라고 하면 해당 역할에 알맞은 이름으로 명명하는 것이 좋아보입니다.

2. 특정 역할을 하는 객체를 생성하고 그 안에 객체가 갖고 있어야 하는 필드를 추가할 때는 불변객체를 기본으로 두고 개발을 시작해보세요. 수정이 필요한 필드에만 setter를 추가하는 식으로 접근함으로써 객체의 캡슐화를 이해하는데 도움이 될 것 같습니다.

## 궁금한거

> 테스트 코드를 잘 적었는지 궁금합니다. 막상 테스트 코드를 쓰고 구현을 하다보니, 비교를 해야 하는데 테스트 코드와 구현 코드가 거의 비슷해져서 이런 식으로 하는 게 맞는지 궁금합니다.

테스트는 관련 비즈니스 로직 처리 후 나온 결과 값을 기대한 결과 값으로 비교함으로써 검증하는 것입니다.
ex) "A를 입력하면 B라는 값이 나오도록 코드를 작성했으니까 B가 정상적으로 나오는지, C가 나오는 예외가 발생하지는 않는지?"

> 사칙 연산 관련해서 상속을 사용했는데, 혹시 더 좋은 방법이 있는지, 아니면 해당 방법은 별로 좋지 않은 방법인지 궁금합니다.

상속으로 구현도 가능하고, 같은 매커니즘으로 인터페이스를 통해 구현 클래스를 두어 동일하게 구현도 가능합니다. 또 enum으로도 가능합니다. 모두 시도해보라고 말씀드리고 싶지만 이 과제만 하는 것은 아니기에 추상클래스를 통해 구현을 해보셨으니 enum으로 수정해보시는 것을 권장합니다.

> 최대한 나눌 수 있는 기능들을 최대한 나누려다 보니 제 생각보다 코드가 조잡해진 것 같습니다. 혹시 이렇게 하나하나 다 구분을 하는 게 맞을까요?

객체지향, 디자인 패턴이 들어간 코드를 구현하는 경우 복잡도가 높아지는 것은 당연한 결과라 할 수 있을 것 같습니다. 다만 무작정 나눈다고 해서 좋은게 아니라서 객체 간의 역할과 책임에 대해 분리할 때 서로 연관관계에 대한 근거가 명확하다면 충분할 것 같습니다.

> 기능을 나누다 보니 서로가 서로의 메소드를 실행하는 경우가 많은데, 이를 개선할 수 있는 방법이 있을까요?

서로가 서로의 메서드를 호출하는 경우가 생기는 상황이 생기는 것은 그 호출하는 메서드의 역할이 명확하게 정해져 있는지, 그리고 그 자리에 있어야 하는 게 맞는지 고민해보시는 것이 좋을 것 같습니다. 
서로가 서로의 메서드를 호출하게 되면 객체 간에 사이클이 생긴다는 것인데 이는 구현의 문제 뿐만아니라 메모리 누수도 발생할 가능성도 존재합니다.

2022-04-02 07:11 UTC, SeokRae commented on src/main/java/arithmetic/Operator.java
> +    private char operator;
구조는 뭔가 시도해보려는 느낌이 있었지만 실제 operator에 대한 필드를 사용하지 않으신 것 같네요.
인터페이스의 목적에 더 알맞은 구조로 보입니다. 
추상클래스를 사용한다는 것은 기본 골격을 갖추고 그보다 디테일한 구조 및 기능 재정의, 훅과 같은 기능들을 사용하기 위함이거든요. 인터페이스와 추상클래스에 대해 정리하고 넘어가는 것도 좋을 것 같습니다.

2022-04-02 07:11 UTC, SeokRae commented on src/main/java/console/StringManipulator.java
> +        if (numberStack == null){
null에 대한 체크를 해야 하는 이유가 뭘까요?

2022-04-02 07:11 UTC, SeokRae commented on src/main/java/arithmetic/ArithmeticOperations.java
> +            if (nowOperatorChar == '+'){
위 연산자 선택 로직과 동일합니다.

2022-04-02 07:11 UTC, SeokRae commented on src/main/java/arithmetic/ArithmeticOperations.java
> +                if (nowOperatorChar == '*'){
Operator 문자열에 대한 특정 클래스를 생성해야 한다면 Factory 패턴으로 작성하는 것도 좋을 듯 하네요.
indent를 줄일 수도 있고, 산술연산자라는 클래스와 특정 연산 간의 결합도도 낮출 수 있을 것 같습니다.

2022-04-03 07:05 UTC, JiyoungMa commented on src/main/java/MainClass.java
> +        Output output = new Output();
Calculator이라는 Class를 만들어서 그 안에서 Output을  사용하는 방식으로 하는 것이 더 나을 것 같습니다!
지금 보니까 굉장히 갑자기 Output이랑 Input 안에서 모든 로직을 처리하는 것 같네요....ㅎㅎ

2022-04-03 07:06 UTC, JiyoungMa commented on src/main/java/MainClass.java
> +        while(true){
예시를 보고 구현하다가 종료 방법을 빼먹었네요...! 메뉴에서 3번을 추가하거나 하는 방식으로 종료를 추가해야겠습니다!

2022-04-03 07:07 UTC, JiyoungMa commented on src/main/java/console/StringManipulator.java
> +    public StringManipulator(){
아마 이건... 중간에 구현 중에 명시적인 기본 생성자가 없어서 오류가 나서 추가를 했던 거 같은데, 최종적으로는 사용한 적이 없네요ㅠ 추후에 삭제해도 될 것 같습니다!

2022-04-03 07:09 UTC, JiyoungMa commented on src/main/java/console/Output.java
> +    public void calculateOutput(String string){
이것도 Calculator class를 만들어서 output은 output만 하도록 일을 더 세분화 해서 개선하겠습니다.

2022-04-03 07:09 UTC, JiyoungMa commented on src/main/java/console/Input.java
> +        switch (menu) {
SRP에 대한 추가 공부를 진행하고 개선하겠습니다~!

2022-04-03 07:13 UTC, JiyoungMa commented on src/main/java/console/Output.java
> +        StringManipulator stringManipulator = new StringManipulator(string);
ArithmeticOperations 생성자가 StringManipulator 객체를 파라미터로 받도록 만들어서 그렇게 했는데, 지금 보니, 그냥 ArithmeticOperations 생성자가 String을 받아서 그 안에서 StringManipulator 객체를 생성하는 것이 좋을 것 같습니다!

2022-04-03 07:14 UTC, JiyoungMa commented on src/main/java/console/StringManipulator.java
> +        operatorStack = new Stack<>();
Stack과 관련된 일들을 initOperatorStack에서 해야한다고 생각해서 그렇게 했습니다!

2022-04-03 07:15 UTC, JiyoungMa commented on src/main/java/console/StringManipulator.java
> +        numberStack = new Stack<>();
이것도 numberStack과 관련된 일들을 initNumberStack에서 해야한다고 생각했습니다.

2022-04-03 07:16 UTC, JiyoungMa commented on src/main/java/console/StringManipulator.java
> +            if (nowChar == '+' || nowChar == '-' || nowChar =='*' || nowChar == '/'){
이 부분은 OperatorArray를 만들어서 그 안에 있는지를 확인하는 방식으로 개선하겠습니다~!

2022-04-03 07:17 UTC, JiyoungMa commented on src/main/java/arithmetic/Operator.java
> +    private char operator;
이번에 이 부분을 구현하면서 상속, 인터페이스, 추상클래스가 언제 필요한지에 대한 공부가 덜 되어있는 것 같아서 추가 공부를 하려고 합니다!

2022-08-16 15:21 UTC, merged