[3기-박현서] 1~2주차 과제 : 계산기 구현 미션 제출합니다
prgrms-be-devcourse/java-calculator pull request #82
Opened 2022-10-24 07:50 UTC by hyena0608

안녕하세요 ~ 😊

자바 계산기 구현 미션 제출하겠습니다 ! 🙏 

감사합니다.

## 📌 과제 설명 

사칙연산 (+, -, *, /) 이 가능한 계산기를 구현하였습니다.

### 연산

계산기에 연산식을 입력하면
기본 연산식으로 파싱하여 기본 연산식 포맷을 맞춥니다.
연산식을 후위 표기법으로 파싱하여
후위 표기식이 된 연산식을 계산합니다.

### 계산 이력 저장, 조회

계산기를 사용하면 자동으로 저장됩니다.
메뉴 기능으로 계산 이력을 전체 출력할 수 있습니다.

## 👩‍💻 요구 사항과 구현 내용 

최신순으로 정렬되어 있습니다.

### 사칙연산, 연산자 우선순위 (+, -, *, /)

> 우선 순위를 비교할 수 있고, 두 피연산자에 대해서 사칙연산을 수행할 수 있습니다.

refactor : 연산자 연산 기능 분리, 우선순위 비교 기능 분리
refactor : 연산자 확인 기능 분리
feat : +, -, *, / 사칙 연산 기능 추가
feat : 연산자 중요도 기능 추가

### 메뉴 선택 및 실행 기능

> 연산, 조회 2가지 기능이 있습니다.

feat : 계산기 메뉴 실행 기능 추가
feat : 메뉴 종류 출력 기능, 메뉴 선택 출력 기능 추가
feat : 사용자 메뉴 입력 후 해당 메뉴 실행 기능 추가
feat : 메뉴 연산 실행 기능 추가

### 후위 표기식 파싱, 연산

> 후위 표기식으로 파싱, 파싱한 표기식으로 연산하는 기능입니다.

fix : 후위 표기식 연산 예외처리 수정
fix : 후위 표기식 파싱 기능 중 남은 피연산자 처리 수정
refactor : 후위 표기법 파싱 메서드 리팩터링
feat : 후위 표기법 계산기 기능 추가
feat : 후위표기법 연산 기능 추가
feat : 후위 표기식 변환 기능 추가

### 기본 연산식 파싱

> 입력 받은 연산식을 인식할 수 있는 포맷으로 파싱하는 기능입니다.
> 예시 )   
>     입력 : 1 9 + 2 1 - 1
>     파싱 : 19+21-1

refactor : 기본 연산식 파싱 내 정규표현식 매치 메서드 분리
feat : 기본 연산식 파싱 중 예외처리 기능 추가
feat : 연산식 소수점 판별 정규표현식 기능 추가
fix : 기본 연산식 파싱 숫자 자릿수 오류 수정
refactor : 기본 연산식 파싱 메서드 리팩터링
fix : 연산식 파싱 결과 중복 오류, 인덱스 범위 수정
feat : 연산식 파싱 기능 추가

### 연산 이력 저장소 저장, 조회

> 연산 이력을 저장하고 조회할 수 있습니다.
> 실수형 부동 소수점 오차를 BigDecimal을 사용하여 해결했습니다.
> 지수 e로 표기되지 않게 제한했습니다.

fix : 정수형 지수로 표현 가능시 표현되는 오류 수정
fix : 연산 지수 e 없이 저장하도록 수정
fix : 실수 표현 방법 변경
fix : 이력 저장소 의존 변경
fix : 실수 부동수소점 오차 이슈 해결
fix : 부정확한 실수. 결과값 소수점 15자리 반올림 설정 변경
fix : 정확한 실수 표현을 위한 BigDecimal로 타입 변경
refactor : 연산 저장소 구현체 리팩터링
feat : 연산 결과 저장소 출력 기능 추가
feat : 연산 결과 저장 기능 추가

## ✅ PR 포인트 & 궁금한 점 

### `history`

저장소를 interface를 구현하는 방식으로 사용하고 있습니다.

기본적인 `저장`, `조회` 기능을 넣었습니다.

현재 연산 이력 저장소가 아닌 다른 저장소가 있다고 한다면 

조회 리턴 값, 저장 인자 타입이 다를 수 있다고 생각하여 history 인터페이스를 다음과 같이 작성했습니다.

```java
public interface History {
    void save(String... history);
    Collection<?> findAllHistories();
}
```

- `장점`으로는 

유연하게 저장이 가능하고, 

컬렉션 타입을 반환하는 저장소를 여러 타입으로 구현할 수 있습니다.

- `단점`으로는 

저장하기 위해서 인덱스를 하나하나 상수화하여 해당 저장소에 넣어놔야 할테고

조회할 때 타입을 변환시켜 비용이 드는 부분입니다.

<br>

비용이 많이 들기도하고 이후에 다양하게 저장해야할 때 번거로운 부분이 있을거 같은데

이런 방식에 대해서는 어떻게 생각하시는지 궁금합니다.

2022-10-25 12:33 UTC, ksy90101 commented on .gitignore
> +.idea/**/workspace.xml
.idea 폴더 자체를 없애보세요.
굳이 올릴 필요가 없어보여요.

2022-10-25 12:33 UTC, ksy90101 commented on build.gradle
> +    id 'java'
java 버전을 명시해보세요.

2022-10-26 02:45 UTC, hyena0608 commented on build.gradle
> +    id 'java'
build.gradle에 자바 명시 하려고 하는데 생각해보니
항상 자동으로 작성된 기억이라 어떤 식으로 적어야 되나 찾아 봤습니다.

sourceCompatibility으로 자바 버전을 명시할 수도 있는데

toolchain이라는 것을 이용해서 자바 버전을 무조건적으로(?) 맞추게 하는 방법도 있어서 사용해봤습니다.
따로 java 버전 때문에 호환이 안되는 상황에 대비해서 toolchain을 사용하고 다른 많은 설정도 있는 거로 이해했고
gradle에 대해서 조금만 봤는데 많이 어렵더라구요 ☺️

[Gradle docs](https://docs.gradle.org/current/userguide/building_java_projects.html#sec:java_cross_compilation)
[Toolchains](https://docs.gradle.org/current/userguide/toolchains.html)

2022-10-26 02:46 UTC, hyena0608 commented on .gitignore
> +.idea/**/workspace.xml
넵 .idea 폴더 자체를 없앴습니다 ! 😄

2022-10-26 15:03 UTC, samkimuel requested changes
현서님 고생하셨습니다~!
몇 가지 코멘트 달았는데 확인해주세요!

2022-10-26 15:03 UTC, samkimuel commented on src/test/java/calculator/calculator/notation/parser/NotationPostfixParserTest.java
> +        Assertions.assertThat(result).isEqualTo(expect);
다른 테스트 클래스와 동일하게 `Assertions`까지 import하시죠!

2022-10-26 15:41 UTC, ksy90101 approved these changes
안녕하세요. 현서님 이번 미션 고생하셨습니다.

전반적인 피드백을 드릴게 하나 있습니다.

전체적으로 코드가 복잡합니다. 분리를 열심히 하시고 많이 고민하신건 느껴지지만, 제가 이 미션을 생각했을때 이정도의 복잡한 코드가 나오지 않아도 충분히 확장가능하고 객체지향적으로 작성이 가능하다고 생각합니다. 

코드가 많은게 좋은걸까요? 저는 아니라고 생각합니다. 무조건적인 분리도 좋지 않구요. 
전체적으로 사용은 하지만, 사실 의미없는 코드들(제가 생각했을때 동일한 행동을 하는 것들이 많이 있을듯 해요.)이 있을듯 해요. 이런 부분들을 다시 한번 제거해나가면 어떨까요?
현재 FileChanged가 54개인데, 45개 정도로 줄여보는걸 추천드려봅니다.

2022-10-26 15:41 UTC, ksy90101 commented on src/test/java/calculator/calculator/history/CalculationHistoryTest.java
> +        );
결국 동일한 친구 같은데, 하나로 합쳐서 중복코드를 없앨수 있지 않을까요?

2022-10-26 15:41 UTC, ksy90101 commented on src/test/java/calculator/calculator/notation/calculation/NotationPostfixCalculationTest.java
> +    }
여기도 중복된 케이스가 보이는듯 한데요?

2022-10-26 15:41 UTC, ksy90101 commented on src/main/java/calculator/calculator/operator/OperatorCalculation.java
> +    private final BiFunction<BigDecimal, BigDecimal, BigDecimal> calculation;
BinaryOperator<BigDecianl>이라는 함수형 인터페이스도 사용 가능합니다.

2022-10-26 15:41 UTC, ksy90101 commented on src/main/java/calculator/view/util/regex/RegexInputUtil.java
> +public class RegexInputUtil {
정적 메서드만 지원하는 클래스는 생성자를 생성하지 못하도록 막는게 좋을듯 해요.

https://github.com/Meet-Coder-Study/book-effective-java/blob/main/2%EC%9E%A5/4_%EC%9D%B8%EC%8A%A4%ED%84%B4%EC%8A%A4%ED%99%94%EB%A5%BC_%EB%A7%89%EC%9C%BC%EB%A0%A4%EA%B1%B0%EB%93%A0_private_%EC%83%9D%EC%84%B1%EC%9E%90%EB%A5%BC_%EC%82%AC%EC%9A%A9%ED%95%98%EB%9D%BC_%EC%9D%B4%ED%98%B8%EB%B9%88.md

2022-10-26 15:41 UTC, ksy90101 commented on src/main/java/calculator/view/util/regex/RegexInputUtil.java
> +    public static final Pattern REGEX_MENU_INPUT = Pattern.compile("^[0-9]+$");
외부에서 사용하지 않는다면 private으로 해주세요.

2022-10-26 15:41 UTC, ksy90101 commented on src/main/java/calculator/calculator/PostfixCalculator.java
> +    }
생성자에서 이렇게 주입한다면, 나중에 확장 용이성이 떨어질듯 해요.
인자로 받아서 처리한다면 차후에 갈아끼우기가 좋을듯 하네요.

2022-10-26 15:41 UTC, ksy90101 commented on src/main/java/calculator/calculator/formula/FormulaBasicParser.java
> +        if (operator.length() == 0) {
isEmpty() vs isBlank()를 알아보시고 해당 메서드를 사용해보면 어떠신가요?

2022-10-26 15:41 UTC, ksy90101 commented on src/main/java/calculator/calculator/history/CalculationHistory.java
> +        return answer.contains(".");
매직스트링!

2022-10-26 15:41 UTC, ksy90101 commented on src/main/java/calculator/calculator/history/CalculationHistory.java
> +    private static final HashMap<String, String> histories = new HashMap<>();
결과식 자체를 객체라고 생각해 Value가 객체면 좋을듯 해요.
key엔 식, value엔 답인듯 한데 이런 형태가 아닌 key엔 유니크한 값(한번 고민해보세요.) value에는 저장해야 할 객체로요.

2022-10-26 15:41 UTC, ksy90101 commented on src/main/java/calculator/calculator/operator/OperatorPriority.java
> +public enum OperatorPriority {
우선순위, 연산자, 연산 행동
자체가 3개로 분리되어 있네요.
분리는 좋지만 이 세개가 하나로 합쳐져야 실제 우리가 생각하는 객체가 나오지 않을까요?
이 3개를 하나의 객체로 관리하는게 더 용이해 보입니다.

2022-10-26 15:41 UTC, ksy90101 commented on src/main/java/calculator/menu/Menus.java
> +    private final Long id;
굳이 Long인 이유가 있나요?
메모리를 아무리 신경쓰지 않아도 된다고 하지만, 성능적으론 지금은 Int로도 충분할듯 한데요.

2022-10-26 22:50 UTC, hyena0608 commented on src/main/java/calculator/menu/Menus.java
> +        menuOutput().printAfter();
호출할 때 마다 객체가 생성되는 상태입니다.

연관 관계와 의존 관계에 대해서 생각하는데
계속해서 사용할 경우는 영구적으로 의존 시키는게 더 좋다고 생각이 들었는데
리턴해서 사용하는게 더 유연하지 않을까 ? 라는 생각도 들어 위 코드 처럼 구현 했었습니다.

역시 제 욕심인듯 해서 바로 수정해버렸습니다 ! 😊

2022-10-26 23:05 UTC, hyena0608 commented on src/test/java/calculator/calculator/history/CalculationHistoryTest.java
> +        );
```
안녕하세요. 현서님 이번 미션 고생하셨습니다.

전반적인 피드백을 드릴게 하나 있습니다.

전체적으로 코드가 복잡합니다. 분리를 열심히 하시고 많이 고민하신건 느껴지지만, 제가 이 미션을 생각했을때 이정도의 복잡한 코드가 나오지 않아도 충분히 확장가능하고 객체지향적으로 작성이 가능하다고 생각합니다.

코드가 많은게 좋은걸까요? 저는 아니라고 생각합니다. 무조건적인 분리도 좋지 않구요.
전체적으로 사용은 하지만, 사실 의미없는 코드들(제가 생각했을때 동일한 행동을 하는 것들이 많이 있을듯 해요.)이 있을듯 해요. 이런 부분들을 다시 한번 제거해나가면 어떨까요?
현재 FileChanged가 54개인데, 45개 정도로 줄여보는걸 추천드려봅니다.
```

위에 전반적인 피드백 댓글 작성이 안돼서 여기에 같이 작성하겠습니다 !

처음에 계산기 구현하면서 목표는 유연함이었습니다.
이전에도 유연하게 코드를 짜야겠다는 생각은 했었지만 실제 구현한 적은 없었기에 한 번 해보고 싶었습니다.

하지만 요즘 코드를 작성하면서 의문점이 들었던 부분들이 있었습니다.

1. 코드가 다른 백둥이들에 비해 너무 길다.
2. 가독성이 좋지않다.
3. 실제 현업이라면 이런 코드는 사용하지 않을 거 같다. -> 협업하기 싫은 코드이다. -> 쓸 때 없이 길다.

추상화 할수록 코드를 이해하기 어렵다는 말은 들었지만
지금 코드는 너무 추상화 했다는 느낌보다는 어디서 코드를 압축(?) 시키지 못했다는 느낌을 받았습니다.

하지만 확실하게 인지하지 못하고 생각이 애매한 상태에서 확실해진 느낌을 받았습니다 ! 감사합니다 😂 👍

---

<br>
<br>

테스트에 중

2022-10-27 01:12 UTC, hyena0608 commented on src/main/java/calculator/view/output/TextUnit.java
> +    public final String unit;
구현 당시 final이라 변경할 수 없어서 상관 없을 거라 생각이 들었습니다 !

매직리터럴로 단순하게 값만 가져온다 생각해서 문제 없지 않나 했는데 
자료를 더 찾아봤더니 여러 방면으로 다양하게 사용하는 것을 보게 됐습니다.

그래서 private으로 감추는게 더 좋다고 생각이 바뀌게 됐습니다 😊

2022-10-27 05:04 UTC, hyena0608 commented on src/main/java/calculator/view/input/MenuInput.java
> +        if (checkWrong(REGEX_MENU_INPUT, menuId)) {
수정했습니다

2022-10-27 05:08 UTC, hyena0608 commented on src/main/java/calculator/view/input/BaseInput.java
> +        return inputValue;
수정했습니다.

예외가 나지 않았을 때 리턴한다는 생각에 내부에서 return 할 생각을 못했습니다

2022-10-27 05:16 UTC, hyena0608 commented on src/main/java/calculator/view/output/MenuHistoryOutput.java
> +        HashMap<String, String> newHistories = new HashMap<>();
수정했습니다. 👍

Map의 구현체인 HashMap이 아닌 Map으로 선언했습니다 !

2022-10-27 05:42 UTC, hyena0608 commented on src/main/java/calculator/calculator/operator/Operators.java
> +    }
수정했습니다 ! 👍

BigDecimal을 사용하다가 혼동했습니다.

후위 표시식을 순서대로 계산하기 위해 
두 피연산자와 한 연산자를 연산하고
다시 Deque에 결과값을 넣고 반복하는데 

실수 오차를 알기 전에 `Double`을 사용하다가
BigDecimal을 사용할 때 String으로 넘어와야 하니 `String`으로 타입 수정 후에 `BigDecimal`로 최종 수정했는데 

이러한 수정하는 부분에서 혼동하여 
피연산자 문자열을 BigDecimal로 파싱하는 식으로 작성하게 됐습니다.

2022-10-27 07:56 UTC, hyena0608 commented on src/test/java/calculator/calculator/PostfixCalculatorTest.java
> +        String result = calculator.calculate(formula).toString();
수정했습니다.

BigDecimal 객체를 생성할 때 String이외로 double로도 생성할 수 있었고
때문에 BigDecimal 이라는 값을 사용하기 위해서는 
직접 필요한 타입으로 파싱 후에 사용해야 된다고 생각했습니다.

```java
BigDecimal a = new BigDecimal(0.01);
BigDecimal b = BigDecimal.valueOf(0.01);
```
의 값이 다르기 때문에 
BigDecimal을 직접사용하면 값이 달라질수도 있지 않을까 의문이 들었고
나올 때의 타입이 달라지면 값이 또 달라지지 않는가? 라는 생각이었습니다.

```java
String stringExample = "0.01";
double doubleExample = 0.01D;

BigDecimal doubleBigDecimal = new BigDecimal(doubleExample);
BigDecimal stringBigDecimal = new BigDecimal(stringExample);

System.out.println("doubleBigDecimal = " + doubleBigDecimal);
System.out.println("stringBigDecimal = " + stringBigDecimal);

System.out.println("doubleBigDecimal.doubleValue() = " + doubleBigDecimal.doubleValue());
System.out.println("stringBigDecimal.doubleValue() = " + stringBigDecimal.doubleValue());

System.out.println(doubleBigDecimal.compareTo(stringBigDecimal));
System.out.println(Double.compare(doubleBigDecimal.doubleValue(), stringBigDecimal.doubleValue()));
```
```
// 출력

doubleBigDecimal = 0.01000000000000000020816681711721685132943093776702880859375
stringBigDecimal = 0.01
doubleBigDecimal.doubleValue() = 0.01
stringBigDecimal.doubleValue() = 0.01
1
0
```

확인 했을 때 생성했을 때의 타입과 동일하게 출력된다는 것을 알 수 있었습니다.

2022-10-27 08:18 UTC, hyena0608 commented on src/test/java/calculator/calculator/history/CalculationHistoryTest.java
> +        assertThat(savedSize).isEqualTo(expectSize);
<img width="739" alt="image" src="https://user-images.githubusercontent.com/82203978/198229395-2e926506-82d9-43cc-82e1-72098f58f49b.png">
(🥲 위에 메서드를 못찾았습니다.)

<br>

Junit5에 assertEqauls(savedSize, expectSize) 를 
AssertJ에서 assertThat(savedSize).hasSize(expectSize) 로 표현하여
한 눈에 봐도 사이즈를 비교하고 있구나 라고 더 빠르게 알 수 있다고 느껴집니다 !

2022-10-27 08:50 UTC, hyena0608 commented on src/test/java/calculator/calculator/history/CalculationHistoryTest.java
> +                .collect(Collectors.toUnmodifiableList());
저장소 부분을 아예 새로 만들어야 한다고 느꼈습니다. 🙆‍♂️
오히려 복잡하기만한 저장소 였습니다.

 History의 구현체인 CalculationHistory를 보면
저장소 필드가 따로 선언되어 있고 
save 메서드와 findAllHistories 메서드를 오버라이딩하는데

오히려 그에 필요한 작업들이 너무 증가하고 점점 복잡해질거 같습니다.
(저장 형식 구현, 조회 형변환 구현, 저장소 구현  이 반복됩니다)

현재  CalculationHistory 코드가 아래와 같습니다.
 ```java
public interface History {
    void save(String... history);
    Collection<?> findAllHistories();
}
```
```java
public class CalculationHistory implements History {

    private static final HashMap<String, String> histories = new HashMap<>();
    private static final int HISTORY_FORMULA_INDEX = 0;
    private static final int HISTORY_ANSWER_INDEX = 1;

    @Override
    public void save(String... history) {
        ...
    }

    @Override
    public Collection<?> findAllHistories() {
        ...
    }
}
```

### 저장
저장하기 위해서는 
인자로 받아올 문자열 배열에 대한 인덱스 선언,
받을 인자도 순서대로 받아야만 합니다.

### 조회
이력들을 모두 불러와 사용하기 위해서는 
해당하는 타입으로 변환해야 하고

### 테스트
저장 이력 테스트하기 위해서는 
테스트 내부에서 형변환을 하거나
따로 해당 저장소 전용 형변환 클래스를 작성해야 합니다.

유연함을 생각하다 억지로 끼워 맞춰버렸고
지금 코드는 필요 요소가 너무 많다고 느꼈습니다.

마르코 멘토가 저장소 관련한 피드백과 같이 수정하겠습니다 😊

2022-10-27 16:39 UTC, hyena0608 commented on src/test/java/calculator/calculator/notation/calculation/NotationPostfixCalculationTest.java
> +    }
마르코님 😊 확인했는데 궁금한점이 있습니다 !

1. 하나의 테스트에 하나의 데이터를 줄 필요가 없는건지 궁금합니다 !
2. 아니면 두 테스트 중 하나의 테스트만 있으면 되는건지 궁금합니다 !

아래 두 테스트 각각 "연산 결과 저장" 기능을 수행하고 있어
테스트를 합치는게 맞는 건지 고민 됩니다.

```java
...
@DisplayName("연산 결과 저장 성공 테스트")
void whenSaveHistoryThenSuccessTest(List<String> formula, List<String> answer) {
    int expectSize = saveHistories(formula, answer); // 연산 결과 저장
    int savedSize = history.findAllHistories().size();

    assertThat(savedSize).isEqualTo(expectSize);
}

...
@DisplayName("연산 결과 조회 성공 테스트")
void whenFindHistoryThenSuccessTest(List<String> formula, List<String> answer) {
    saveHistories(formula, answer); // 연산 결과 저장

    List<String> findAnswersByFindHistories = history.findAllHistories()
            .stream()
            .map(findHistory -> (Map.Entry<String, String>) findHistory)
            .map(Map.Entry::getValue)
            .collect(Collectors.toUnmodifiableList());

    assertThatList(findAnswersByFindHistories).containsAll(answer);
}
```

2022-10-28 01:59 UTC, hyena0608 commented on src/test/java/calculator/calculator/notation/calculation/NotationPostfixCalculationTest.java
> +    }
확인했습니다 ! 😊

whenCalculatePostfixNotationThenSuccessDummy 메서드는 "정상적인 후위 표기법"

whenCalculatePostfixNotationThenExceptionDummy 메서드는 "잘못된 후위 표기법" 으로 나눠서 작성했습니다 !

생각해봤을 떄
정상적인 표기법에서 마지막 값을 제거 하면 
똑같이 "잘못된 후위 표기법"으로 만들어지기도 하는데
테스트 데이터를 작성할 때 확실하게 나눠 놓는게 나을까요 ?

2022-10-28 02:34 UTC, hyena0608 commented on src/main/java/calculator/calculator/operator/OperatorCalculation.java
> +    private final BiFunction<BigDecimal, BigDecimal, BigDecimal> calculation;
수정했습니다 !

BinaryFunction과 비슷한 BinaryOperator를 알게 되었고
인자가 다 같은 타입일 경우에 BinaryOperator를 이용하니 훨씬 보기 편해졌습니다 ! 👍

2022-10-28 02:36 UTC, hyena0608 commented on src/main/java/calculator/view/util/regex/RegexInputUtil.java
> +    public static final Pattern REGEX_MENU_INPUT = Pattern.compile("^[0-9]+$");
수정했습니다 !

2022-10-28 02:38 UTC, hyena0608 commented on src/main/java/calculator/view/util/regex/RegexInputUtil.java
> +public class RegexInputUtil {
수정했습니다 !

2022-10-28 02:58 UTC, hyena0608 commented on src/main/java/calculator/calculator/formula/FormulaBasicParser.java
> +        if (operator.length() == 0) {
수정했습니다 👍

isEmpty() : Java6, 문자열의 길이가 0일 경우 true
isBlank() : Java11,  문자열이 비어있거나, 빈 공백으로만 이루어져 있는 경우 true

이런 좋은 메서드가 있었는데 제가 전혀 생각도 안하고 있었네요 🧎🥲
감사합니다 ㅎㅎ

2022-10-28 04:33 UTC, hyena0608 commented on src/main/java/calculator/calculator/PostfixCalculator.java
> +    }
MenuCalculator에 Calculator calculator = new PostfixCalculator();
이런 식으로 구현되어 있었고 PosfixCalculator 가 아닌 PrefixCalculator로 곧장 바꿔 사용할 수 있게하려고
일부러 생성자에서 주입했었습니다.

하지만 사용하지 않는 클래스가 있다는 거는  필요없는거라 생각해서
PostfixCalcultor를 지우고 추상 클래스였던 Calculator를 클래스로 변경했습니다.


```java
public class Calculator {

    private final NotationCalculation calculation;
    private final NotationParser notationParser;
    private final FormulaParser formulaParser;

    public Calculator(NotationCalculation calculation, 
                      NotationParser notationParser, 
                      FormulaParser formulaParser) {
        this.calculation = calculation;
        this.notationParser = notationParser;
        this.formulaParser = formulaParser;
    }

    public BigDecimal calculate(String formula) {
        return calculation.calculate(
                        notationParser.parseFrom(
                                formulaParser.parseFrom(formula)));
    }
}
```
```java
public class MenuCalculator implements Menu {

    private final MenuCalculatorInput input;
    private final MenuCalculatorOutput output;
    private final History history;
    public final Calculator calculator;

    public MenuCalculator() {
        input = new MenuCalculatorInput();
        output = new MenuCalculatorOutput();
        history = new CalculationHistory();
        calculator = new Calculator(
                new NotationPostfixCalculation(),
                new NotationPostfixParser(),
                new FormulaBasicParser()
        );
    }
}
```

Caclulator를 생성하기 위해 여러 인자를 필요로하는데
너무 많은게 아닌가 싶은 느낌이 드는데
이런식으로 해도 상관 없는건지 잘 모르겠습니다

2022-10-30 00:01 UTC, ksy90101 commented on src/test/java/calculator/calculator/history/CalculationHistoryTest.java
> +        );
현재 본다면 결국 조회라긴 보단 저장에 가까운듯 해요.
결국 행동은 메서드를 통해 결정되는데요.
결국 두개는 동일한 동작을 하는거 같은데요?

2022-10-30 00:02 UTC, ksy90101 commented on src/test/java/calculator/calculator/notation/calculation/NotationPostfixCalculationTest.java
> +    }
말씀하신대로 각 테스트에 대한 데이터라면 나눠놓는게 좋을듯 해요 ㅎㅎ
이런 경우엔 아니면 Common에 대한것을 만들고
그걸 각 테스트 데이터에서 같이 사용하게 만들수도 있을듯 하네요.
그러면 중복이 만힝 사라질듯 해요.

2022-11-03 13:42 UTC, hyena0608 commented on src/main/java/calculator/calculator/history/History.java
> +    void save(String... history);
```java
String formula = "1 + 1";
String operator = "+"; // 연산자가 필요할 경우 (?)
String calculationResult = "2";
```

```java
private static final int FORMULA_INDEX = 0;
private static final int CALCULATION_RESULT_INDEX = 1;

String formula = history[FORMULA_INDEX];
String calculationResult = history[CALCULATION_RESULT_INDEX];
```
<<결론 : 다른 형식으로 수정했습니다 !>>


<<느낀점>>
이런 식으로 순서에 맞춰서 원하는 값들을 저장하고 싶었습니다.
"처음에 구현하고나서도 가변인자를 사용한다고 해도 그렇게 까지 해야될 요소가 있나 ?" 라는 생각이 계속 들었고
정확하게 답은 나오지 않고 억지로 끼워 맞춰서 대답하게 되더라구요 😱

실제로 저런 방식이 필요한 경우도 정말 있을 수도 있다라고 생각은 들지만
현재 연산식, 연산결과를 저장하는 곳에는 필요없는 방식이고
단지 유연하게 해야된다라는 생각만 고집한 결과였습니다.

유연하게 코드를 작성하는 것은 좋지만
현재 구현하는데 있어서 무엇이 더 중요한지 판단하고
만약 새로운 방식을 적용한다면 좀 더 확실한 근거를 가지고 적용하겠습니다 ! 😊

2022-11-03 13:44 UTC, hyena0608 commented on src/main/java/calculator/calculator/history/History.java
> +    Collection<?> findAllHistories();
수정했습니다 !

저도 작성하면서 이게 맞나.. 라고 생각만 했고
대부분의 코멘트와 같이 유연하게 만들고 싶다라는 
생각을 고집하고 확실한 근거를 찾지 못한게 원인이라 판단하여
현재 요구사항에 더 적합한 설계가 뭔지 생각하며 수정했습니다 !

2022-11-03 13:45 UTC, hyena0608 commented on src/main/java/calculator/calculator/history/CalculationHistory.java
> +        return answer.contains(".");
수정했습니다 !

2022-11-03 13:50 UTC, hyena0608 commented on src/main/java/calculator/menu/Menus.java
> +    private final Long id;
수정했습니다 !

말씀해주신 것처럼
현재 메모리를 더 사용한다고 해도 현재 애플리케이션에서는 별다른 상관 없다고 생각해서 long 타입을 사용했습니다.

좀 더 생각해보면 메뉴가 약 21억 이상이 될 일은 전혀 없다고 판단되어 int 타입으로 수정했습니다. 👍

2022-11-04 14:37 UTC, samkimuel commented on src/main/java/calculator/calculator/history/History.java
> +    void save(String... history);
이펙티브 자바에서도 가변인수에 대해 말해주고 있는데, 한 번 읽어보시면 좋을 것 같아요~

https://github.com/Meet-Coder-Study/book-effective-java/blob/main/8%EC%9E%A5/53_%EA%B0%80%EB%B3%80%EC%9D%B8%EC%88%98%EB%8A%94_%EC%8B%A0%EC%A4%91%ED%9E%88_%EC%82%AC%EC%9A%A9%ED%95%98%EB%9D%BC_%EA%B9%80%EC%84%B8%EC%9C%A4.md

2022-11-04 15:06 UTC, samkimuel commented on src/main/java/calculator/calculator/operator/Operators.java
> +    }
한 곳만 수정하는 게 아니라 여러 곳을 수정하게 되면서 놓치는 경우가 있죠😢

2022-11-04 16:48 UTC, hyena0608 commented on src/main/java/calculator/calculator/history/History.java
> +    void save(String... history);
감사합니다 ㅎㅎ 😊

이펙티브 자바에 제가 고민하던 부분에 대한 글이 생각보다 많이 있는거 같네요 !
어려울거 같아 덤비지 못했었지만 이펙티브 자바에서도 필요한 부분만 읽는 시도를 해봐야겠습니다 👍

2022-11-04 17:46 UTC, samkimuel approved these changes
현서님 고생하셨습니다👍
느낀점까지 남겨주셨네요. 최곱니당👍
다음 과제들도 파이팅하세요!

2022-11-05 03:50 UTC, hyena0608 commented on src/main/java/calculator/calculator/history/History.java
> +    Map<Formula, CalculationResult> findAllHistories();
수정했습니다 !

일단.. 제가 예외처리를 하지 않았군요..! 😌

<<현재 커멘트 해주시기 전>>

`Formula` : 일급 객체
`FormulaBasicParser` : Formula 를 갖고 있는 파싱 클래스

```java
public class Formula {

    private final List<String> formula;

    public Formula(List<String> formula) {
        this.formula = formula;
    }
...
```
```java
public class FormulaBasicParser implements FormulaParser {

    private Formula formula;

    public FormulaBasicParser() {
    }

    private void initFormulaParser() {
        this.formula = new Formula(new ArrayList<>()); // FormulaBasicParser는 재생성하지 않고 사용합니다.
    }
...
```

기존에 연산식이 FormulaBasicParser에 final로 선언되어 `formula.clear()` 
이런 식으로 사용해서 똑같은 객체라 저장에 문제가 생겼습니다.

때문에 FormulaBasicParser에서 Formula에 final 을 붙이지 않고 항상 새롭게 생성하게 했습니다.

그래서 "해결됐다 ~" 하고 끝냈나 봅니다 !

<<중복된 연산 예외처리 기능 추가>>

이미 저장된 키값일 경우 예외처리 했습니다.

```java
    @Override
    public void save(CalculationHistoryForm calculationHistoryForm) {
        Formula formula = calculationHistoryForm.getFormula();
        CalculationResult calculationResult = calculationHistoryForm.getCalculationResult();

        if (checkFormulaOverlap(formula)) {
            throw new IllegalArgumentException(HISTORY_SAVE_OVERLAP_EXCEPTION.getMessage());
        }

        if (checkSaveFormWrong(formula, calculationResult)) {
            throw new NumberFormatException(HISTORY_SAVE_EXCEPTION.getMessage());
        }

        saveEachCase(formula, calculationResult);
    }
```

2022-11-05 03:58 UTC, merged

2022-11-05 04:11 UTC, samkimuel commented
요구사항에 따라 구현은 달라질 것 같네요.
현서님이 생각하신 동일한 연산식을 입력할 때 예외가 발생하는 계산기일 수도 있고,
동일한 연산식을 입력하더라도 중복 저장 가능하도록 하는 계산기를 구현하실 수도 있을 것 같네요. (입력 순서도 고려하는 것도?)

구현하기전에 요구사항을 잘 작성해놓는다면 구현하면서 방향을 잃어버리지 않으실 거에요. (문서화 하기!🙃)

2022-11-05 06:17 UTC, hyena0608 commented
### <<중복 연산식 저장>>
처음에 동일한 연산식일 경우는 중복해서 저장하지 않는 방식으로 구현 했었습니다.

하지만 동일한 연산식이여도 중복해서 저장하는 이유는 
"연산 이력"이라는 말을 
"계산기로 연산한 모든 이력"이라고 생각을 바꿨기 때문입니다.

### <<입력 순서>>
근데 명환님 말씀처럼 입력 순서를 고려하기 위해 시간 필드도 추가하려 했는데
그러면 정렬도 해주면서 출력해줘야 하니 일이 점점 커질거 같아서 구현하진 않았습니다 ! 😂

만약 시간 필드를 넣는다면 
일급 객체인 `Formula`, `CalculationResult`에 넣지 않고 
기존에 두 객체를 넘겨주기 위해 만든 클래스(`CalculationHistoryForm`)를 사용할 거 같습니다.

```java
// 기존
Map<Formula, CalculationResult> storage = new HashMap<>();

// 변경
Map<Long, CalculationHistoryForm> storage = new HashMap<>();

public class CalculationHistoryForm {

    private final Formula formula;
    private final CalculationResult calculationResult;
    private final LocalDateTime createdTime;

    public CalculationHistoryForm(Formula formula, CalculationResult calculationResult) {
        this.formula = formula;
        this.calculationResult = calculationResult;
        this.createdTime = LocalDateTime.now();
    }
...
```

하지만 key-value이 (Formula-CalculationResult)가
연산식에 대한 연산값으로 저장되니 더 쉽게 읽힐거 같습니다.
연산식만 필요할 때, 
연산값만 필요할 때
가 있을 수도 있어 이런 부분도 결국 "트레이드오프"인가 생각 듭니다 (?)

### <<요구사항>>

문제 분석에 더 시간을 투자해야함을 느꼈습니다. 👍

처음에 기능 요구사항을 적고 그림을 그리고 시작 했었습니다. (UML,  기능 list-up)

물론 요구사항이 계속 바뀔거란 예상은 했었지만
- 워크플로우를 그리면서 추상적인 요구사항에 대해서 확실하게 정하고 진행해보겠습니다.

(+ 그렇다고해서 너무 문제 이해에만 시간을 투자하진 않으려고 합니다. 항상 시간 배분 연습을..🔥🥲🙆‍♂️)