[마르코팀]김기웅- 계산기 미션 첫 pr
prgrms-be-devcourse/java-calculator pull request #83
Opened 2022-10-24 10:23 UTC by kivv00ng

## 📌 과제 설명 
  문자열 계산기를 구현하여 보았습니다!

## 👩‍💻 요구 사항과 구현 내용 
 -기능구현: 기능 구현을 하였습니다.
 -상수정의 및 테스트 코드 작성: 상수를  따로 정의하여 주고, 테스트 코드로 작동을 확인해 보았습니다.

## ✅ PR 포인트 & 궁금한 점 
1.강의에서는 비슷한 미션을 input과 output 모두 interface로 작성한 뒤, 각 구현체들이 직접적으로 의존하지 않도록 해주었는데,그렇게 하는게 맞았을까요? 만약 맞다면, 도메인 로직이 아닌 view까지도 그렇게 해야할까요?ㅜㅜ

2022-10-25 10:44 UTC, ksy90101 commented
@kivv00ng gitignore를 잘 해보시겠어요?
현재 쓸모없는 파일들이 모두 올라가있네요.

2022-10-25 12:28 UTC, ksy90101 commented on .gitignore
> +.idea
아직 .idea 폴더가 남아있네요.
```
git rm -r -f --cached -- .
```
이걸 해보세요.

2022-10-25 12:30 UTC, ksy90101 commented on build.gradle
> +    id 'java'
java 버전을 명시해보세요.

2022-10-25 12:31 UTC, ksy90101 commented on src/main/java/com/programmers/controller/StringCalculator.java
> +        }
복잡성이 굉장히 높네요.
method를 이용해 한번 분리해보면 어떨까요?
중복코드가 보이기도 하구요.

2022-10-25 12:31 UTC, ksy90101 commented on src/main/java/com/programmers/controller/StringCalculator.java
> +        int sign2_Index = inputString.indexOf(sign2);
자바는 카멜케이스를 사용하고 있습니다.

2022-10-25 12:31 UTC, ksy90101 commented on src/main/java/com/programmers/domain/CalculatorType.java
> +        throw new IllegalArgumentException("제대로된 사칙연산기호를 입력해 주세요. 입력 값: " + sign);
굳이 swtch문으로 할 필요가 없어보이는데요.
stream으로 한번 변경해보실래요?

2022-10-25 12:31 UTC, ksy90101 commented on src/main/java/com/programmers/domain/CalculatorType.java
> +    public static final int ZERO_NUMBER = 0;
private으로도 충분할듯 하네요.

2022-10-25 12:32 UTC, ksy90101 approved these changes
간단한 피드백을 남겼는데, 수정해보세요 💯

2022-10-25 12:54 UTC, kivv00ng commented on src/main/java/com/programmers/domain/CalculatorType.java
> +        throw new IllegalArgumentException("제대로된 사칙연산기호를 입력해 주세요. 입력 값: " + sign);
네!

2022-10-25 15:40 UTC, kivv00ng commented on src/test/java/com/programmers/domain/CalculatorTypeTest.java
> +    }
네! 방금 공부해서 적용해보았습니다.ㅎㅎ

2022-10-25 16:18 UTC, kivv00ng commented on src/main/java/com/programmers/controller/StringCalculator.java
> +        }
네!

2022-10-26 15:43 UTC, ksy90101 commented on build.gradle
> +    testImplementation 'org.mockito:mockito-core:3.11.2'
mockito를 실제 쓰는지 잘 고민해보세요.

2022-10-26 15:44 UTC, ksy90101 commented on src/main/java/com/programmers/domain/CalculatorType.java
> +    private static int ZERO_NUMBER = 0;
```suggestion
    private static final int ZERO_NUMBER = 0;
```

static이 붙으면 전체 스레드에 공유를 하겠죠.
변경하지 않도록 final을 붙이는것이 중요합니다.

2022-10-26 15:45 UTC, ksy90101 commented on src/main/java/com/programmers/domain/CalculatorType.java
> +    private BinaryOperator<Integer> expression;
enum 필드는 fianl을 붙여야 하는데요.
그 이유를 잘 한번 생각해서 답을 적어주세요.

2022-10-26 15:48 UTC, ksy90101 commented on src/main/java/com/programmers/view/ResultView.java
> +        for (String input : results.keySet()) {
entrySet()을 알아볼까요?

2022-10-26 15:52 UTC, ksy90101 commented on src/main/java/com/programmers/controller/StringCalculator.java
> +        int result = CalculatorType.selectType(inputString.charAt(index)).calculate(numOne, numTwo);
디미터의 법칙을 위반했네요.

2022-10-26 15:54 UTC, ksy90101 commented on src/main/java/com/programmers/view/InputView.java
> +        }
이러힌 부분은 메서드로 분리하는게 더 좋습니다.

2022-10-26 16:22 UTC, samkimuel requested changes
기웅님 고생하셨어요~
간단히 코멘트 달았는데 확인해주세요~!

2022-10-27 02:02 UTC, kivv00ng commented on build.gradle
> +    testImplementation 'org.mockito:mockito-core:3.11.2'
아 private 메소드 테스트 했다가 지웠는데 gradle에서는 깜빡했네요ㅜ

2022-10-27 02:03 UTC, kivv00ng commented on src/main/java/com/programmers/domain/CalculatorType.java
> +    private static int ZERO_NUMBER = 0;
네! 감사합니다ㅎㅎ 오늘 static이랑 jvm을 공부해봐야겠네요ㅎㅎ

2022-10-27 02:04 UTC, kivv00ng commented
> 안녕하세요 기웅님. 전체적으로 고생 많으셨습니다.
> 
> 전반적인 피드백을 하나 드리면 테스트 코드를 작성하실줄 아는듯 해요. 근데 테스트 코드가 많이 부족하네요.
> 
> 테스트 코드를 어떤걸 작성해야 할지 모른다면 현재 domain이라고 넣어둔 객체들의 메서드들을 1회라도 테스트 코드를 작성해보면 어떨까요? 테스트 코드에 익숙해지기 위해서요. (충분히 가능할듯 해서 제안드리는 부분입니다.)

네! 명환님! 감사합니다!ㅎㅎ 항상감사합니다

2022-10-27 02:10 UTC, kivv00ng commented on src/main/java/com/programmers/domain/CalculatorType.java
> +    private BinaryOperator<Integer> expression;
enum 에 들어가있는  상수들은  public static final로 정의된 인스턴스이므로 각 인스턴스의 필드 역시도 private final이 되어야한다.. 맞나요? 단순히 컴파일 에러가 뜨지 않아서 저렇게 표현해봤는데, 안좋은 코드였군요!

2022-10-30 13:29 UTC, kivv00ng commented on src/main/java/com/programmers/view/ResultView.java
> +            stringBuilder.append(input + MIDDLEMAN + results.get(input) + "\n");
아 넵! os에 따라 개행문자가 달랐는지는 지금 처음 알았네요 ㅎㅎ.

2022-10-30 13:31 UTC, kivv00ng commented on src/main/java/com/programmers/controller/StringCalculator.java
> +    private final String DIVIDE = "/";
왜 상수를 static final로 지정해야하는지, static공부후에 깨달았습니다.하하

2022-10-30 16:38 UTC, kivv00ng commented on src/main/java/com/programmers/controller/StringCalculator.java
> +            return ++result;
음수값은 "-"(띄어쓰기없음)으로, 빼기 기호는 " - "(양쪽띄어쓰기있음)으로 구분하기 위해서 사용하여 주었습니다.그래서 빼기일 경우 띄어쓰기 보다 한칸 뒤쪽으로 index값을 더해준 것입니다!

2022-10-30 16:39 UTC, kivv00ng commented on src/main/java/com/programmers/controller/StringCalculator.java
> +        return Integer.parseInt(inputString);
정규표현식으로 검증해줘서 괜찮다고 판단했는데 메소드를 추가하는게 맞을까요?

2022-10-30 17:01 UTC, kivv00ng commented on src/main/java/com/programmers/view/InputView.java
> +            if (selectNum.equals("1") || selectNum.equals("2") || selectNum.equals("3")) {
네!ㅎㅎ

2022-10-30 17:02 UTC, kivv00ng commented on src/main/java/com/programmers/controller/StringCalculator.java
> +    private final String DIVIDE = "/";
네! ㅎㅎ static공부했습니다

2022-10-30 17:02 UTC, kivv00ng commented on src/main/java/com/programmers/controller/StringCalculator.java
> +    private final String SUBTRACT = " - ";
네 음수랑 구분하려고 이렇게했습니다ㅎㅎ 조금 별로인가요??

2022-10-30 17:03 UTC, kivv00ng commented on src/main/java/com/programmers/view/InputView.java
> +    }
네!ㅎㅎ

2022-11-04 12:33 UTC, samkimuel approved these changes
기웅님 피드백 반영하느라 고생하셨습니다👏
코드가 전보다 훨씬 깔끔해졌네요👍
코멘트 몇 개 달았으니 수정해보시면 좋을 것 같고, 저는 여기서 approve 하겠습니다 ㅎㅎ 고생하셨어요~

2022-11-04 12:33 UTC, samkimuel commented on src/main/java/com/programmers/domain/CalculatorType.java
> +        }
예외 던질 때 프로그램이 종료되나요? 아니면 작업을 이어나가나요?

2022-11-04 12:33 UTC, samkimuel commented on src/main/java/com/programmers/view/MenuType.java
> +                .anyMatch(selectNumber -> selectNumber.equals(number))) {
저는 if문의 조건식이 너무 길어지면 변수로 선언 후에 넣어주거나, 메서드로 분리하는 편이에요.

2022-11-04 12:33 UTC, samkimuel commented on src/main/java/com/programmers/view/ResultView.java
> +                + "선택 : ");
StringBuilder 한 번 써볼까요?

2022-11-04 12:33 UTC, samkimuel commented on src/test/java/com/programmers/domain/CalculatorTypeTest.java
> +    }
하나의 테스트에서 조건문으로 분기해서 두 가지 테스트를 하는데, 분리해보면 어떨까요?
https://jojoldu.tistory.com/642

2023-06-05 18:38 UTC, closed without merging