[3기 - 김기서] 1~2주차 과제: 계산기 구현하기 제출합니다.
prgrms-be-devcourse/java-calculator pull request #87
Opened 2022-10-25 05:10 UTC by rlarltj

안녕하세요!!

자바 계산기 구현 미션 제출합니다 !!!

감사합니다.

## 📌 과제 설명 
#### 우선순위를 지키는 사칙연산
입력 받은 연산식을 최소단위 Token으로 쪼갠 뒤 연산자와 피연산자를 검사합니다.
검증된 토큰은 후위표기법으로 변환합니다.
후위표기법으로 변환된 연산식을 계산합니다.

#### 연산 결과 저장, 이전 히스토리 조회
연산 수행 시 메모리에 자동 저장됩니다.
이전 연산 히스토리들을 조회할 수 있습니다.

## 👩‍💻 요구 사항과 구현 내용 
### 요구사항
- 콘솔로 구현입니다.(스윙으로 구현하시는 분들 계실까봐) 
- 객체지향적인 코드로 계산기 구현하기
    - [x]  더하기
    - [x]  빼기
    - [x]  곱하기
    - [x]  나누기
    - [x]  우선순위(사칙연산)
- [x]  테스트 코드 구현하기
- [x]  계산 이력을 맵으로 데이터 저장기능 만들기
- [x]  정규식 사용

#### 프로젝트 구조
<img width="342" alt="프로젝트구조2" src="https://user-images.githubusercontent.com/81108344/197681453-28583147-4d3f-489d-9376-ed663677bef1.png">

#### 주요 클래스, 인터페이스 소개
- Calculator: 사용자의 입력 값 처리, 결과 출력, 연산, 저장을 핸들링
- Computer: Calculator의 연산 기능을 도맡아서 처리
  - Converter: 사용자의 연산 식을 Token으로 분리, 후위 표기법으로 변환하는 기능
  - Operater: 연산자 저장 및 사칙연산 수행 
  - Validator: 연산 식이 올바른지 검증
- History: Calculator의 저장 기능을 도맡아서 처리
- Input, Output: Calculator의 I/O 기능을 도맡아서 처리 
- Token: 사용자의 연산 식을 분리해서 저장(1토큰 = 1연산자 or 1피연산자)

## ✅ PR 포인트 & 궁금한 점 
1. 전체적으로 객체 간 기능 분리가 잘 되었는지, 클래스 간 의존도는 어떤지 궁금합니다.
2. Calculator 클래스에서 사용자의 입력 값(0~2)에 따라 if-else문으로 처리를 하였는데, 개선할 수 있는 좋은 방법이 있을까요..?
3. 코드의 가독성이 어떤지 궁금합니다.
4. 멘토님들이라면 어떤 순서로 계산기 작업을 진행하실 지 궁금합니다.
저는 입/출력 기능 --> 저장 기능 --> 연산식 검증/변환 --> 연산 처리 기능 순으로 작업을 진행했는데 큰 설계도 없이 주먹구구식으로 개발한 것 같습니다 🤣🤣

부족한 코드 잘부탁드립니다!!!!

2022-10-25 14:26 UTC, seung-hun-h reviewed
기서님 안녕하세요 함승훈입니다!
일단 테스트도 성실히 작성하셨고, 클래스도 역할과 책임에 따라 잘 분리하려는 모습이 보여 좋습니다!
리뷰 남겼으니 확인해주세요! 제가 하는 말이 반드시 맞는 것이 아니므로 의견이 있으면 편하게 남겨주세요.

질문 남긴것이 있어 답변드릴게요
1. 전체적으로 객체 간 기능 분리가 잘 되었는지, 클래스 간 의존도는 어떤지 궁금합니다.
- 객체를 잘 나눈 것 같아요. 하지만 조금 과하게 나눈 것은 아닐까하는 부분도 있네요. 그리고 Calculator가 입출력까지 하고 있어 과한 책임을 가지고 있다는 생각도 드네요
- 클래스간 의존도는 어떤 것을 말씀하시는 지 잘 모르겠네요. 의존하고 있는 클래스의 수를 말씀하시는 것이면 적당한 것 같아요
2. Calculator 클래스에서 사용자의 입력 값(0~2)에 따라 if-else문으로 처리를 하였는데, 개선할 수 있는 좋은 방법이 있을까요..?
- Enum을 사용하면 좋을 것 같네요
3. 코드의 가독성이 어떤지 궁금합니다.
- 메서드에 1, 2, "A" 같은 값을 직접 작성하는 것 보다 상수나 Enum을 사용하면 의미를 좀 더 정확히 파악할 수 있고, 메서드로 분리하면 가독성이 더 좋아질 것 같아요
4. 멘토님들이라면 어떤 순서로 계산기 작업을 진행하실 지 궁금합니다.
- 저도 기서님과 비슷한 흐름으로 작성 했을 것 같아요. 
- 코드를 작성하는 것보다 설계를 먼저 잘하는 것이 중요할 것 같아요

2022-10-25 14:26 UTC, seung-hun-h commented on src/main/java/engine/io/ConsoleInput.java
> +    }
인자로 전달된 `msg`는 사용자가 선택할 수 있는 선택지를 말하는 건가요? 그건 어떻게 알 수 있을까요?

2022-10-25 14:26 UTC, seung-hun-h commented on src/main/java/engine/io/ConsoleInput.java
> +    }
`msg`를 사용하지 않는데 메서드 시그니처를 이렇게 설계한 이유가 있을까요?
[메서드 시그니처란?](https://www.thoughtco.com/method-signature-2034235)

2022-10-25 14:26 UTC, seung-hun-h commented on src/main/java/engine/option/Option.java
> +public enum Option {
Enum 활용하신거 좋은 것 같네요!

2022-10-25 14:26 UTC, seung-hun-h commented on src/main/java/engine/option/Option.java
> +        if (comm == 0 || comm == 1 || comm == 2)
메서드로 분리해서 의미를 명확하게 하면 좋을 것 같네요

2022-10-25 14:26 UTC, seung-hun-h commented on src/test/java/engine/compute/ComputerTest.java
> +
private 접근 제어자를 사용하면 좋겠네요

2022-10-25 14:26 UTC, seung-hun-h commented on src/test/java/engine/compute/ComputerTest.java
> +    }
한 개의 테스트에 여러 검증문을 사용하는 것은 안티 패턴으로 알고 있습니다. 
Parameterized Test에 대해서 알아보면 좋을 것 같네요
https://www.baeldung.com/parameterized-tests-junit-5

2022-10-25 14:26 UTC, seung-hun-h commented on src/test/java/engine/compute/validator/ValidatorTest.java
> +    void isNumberTest() {
테스트 메서드 이름은 어떻게 짓는 것이 좋을까요?
https://methodpoet.com/unit-test-method-naming-convention/

2022-10-25 15:09 UTC, hongbin-dev requested changes
기서님! 미션 빠르게 제출해주셨군요. 좋습니다.
승훈님이 리뷰를 많이남겨주셔서 가볍게 훑어봤는데요. 추가로 궁금하신거 있으면 코멘트나 슬랙채널에 남겨주세요~

2022-10-25 15:09 UTC, hongbin-dev commented on src/test/java/engine/model/ExpressionTest.java
> +    }
한글로 테스트명하신점 읽기 좋네요ㅎ 
대신 assert문이 없으면 테스트자동화가 어렵습니다. 단순 출력문으로 테스트가 성공한지, 실패하는지는 수동으로 확인해야해요.

2022-10-25 15:09 UTC, hongbin-dev commented on src/main/java/engine/compute/Computer.java
> +    private OperateMachine operateMachine;
검증객체, 변환객체, 계산객체가 세개로 나눠지는데요. 

1. expressionConverter로 입력을 변환한다
2. expressionValidator가 변환한 입력을 검증한다
3. operateMachine로 검증된 값을 계산한다

라는 순차적으로 되어있는데요. 만약 다른 사용자가 3개의 객체를 본다면 위와 같은순서를 인지할 수 있고, 동일한 순서로 작성할 수 있을까요?
이 부분을 객체로 나누지않고, 하나의 클래스로 응집시키면 어떨까요?

2022-10-27 02:41 UTC, rlarltj commented on build.gradle
> +    testAnnotationProcessor 'org.projectlombok:lombok:1.18.24'
롬복 의존성 삭제하였습니다!!

2022-10-27 02:44 UTC, rlarltj commented on src/main/java/engine/calculator/Calculator.java
> +        boolean exitFlag = true;
수정한 코드에서 플래그 변수를 삭제했습니다!
while문의 종료 조건을 고민해보았는데 
현재 수정한 코드 외에 다른 좋은 방법이 떠오르지 않습니다.ㅠ

2022-10-27 02:45 UTC, rlarltj commented on src/main/java/engine/calculator/Calculator.java
> +            String userCommand = input.showOption(sb);
두 가지 기능을 아래 두 개 메소드로 분리하였습니다! 
void showOption()으로 옵션 리스트 출력
String getUserInputOption() 으로 사용자 입력 값 받아오기

2022-10-27 02:46 UTC, rlarltj commented on src/main/java/engine/calculator/Calculator.java
> +                int comm = Option.checkUserInput(userCommand.trim());
모든 코드에서 변수 명, 메소드 명을 명확하게 변경해보았습니다.

2022-10-27 02:58 UTC, rlarltj commented
현재 Computer 객체랑 이와 연관된 expressionConverter, expressionValidator, operateMachine 등의 객체는 수정중에 있습니다..!!

Calculator 클래스를 조금 리팩토링 해보았는데 잘 진행되었는지 궁금합니다 !!
감사합니다.

개선사항
[모든 코드]
-  private 선언이 누락된 필드에 private을 추가하였습니다.
- 의미가 없거나 축약형인 변수명, 헷갈리는 메소드 명을 수정했습니다.
- 1, 0, "+", "-"의 값을 노출하기 보다 Enum을 사용해 처리했습니다.
- 주석 제거했습니다.
[테스트 코드]
- 모든 테스트코드를 Assertion을 사용해 자동화 했습니다.
- 한 테스트 메소드에서 여러 검증 메소드 사용을 지양했습니다.

[Calculator]
- 종료 조건인 boolean flag를 삭제했습니다.
- 기존 if-else 구문을 executeUserCommand 메소드로 분리했습니다.
다만 flag 변수를 삭제하니 while문 처리를 어떻게 해야 좋을까 고민해보았는데
지금보다 더 좋은 방법이 떠오르지 않습니다..

TODO
- Computer 객체가 사용하는 컨버터, 검증기, 연산기를 하나의 객체로 응집하기
- Calculator 객체가 입/출력까지 담당하고 있는데, 분리할 수 있는 방법 생각해보기

2022-10-27 03:03 UTC, rlarltj commented on src/test/java/engine/model/ExpressionTest.java
> +    }
전부 Assertion 검증 방식으로 수정했습니다!!

2022-10-27 03:03 UTC, rlarltj commented on src/main/java/engine/option/Option.java
> +        if (comm == 0 || comm == 1 || comm == 2)
상수를 Enum 값으로 처리했습니다!

2022-10-27 03:04 UTC, rlarltj commented on src/main/java/engine/compute/converter/ExpressionConverter.java
> +                    case "/":
enum 값으로 변경했습니다!

2022-10-27 03:04 UTC, rlarltj commented on src/main/java/engine/calculator/Calculator.java
> +                } else if (comm == 1) {
일단 메소드로 분리하여 2 depth로 개선했습니다!!

2022-10-27 03:08 UTC, rlarltj commented on src/main/java/engine/compute/Computer.java
> +    private OperateMachine operateMachine;
좋은 의견 감사합니다!! 
Computer가 현재 의존하는 검증, 변환, 계산 객체를 'Machine' 이라는 하나의 클래스로 옮기고
Computer 객체는 machine의 메소드 하나만 호출하면 되게끔 설계하는 방식일까요?.?

2022-10-27 03:11 UTC, rlarltj commented on src/main/java/engine/calculator/Calculator.java
> +                }
enum 값으로 변경했습니다!!

2022-10-27 03:13 UTC, rlarltj commented on src/main/java/engine/compute/validator/ExpressionValidator.java
> +public interface ExpressionValidator {
추후에 다른 Validator를 사용할 수 있지 않을까..? 싶어서 일단 인터페이스를 사용했습니다 !.!

2022-10-27 15:58 UTC, hongbin-dev commented on src/main/java/engine/compute/converter/ExpressionConverter.java
> +                    case DIVIDE:
switch를 빼도 되겠는데요..!?

2022-10-27 15:58 UTC, hongbin-dev commented on src/test/java/engine/compute/validator/ValidatorTest.java
> +        List<Token> tokens1 = converter.convertUserInputToTokenList("3+5");
테스트 코드도 하나의 문서로 볼 수 있는데요. 가독성이 좋으면 읽기 좋을 것 같아요
given, when, then 스타일로 작성해보면 좋을 것 같아요.

2022-10-27 15:58 UTC, hongbin-dev commented on src/main/java/engine/compute/converter/ExpressionConverter.java
> +            }
else를 제거할 수 있는 방법은 없을까요?

2022-10-27 15:58 UTC, hongbin-dev commented on src/main/java/engine/compute/converter/ExpressionConverter.java
> +        }
switch의 의미가 없어보이네요..!? 제거하는게 낫지않을까요?

2022-10-27 15:58 UTC, hongbin-dev commented on src/main/java/engine/compute/operate/OperateMachine.java
> +            }
이 부분은 isNumber, isOperator가 아니면 아무일도 일어나지 않을 것 같네요.

2022-10-27 15:58 UTC, hongbin-dev commented on src/main/java/engine/compute/Computer.java
> +    private OperateMachine operateMachine;
네 맞습니다. 그렇게 진행해보셔도 좋을 것 같아요.
하나의 일을 하는 객체가 나눠져있어서, 응집도가 떨어져보이네요.

2022-10-27 16:08 UTC, hongbin-dev reviewed
추가 코멘트 남겼습니다~!
반영되면 알려주세요 ㅎㅎ

2022-10-27 16:08 UTC, hongbin-dev commented on src/main/java/engine/compute/operate/Operator.java
> +    }
enum에서 기본으로 제공하는 values() 메서드를 활용하면 좋겠네요~

2022-10-27 16:08 UTC, hongbin-dev commented on src/main/java/engine/compute/operate/Operator.java
> +    }
n1, n2의 의미를 더 부여해보면 좋겠네요~

2022-10-27 16:08 UTC, hongbin-dev commented on src/main/java/engine/compute/operate/Operator.java
> +        return Arrays.stream(values()).filter(operatorEnum -> operatorEnum.operator.equals(operatorString)).findFirst().get();
한줄에 한점을 찍는다. 반영해보시면 좋겠습니다 ㅎ

2022-10-27 16:08 UTC, hongbin-dev commented on src/main/java/engine/history/MapHistory.java
> +    }
String으로 변환하는건 출력하는 객체의 책임일 것 같아요~ 이 객체에서는 데이터만 제공하는게 어떨까요?

2022-10-27 16:08 UTC, hongbin-dev commented on src/main/java/engine/history/MapHistory.java
> +public class MapHistory implements History {
History라는 객체로 명명하셨는데, 복수의 자원(컬렉션)을 표현하는 것 같아요. `Histories` 라는 네이밍은 어떨까요?

2022-10-27 16:08 UTC, hongbin-dev commented on src/test/java/engine/history/MapHistoryTest.java
> +        System.out.println(all);
단위테스트는 일반적으로 한번에 1개를 테스트 진행해요.
한번에 여러 테스트를 진행하면 단점이 무엇일까요?

2022-10-27 16:08 UTC, hongbin-dev commented on src/main/java/engine/compute/converter/ExpressionConverter.java
> +        String operatorRegEx = "(?=[+/*-])|(?<=[+/*-])";
상수로 관리하면 좋겠군요~

2022-10-28 02:46 UTC, rlarltj commented on src/main/java/engine/compute/converter/ExpressionConverter.java
> +        }
앗 그러네요 !! 바로 제거하였습니다

2022-10-28 02:51 UTC, rlarltj commented on src/main/java/engine/compute/converter/ExpressionConverter.java
> +            }
else문을 if(expressionValidator.isOperator) 로 변경했습니당

2022-10-28 06:12 UTC, rlarltj commented on src/test/java/engine/history/MapHistoryTest.java
> +        System.out.println(all);
여러 테스트 중 하나가 실패하면 그 이후로는 테스트가 진행되지 않습니당

2022-10-28 06:12 UTC, rlarltj commented on src/main/java/engine/history/MapHistory.java
> +    }
말씀하신 대로 수정했습니다 : )

2022-10-28 06:20 UTC, rlarltj commented on src/main/java/engine/compute/operate/Operator.java
> +    }
values() 메소드와 stream을 사용해서 수정했습니다 !!

2022-10-28 15:01 UTC, rlarltj commented
안녕하세요 !!
바쁘실텐데 자세히 리뷰해주셔서 정말정말 감사합니다!!!

이번에 개선한 부분입니다.
- 불필요한 else문, switch문 제거
- 테스트 코드 given/when/then 형식으로 수정
- `History` -> `Histories` 변경 및 map -> String으로 변환하는 작업을 `Histories` -> `Output` 객체로 이동
- ComputeService를 생성하여 검증, 변환, 연산 객체를 응집

코드를 수정하면서 궁금한 점이 생겼는데요,

1. 기존 `Compute`  객체에서 총 3가지 객체(검증객체, 변환객체, 연산객체)에 의존한 뒤 각각 메소드를 호출했었는데요
변경한 코드에서는 `ComputeService` 라는 인터페이스와 
구체 클래스인 `ComputeServiceImpl` 을 두어 이곳에 3가지 객체를 응집했습니다.
이전에 "하나의 클래스로 응집시키면 어떨까요?" 하고 조언해주셨는데 이렇게 변경하는 것이 맞는지 궁금합니다..

2. 객체를 응집(?)한 `ComputeServiceImpl`에서 
1) 변환객체 - 유저의 입력값을 `List<Token>`으로 쪼개기
2) 검증객체 - `List<Token>`을 순회하며 `숫자 or Enum의 연산자인지`, `올바른 순서인지` 검증 --> 아닐 시 Exception 발생
3) 변환객체 - 검증된 List<Token>을 후위표기법으로 변환
4) 연산객체 - 후위 표기식으로 연산 수행
위 순서로 작업이 진행되는데요

검증객체 다음 순서인 3, 4번 과정을 수행하는 메소드에 잘못된 값이나 
다른 값이 들어오는 경우에 대비해서 예외처리를 해주어야 하는지 궁금합니다!! 
만약 예외 처리를 해주어야 한다면,
현재 public인 접근제어자와 패키지 구조를 수정해서 다른 클래스들은 
검증객체, 변환객체, 연산객체를 호출할 수 없게끔 설계하는 방식을 생각해보았는데 어떤지 궁금합니다 !!

👍 👍 다시 한 번 리뷰해주신 멘토님들께 감사드립니다 👍 👍

2022-10-29 12:58 UTC, hongbin-dev commented
> 검증객체 다음 순서인 3, 4번 과정을 수행하는 메소드에 잘못된 값이나
다른 값이 들어오는 경우에 대비해서 예외처리를 해주어야 하는지 궁금합니다!

검증객체가 모두 검증되어  있지 않나요? 
다른 예외케이스가 있을까요? 지금같은 상황에서 검증객체에서 검증이 가능하다면, 그쪽에서 선행해주는게 좋아보입니다.
그게어렵다면 계산하는 객체에도 추가 검증이 필요해보이긴하네요.

2022-10-29 12:58 UTC, hongbin-dev approved these changes
고생많으셨습니다~

2022-10-29 12:58 UTC, hongbin-dev commented on src/test/java/engine/history/MapHistoriesTest.java
> +        System.out.println(all);
테스트에는 출력으로 테스트하지않고, assert문으로 검증해주세요. 출력형태는 테스트자동화를 할 수 없습니다~

2022-10-29 12:58 UTC, hongbin-dev commented on src/main/java/engine/compute/operate/Operator.java
> +                    .get();
`get()` 했을때 인텔리제이에서 노랗게 나오지않나요?
대체값을 주거나, 예외를 던지는 방향은 어떨까요?

2022-10-29 12:58 UTC, hongbin-dev commented on src/main/java/engine/history/MapHistories.java
> +    public Map<String, String> getHistories() {
👍

2022-10-29 12:58 UTC, hongbin-dev commented on src/main/java/engine/io/ConsoleOutput.java
> +        return stringBuilder.toString();
출력객체가 적절한 수식으로 변경해주는게 좋네요.

2022-10-29 12:58 UTC, hongbin-dev commented on src/main/java/engine/compute/ComputeServiceImpl.java
> +public class ComputeServiceImpl implements ComputeService {
Service라는 네이밍보단 Compute로 관리해도 좋을 거 같아요~

2022-10-29 12:58 UTC, hongbin-dev commented on src/test/java/engine/compute/validator/ValidatorTest.java
> +        Assertions.assertEquals(validator.isCorrectOrder(tokens), true);
테스트코드가 한결 깔끔해졌군요 👍

2022-10-29 16:34 UTC, rlarltj commented on src/main/java/engine/compute/operate/Operator.java
> +                    .get();
어째서 제 인텔리제이는 알려주지 않는 것일까요..ㅜ
get()보다 orElseThrow()가 더 자연스러운 것 같아서 변경하였습니다!!
감사합니다 (__)

2022-11-06 00:18 UTC, merged