[2주차 과제] 계산기 TDD, OOP로 만들기 과제 제출 PR 입니다!
prgrms-be-devcourse/java-calculator pull request #88
Opened 2022-10-25 08:03 UTC by thguss

## 📌 과제 설명 
- 입력값으로 선택 값 받아오기 (1. 조회 2. 계산 3. 종료)
- (계산 로직 구현) 계산식 입력 값 받아오기
- (계산 로직 구현) +, -, *, /, 숫자 우선순위 지정 메소드 구현
- (계산 로직 구현) 파싱: 입력 값(계산식)을 후위표기법으로 큐에 저장하여 반환
- (계산 로직 구현) 사칙연산: 후위표기법 형식의 큐에서 우선순위를 고려하여 하나씩 빼서 계산 및 계산 결과 반환
- (계산 로직 구현) 반환 받은 계산 결과를 CaculaotrHistory 클래스로 넘겨 Map 으로 저장
- (조회 로직 구현) Map에 저장된 계산 결과 식 (String) 을 Collection으로 모든 이력 출력
- (종료 로직 구현) 3 으로 입력값이 들어오면 프로그램 종료

## 👩‍💻 요구 사항과 구현 내용 
- 프로젝트 초기 세팅: main 레포를 포크 -> 새로운 인텔리제이 프로젝트 생성 후 커밋&푸시
- 사칙연산 구현: `App` `Calculator` `Console` 클래스 구현
  - `Console` 에서 입력값 받아오기 및 결과 출력
  - `Calculator` 에서 사칙 연산 계산 로직 구현
  - `App` 에서 `Calculator` run
- 조회 로직 구현:  `CalculatorHistory` 클래스 추가 -> Map 으로 계산 이력을 문자열로 저장 및 출력
- 롬복 지양: `Calculator` 에서 롬복 어노테이션 제거 및 생성자 추가
- 배열 지양: 조회 로직 구현 (계산이력 출력) 에서 ArrayList를 제거하고 `Collection` 클래스 생성 및 Collection 으로 이력 출력

## ✅ PR 포인트 & 궁금한 점 
- 코드가 객체지향으로 잘 나누어졌는 지 궁금해요!
- 최대한 롬복과 배열을 지양하고자 했는데 잘 됐는 지 궁금해요!
- 변수명이 직관적으로 잘 지어졌는 지도 궁금해요..!!

감사합니다 :)

2022-10-25 08:48 UTC, hongbin-deali commented
소현님! .idea .build 파일 등 많은 파일들이 올라왔는데요.
깃이그노어 추가하셔서 해당파일 제외해주시고 푸시 부탁드려요~

2022-10-25 15:12 UTC, hongbin-dev commented on calculator/.gitignore
> +.idea/**/shelf
빠른반영 좋네요 👍

2022-10-25 15:32 UTC, hongbin-dev requested changes
안녕하세요 소현님. 미션 고생많으셨습니다 👍
build.gradle파일이 calculate 폴더에 존재하는데, 루트 경로로 옮겨주면 좋겠네요.
궁금하신점은 코멘트나 슬랙채널에서 편하게 여쭤보셔도 좋습니다!

## 코드가 객체지향으로 잘 나누어졌는 지 궁금해요!
큼지막하게 잘 나눠주셨으나, 메인인 Calculator객체가 하는일이 너무 많습니다!
명령어별로 분기하는 객체, 입출력을 담당하는 객체, 계산을 담당하는 개체로 크게 나눠보면 어떨까요?

## 최대한 롬복과 배열을 지양하고자 했는데 잘 됐는 지 궁금해요!
네! 잘하셨습니다. 추가로 롬복 의존성을 삭제해주시면 더 좋을 거 같네요.

## 변수명이 직관적으로 잘 지어졌는 지도 궁금해요..!!
각각에 코멘트 남겨드렸습니다~

2022-10-25 15:32 UTC, hongbin-dev commented on calculator/build.gradle
> +    testAnnotationProcessor 'org.projectlombok:lombok:1.18.24'
사용하지않는다면 삭제해도 좋을 것 같아요~

2022-10-25 15:32 UTC, hongbin-dev commented on calculator/build.gradle
> +    implementation 'com.github.javafaker:javafaker:1.0.2'
이 의존성은 왜 필요한가요?

2022-10-25 15:32 UTC, hongbin-dev commented on calculator/src/main/java/com/programmers/calculate/Collection.java
> +public class Collection<T> {
이 객체를 만드신 이유가 있을까요? 
Collection이라는 이름이 List객체가 구현하고있는 컬렉션과 동일하지 않나요..?

2022-10-25 15:32 UTC, hongbin-dev commented on calculator/src/main/java/com/programmers/calculate/engine/Calculator.java
> +                    break;
객체지향 생활체조 ` 한 메서드에 오직 한 단계의 들여쓰기만 한다.` 이 부분이 지켜지지않았네요. 
현재 3개의 뎁스인데, 2개정도로 줄일 순 없을까요?

2022-10-25 15:32 UTC, hongbin-dev commented on calculator/src/main/java/com/programmers/calculate/engine/Calculator.java
> +                switch (exp) {
이 부분도 depth가 깊어서 코드를 읽기 어렵네요.

+ 객체지향 생활체조 ` else 키워드를 쓰지 않는다.`를 참고해주시길 바래요~

2022-10-25 15:32 UTC, hongbin-dev commented on calculator/src/main/java/com/programmers/calculate/engine/Calculator.java
> +    protected int calculate(Queue<String> queue) {
protected로 지정하신 이유가 있을까요?

2022-10-26 13:34 UTC, seung-hun-h reviewed
안녕하세요 소현님 함승훈입니다.
작성하신 코드 살펴보니 최대한 객체를 잘 나누려하신 점 좋았습니다!

다만 클래스의 역할과 메서드의 책임을 좀 더 명확히 정의하고 구현 했으면 더 좋을 것 같아요.
리뷰 남겼으니 확인해주세요

**배열 지양: 조회 로직 구현 (계산이력 출력) 에서 ArrayList를 제거하고 Collection 클래스 생성 및 Collection 으로 이력 출력** 으로 설명을 남겨 주셨는데 배열 사용을 지양하는데 ArrayList를 제거한 이유가 있을까요?

2022-10-26 13:34 UTC, seung-hun-h commented on calculator/src/main/java/com/programmers/calculate/Console.java
> +    }
메서드의 이름과 역할이 매칭되지 않는 것 같아요.
`printErrorMessage` 같은 이름을 지어주는 것이 좋겠네요.

2022-10-26 13:34 UTC, seung-hun-h commented on calculator/src/main/java/com/programmers/calculate/Console.java
> +public class Console implements Input, Output {
Console의 역할은 무엇인가요? Console의 역할을 정의 해보면 좋을 것 같아요.

2022-10-26 13:34 UTC, seung-hun-h commented on calculator/src/main/java/com/programmers/calculate/CalculatorHistory.java
> +    private Long key = 0L;
key를 사용하는 이유가 있나요?
key를 반환해서 클라이언트 코드에서 사용할 수 있도록 설계되지 않은 것 같아요

2022-10-26 13:34 UTC, seung-hun-h commented on calculator/src/test/java/com/programmers/calculate/engine/CalculatorTest.java
> +    void 우선순위() {
테스트 메서드 이름을 보고 어떤 테스트인지 알아보기 쉽지 않을 것 같아요
어떠한 조건에서 무엇을 실행하면 어떤 결과가 나타나야 하는지를 표현해보면 좋겠네요

2022-10-27 07:44 UTC, thguss commented on calculator/build.gradle
> +    implementation 'com.github.javafaker:javafaker:1.0.2'
강의에서 따라 친 build.gradle 그대로 가져오다보니 필요 없는 것까지 온 것 같습니다..!! ㅋㅋ큐ㅠㅠㅠ 언급 감사합니다 :)

2022-10-27 07:52 UTC, thguss commented on calculator/src/main/java/com/programmers/calculate/CalculatorHistory.java
> +        history.forEach(System.out::println);
배열을 지양해야 한다고 이해했었는데, 이 경우에는 배열을 사용하는 것이 바람직한 이유가 궁금합니다!

2022-10-27 08:10 UTC, thguss commented on calculator/src/main/java/com/programmers/calculate/CalculatorHistory.java
> +    public void findAll() {
출력을 담당하는 객체를 넘겨서, 출력에서 Map 값 리스트를 출력하도록 처리했습니다.
제가 잘 이해한 것이 맞을까요??
```
    public void findAll(Output output) {
        output.printMapValues(historyMap);
    }
```

2022-10-27 08:11 UTC, thguss commented on calculator/src/main/java/com/programmers/calculate/CalculatorHistory.java
> +    private Long key = 0L;
history 로 변수명 수정했습니다. 감사합니다 :)

2022-10-27 08:13 UTC, thguss commented on calculator/src/main/java/com/programmers/calculate/Collection.java
> +public class Collection<T> {
배열을 지양해야 한다는 점을 보고 따로 Collection 객체로 만들게 되었습니다! (List 객체 역할과 동일해서 List 객체로 수정했습니다 :) )

2022-10-27 08:13 UTC, thguss commented on calculator/src/main/java/com/programmers/calculate/engine/Calculator.java
> +    History history;
감사합니다 :)

2022-10-27 08:16 UTC, seung-hun-h commented on calculator/src/main/java/com/programmers/calculate/CalculatorHistory.java
> +        history.forEach(System.out::println);
흠 소현님 ArrayList를 배열로 이해하고 계신 것 같아요. 내부 구현이 동적 배열로 되어있다고 알고 있지만, ArrayList는 배열이 아닙니다!
https://www.geeksforgeeks.org/array-vs-arraylist-in-java/

2022-10-27 08:50 UTC, thguss commented on calculator/src/main/java/com/programmers/calculate/engine/Calculator.java
> +            int num = input.selectNumber();
Menu라는 enum 파일을 따로 만들어서 표기했습니다. 제가 한 방식이 맞을까요?!

2022-10-27 09:02 UTC, thguss commented on calculator/src/main/java/com/programmers/calculate/engine/Calculator.java
> +    protected int calculate(Queue<String> queue) {
private 로 지정하면 테스트 파일에서 메소드가 호출되지 않았어요 ㅠㅠ

2022-10-27 09:06 UTC, thguss commented on calculator/src/main/java/com/programmers/calculate/Console.java
> +public class Console implements Input, Output {
입출력을 담당하는 객체로 생각했습니다!

2022-10-27 09:35 UTC, seung-hun-h commented on calculator/src/main/java/com/programmers/calculate/Console.java
> +public class Console implements Input, Output {
입출력을 담당하는 객체가 사용자에게 노출할 메뉴 정보까지 알고있는 것 같아요. 
Console은 소현님이 말씀하신대로 입출력을 담당하고, 인자로 message를 전달 받는 방식이 좋을 것 같아요

2022-10-27 15:29 UTC, thguss commented on calculator/src/main/java/com/programmers/calculate/CalculatorHistory.java
> +    private Long key = 0L;
map 구조라서 key 값이 필요하다고 생각했습니다!

2022-10-29 13:02 UTC, hongbin-dev commented on calculator/src/main/java/com/programmers/calculate/CalculatorHistory.java
> +    public void findAll() {
CalculatorHistory는 출력객체는 알 필요가 없을 것 같아서요~

```
 public Map<Long, String> findAll() {
        return ...
    }
```

이런형태를 생각했어요 ~

2022-10-29 13:03 UTC, hongbin-dev commented on calculator/src/main/java/com/programmers/calculate/CalculatorHistory.java
> +    private Long key = 0L;
(한번에 말씀드렸으면 좋았을텐데) 컬렉션은 주로 복수로 표현합니다~ histories

2022-10-29 13:04 UTC, hongbin-dev commented on calculator/src/main/java/com/programmers/calculate/engine/Calculator.java
> +            int num = input.selectNumber();
제가 생각한 방향입니다~!

2022-10-29 13:05 UTC, hongbin-dev commented on calculator/src/main/java/com/programmers/calculate/engine/Calculator.java
> +    protected int calculate(Queue<String> queue) {
private 메서드는 어떻게 테스트해야할까요?

2022-10-29 13:07 UTC, hongbin-dev approved these changes
피드백 반영 좋네요 🙂
여기서 approve 하겠습니다

2022-10-29 13:07 UTC, hongbin-dev commented on calculator/src/main/java/com/programmers/calculate/engine/Calculator.java
> +            }
- str의 의미를 알 수 있도록 표현하면 좋을 것 같아요.
- "-?\\d+" 를 상수로 관리해볼까요?

2022-10-29 13:07 UTC, hongbin-dev commented on calculator/src/main/java/com/programmers/calculate/engine/Calculator.java
> +            }
default 예외처리 좋네요.

2022-11-01 05:01 UTC, seung-hun-h commented on calculator/src/main/java/com/programmers/calculate/CalculatorHistory.java
> +    private Long key = 0L;
key를 사용한다면 저장할 때 반환해줘서 객체를 찾을 수 있게 하는 것이 좋을 것 같다고 생각했어요!
지금 상태에서는 `List`를 사용해서 저장하는 것과 별반 다르지 않는 것 같네요

2022-11-06 00:17 UTC, merged