[3기-장영지] 1~2주차 과제 : 계산기 구현하기 제출합니다.
prgrms-be-devcourse/java-calculator pull request #91
Opened 2022-10-25 13:10 UTC by youngjijang

## 📌 과제 설명 
OOP를 적용한 사칙연산 계산기 구현하기
## 👩‍💻 요구 사항과 구현 내용 
- 객체지향적인 코드로 계산기 구현하기
    - [X]  더하기
    - [X]  빼기
    - [X]  곱하기
    - [X]  나누기
    - [X]  우선순위(사칙연산)
- [ ]  테스트 코드 구현하기
- [X]  계산 이력을 맵으로 데이터 저장기능 만들기

**프로젝트 구조**
<img width="377" alt="스크린샷 2022-10-25 오후 10 07 54" src="https://user-images.githubusercontent.com/100327413/197781292-be51d21c-2242-4c80-9507-761d0c02cba1.png">

## ✅ PR 포인트 & 궁금한 점 
- 프로젝트 세팅이 올바르게 되었는지 궁금합니다.
- interface와 class를 올바르게 나눴는지 궁금합니다. (객체지향적으로 코드를 짰는지, 부족한 부분이 무엇인지)

2022-10-26 16:08 UTC, ksy90101 requested changes
안녕하세요.
미션 하시느라 고생 많으셨습니다 💯 
간단한 피드백을 남겼어요..

전반적으로 하나만 이야기 드리면 객체가 무엇인지 계산기 미션에 객체가 무엇이 필요할지 한번 고민해보세요. 그렇다면 좀 더 객체지향적으로 작성할수 잇을듯 해요.

아울러 테스트 코드도 model에 있는 메서드들만 해보세요. 충분히 가능할듯 해요.

질문이 잇다면 언제든 주세요.

2022-10-26 16:08 UTC, ksy90101 commented on src/main/java/com/programmers/java/engin/postfixCalculation.java
> +                        }else{
이 부분을 enum으로 관리해서 전략패턴을 한번 적용해 볼수 있을듯 해요.

https://rutgo-letsgo.tistory.com/167

위 글을 한번 참고해보시겠어요?

2022-10-26 16:08 UTC, ksy90101 commented on src/test/java/com/programmers/java/engin/postfixCalculationTest.java
> +class postfixCalculationTest {
테스트 코드가 비슷해 보이는데요.

@ParametziedTest를 이용한다면 중복코드 제거가 가능합니다.

2022-10-26 16:08 UTC, ksy90101 commented on src/main/java/com/programmers/java/engin/postfixCalculation.java
> +        * */
극단적으로 주석없이도 이해할수 있는 코드를 작성하는 방법을 고민해보세요.

2022-10-26 16:08 UTC, ksy90101 commented on src/main/java/com/programmers/java/engin/postfixCalculation.java
> +        for (String s : expression.split(" ")){
stack, s 처럼 의미없는 변수보단 의미있는 변수명을 지어둔다면 우리는 코드로만으로도 소통할수 있습니다.

2022-10-26 17:34 UTC, samkimuel requested changes
영지님 고생많으셨어요~!
마르코가 먼저 리뷰 하셔서 저는 조금 더 보태서 코멘트 달았습니다 ㅎㅎ 확인해주세요~!

- PostfixCalculation.getResult()가 많은 역할을 하고 있어요. 해당 메서드 내부 로직을 나누면 더 좋을 것 같아요.
- 메서드를 나누면서 해당 메서드가 이 클래스에 있는게 맞을까?라고 생각하면서 클래스 분리를 시도해보는 것도 좋을 것 같아요. + 테스트 코드도 더 세밀하게 작성해볼 수 있겠죠?

2022-10-26 17:34 UTC, samkimuel commented on src/main/java/com/programmers/java/engin/postfixCalculation.java
> +        * */
마르코의 코멘트에 동의합니다 ㅎㅎ
추가적으로 주석으로 `ver 1`을 작성하신 것 보니 업데이트가 될 가능성이 있는 코드같은데, 코드 버전 관리가 되니까 굳이 주석을 달지 않아도 될 것 같아요.

2022-10-26 17:34 UTC, samkimuel commented on src/main/java/com/programmers/java/engin/Calculator.java
> +    }
[객체지향 생활 체조 원칙](https://blogshine.tistory.com/241)
1. 한 메서드에 오직 한 단계의 들여 쓰기만 한다.

를 지키도록 리팩토링 해보실래요??

뎁스가 깊어질수록 코드 읽기가 더 힘들어져요.
메서드를 분리해보면 어떨까요?

2022-10-26 17:34 UTC, samkimuel commented on src/main/java/com/programmers/java/engin/postfixCalculation.java
> +        return Optional.of(df.format(stack.pop()));
df라는 변수명이 무엇을 뜻하는지 모르겠어요! 축약하기보다 의미있게 수정하면 좋을 것 같아요~!

2022-10-26 17:34 UTC, samkimuel commented on src/main/java/com/programmers/java/engin/postfixCalculation.java
> +    }
1, 2를 리턴하는데, 각각 어떤 의미를 가지고 있는지 파악하기 힘든 것 같아요. 상수로 추출하면 좋을 것 같아요!

2022-10-26 17:34 UTC, samkimuel commented on src/main/java/com/programmers/java/engin/postfixCalculation.java
> +public class postfixCalculation implements Calculation {
클래스명은 대문자 필수입니닷!

2022-10-28 17:57 UTC, youngjijang commented
![스크린샷 2022-10-29 오전 2 43 04](https://user-images.githubusercontent.com/100327413/198699435-3a5da1cb-2ac6-4ff1-ab2d-bfe0e53d7dd1.png)

@ksy90101 
리뷰 감사합니다😇 새롭게 알게된게 많네요..!
객체에 대해 고민을 해보고 최대한 객체끼리 연결성을 줄이려고 노력은 해보았는데 막상보니 큰틀은 수정된게 거의 없는것 같아요ㅜㅜ 아직 객체를 나누는 기준이 잘 서지 않는 것 같습니다.. 그리고 logs에 대해서 테이블 스키마 처럼 생각해보라고 하셨는데 아무리 고민해봐도 logs 객체에 포함되어야할 데이터나 동작이 떠오르지않아서 더 자세히 어쭙고 싶어요..! 빠른 시일내에 DM 드리겠습니다❗️ 

@samkimuel 
리뷰 감사합니다 명환님!! 아직 부족하지만 코드가 좀더 보기 좋게 정리된거같아요!🙂
getResult에서 너무 많은 기능을 하는거 같다고 하셨는데 연산자 계산은 enum으로 따로 작성하니 한결 깔끔해진것 같아요! 그런데 toPostfix같은 메소드는 PostfixCalculation 외에 재사용되지 않을 것 같아 따로 클래스로 구분하기가 애매하더라구요..? 어떻게 생각하시나요?! 아직도 getResult가 무거운 느낌이 있는데 어떻게 보안하면 좋을지 좀 더 힌트를 주실 수 있을까요..🥺

2022-11-03 14:09 UTC, samkimuel reviewed
영지님 고생하셨어요! 코멘트 살짝 남겼습니다. 확인해주세요 ㅎㅎ

2022-11-16 11:22 UTC, youngjijang commented
명환님 늦었지만 코드리뷰 반영 조금 해보았습니다..!ㅎㅎ
크게 log 일급컬렉션 구현과 InputExpression class를 구현하여 toPostfix를 분리해봤어요!
아직 부족한게 많지만 코드가 처음 보다 많이 나아진것 같아요. 감사합니다😃😃😃
부족한 부분 있다면 또 말씀해주세요❗️

2022-11-20 11:41 UTC, samkimuel approved these changes
영지님 정말 고생 많았어요💯 
다른 과제하느라 많이 바쁘실텐데 잘 수정해주셨네요.
코드가 처음보다 정말 많이 나아진걸 체감하시나요? ㅋㅋ 고치면서 많이 배우셨으리라 생각됩니다.
앞으로도 쭉 파이팅 하시고 좋은 결과 있길 바라겠습니다🙏🏻

2022-11-20 11:41 UTC, samkimuel commented on src/main/java/com/programmers/java/engin/model/ConsoleInputExpression.java
> +    }
꺼내와서 처리하기보다는 OperatorType 에게 시킬 수도 있을 것 같네요 ㅎㅎ

2022-11-20 11:41 UTC, samkimuel commented on src/main/java/com/programmers/java/engin/model/Log.java
> +public class Log {
클래스 분리 👍🏻

2022-11-20 11:41 UTC, samkimuel commented on src/main/java/com/programmers/java/engin/model/LogGroups.java
> +}
일급 컬렉션 잘 만드셨네요! 👍🏻

2023-06-05 18:38 UTC, closed without merging