자바 계산기 OOP 구현 첫 풀리퀘스트입니다
prgrms-be-devcourse/java-calculator pull request #95
Opened 2022-10-26 06:11 UTC by boompatron

## 📌 과제 설명 
OOP를 활용한 간단한 계산기 구현 미션입니다. 

## 👩‍💻 요구 사항과 구현 내용 
사칙연산 과 DB 조회 기능이 있습니다.

계산 부분에서는 사칙연산의 우선순위를 고려하였고, 괄호가 포함되더라도 알맞게 계산할 수 있도록 구현하였습니다
계산이 완료되면 DB에 저장합니다
DB 조회 기능은 단순하게 지금까지의 연산 기록을 저장하도록 하였습니다

## ✅ PR 포인트 & 궁금한 점 
클래스 구조를 많이 생각하다보니 현재 제 프로젝트의 구조가 적절한지, 더 효율적으로 아님 어떻게 코드를 짜는게 더 좋은지 궁금합니다!!
예를 들면 calculate 메소드는 여기에 들어가있는 것 보다는 다른 클래스에 위치시키는 것이 더 좋다!
굳이 이 메소드의 리턴값을 이렇게 하는 것 보다는 다르게 하는 것이 더 효율적으로 보인다

개선점 또한 많이 피드백받고 싶습니다. 제가 봐도 비효율적인 부분이 존재하는 같긴 한데, 멘토님들이 보시기에는 어떻지....

2022-10-26 06:19 UTC, boompatron commented
계산 로직은 다음과 같습니다
2개의 스택을 이용해서 연산자와 괄호 등 복합적인 우선순위를 고려하면서 계산을 진행합니다.

식을 보다가
숫자가 나오면 > 숫자 스택에 push 합니다

연산자가 나오면
1. 연산자 스택이 비어있는 경우 : 그냥 push
2. 연산자 스택의 맨 위의 연산자가 현재 연산자보다 우선순위가 같거나 높은 경우 : 숫자 스택에서 2개를 pop 하고 연산자 스택에서도 하나를 pop 한 후, 계산을 진행, 계산 결과를 숫자 스택에 넣음, 현재 연산자도 연산자 스택에 넣음
3. 그 외의 경우 : 그냥 push

괄호가 나오면
( : 다음 계산 때, 연산자의 우선순위에 상관없이 그냥 연산자를 push 하게 합니다
) : 무조건 숫자 2개와 연산자 1개를 pop 하고 계산을 진행합니다

2022-10-26 06:21 UTC, boompatron reviewed
기존에는 Validator가 다중상속을 하였으나, 이제는 2개의 valdator가 각각 validator 인터페이스를 상속하는 식으로 상속의 방향을 변경하였습니다

원래 계산식을 저장하는 방식은 Formula에서 하나의 String으로 저장하였으나, 검증와 계산의 편의성을 위해서 LinkedList로 변경하였습니다
순차적으로 접근해서 LinkedList를 사용했습니다

DB도 저장되는 데이터의 형식을 변경하였습니다. 역시 LinkedList 입니다

2022-10-26 08:19 UTC, boompatron commented
검증 과정에 대한 세부사항 설명입니다
우선 식의 괄호에 대한 검증을 먼저 합니다
열린 괄호와 닫힌 괄호의 숫자가 일치 하는지만 검증을 합니다
수가 일치하면 계산을 위해 변형한 inkedlist를 리턴하고 아니면 빈 링크드리스트를 리턴합니다

숫자와연산자에 대한 검증을 그 다음에 진행합니다
수와 연산자의 경우 숫자의 개수 = 연산자의 개수  + 1 임을 확인합니다
만약 맞으면 제대로 변환한 식을 리턴해 주고, 오류가 있을 경우 역시나 빈 링크드리스트를 리턴합니다

변환은 연산자를 toString으로 변환하는 겁니다
숫자는 건들지 않고 연산자와 괄호는 PLUS, MINUS, 와 같이 같은형태로 변환시킵니다
enum을 활용하는 과정에서 다소 복잡하게 변환을 하게 되었씁니다

2022-10-26 16:08 UTC, ksy90101 commented
gitingore 처리해주세요.
그거 처리하면 리뷰할게요.

@boompatron

2022-10-27 16:32 UTC, samkimuel requested changes
보섭님 고생하셨습니다~!
몇 가지 코멘트 달았는데 확인해주세요!

코멘트로도 달았지만, 전체적으로 의미있는 변수명 사용해주시면 좋을 것 같습니다. 개행도 신경써주세요 ㅎㅎ
어떻게 하면 읽기 쉬운 코드를 작성할 수 있을지 고민하고 수정해보시죠🙂

2022-10-27 16:32 UTC, samkimuel commented on src/main/java/com/programmers/engine/validate/Validator.java
> +    public LinkedList<String> validate(LinkedList<String> s);
public 지우셔도 됩니다~! 
왜 지워도 되는지 공부해보시죠!

2022-10-27 16:32 UTC, samkimuel commented on src/main/java/com/programmers/engine/validate/NumOperatorValidator.java
> +                (l) -> {
여기도 의미있는 변수명 사용해주세요:wink:

2022-10-27 16:32 UTC, samkimuel commented on src/main/java/com/programmers/engine/Calculator.java
> +    );
이미 Enum으로 정의하고 있는데, Map을 사용하는 이유가 있을까요?
다른 곳에서도 중복코드가 보이는 것 같아서요.

2022-10-27 16:32 UTC, samkimuel commented on src/main/java/com/programmers/engine/Calculator.java
> +            }
뎁스가 깊어지면 깊어질 수록 가독성이 안좋아져요😢
메서드를 분리해보는 게 어떨까요?

2022-10-27 16:32 UTC, samkimuel commented on src/main/java/com/programmers/engine/Calculator.java
> +                else if (num.get() == 2) {
1, 2는 매직넘버입니다. 상수로 정의하는 게 좋을 것 같아요!

2022-10-27 16:32 UTC, samkimuel commented on src/main/java/com/programmers/engine/Calculator.java
> +
사용하지 않는 주석, 코드는 제거해주세요!

2022-10-27 16:32 UTC, samkimuel commented on src/main/java/com/programmers/engine/Calculator.java
> +                //reuslt.ifPresent(numStack::push);
주석으로 코드를 설명하기보다 이해하기 쉬운 코드를 작성하도록 노력해보시죠!(주석제거!)

2022-10-27 16:32 UTC, samkimuel commented on src/main/java/com/programmers/engine/Calculator.java
> +        Stack<BigDecimal> numStack = new Stack<>();
https://tecoble.techcourse.co.kr/post/2021-05-10-stack-vs-deque/
참고해서 수정해보시죠~!

2022-10-27 16:32 UTC, samkimuel commented on src/main/java/com/programmers/engine/Calculator.java
> +                 && (a.equals(Operator.DIV.toString()) || a.equals(Operator.MUL.toString()))){
Enum을 활용할 수 있을 것 같은데요?

2022-10-27 16:32 UTC, samkimuel commented on src/main/java/com/programmers/engine/model/DataBase.java
> +    public void addData(String s){data.add(s);}
```suggestion
    private final LinkedList<String> data = new LinkedList<>();
    
    public void showAll() {
        if (data.isEmpty()) System.out.println("저장된 데이터가 없습니다");
        else                data.forEach(System.out::println);
    }
    
    public void addData(String s){data.add(s);}
```
개행넣어주세요~!

2022-10-27 16:32 UTC, samkimuel commented on src/main/java/com/programmers/engine/model/DataBase.java
> +        if (data.isEmpty()) System.out.println("저장된 데이터가 없습니다");
출력은 Console역할 같은데 어떻게 생각하시나요??:🤔

2022-10-27 16:32 UTC, samkimuel commented on src/main/java/com/programmers/engine/validate/BracketValidator.java
> +    AtomicInteger closeBracket = new AtomicInteger();
멤버변수는 private으로 숨기는 게 어떨까요?
```suggestion
    private AtomicInteger openBracket = new AtomicInteger();
    private AtomicInteger closeBracket = new AtomicInteger();
```

2022-10-28 01:05 UTC, boompatron commented on src/main/java/com/programmers/App.java
> +        NumOperatorValidator validator2 = new NumOperatorValidator();
아...!!! 실행 부분에서 잠깐 돌아가는 부분이라 신경을 못 썼었던 부분 같습니다!

2022-10-28 01:28 UTC, boompatron commented on src/main/java/com/programmers/engine/Calculator.java
> +            }
며칠 전에 규현님이 아도겐 코드 작성하는게 아니냐고 했는데... 제가 그러고 있었네요ㅠ
최대한 뎁스를 줄이는 방법으로 수정해보겠습니다!

2022-10-28 01:31 UTC, boompatron commented on src/main/java/com/programmers/engine/Calculator.java
> +    );
계산을 진행하는 부분에서 자료형을 통일하게 하기 위해서 숫자와 연산자 모두를 String 형으로 변환해서 사용해서 다시 enum type으로 바꿔줄 map이 필요해서 사용했습니다!!
처음에는 구현에 급급해 map을 만들고 다른 클래스에서도 만들어서 사용했는데...
map을 사용할 거면 따로 빼 놓고 사용하는 방식으로,
사용을 하지 않으면 기존 코드 안에서 최대한 사용하는 방식으로 고쳐보겠습니다!

일단은 최대한 저 Map을 없애는 방향으로 고쳐볼게요!

2022-10-30 00:23 UTC, ksy90101 requested changes
안녕하세요 :)
미션하시느라 고생하셨습니다!
전체적인 피드백이 조금 있습니다.

1. 주석을 모두 삭제해주세요. (주석으로 인해 코드를 이해하는데 더 어려움을 가지게 됩니다.)
2. 극단적으로 객체지향 생활체조를 지켜보세요.
3. 한줄 코딩을 멈춰주세요

위 3개만 해도 깔끔한 코드가 될듯 합니다.

2022-10-30 00:23 UTC, ksy90101 commented on src/main/java/com/programmers/App.java
> +        //new Calculator(console, console, validator1, validator2, dataBase, formula).run();
주석은 코드를 이해하는데 어려움을 줍니다 :) 
필요없는 코드는 삭제해주세요.

2022-10-30 00:23 UTC, ksy90101 commented on src/main/java/com/programmers/engine/validate/NumOperatorValidator.java
> +    String operators = "+-*/";
자바의 상수는 어떻게 적을까요?
static final 키워드를 한번 찾아보세요.

2022-10-30 00:23 UTC, ksy90101 commented on src/main/java/com/programmers/engine/validate/NumOperatorValidator.java
> +        return newList;
validate 메서드에서 많은 것을 validate하는듯 한데요.
각 validate마다 메서드를 분리해보세요.

2022-10-30 00:23 UTC, ksy90101 commented on src/main/java/com/programmers/engine/validate/NumOperatorValidator.java
> +    Map<String, String> operatorMap = Map.of(
Enum의 메서드를 이용하면 이렇게 Map을 만들지 않아도 쉽게 validate가 가능할듯 해요.

2022-10-30 00:23 UTC, ksy90101 commented on src/main/java/com/programmers/engine/Calculator.java
> +
개행도 의미를 전달하기 위한 수단입니다.
의미없는 개행을 작성함에 있어, 의미가 희석될수 있어요.

2022-10-30 00:23 UTC, ksy90101 commented on src/main/java/com/programmers/engine/Calculator.java
> +                } // DB 조회
극단적으로 주석을 삭제해 코드로만 이해할수 있게 해보시겠어요?

2022-10-30 00:23 UTC, ksy90101 commented on src/main/java/com/programmers/engine/Calculator.java
> +        output.bye();
![image](https://user-images.githubusercontent.com/53366407/198857118-28a563e4-c796-4273-bad7-7242d9231ec6.png)

아도겐 코드 같네요 ㅎㅎ
어떻게 하면 이이런 코드들을 예쁘게 잘 할 수 잇을까요?

2022-10-30 00:23 UTC, ksy90101 commented on src/main/java/com/programmers/engine/Calculator.java
> +                if (num.get() == 1) {
num이 Optional인데 null이면 어떻게 될까요?

2022-10-30 00:23 UTC, ksy90101 commented on src/main/java/com/programmers/engine/Calculator.java
> +                if (num.get() == 1) {
아울러 어떻게 Null Safe하게 할수 잇을까요?

2022-10-30 00:23 UTC, ksy90101 commented on src/main/java/com/programmers/engine/Calculator.java
> +import java.util.concurrent.atomic.AtomicInteger;
사용하지 않는 import는 제거해주세요.

2022-10-30 00:23 UTC, ksy90101 commented on src/main/java/com/programmers/engine/model/Formula.java
> +    public Boolean validate(Validator validator) {
Boxed 타입을 사용하신 이유가 있나요?

2022-10-30 00:23 UTC, ksy90101 commented on src/main/java/com/programmers/engine/model/Formula.java
> +        if (value.size() == 0) return false;
collection이 비어있는지 확인할수 있는 좋은 메서드가 있습니다.

2022-10-30 00:23 UTC, ksy90101 commented on src/main/java/com/programmers/engine/Calculator.java
> +            else return Optional.of(b2.divide(b1, 2, BigDecimal.ROUND_HALF_DOWN));
1. divide() 메서드는 deprecated입니다.
2. ROUND_HALF_DOWN deprecated입니다.


두개 다 다른 방향을 찾아보세요.

2022-10-30 00:23 UTC, ksy90101 commented on src/main/java/com/programmers/engine/Calculator.java
> +        else if     (op.equals(Operator.MUL))       return Optional.of(b2.multiply(b1));
enum을 Stream으로 순회하면 이러한 Return문은 없앨수 있어요.
https://rutgo-letsgo.tistory.com/167
위 글을 한번 참고해보세요.

2022-10-30 00:23 UTC, ksy90101 commented on src/main/java/com/programmers/engine/model/DataBase.java
> +    private final LinkedList<String> data = new LinkedList<>();
한번 실제 데이터베이스처럼 테이블을 넣는다는 느낌으로 객체를 넣어보실까요?

2023-06-05 18:38 UTC, closed without merging