[3기-김선호] 1~2주차 과제 : 계산기 구현 미션 제출합니다
prgrms-be-devcourse/java-calculator pull request #98
Opened 2022-10-26 10:43 UTC by preferKim

안녕하세요 리뷰어 `마르코`님, `명환`님! 계산기 미션 제출합니다!
아직 예외처리나 세부적인 부분은 구현하지 못했지만 먼저 PR하고 이후 수정하며 채워나가겠습니다! 
flowchart 와 구현한 클래스의 UML 등은 [여기](https://github.com/preferKim/devcourse-calculator)에 남겨두었습니다! 감사합니다!

# 📌 과제 설명 

![image](https://user-images.githubusercontent.com/65555299/198002302-40e0fefd-d174-4996-bacc-aef4d72bd8e4.png)

사용자로부터 중위식을 콘솔 입력받고, 이를 후위식으로 변환 & 계산하는 계산기 애플리케이션입니다.
계산이 완료되면 결과를 콘솔 출력하고, 계산이력을 저장합니다.
사용자는 전체 계산이력을 조회할 수 있으며, 실행 중인 계산기 프로그램 또한 종료할 수 있습니다.

# 👩‍💻 요구 사항과 구현 내용 

## 계산

[feat: 입력한 식을 계산하는 로직 구현](https://github.com/prgrms-be-devcourse/java-calculator/commit/30c8f24d0b39399818dab4187498f28d6785baca)
[feat: 연산자, 연산자 우선순위 객체 구현](https://github.com/prgrms-be-devcourse/java-calculator/commit/eb4f664f3d44da87c7bf5e8efab2c7b970022625)

### 중위식 -> 후위식 변환 

[feat: 후위식 변환 기능 구현](https://github.com/prgrms-be-devcourse/java-calculator/commit/ae41e6aa5e656cec43ac123dd4ac5a6b9cf9714a)

### 후위식 계산 

[feat: 후위식 계산 기능 구현](https://github.com/prgrms-be-devcourse/java-calculator/commit/c7b0344b1ee100f8f7113e04500e2efc7178c070)

## 계산 이력

[feat: 계산 결과 저장 및 조회 구현](https://github.com/prgrms-be-devcourse/java-calculator/commit/52b12f59c50129c64116bccb11d00cafa59f3cba)
[fix: 계산 이력 없을 시 출력되는 메시지 추가](https://github.com/prgrms-be-devcourse/java-calculator/commit/37e6095888adc9a07a25fe57da1a327362d5c2ca)

## 입출력

[refactor: SelectOption 객체가 스스로 리터럴 생성을 할 수 있도록 책임 변경](https://github.com/prgrms-be-devcourse/java-calculator/commit/2d9d08bb1bcc63e079a0c886adf41bd619fe3ff7)
[feat: 사용자 선택 옵션(계산, 조회) 콘솔 출력 구현](https://github.com/prgrms-be-devcourse/java-calculator/commit/8d39e4bfd88787b531c5e50b2779bcc145892218)
[feat: Console - 선택 옵션에 대한 입력 구현](https://github.com/prgrms-be-devcourse/java-calculator/commit/a85869f8ee344b1972346c6549a3abd24f0cfd82)
[feat: 식을 입력받는 기능 구현](https://github.com/prgrms-be-devcourse/java-calculator/commit/6d5f8415071d648d362c367c2a30e60ef4838277)
[feat: 계산 결과 출력 구현](https://github.com/prgrms-be-devcourse/java-calculator/commit/aa8b5b063bcc0a61f32b50fc86ab3ce78076f12b)

## 애플리케이션 실행, 종료

[refactor: 애플리케이션 엔트리 포인트 변경](https://github.com/prgrms-be-devcourse/java-calculator/commit/8a358edc7ccaa283be3880b6baa568cda10e3c1e)
[refactor: 애플리케이션 엔트리 포인트 변경 (스레드를 사용하여 실행)](https://github.com/prgrms-be-devcourse/java-calculator/commit/30b5f77a75dbd1e61b29a785269f0f8f8e4914bf)
[refactor: 애플리케이션 엔트리 포인트](https://github.com/prgrms-be-devcourse/java-calculator/commit/6ebf4855af712c8c143e8f9e8feb4cd37d9be955)
[feat: 애플리케이션 종료 조건 구현](https://github.com/prgrms-be-devcourse/java-calculator/commit/a96dc08dfa89b78c23cec6defb0df7348b388d7a)
[refactor: Controller 객체의 루프문 메서드 추출(depth 감소)](https://github.com/prgrms-be-devcourse/java-calculator/commit/a7cf1d3f490fb4e48f4d15caa8545a37f0e6c25a)

## ✅ PR 포인트 & 궁금한 점 

- 최대한 각 객체의 역할을 나누어 Entity를 작게 가져가고자 했는데 생각처럼 많이 나누지는 못했습니다. 객체지향적이지 못한 부분, 역할이나 책임등이 과하거나 `이건 여기에 있을 게 아닌데..` 하는 부분을 가감없이 짚어주시면 감사하겠습니다!
- 외부에 공개하는 메서드명은 빠르게 작명할 수 있었지만 내부적으로 세부 구현을 하는 부분에서는 제대로된 작명을 하지 못하여 불분명한 의미를 갖게되었습니다. `부자연스러운 흐름`을 갖거나 `메서드의 순서` 등 style 적인 부분도 아낌없이 조언해주시면 감사하겠습니다!

- 코드 내용에 대해 궁금한 부분은 댓글로 남기겠습니다! 감사합니다😁

2022-10-26 22:09 UTC, preferKim reviewed
코드 내용적으로 궁금한 점은 댓글로 남겼습니다. 감사합니다!

2022-10-28 18:51 UTC, samkimuel requested changes
선호님 고생 많으셨습니다!
많이 고민하고 코드를 작성하신 것 같네요.

부족하지만 코멘트 달았으니 확인해주세요~!

2022-10-28 18:51 UTC, samkimuel commented on src/main/java/calculator/engine/converter/PostfixConverter.java
> +        deque.addFirst(operator);
뎁스 줄이기 위해 메서드 분리하는 방법 잘하셨어요👍

seperate() 를 더 쪼개볼 수도 있을 것 같아요. seperate() 라는 의미의 범위가 크다는 느낌을 받네요.

2022-10-28 18:51 UTC, samkimuel commented on src/main/java/calculator/engine/controller/RunningState.java
> +    }
Controller 와 RunningState의 관계를 생각해보면 될 것 같아요.
Controller를 RunningState의 외부라고 할 수 있을까요?? 이미 두 객체의 관계가 강하게 결합되어 있어서 분리해서 볼 수 없을 것 같아요.

외부에 의해 내부 상태 값이 변경되면 객체지향적이지 못한 코드라고 생각되는 포인트가 정확히 어떤 것인지 궁금합니다🤔
선호님은 외부에 의해 영향받지 않는 객체들을 설계하고 구현해내야만 하는 것이 객체지향 프로그래밍이라고 생각하시는 걸까요~?

2022-10-28 18:51 UTC, samkimuel commented on src/test/java/ConfigTest.java
> +}
이 테스트는 지우셔도 될듯하네요ㅎㅎ

2022-10-28 18:51 UTC, samkimuel commented on src/test/java/calculator/engine/calculator/ArithmeticCalculatorTest.java
> +    void test1() {
테스트 메서드명도 의미있게 작성하시면 좋아요!

2022-10-30 00:25 UTC, ksy90101 commented on src/main/java/calculator/engine/repository/CalculationHistory.java
> +    }
Map을 사용한것은 좋습니다.
실제 데이터를 저장할때 String과 같은게 아니라 객체를 저장하는것이 좋습니다. 위와 같은 객체가 어떻게 보여질지에 대해서는 DB가 아니라 객체가 가지고 잇겟죠.
지금은 Collection에 View코드를 넣어서 그런거 같아요.

2022-10-30 00:26 UTC, ksy90101 commented on src/main/java/calculator/engine/controller/Calculator.java
> +    }
그 코드를 동작하게 만들고 커밋을 하죠.

2022-10-30 00:26 UTC, ksy90101 commented on src/main/java/calculator/application/io/Parser.java
> +    }
지금만으로도 충분합니다 👍

2022-10-30 00:27 UTC, ksy90101 commented on src/main/java/calculator/application/Application.java
> +        CalculatorApplication.interrupt();
외부 의존성을 받도록만 유지하는게 좋습니다.

2022-10-30 00:36 UTC, ksy90101 requested changes
안녕하세요 :)
명환님이 리뷰를 잘 남겨주셔서 크게 리뷰는 없네요.
간단한 피드백을 남겼으니, 한번 참고해보세요.
고생 많으셨습니다 💯

2022-10-30 00:36 UTC, ksy90101 commented on src/main/java/calculator/engine/calculator/ArithmeticOperator.java
> +            return firstOperand / secondOperand;
분모가 0이면 어떻게 될까요?

2022-10-30 00:36 UTC, ksy90101 commented on src/main/java/calculator/application/Application.java
> +        Thread CalculatorApplication = new Thread(controller);
자바의 명명규칙은 어떻게 될까요?

2022-10-30 00:36 UTC, ksy90101 commented on src/main/java/calculator/engine/repository/CalculationHistory.java
> +    public void record(Expression infix, CalculationResult result) {
record는 자바 예약어에요 ㅎㅎ

2022-10-30 00:36 UTC, ksy90101 commented on src/main/java/calculator/application/io/Parser.java
> +public class Parser {
명환님이 좋은 이야기 해주셨네요 👍 
https://github.com/Meet-Coder-Study/book-effective-java/blob/main/2%EC%9E%A5/4_%EC%9D%B8%EC%8A%A4%ED%84%B4%EC%8A%A4%ED%99%94%EB%A5%BC_%EB%A7%89%EC%9C%BC%EB%A0%A4%EA%B1%B0%EB%93%A0_private_%EC%83%9D%EC%84%B1%EC%9E%90%EB%A5%BC_%EC%82%AC%EC%9A%A9%ED%95%98%EB%9D%BC_%EC%9D%B4%ED%98%B8%EB%B9%88.md

위 글을 참고해보세요.

2022-10-30 00:36 UTC, ksy90101 commented on src/main/java/calculator/application/io/Output.java
> +    void logResult(String result);
if문을 대표적으로 사용하긴 하구요.
전략패턴을 적용하기도 합니다.

또한 다형성을 지켜 객체를 구현하기도 합니다.

2022-10-30 00:36 UTC, ksy90101 commented on src/main/java/calculator/engine/controller/Controller.java
> +        }
각 Enum의 값들이 자신이 해야 하는 행동들을 가지고 있는것도 좋겠네요.

2022-10-30 00:36 UTC, ksy90101 commented on src/main/java/calculator/engine/converter/PostfixConverter.java
> +        while (!deque.isEmpty() && deque.getFirst().hasSamePriorityOrPrecede(operator)) {
deque.getFirst().hasSamePriorityOrPrecede(operator)

디미터의 법칙을 위반한듯 하네요.

2022-10-30 00:36 UTC, ksy90101 commented on src/main/java/calculator/engine/repository/CalculationHistory.java
> +    private final Map<Long, Map<Expression, CalculationResult>> history = new LinkedHashMap<>();
Map의 Map이 있어야 할 정도일까요?
실제 데이터베이스는 어떻게 되어 잇는지 고민을 해보세요.
(결론 객체 하나만 있어야 하지 않을까 라는 이야기입니다.)

아울러 이런 경우 static이 붙혀있지 않으면 어떤 문제가 있을까요?

2023-06-05 18:38 UTC, closed without merging